### ISSUE TITLE
 VarInt in this project is CompactSize in Bitcoin Core

### ISSUE THREAD

**Issue by dagurval** [rust-bitcoin/rust-bitcoin#1016]
The Bitcoin Code source code uses the name "CompactSize" for what is named "VarInt" in this project.

"CompactSize/VarInt" in [this project](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/consensus/encode.rs#L379) and [in Bitcoin Core](https://github.com/bitcoin/bitcoin/blob/master/src/serialize.h#L246).

In Bitcoin Core, there is also a different integer encoding named [VarInt](https://github.com/bitcoin/bitcoin/blob/master/src/serialize.h#L370). 

I assumed `VarInt` was the same integer encoding for both projects and this confused me for a while.

**Comment by Kixunil** [comment]
Given that `VarInt` exists in Core and means something else I'd be in favor of renaming. Although I suspect not having the *type* in the first place might be even better (just have functions). They'd still need to be named accordingly.

**Comment by apoelstra** [comment]
You cannot replace a format-modifying wrapper type with functions, at least not ergonomically.

Agree that we ought to rename the type. I believe I was originally making some philosophical stand about Core's choice of naming, but this isn't wise.

**Comment by Kixunil** [comment]
`fn encode_compact_size(number: u64, writer: impl Write) -> Result<(), Error>`, `fn decode_compact_size(reader: impl Read) -> Result<u64, Error>` I actually wrote my own parser in the past to learn about Bitcoin and this worked for me.

**Comment by apoelstra** [comment]
Hmm, yeah, I think that could work actually. AFAIK varints are not actually stored anywhere where they retain their "varint character" ... or at all. They're mostly used to encode the lengths of objects.

We would also need a convenience function to get the varint-encoded length of a number.

**Comment by RCasatta** [comment]
Another option is to provide blanket implementations in our `ReadExt` and `WriteExt` traits

**Comment by Kixunil** [comment]
@RCasatta I like that idea! length should be separate though. Maybe do it like this:

```rust
trait CompactSize {
    fn encode_compact_size<W: Writer>(&self, writer: W) -> io::Result<()>;
    fn decode_compact_size<R: Read>(reader: R) -> io::Result<Self>;
    fn compact_size_len(&self) -> usize; // maybe prefer u8 to allow conversions but may be too annoying in common case
}

// impl CompactSize for u8 and other integers using a macro

trait ReadExt {
    fn read_compact_size<T: CompactSize>(&mut self) -> io::Result<T>;
}

trait WriteExt {
    fn write_compact_size<T: CompactSize>(&mut self, value: CompactSize) -> io::Result<()>;
}
```

**Comment by tcharding** [comment]
According to this [document](https://en.bitcoin.it/wiki/Protocol_documentation#Variable_length_integer) varint is correct?

> If you're reading the Satoshi client code (BitcoinQT) it refers to this encoding as a "CompactSize". Modern Bitcoin Core also has the VARINT macro which implements an even more compact integer for the purpose of local storage (which is incompatible with "CompactSize" described here). VARINT is not a part of the protocol.

**Comment by Kixunil** [comment]
@tcharding did you also read "incompatible" as "compatible"? I did at first but then I found it too weird and re-read it. If it's incompatible and we're clearly implementing compact size, not varint, then varint is **not** correct name.

**Comment by tcharding** [comment]
Oh bother, yes I missed that. Converting to draft to think it through with fresh eyes. Thanks man.

**Comment by tcharding** [comment]
This issue will likely be closed by: https://github.com/rust-bitcoin/rust-bitcoin/pull/2931

**Comment by Kixunil** [comment]
It doesn't rename them and we should start using `push_decode` anyway (but still, it should be `CompactSizeEncoder`)

**Comment by apoelstra** [comment]
Probably we should rename them in #2931.

**Comment by Kixunil** [comment]
@apoelstra I'll take that as "also rename them in `push_decode` impl"

**Comment by tcharding** [comment]
I'm confused, why rename, I thought #2931 _removes_ the `VarInt` type - so that invalidates this issue, right? Or am I missing something?

**Comment by apoelstra** [comment]
@tcharding #2931 does remove the type, by replacing it with methods that have the same name as the type. I'm saying we should change the name (from `varint` to `compact_size`).

**Comment by tcharding** [comment]
ooooo, I amuse myself at how slow I am sometimes :)

**Comment by tcharding** [comment]
Seems we are not the only ones that confuse "var int" with "compact size" - the BIP141 also uses "var int"

> A witness field starts with a var_int to indicate the number of stack items for the txin. It is followed by stack items, with each item starts with a var_int to indicate the length. Witness data is NOT script.
