### ISSUE TITLE
`Address::from_script` to return a `Result`

### ISSUE THREAD

**Issue by dpc** [rust-bitcoin/rust-bitcoin#1022]
https://github.com/rust-bitcoin/rust-bitcoin/pull/1021#discussion_r884152633

**Comment by sanket1729** [comment]
Added another fail condition to be checked: https://github.com/rust-bitcoin/rust-bitcoin/pull/1021#issuecomment-1143312781

**Comment by nlanson** [comment]
> Added another fail condition to be checked: [#1021 (comment)](https://github.com/rust-bitcoin/rust-bitcoin/pull/1021#issuecomment-1143312781)

@sanket1729 Is this check not already performed when `script.is_witness_program()` is called within `Payload::from_script()`?

**Comment by sanket1729** [comment]
@nlanson, you are correct! This is already being done. Sorry for the confusion. But as far as this issue is concerned, we should have a dedicated error type here.
