### ISSUE TITLE
Remove the `Sighash::Reserved` variant

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#1030]
We have a `SchnorrSignatureHash::Reserved` variant that is not useful. All other values of sighash types are invalid by consensus, and the reserved is serving no purpose.

Initially, we had these because we tried to combine the `EcdsaSignatureHashType`, `SchnorrSignatureHashType`  and future possible upgrades into a single enum `SigHashType`. In order to mark it `non-exhaustive, it was suggested to add the `Reserved` variant

Later on, we cleanly split into `SchnorrSignatureHashType` and `EcdsaSignatureHashType` and this is no longer needed and only confuses the reader. If in the future, we have a new signature algorithm or a hash type, we can add another enum for it. De-duplicating code here is not worth it.

**Comment by Eunoia1729** [comment]
Picking this up
