### ISSUE TITLE
Get access to the data within `PartialMerkleTree`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1046]
It would be nice to have a way of accessing the the fields of [`PartialMerkleTree`](https://docs.rs/bitcoin/0.27.1/bitcoin/util/merkleblock/struct.PartialMerkleTree.html) when, e.g., receiving a [`MerkleBlock`](https://docs.rs/bitcoin/0.27.1/bitcoin/util/merkleblock/struct.MerkleBlock.html) over the network. 

This issue was originally posted as a PR: https://github.com/rust-bitcoin/rust-bitcoin/pull/943, see discussion for solution idea.

**Comment by Eunoia1729** [comment]
Picking this up :)
