### ISSUE TITLE
Optimize `Witness::to_vec` to use known lenght for reserving.

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1050]
We know the number of witnesses so we could pre-allocate the `Vec`. There are two ways to do it:

* Add `len` to the iterator and decrease it on each iteration, implement `size_hint` and `ExactSizeIterator`. This makes *all iterations* (including those that don't need it) slower by one decrement instruction for each iteration but is pretty general and can be used in other contexts.
* Just reserve the `Vec` in `to_vec` and use `extend()` instead of `collect()`
* Make two iterator types one tracking the length, the other not tracking.

I think the cost of decrementing is reasonably small, especially for `Witness` which shouldn't have many items anyway, so I like that approach the most.

**Comment by apoelstra** [comment]
We know the number of witness elements, but not the length of each one, right? Can we still pre-allocate a `Vec`?

**Comment by Kixunil** [comment]
Yes, the top-level one. And then as we iterate, we just use `to_owned()` which does the right (fast) thing.

**Comment by apoelstra** [comment]
Ah, of course! I forgot that `to_vec` returned a `Vec<Vec>`, not a a`Vec`.
