### ISSUE TITLE
Tracking issue - PSBT refactoring & PSBTv2

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1055]
This is a tracking issue for ongoing PSBT work, including but not limited to implementing support for PSBT v2 [BIP-370](https://github.com/bitcoin/bips/blob/master/bip-0370.mediawiki).

For reference we do support PSBT v0 [BIP-174](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki).

There is a GitHub project already for this epic: https://github.com/rust-bitcoin/rust-bitcoin/projects/1

There is not currently a champion for this epic: https://github.com/rust-bitcoin/rust-bitcoin/issues/787

**Comment by tcharding** [comment]
Field names discussion: https://github.com/rust-bitcoin/rust-bitcoin/discussions/1054

**Comment by Kixunil** [comment]
I think one of the first, significant steps is to put `TxIn` into `Input` so that consistency is guaranteed.For consideration `CheckedPsbt` which additionally guarantees that you can get a correct previous output for each input.

**Comment by tcharding** [comment]
Closing in favour of https://github.com/rust-bitcoin/rust-bitcoin/issues/1115
