### ISSUE TITLE
Remove other Transaction::signature_hash

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#1056]
One user got confused about which API to use and asked a question on stack exchange. https://bitcoin.stackexchange.com/questions/114116/how-do-you-commit-to-the-previous-outputs-amount-when-signing-a-segwit-input-wi

**Comment by Kixunil** [comment]
And remove useless `util` nesting...

**Comment by sanket1729** [comment]
As suggested in the comment here, signing API could also use example code: 
> https://bitcoin.stackexchange.com/a/114127/44760

Perhaps, we should be writing more examples instead of tests.

**Comment by Kixunil** [comment]
Already removed.
