### ISSUE TITLE
`AddressType` `FromStr` impl returns bad error type

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1064]
Returns `()`, should be a custom error.

We should at least have `#[non_exhaustive] struct AddressTypeParseError;` but ideally store the input as `String` too for better error reporting. + impl `Error` of course.

**Comment by arturomf94** [comment]
I'd like to take this up. Could it be assigned to me?

**Comment by Kixunil** [comment]
You have it! :)

**Comment by arturomf94** [comment]
Hey @Kixunil - opened https://github.com/rust-bitcoin/rust-bitcoin/pull/1091

I'd appreciate it if you could have a look at it. Hopefully it works as expected!
