### ISSUE TITLE
Ecosystem-wide hash unsoundness/invariants

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1090]
This problem affects `bitcoin_hashes`, `secp256k1` and relates to types in `bitcoin` as well.

[ThirtyTwoByteHash](https://docs.rs/secp256k1/0.23.3/secp256k1/trait.ThirtyTwoByteHash.html) requires the type to be a random value but it's possible to produce a bad value without *obvious warning*:

```rust
let bad_value = "0000000000000000000000000000000000000000000000000000000000000000".parse::<sha256::Hash>()?;
fn_accepting_message(bad_value.into());
```

Further, technically types like `Txid` look like candidates to impl `ThirtyTwoByteHash` but actually `Txid` is used in `OutPoint` which can come from untrusted source and even can correctly contain all zeros in coinbase txes. Also the type has `all_zeros` method which is at least not public but IMO still bad.

The situation looks messy but I think there's a path forward:

* Remove `FromStr`, deserialization or other dubious constructors from guaranteed hashes
* Define special hash types that are allowed to contain any value but do not impl `ThirtyTwoByteHash`, nor guarantee anything. These have `all_zeros` available. Maybe even public. At least `PrevTxid` used in `OutPoint` should have it public.
* Provide `fn from_byte_array_unchecked()` for hashes that guarantee randomness. The doc will explain it and people who parse trusted inputs can use it if needed.
* To help with parsing provide a free function that parses hex into slice or `HashUnchecked` type with `FromStr` (former seems simpler)

This should ensure that any dangerous path has Rust-idiomatic `unchecked` word which should hopefully immediately attract attention of the reviewers.

Simpler alternative: keep hashes unrelated to signing without guarantees but remove the ability to convert them into those that do guarantee randomness and remove parsing/deserialization from guaranteed types.

Side note: none of this is related to UB and I think we should keep UB-related stuff as-is - code must not invoke UB even if invariants are broken.

FYI I gotta go, will probably reply Monday.

**Comment by apoelstra** [comment]
I think the term "unsoundness" is a dramatic exagerattion of this issue.

Yes, you can parse invalid hashes from strings (or from byte slices, or from the blockchain, or whatever), and I suppose that if you were to then ECDSA-sign such an object, you would reveal the ratio of your secret nonce to secret key, enabling an indefinite number of forgeries rather than only the one that you voluntarily created by signing an opaque hash.

I don't think this is a problem and do not think it is worth *any* reduction in ergonomics.

**Comment by apoelstra** [comment]
If `ThirtyTwoByteHash` is so controversial we can just drop it I guess and go back to writing `.unwrap` everywhere when trying to validate signatures.

**Comment by apoelstra** [comment]
I think the majority of my interactions with hash types are manipulating txids, but okay, I'm never signing those so I wouldn't mind if they stayed in some non-`Message`-compatible type.

Ok, I'm warming up to this. I'm sorry @Kixunil for my initial hostile response.

**Comment by dpc** [comment]
@Kixunil Please include https://docs.rs/secp256k1/0.23.3/secp256k1/trait.ThirtyTwoByteHash.html in the first post for unfamiliar readers. I wasn't ware of that type and was a bit confused.

Yeah, this type requires some work, in particular with documentation. Like "promises to be a 32-byte random number". A hash is not random at all, as far as I understand the terminology. Without being more specific about the use case and guarantees it's hard to tell how to "fix it".

**Comment by apoelstra** [comment]
I believe what is meant by that comment (which I might've written..) is that the value should be the output of a hash function which can be modelled by a random oracle ... and what **that** means is the [subject of decades of debate](https://eprint.iacr.org/2015/140).

But to a first approximation, hash values should not be attacker-controllable except with exponential work (e.g. to force 10 bits to be a particular value you have to try 2^10 different preimages, on average).

**Comment by dpc** [comment]
> hat the value should be the output of a hash function which can be modelled by a random oracle

I understand this (I think), but I can't see how is it useful exactly. If you don't control what are these hashes from, they can be considered predictable, non-random and controllable. I can always give the same set of values as a preimage and get a controllable output. I think you'll see the point I'm making. The hash value is only a random oracle in relation to the original value, and without the context of the hashing operation, it just doesn't seem to me like a useful property encoded in an otherwise global context of the type system.

Is there some use case that I'm missing here?

**Comment by apoelstra** [comment]
>I don't understand this? Txids, constructed from hashed data, qualify as hashes that are safe?

Most txids I encounter are deserialized from outpoints rather than directly constructed.

>Is there some use case that I'm missing here?

Basically all of provable security for digital signatures for the last 30 years :). I get what you're saying, that you can "control" a hash to be equal to a specific value that you got from the hash function itself, provided that you fix the preimage, but from an attacker's perspective this is not enough to meaningfully break cryptosystems.

**Comment by dpc** [comment]
I get the use cases of hashes. I don't get the use case of type system meaning of this trait. :)

**Comment by apoelstra** [comment]
> I don't think that's type-system encodable, at least in Rust.

That's kinda out of character for you :P.

I think it **is** encodable in the type system, by having a type that you can only construct by using the sha2 function -- then if you assume that sha2 can be modeled as a random oracle, you're ok. It's true that users can still find ways to undermine this, for example by defining cryptosystems in terms of the gross details of the sha2 algorithm, but they'd need to work pretty hard at it.

**Comment by dpc** [comment]
Hmmm... I guess, as hand-holding thing it's OK...

It does need a good explanation of the intent. As I understand, all it is supposed to guarantee is that the value inside is an output of cryptographic hash function of _something_, and that's it. I would especially avoid 'random' word.

**Comment by Kixunil** [comment]
So do I understand correctly most of you prefer the simpler solution to make `sha256::Hash` only constructible using SHA256 (and maybe `_unchecked` fn) and keep the rest as-is?

Also I know "unsound" isn't fitting. I couldn't find a better term in hurry.

**Comment by Kixunil** [comment]
@apoelstra that's a really great idea! I'm not entirely sure about type inference succeeding to infer `Known` but it's worth a shot and probably not a huge issue even if it doesn't work - consumer just has to mark exact type.

I now prefer your solution. :)

**Comment by sanket1729** [comment]
Concept ACK. This should clean up a lot of "Cryptographically unreachable code" type unwraps in taproot tweak derivations, bip32 derivations, etc.

**Comment by apoelstra** [comment]
Closing in favor of https://github.com/rust-bitcoin/bitcoin_hashes/issues/188. I don't think this issue belongs in this repo.

**Comment by apoelstra** [comment]
> This should clean up a lot of "Cryptographically unreachable code" type unwraps in taproot tweak derivations, bip32 derivations, etc

Frustratingly, to get rid of "cryptographically unreachable" branches, we would need to know not only that a tweak came from a hash, but that it came from a *hash of the key being tweaked*. I'm unsure how to do this without dependent types. (Though I'll spend some time trying :))

**Comment by Kixunil** [comment]
@apoelstra I found how though not sure how practical it will be:

```rust
impl PublicKey {
    pub fn self_tweak<H: Hash + ThirtyTwoByteHash>(self, ctx: &Secp256k1<impl Signing>, engine: H::Engine, suffix: &[u8]) -> Self {
        engine.input(&self.serialize());
        engine.input(suffix);
        let hash = H::from_engine(engine);
        self.add_tweak(&ctx, &hash.into()).expect("the key was just hashed")
    }
}
```

So the user supplies a potentially pre-seeded hash engine and a suffix, pubkey writes itself into the engine and tweaks itself. So the hash is:

`PREFIX || PUBKEY || SUFFIX`

Maybe suffix should be something more generic though.

**Comment by apoelstra** [comment]
@Kixunil I'd considered something like this .. my inclination is that it's (a) probably a big ergonomic hit to require `suffix` to be known upfront; this means that this is only useful in cases where the tweaking code is self-contained and already "obviously" correct; (b) it still uses `expect` :) though I guess if it's hidden inside this function that's ok.

**Comment by Kixunil** [comment]
a) maybe still fine for many uses and it'd remove the burden of reviewing and such
b) I think it's only possible to solve it if there's a C function that simply ignores checking and trusts the caller to do the right thing. So yes, hidden panic is fine.

**Comment by apoelstra** [comment]
What if we made a macro which turned into `x.expect()` in debug mode but `let _ = x` in release mode?

**Comment by Kixunil** [comment]
There's no point of saving one branch especially after heavy crypto operation. The point of making it "panic-free" is to make review easier. The code should prove to the reviewer that it does the right thing. And expect is in short block that is obviously correct and was verified by many eyes.
