### ISSUE TITLE
Issue linking secp256k1 for embedded

### ISSUE THREAD

**Issue by maxdignan** [rust-bitcoin/rust-bitcoin#1102]
Hey there, I'm trying to include rust-bitcoin in a rust crate that I am building for ESP32. The plan is to then to link that crate - built with `[lib] crate-type = ["staticlib"]` - to a larger embedded C app for ESP32s2. I am using cmake to do so like so: `   target_link_libraries(${project_elf} ${RUST_BUILD_DIR}/librust_testing_idf_rust.a)`. I am getting it to compile in the rust crate with `cargo build --release --all --target xtensa-esp32s2-espidf -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort` . Then running the cmake build. I am getting the following error: (in brief) ` undefined reference to `rustsecp256k1_v0_5_0_ec_pubkey_create'` (and other secp256k1 functions are marked as missing as well).

<img width="1262" alt="Screen Shot 2022-07-18 at 3 24 45 PM" src="https://user-images.githubusercontent.com/8184722/179602141-314d8046-a1c4-4c61-aec4-fa708c0351e2.png">

I have also tried to run the rust crate build with the `RUSTFLAGS="--cfg=rust_secp_no_symbol_renaming"` flags thinking that this may be the issue. But it still can't find those either at linking stage.

`undefined reference to `secp256k1_ec_pubkey_create'` (and other missing secp256k1 functions as well)

I have attempted to include in the libsecp256k1.a file that gets build as well for the build artifacts with `target_link_libraries`, but that doesn't seem to work either.

I think I'm missing something, or misunderstanding something?

Thanks for your help!

**Comment by maxdignan** [comment]
Hey @apoelstra thanks for looking into this. Yes, I see that function - and the other "missing" ones - when running strings on the .a file. They are prefixed with `_rustsecp256k1_v0_5_0_`. The only thing that jumps out there is the leading `_` in front of the name...

**Comment by apoelstra** [comment]
I believe the leading `_` is a linker convention and shouldn't be the cause of your problem.

Out of curiosity, could you write a small C program and try to link it against the produced `libsecp256k1.a` with `-bstatic` or whatever you think would most closely resemble the Rust compiler?

**Comment by apoelstra** [comment]
cc @elichai @real-or-random do you have any idaes here?

**Comment by maxdignan** [comment]
@tcharding should I include rust-bitcoin from a subdirectory while making the changes you made in your PR? Do you expect this will resolve the issue, or is there more work to be done?

**Comment by tcharding** [comment]
Hi @maxdignan, I'm in a state of confusion this morning, I thought this issue had @apoelstra mentioning that we didn't upgrade the secp version but its not here now, that is why I mentioned this issue. I have no idea what the problem you are hitting is from, so if I was you I'd just ignore me for now :)

**Comment by tcharding** [comment]
Oh boy, finally found it. Sorry for the noise. (FTR: https://github.com/rust-bitcoin/rust-bitcoin/issues/824#issuecomment-1188419708)

**Comment by maxdignan** [comment]
@tcharding no prob! I’ll play around with it nonetheless 🙂🙏

**Comment by real-or-random** [comment]
can you post the output of `objdump -t libsecp256k1.a`?

**Comment by elichai** [comment]
> For sure.
> 
> I wrote the following main.c file (that successfully runs and compiles for esp32s2):
> 
> [main.txt](https://github.com/rust-bitcoin/rust-bitcoin/files/9135717/main.txt)
> 
> It uses the following rust code (only using the `rust_main` function though that doesn't require secp256k1):
> 
> [lib-rs.txt](https://github.com/rust-bitcoin/rust-bitcoin/files/9135727/lib-rs.txt)
> 
> However, whenever I use `get_addr_wrapper` in C - and it isn't shaken from the build, I get the `undefined reference` issue (same as before). When I instead comment either or both of the rust calls out, and then call `extern int rustsecp256k1_v0_5_0_ec_pubkey_create(void *arg);` I also get the error from before. This is regardless of whatever permutation and ordering of target_include_libraries I do with the rust lib crate's .a file and the built libsecp256k1.a file.

Could you maybe open a minimally reproducible repository that we could build and link to see that error and try to debug it?

**Comment by maxdignan** [comment]
@real-or-random yes, here it is:
[objdump_output.txt](https://github.com/rust-bitcoin/rust-bitcoin/files/9144098/objdump_output.txt)

and @elichai I will plan on giving that a shot tn

**Comment by real-or-random** [comment]
> and @elichai I will plan on giving that a shot tn

Yes I think that will be helpful, the objdump output looks good.

**Comment by stonexang** [comment]
@maxdignan 
![image](https://github.com/user-attachments/assets/facfce91-2a28-424c-b94d-c5dbad3e4abe)
hi，Did you resolve your issue in the end?
I'm encountering compatibility issues with secp256k1 while linking a Rust static library for ESP32. and I found the following message:  `'c928380082b86401-secp256k1.o: file format not recognized'.`

**Comment by maxdignan** [comment]
Unfortunately, I had to drop working on this project a couple years ago and wasn't able to get this fixed before then

**Comment by Kixunil** [comment]
There's also https://github.com/rust-bitcoin/rust-secp256k1/issues/598

Closing this as stale, please open a new issue at secp256k1 repo if needed.
