### ISSUE TITLE
Add a type that represents bitcoin amounts.

### ISSUE THREAD

**Issue by jeandudey** [rust-bitcoin/rust-bitcoin#111]
I think it's useful to have a type that represents bitcoin amounts, currently there isn't a standard way to do this in rust and there isn't too much documentation on how developers should handle BTC amounts (e.g. wrongly using `f64` or `f32`instead of using fixed point math).

Ideally it would be called `Amount` and live under the `util::amount` module.

Some features it should implement:
- implement serde `Deserialize`/`Serialize` traits.
- it should have a function to construct amounts from `strason::Json` numbers (for bitcoind JSON-RPC).
- implement rust math operation traits (`Add`, `Mul`, `Sub`, `Div`, etc).
- wrapping operations (`wrapping_add`, `wrapping_sub`, etc).
- pretty printing (e.g printing "0.00025587 BTC" or "25587 sat").
- `MIN`/`MAX` constants.

**Comment by dr-orlovsky** [comment]
Why this issue was closed? I do agree with the topic, it may help in having more semantic/clear code and prevent some errors.

**Comment by dpc** [comment]
https://github.com/rust-bitcoin/rust-bitcoin/pull/270 ?
