### ISSUE TITLE
Enable `FromStr` implemenations to accept hex

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1112]
We have various tuple structs with a single `u32`, many of these have a `FromStr` implementation that allows construction from an integer as a string. It may be useful if we also supported hex strings e.g., `Sequence::from_str("0x0000ffff");

For types to consider, grep the codebase for:  `'\(u32\)'` and `'\(pub u32\)'`

**Comment by dpc** [comment]
Seems like a potential source of errors, some even severe. Things working e.g. when `0x` prefix was missed, for low numbers used in tests (`0-9`) etc.

Would it be safer and as convenient to have a `FromHexStr::from_hex`?

**Comment by Kixunil** [comment]
@dpc There's a difference between "string has to be hex" and "string may be hex". In the former case using `FromStr` would be wrong. In the latter the mere possibility of parsing both should make people aware of need to add prefix but yes, good documentation is still needed.

I'd be OK with having `FromHexStr` which *requires* hex. But should it require the prefix?

**Comment by apoelstra** [comment]
I think that hex values for numerics should always require the prefix.

**Comment by Kixunil** [comment]
Yeah, looks less error-prone.

**Comment by dpc** [comment]
> Yeah, looks less error-prone.

But in many cases require extra allocation, where skipping two bytes in front doesn't. :)
