### ISSUE TITLE
New release with wasm support

### ISSUE THREAD

**Issue by josediegorobles** [rust-bitcoin/rust-bitcoin#1117]
Hi, the issue i put here: https://github.com/rust-bitcoin/rust-bitcoin/issues/1086 is addressed in the rust-secp256k1 repository and is solved for the last release (0.24). I saw that is updated on master branch, but I was asking myself when is going to be a new release of rust-bitcoin with that. I think it's important to restore wasm support, but I don't know what is the plan for the next release.

**Comment by Kixunil** [comment]
We're close to releasing, see https://github.com/rust-bitcoin/rust-bitcoin/pull/1109
