### ISSUE TITLE
Useless TCP test

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1123]
Looking at #1119 I noticed that tests use TCP with seemingly the only intention being testing whether the code can handle broken-up packets. This can be achieved without TCP and without artificial delay of 1s considerably slowing down the tests. I've seen an entire library to simulate breaks at random points, I just can't remember how it was called. But it can be done manually too:

```rust
// Breaks up reading to force multiple `read` calls when it reaches the end of each part
struct BreakingReader {
    // Changing to iterators left as an exercise for the reader
    data: Vec<Vec<u8>>,
    idx: usize,
    pos: usize,
}

impl BreakingReader {
    fn new(data: Vec<Vec<u8>>) -> Self {
        BreakingReader {
            data,
            idx: 0,
            pos: 0,
        }
    }
}

impl io::Read for BreakingReader {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        if self.idx >= self.data.len() {
            return Ok(0)
        }
        // We never let pos to go out of bounds
        let part = &self.data[self.idx][self.pos..];
        let to_copy = part.len().min(buf.len());
        buf[..to_copy].copy_from_slice(&part[..to_copy]);
        if to_copy == part.len() {
            self.pos = 0;
            self.idx += 1;
        } else {
            self.pos += to_copy;
        }
        Ok(to_copy)
    }
}
```

Then just replace `serve_tcp()` with `BreakingReader::new()` and remove the `handle`/`join`.

**Comment by Kixunil** [comment]
After thinking about this I found even better solution: split the input at each byte. If we have incorrectly handled `read` (instead of `read_exact`) it's guaranteed to be hit. There's one more problem: if we create the buffer initialized with zeros and input contains zeros it could happen that "uninitialized" buffer is confused with data and we wouldn't see failure. To prevent this scramble the buffer by writing bit-negation of would-be-written next byte to the unused part of the buffer. (`Read` impl does neither allow nor forbid this and relying on it not being overwritten would be a bad idea.)

So:

```rust
struct BreakingReader<'a>(&'a[u8]);

impl io::Read for BreakingReader {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        if buf.len() > 1 && self.0.len() > 1 {
            buf[1] = !self.0[1];
        }
        // intentional panic when buf.len() == 0: buggy use of the reader
        self.0.read(buf[..1])
    }
}
```

**Comment by Kixunil** [comment]
So I was thinking about it a bit more and turned it into a [crate](https://docs.rs/io_check/latest/io_check/) :)

Will be happy to share maintainership!

**Comment by Kixunil** [comment]
Oh, the whole module is deprecated :man_facepalming: :man_facepalming: :man_facepalming:

**Comment by apoelstra** [comment]
Oh, lol, I knew when I saw that module here that I'd complained about its existence but totally forgot how that was resolved..
