### ISSUE TITLE
Print tool versions in CI

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1124]
Add commands to (verbosely) print out versions of Rust, Clippy, Cargo... before each run in CI. This will help with reporting bugs like I did in https://github.com/rust-bitcoin/rust-bitcoin/pull/1120#issuecomment-1192294554 - it would've been nicer if I could report our version too.

**Comment by nlanson** [comment]
Maybe add it in #1099?

**Comment by Kixunil** [comment]
Orthogonal but yes, #1099 should have it (eventually).

**Comment by PaarthAgarwal** [comment]
> Add commands to (verbosely) print out versions of Rust, Clippy, Cargo... before each run in CI. This will help with reporting bugs like I did in [#1120 (comment)](https://github.com/rust-bitcoin/rust-bitcoin/pull/1120#issuecomment-1192294554) - it would've been nicer if I could report our version too.

Please point me to the relevant files. I went through https://github.com/rust-bitcoin/rust-bitcoin/pull/1099/files#diff-f5534f0b6fb07c7e1bfedf7bdad375ddd70b29143fbbfa4502cb2e47cef197b7. Should I modify workflows/rust.yml for this change?

**Comment by apoelstra** [comment]
What I propose is:

1. Move the `cargo --version` and `rustc --version` lines out of `bitcoin/contrib/test.sh` etc., and into `contrib/test.sh`.
2. Add more lines for `cargo clippy` and `cargo fmt` -- though these will need to be gated somehow to not kill CI during the runs where those commands aren't available.

**Comment by Kixunil** [comment]
Also all this with `--verbose` flags and for each version we use (stable, nightly...).

**Comment by tcharding** [comment]
We do this already.
