### ISSUE TITLE
`CommandString` has inherent `try_from` function instead of trait

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1135]
Since `TryFrom` is available we should change it to convert any stringly type and provide `try_from_static(s: &'static str)` for the static use case.

Said another way, `TryFrom<T>` where `T` is `String`, `&str`, and `Box<str>`. And also `FromStr`.

**Comment by tcharding** [comment]
Ha! I made my edits and label addition before seeing you had an open PR to fix this :)
