### ISSUE TITLE
Inconsistent, undocumented behavior of `script::Builder::push_verify()`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1153]
The function doesn't clear `1` field which can cause strange behavior if `push_verify` is called multiple times:

* If `OP_VERIFY` was pushed last it's pushed again
* If an instruction was replaced it's replaced again, essentially causing no-op

I think the desirable behavior is to ignore `push_verify` right after last `push_verify` or `push_opcode(OP_VERIFY)` and this should be documented as well. (OT: doc doesn't look great either)

**Comment by Kixunil** [comment]
Oops, didn't realize `push_opcode` updates `1`

**Comment by apoelstra** [comment]
Phew! If repeated `push_verify` was a no-op I think that'd definitely be a bug :).

Wouldn't be opposed to adding a unit test here.
