### ISSUE TITLE
Should `script::Builder::push_verify()` allow duplicate verify pushes?

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1154]
If the last opcode was `OP_VERIFY` or any other `_VERIFY` variant `push_verify` still pushes `OP_VERIFY`. Is this desirable? It looks like the function wants to prevent redundant instructions but it fails to do so in this case.

**Comment by apoelstra** [comment]
Yes, it should allow duplicate `VERIFY`s. These aren't actually redundant, since each `VERIFY` consumes its input, so if they're repeated you'd actually be checking separate values.

**Comment by Kixunil** [comment]
Ah, yes, looks like I didn't have bright mind when I was looking at it. Could be worth doc though.

**Comment by apoelstra** [comment]
Can I close this issue? Or is there a specific line of documentation you'd like to add?

**Comment by Kixunil** [comment]
Made a PR.
