### ISSUE TITLE
Rust-version-dependent compilation

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1168]
The crate documentation now says:

> This library should always compile with any combination of features (minus no-std) on **Rust 1.41.1** or **Rust 1.47** with no-std.

Naively, this has at least four limitations:

1. If newer versions provide new, interesting features that would improve our *API*, we can't provide it to users of newer Rust versions ( in the past: solvable `TryFrom` trait, unsolvable `#[non_exhaustive]`)
2. If newer versions contain APIs that improve non-public code - e.g. by having better performance (not relevant to this crate but `sort_by_cached_key` is an example of such API), or debugging (`#[track_caller]` is current example) they can not be used
3. Occasionally a newer version of Rust is required to fix UB properly or not ending up with horrible hacks (taking a reference to unaligned field, `c_void` type should be [`extern type`]())
4. Type compatibility issues when we have to define our own types that are in `core`/`std` in newer versions people can't just assign them. This is almost a problem with `secp256k1_sys::types` but thankfully those are just type aliases (`core::ffi` module will be released as stable soon). This is actually a more serious variant of issue 1.

I believe it'd be good to change our policy to:

> This library should always compile with any combination of features (minus no-std or features prefixed `rust_v_`) on **Rust 1.41.1** or **Rust 1.47** with no-std.

And then create feature e.g. `rust_v_1_42` for new API available in Rust 1.42 if we need it. Being explicit and visible will make docs documented and nudges people to be explicit about MSRV.

However, for internal behavior like performance or debugging I'd instead use custom `cfg` enabled from build script. `secp256k1` already has a build script and we could add something simple to `bitcoin` & others. I've seen build scripts that detect compiler features instead of version by trying to build things. IMO this is over-complicated and wastes compile time. The script should have no additional dependencies and only consist of a simple match on version and printing appropriate `cargo:` messages.

Note that by doing the latter we don't actually need to change the policy, but changing it is still desired by me.

**Comment by apoelstra** [comment]
Yeah, I like this idea. Though we should be mindful not to have a configuration explosion where we've got large amounts of code duplicated between non-`rust_v_whatever` and `rust_v_whatever`

**Comment by Kixunil** [comment]
We definitely shouldn't be doing things like conditionally NIH `matches!` macro :) Most added APIs are very simple. For complex things I like to define no-op types which get swapped if a feature is on. [Example in `io_check` crate](https://github.com/Kixunil/io_check/blob/946c3ebce1664b7b80e2c6dc98b61e3fb49fa768/src/backtrace_impl.rs) The rest of the crate is cfg-free aside from the `track_caller` attribute.

**Comment by thomaseizinger** [comment]
Not sure if anyone is aware but https://docs.rs/autocfg/latest/autocfg/ might help here without having a feature explosion.

**Comment by Kixunil** [comment]
@thomaseizinger I'd prefer to have something simpler without dependency. There's no feature explosion, just emit feature for all relevant versions lower or equal to the current one.

**Comment by Kixunil** [comment]
This was already implemented for a while.
