### ISSUE TITLE
Pin serde in tests

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1175]
`serde` now uses `resolver` feature which isn't supported by our MSRV. Our CI breaks without pinning.

**Comment by tcharding** [comment]
All this pinning is kind of shit, if `serde` experiences a critical bug and patches it, along with a patch version bump, what are we supposed to do?

**Comment by Kixunil** [comment]
MSRV-using users are still screwed in such case though.
