### ISSUE TITLE
Messed up release

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1176]
We messed up by accidentally publishing our internal macros. This is mainly my fault for incorrectly using `macro_export`. I've read they are not exported from crate unless in root but didn't verify it and it looks like it's wrong. I will submit a PR soon.

Suggested approach: release 0.29.1 and yank 0.29.0. Hopefully nobody started depending on it yet.

**Comment by apoelstra** [comment]
ACK releasing 0.29.1 and yanking 0.29.0.

I wouldn't worry too much about the breakage. This is certainly not the first time we've messed up macro visibility :)
