### ISSUE TITLE
Release version 0.29.1

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1184]
I've created the branch `0.29.x` with a commit bumping the version and an entry in changelog, it can be used for release.

**Comment by tcharding** [comment]
Any reason https://github.com/rust-bitcoin/rust-bitcoin/pull/1177/commits/94eeabfd6c3de9102a3ba05ac2853683bb8492ad is not on the branch before the release commit?

**Comment by Kixunil** [comment]
Because I made it when too tired. It's fixed now. I can change to a different branch if that's desired, I wanted it out ASAP.

**Comment by apoelstra** [comment]
Looks good! Tagged, signed and published. Thanks for doing the fiddly branch work.

**Comment by Kixunil** [comment]
I don't see 0.29 yanked. Did you forget or is crates.io messed up?

**Comment by apoelstra** [comment]
I just forgot. Should be yanked now.
