### ISSUE TITLE
Use `hex_literal` crate (at least in tests)

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1189]
The crate provides `hex!()` proc macro converting hex strings into arrays at compile time. It would help us avoid ton of annoying `Vec` conversions and prove length of the array which is sometimes useful. It's maintained by RustCrypto organization which should be trustworthy.

**Comment by apoelstra** [comment]
I disagree that they are trustworthy, at least as far as maintaining dependencies go. We have had trouble with them in the past.

**Comment by Kixunil** [comment]
Maybe pin `hex_literal` to specific version? If it's only a dev dependency it shouldn't make problems.

**Comment by apoelstra** [comment]
I really do not want a RustCrypto dependency in any capacity, especially for something as basic as this.

**Comment by Kixunil** [comment]
Do we really want to NIH a proc macro?

**Comment by Kixunil** [comment]
FYI my motivation is that for #1190 I had to expand some hex strings into slices to avoid annoying method calls.

But now I got an idea how it could be done with `const fn` (maybe), I'm going to try it.

**Comment by Kixunil** [comment]
Great news, I figured it out! I also realized it doesn't have to be usable in const context (our current `hex!` macro isn't) but I can still get fixed-size array type (without writing down the length!). I can make it usable in const fn since Rust 1.46 and a bit more nicely usable in const fn in Rust 1.57. :)

**Comment by apoelstra** [comment]
Thanks for following through! I imagine it's pretty frustrating to be shot down over a dev-dependency (I stand by my stance, I just acknowledge that it's frustrating).

**Comment by Kixunil** [comment]
I'm actually glad you challenged me to find a way to avoid proc macros. `const fn`s are really elegant and don't blow up compile times. :)

**Comment by Kixunil** [comment]
I turned my idea into [a crate](https://docs.rs/hex_lit/0.1.1/hex_lit/). We could use it for additional features like compile-time checking but don't have to. Also there is one case outside of tests where `hex!` macro is useful, so it may be better to have it as a normal dependency. I'm willing to share maintainership of course.

**Comment by Kixunil** [comment]
@apoelstra should I add `hex_lit` (not to be confused with `hex_literal`) dependency or should I NIH it? I can make you co-maintainer if you want and I'd make the crate 1.0 once it's tested a bit in `bitcoin`.

**Comment by apoelstra** [comment]
Yeah, I'd be fine with it. I'd like to eventually move it into `bitcoin-internals` I guess, but even better would be if we could just use `crev` to mark the dep as trusted.

cc @TheBlueMatt what do you think? This is a zero-dep additional dependency maintained entirely by @Kixunil

**Comment by Kixunil** [comment]
> even better would be if we could just use `crev` to mark the dep as trusted

Fully agree, feel free to ping me if I don't setup `crev` in two weeks. :)

**Comment by Kixunil** [comment]
Ping @TheBlueMatt

**Comment by tcharding** [comment]
I've reviewed and published a crev proof for `hex_lit`.

**Comment by tcharding** [comment]
@Kixunil commented on the 3rd of December

> Fully agree, feel free to ping me if I don't setup crev in two weeks. :)

I don't see a `crev-proofs` repository on your github account so I'm guessing you haven't gotten around to setting up `crev` - this is your friendly reminder :)

**Comment by apoelstra** [comment]
@tcharding could you set up a `contrib/` script of some sort that would let us dump crev output?

It looks like from https://github.com/rust-bitcoin/rust-bitcoin/discussions/1396 that we just need to run `cargo crev verify --for-id <ID>`. Fine for you to hardcode your own ID, at least for now.

**Comment by tcharding** [comment]
Sure thing can do.

**Comment by Kixunil** [comment]
I've sent you collaboration invites.

Regarding `crev`, I didn't figure out some Qubes issues, will probably give up more extreme setup but would still prefer to not have to review whole crev code just to use it. Obviously I can't use crev to check itself if I don't have it. Also will need to get Rust GPG keys from trusted source.
