### ISSUE TITLE
Don't Panic if slice is not hex encoded

### ISSUE THREAD

**Issue by JeremyRubin** [rust-bitcoin/rust-bitcoin#1193]
Not sure when we'd hit this, but seems like panicking is definitely wrong.

https://github.com/rust-bitcoin/rust-bitcoin/blob/67e88e732ce6953baf32e248c42829a5a779d31e/src/util/psbt/serialize.rs#L128

**Comment by apoelstra** [comment]
We are literally decoding from a slice, not from hex. How could we possibly get a hex error?

**Comment by Kixunil** [comment]
Would be nicer to prove it via type system. I already wanted to at least separate hex errors from everything else and this looks like a motivating case. Marking 1.0 since I'd like it to be resolved before stable.

**Comment by JeremyRubin** [comment]
That makes sense to me; we can have a different error type which encapsulates which subsystem the error is originating from, and make it so that slice can't throw hex.
