### ISSUE TITLE
The name `is_final` requires historical Bitcoin knoweldge to understand

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1198]
EDIT: The thread of discussion below resolves to the following tasks to close this issue
1. Add new more descriptively named method to replace `is_final`
2. Document with notes on the term 'final' used in Bitcoin Core for historical context
3. Deprecate `is_final`

## Original issue text

I never know why we used the term 'final', as in `Sequence::is_final`. Yesterday @llfourn suggested it might be because the sequence number in the original Bitcoin code was intended to be incremented in order to replace a transaction, so once the sequence number got to `u64::MAX` it could no longer be increased, hence it was 'final'.

Two issues:
1. Do we even need to provide this public method `Sequence::is_final`?
4. If we do need to provide it can we come up with a more descriptive name for what ever use case there is for this method?

**Comment by LLFourn** [comment]
The actual semantics of it seems to be `disables_absolute_locktime`.

**Comment by apoelstra** [comment]
Sequence numbers are for relative locktimes, not absolute locktimes.

The modern semantics of finality is that setting this flag disables RBF (though there are murmers about ignoring the flag in the near future..). I think "final" continues to be a reasonable word for this, even ignoring the fact that this is a widely used and understood term in the Bitcoin developer community.

**Comment by LLFourn** [comment]
> Sequence numbers are for relative locktimes, not absolute locktimes.

I wish this were the case but it's not. The `0xFFFFFFFF` sequence value is for disabling absolute locktimes. In particular if all seqence numbers in a tx are set to that value then the `lock_time` field is ignored ([bitcoin wiki reference](https://en.bitcoin.it/wiki/Protocol_documentation#tx)).

> The modern semantics of finality is that setting this flag disables RBF (though there are murmers about ignoring the flag in the near future..). I think "final" continues to be a reasonable word for this, even ignoring the fact that this is a widely used and understood term in the Bitcoin developer community.

According to BIP125 there are two values that disable RBF though: `0xFFFFFFFE` and `0xFFFFFFFF` why should only the latter be called final?

**Comment by Kixunil** [comment]
Heh, I knew the context so `is_final` didn't seem too strange to me but now that you bring it up I believe it makes sense to rename it. However using a method for appropriate semantics is better: `is_rbf()`, `enables_absolute_locktime()`... Then `final` should not be needed. If there's a very specific niche case for needing it people can just use `x == Sequence::MAX`

**Comment by apoelstra** [comment]
>I wish this were the case but it's not. The 0xFFFFFFFF sequence value is for disabling absolute locktimes. In particular if all seqence numbers in a tx are set to that value then the lock_time field is ignored (bitcoin wiki reference).

lol TIL.

I'm fine with adding more descriptive names but i do think we should have `is_final` because it's a one-ilner and people familiar with Bitcoin will be expecting it.

**Comment by tcharding** [comment]
> lol TIL.

Holy shit, if there are corner cases in the timelocks that someone messing with Bitcoin as long as you doesn't know off hand it poses the question, perhaps the timelocks are too complicated :)

**Comment by apoelstra** [comment]
>Holy shit, if there are corner cases in the timelocks that someone messing with Bitcoin as long as you doesn't know off hand it poses the question, perhaps the timelocks are too complicated :)

Yes :) yes, they are.

Hopefully we can design an API so that we'll only need to know this stuff once, when writing the code, and then the API will hold our hands..

**Comment by LLFourn** [comment]
Do we a agree that `is_final` is a name that is left over from the now defunct use of sequence numbers where a tx could be replaced by one with a higher sequence number? If so then docs explaining this would have been sufficient to avoid the trouble @tcharding went through with me to explain this to me. I think an alias method `disables_absolute_locktime` which is the current semantics of that value would be helpful too.

**Comment by tcharding** [comment]
> I'm fine with adding more descriptive names but i do think we should have is_final because it's a one-ilner and people familiar with Bitcoin will be expecting it.

@LLFourn my interpretation from this comment is that @apoelstra would ack the addition of a more descriptively name method that calls `is_final()` - with some nice docs explaining the history of 'final' I'd say. If you are too buys just say and I'll throw it on my todo list.

**Comment by LLFourn** [comment]
ACK thanks @tcharding!

**Comment by tcharding** [comment]
>  I'll throw it on my todo list

Hell, I added 'good first issue' to see if it magically gets done for me :)

**Comment by Kixunil** [comment]
Actually this is `!enables_absolute_lock_time()` (which ironically calls `!final()`). Since we have it there already I suggest we just deprecate `final` and move the body of `is_final` into `enables_absolue_lock_time` and negate it.
