### ISSUE TITLE
use mioco for io operations

### ISSUE THREAD

**Issue by chpio** [rust-bitcoin/rust-bitcoin#12]
i thought mioco/mio is "the" io lib for rust?! We should maybe consider using it instead of the blocking std::net module.

**Comment by chpio** [comment]
or much simpler: allow the user to pass in an trait object (and provide a default std::net implementation).

**Comment by apoelstra** [comment]
@chpio rust-bitcoin is much older than mio.

I'll leave this bug open because I would like to explore using mio, but doing so would amount to rearchitecting all the network code and I don't have the time to do this right now.

**Comment by dongcarl** [comment]
Could we close this with the deprecation of most low-level networking here: https://github.com/rust-bitcoin/rust-bitcoin/issues/155?

**Comment by apoelstra** [comment]
Yes

**Comment by TheBlueMatt** [comment]
I mean if anything we should probably move all the networking stuff out of rust-bitcoin.

**Comment by dongcarl** [comment]
@TheBlueMatt doing so in #155

@apoelstra I don't have permission to close tickets

**Comment by apoelstra** [comment]
Sure, I'll close this.

@TheBlueMatt I was planning to deprecate it all for a version first and see if anyone comes out of the woodwork as actually using this stuff.
