### ISSUE TITLE
`impl_display_from_debug` should be `impl_debug_from_display`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1201]
The macro tempts us to slap `#[derive(Debug)]` on a type and then use the macro but that is wrong since `Debug` must not be used in human-friendly contexts (the reverse is OK though). The macro should do the opposite and all existing `Debug` impls that also provide `Display` should be changed to implement `Display` instead.

**Comment by tcharding** [comment]
Good first issue?

**Comment by hrouis** [comment]
Hell, i am relatively new to rust and this project, i wanted to chip in with this issue. I began implementing Display on structs and enums using the original macro.  Is it ok to use something like [strum](https://docs.rs/strum/latest/strum/) for deriving Display for big enums like _Ordinary_ ?

**Comment by apoelstra** [comment]
Hi @hrouis, and welcome to the project!

Thanks for asking, but no, we really strive to minimize our dependency tree. I'm happy to elaborate more on the reasons for this, but the upshot is that we can't accept a new dep for something as straightforward as this.

**Comment by tcharding** [comment]
This was fixed by #1204
