### ISSUE TITLE
Make network compatible with `bitcoind -chain=NETWORK`

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-bitcoin#1207]
It would be nice if `Network.to_string()` could be used as an argument to `bitcoind`'s `-chain` flag.

This could be done if `Network::from_str` supported `main` as an alias for `Network::Bitcoin`, and `test` as an alias for `Network::Testnet`. `regtest` and `signet` are already supported. For completeness, I would also add `mainnet` as an alias for `Network::Bitcoin`, since it's probably commonly used as an alias for mainnet that `bitcoin`.

**Comment by apoelstra** [comment]
Sounds good to me. I don't think there's any obvious reason for the existing `to_string` implementation.

**Comment by Kixunil** [comment]
I think changing `Display` would at least break `electrs`, probably other things too. ACK parsing aliases.

We could also have `fn to_core_arg(self) -> &'static str` but not sure if it works with the proposed custom signet support.

**Comment by apoelstra** [comment]
We could probably just do `to_core_arg() -> String` ... it's inefficient but so is everything related to constructing a command-line string, and it's not like it'll be done in a tight loop.
