### ISSUE TITLE
`pmt_tests` takes too much time

### ISSUE THREAD

**Issue by RCasatta** [rust-bitcoin/rust-bitcoin#1214]
The test `pmt_tests` takes a little bit too much for a unit test, almost 10 seconds. 

Investigate if there is a solvable performance issue or at least breaking the test into 12 tests (one for each `tx_counts`) should help given nowadays available CPU parallelism.

**Comment by Kixunil** [comment]
Yeah, I'm not happy about total test time either. I looked briefly in the past but didn't see an obvious solution. Parallelism sounds good.

**Comment by hrouis** [comment]
AFAIK multithreading is not an option with no_std. Do you think async/await can enhance performance?

**Comment by Kixunil** [comment]
Tests always use `std` and even threads.
