### ISSUE TITLE
Method to calculate `PartiallySignedTransaction` fee

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-bitcoin#1220]
It can be done manually, but it would be nice if there was a method to calculate a transaction's fee. Perhaps `tx.fee()` or `tx.calculate_fee()`.

**Comment by Kixunil** [comment]
Impossible because `Transaction` would have to know previous outputs. It could be done on PSBT or with additional argument supplying previous outputs. In either case it'd would still return `Option`/Result` if previous outputs are not found.

**Comment by Kixunil** [comment]
Yep, this is useful for payjoin as well. So in a way duplicate of #630

**Comment by apoelstra** [comment]
Good to have a specific issue about this.
