### ISSUE TITLE
Missing fields from PSBT

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-bitcoin#1221]
I'm trying to calculate the fee for a PSBT. This requires knowing the sat values of the inputs and outputs. 

For witness inputs, this is easy, `Input::witness_utxo` is a TxOut, which contains the value. For non-witness inputs, `Input::non_witness_utxo` is a `Transaction`, so the index of the output being spent is required to figure out what the value is.

[BIP-174](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki) specifies that each input should have `PSBT_IN_OUTPUT_INDEX`, which is what's needed, but that seems to be missing from `PartiallySignedTransaction`.

The BIP also specifies that each output should have `PSBT_OUT_AMOUNT`, which is required to calculate the total output value. However, this also appears to be missing.

My first instinct is that I'm misunderstanding something, so I wanted to check. Am I understanding these fields correctly? Are they not present because they duplicate information in the `unsigned_tx` field?

**Comment by Kixunil** [comment]
You can just call [`iter_funding_utxos()`](https://docs.rs/bitcoin/latest/bitcoin/util/psbt/struct.PartiallySignedTransaction.html#method.iter_funding_utxos) on PSBT to get the iterator of funding outputs. FYI each index is in the input - within `OutPoint`.

**Comment by casey** [comment]
Nice, thank you, I missed that!

If fields are omitted because they duplicate other parts of the PBST (i.e. the `unsigned_tx`) it might be nice to document that.

**Comment by sanket1729** [comment]
@casey , those fields are not a part of BIP 174, but BIP370 (Psbt v2). Pbstv2 is currently a WIP in rust-bitcoin.

**Comment by sanket1729** [comment]
The progress can be tracked https://github.com/rust-bitcoin/rust-bitcoin/issues/1115

**Comment by casey** [comment]
@sanket1729 I'm a little confused, aren't PSBT_IN_OUTPUT_INDEX and PSBT_OUT_AMOUNT both mentioned in BIP-174? Or is BIP-174 updated with new fields?

**Comment by sanket1729** [comment]
@casey BIP174 is updated with new fields. The fields have rows "versions requiring inclusion"

**Comment by casey** [comment]
> @casey BIP174 is updated with new fields. The fields have rows "versions requiring inclusion"

Ahh, okay, I missed that, thank you!
