### ISSUE TITLE
`impl From<core::convert::Infallible> for $error_type`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1222]
All error types should implement this conversion to make error handling easier.

**Comment by PaarthAgarwal** [comment]
Please provide more context on this issue.

**Comment by Kixunil** [comment]
For each error type we should implement this:

```rust
impl From<core::convert::Infallible> for Error {
    fn from(never: core::convert::Infallible) -> Self {
        match never {}
    }
}
```

**Comment by tcharding** [comment]
Probably best to define and use a macro

**Comment by PaarthAgarwal** [comment]
> Probably best to define and use a macro

alright. I'm defining the macro in internals/src/errors.rs because I think error-handling macros should exist here. Is it okay?

**Comment by Kixunil** [comment]
Yep, that sounds good.

**Comment by Kixunil** [comment]
@tcharding it makes it easier to compose the code. Examples:

```rust
fn foo() -> Result<(), BitcoinError> {
    // ...
    // write_all from push_bytes
    vec.write_all(bytes)?; // works! Although something like .infallible() could be argued to be better
    // ...
}
```

A stronger reason
```rust
trait Foo {
    type Error;
    // ...
    // IIRC there's something like this in futures or tokio.
    fn convert_err<E2>(self) -> ConvertErr<Self, E2> where Self::Error: Into<E2>;
}
```

With this if something expects an object that returns specific error you can also pass any object that returns infallible and use conversion helpers.

**Comment by liamaharon** [comment]
Hi, I've opened a PR to hopefully close this issue https://github.com/rust-bitcoin/rust-bitcoin/pull/2516. 

Cheers
