### ISSUE TITLE
`Cargo.lock` strategy

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1230]
The current recommendation is to not commit `Cargo.lock` for libraries but commit it for binaries. The main reason being that it doesn't affect downstream crates. However I think that committing it has some value - it says "we tested this crate with these versions of dependencies". And if we review the crates (ensuring the hashes match) it also acts as a lightweight `cargo-crev`. (I myself don't want to commit to this for now, maybe around 1.0 where versions will be more stable.)

However we could have these problems: people accidentally changing and committing it possibly causing merge conflicts, older versions of crates not being recorded.
As a solution I propose having `Cargo-minimal.lock` and `Cargo-recent.lock`. CI will just copy them over `Cargo.lock` before run.
`Cargo-minimal.lock` would contain minimal versions (See #1229 ) and would be only updated when we update `Cargo.toml` (We can probably have a check for this.) `Cargo-recent.lock` could be updated more often but always in a distinct PR to not cause merge conflicts.

**Comment by apoelstra** [comment]
This is a neat idea. I like it.

**Comment by tcharding** [comment]
Cool, I'd like a script (with same name in each crate) that I can run during development that says
- Use `Cargo-recent.lock` and run enough tests that most silly mistakes are caught but I don't have to wait 10 minutes for `contrib/test.sh` to run (optimized for good-enough coverage and fast)
- As above for clippy

Would save me having to look up what feature set I need to run everytime I switch which carte I'm hacking on.

**Comment by Kixunil** [comment]
Yeah, same script will be used in CI.

**Comment by apoelstra** [comment]
@MUCCHU if you'd like to take a look at this, the strategy is pretty straightforward, though tedious:

1. Run `cargo update` in this repo with a recent rustc. Copy the resulting `Cargo.lock` to `contrib/Cargo.tested.lock`.
2. Run `cargo tree --all-features`. Then for every single package in the tree, run `cargo update -p <package> --precise <exact version>`.
3. Copy the resulting `Cargo.lock` to `contrib/Cargo.minimal.lock`.

In step 2, for `exact version`, you should check our Cargo.toml, and use the version specified there (for direct dependencies) or just bisection-search to find the oldest version that works (for indirect dependencies). After each `cargo update` you should re-run `cargo test --all-features` to check that things stil compile.

If something **doesn't** compile with a version that our Cargo.toml says it should, please edit the Cargo.toml and/or file a bug.

You might want to try this first on rust-bech32, rust-secp256k1, or rust-bitcoinconsensus, which are also maintained by us, but which have smaller dependency trees.

**Comment by Kixunil** [comment]
You can also just remove `Cargo.lock` and run `cargo +nightly check --all-features -Z minimal-versions` in step 2.

**Comment by MUCCHU** [comment]
Thank you for your help. Yesterday I was trying to run a github repo and my device ran out of storage(maybe because it tried to clone the entire bitcoin blockchain). And I am unable to boot into it. Somehow today I got terminal access via recovery mode and am backing up data. I will set up the system and get back to you.

**Comment by apoelstra** [comment]
I've spent a little bit of time trying this on rust-bitcoinconsensus. Right now our serde version is "1" which works out to `1.0.60` after all the other deps' min versions. But actually serde itself doesn't even *compile* on stable (it uses `feature(alloc)` which isn't allowed I guess) until `1.0.100` or so. And then we have some other "proc-macro panicked" kinda errors for a bit after that.

So I think our actual minimum serde version should be 1.0.103 everywhere. Though I'd like somebody to double-check that.

**Comment by Kixunil** [comment]
`<= 0.8.3` is definitely completely broken. Even if pinning via `Cargo.toml` wasn't a bad idea itself the version should be `>= 0.8.0, <= 0.8.3`

**Comment by apoelstra** [comment]
Agree, with schemars we should totally remove the pin.

Ironically, given how much I fought Jeremy over the inclusion of this crate, it actually has a pretty conservative/reasonable MSRV policy (it was 1.37, and in the latest version was bumped to 1.45). So for now, with 1.41, we should remove the pin and add a README line with `cargo update --precise` instructions. But after release when we move to 1.48 MSRV we can drop even that.

**Comment by tcharding** [comment]
#1696 should take care of schemars and other pinning stuff. I can't seem to find the PR that came past this last couple of days commiting lock files to the repo? That was to fix this issue, right?
