### ISSUE TITLE
Why do sighash tests manually parse json?

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1231]
`util::sighash` parses json manually without derive. Does this have a specific reason? It doesn't seem to test serialization... Unless there is a good reason I'd look into making a PR to change to derives since those are easier to maintain.

**Comment by sanket1729** [comment]
Are you referring to `bip_341_sighash_tests`? If so, then the answer is probably my unawareness about serde/reluctance to use it. 
The purpose of the code was to test the sighash value calculations, not the serialization values. Note that the serialization of intermediate hash values is not well defined in any spec. 

> Unless there is a good reason I'd look into making a PR to change to derives since those are easier to maintain.

There is no good reason. It was the most obvious thing I could think of while parsing test JSON data from the spec. Feel free to change it to derives as you see fit.

**Comment by Kixunil** [comment]
Thanks! I strongly recommend taking a look at `serde` derives. It's one of the most awesome libraries in Rust. :)
