### ISSUE TITLE
Manual implementation of `abs` method

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1247]
As of Rust 1.31.1 we have an `abs` method on signed integer types. We have manual implementations of `abs`, an artifact of our previous MSRV (Rust 1.29).

Example: https://github.com/rust-bitcoin/rust-bitcoin/blob/ed9012c25c937744028f92ed78cf4e17e41934e8/src/blockdata/script.rs#L236

**Comment by Kixunil** [comment]
It looks like in the example you gave we may actually prefer `unsigned_abs`. In general I'd suggest using that pretty much everywhere. (IMO `abs` should've been unsigned and there shouldn't have been a signed one but it's too late for that now :( )

Given we already use it in `amount` I suggest putting this into internals:

```rust
/// Extensions for signed integers
pub trait IntExt {
    type Unsigned;
    #[cfg(not(rust_v_1_51))]
    fn unsigned_abs(self) -> Self::Unsigned;
}

// impl IntExt for all signed ints with a macro copying `core`.
```

The cfg is to avoid warnings about potentially confusing methods.

**Comment by tcharding** [comment]
Oh wow, I did not even notice the signed return type - that's a bit silly isn't it. I like the `IntExt` trait idea. There may be other things in newer Rust that we can use too so this is a good pattern to add. FTR lets wait till[ `bitcoin-internals` ](https://github.com/rust-bitcoin/rust-bitcoin/pull/1239) merges before attempting this.

**Comment by jim4067** [comment]
let me try this

**Comment by tcharding** [comment]
Go for it, thanks!

**Comment by Kixunil** [comment]
Lol, we were both looking at it and didn't notice `as usize` instead of `as u64`...
