### ISSUE TITLE
`SchnorrSighashType` serialization

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1257]
Why is it via string? Shouldn't it be a number?

Marking as possible bug since we likely broke the format.

See also https://github.com/rust-bitcoin/rust-bitcoin/runs/8268615029?check_suite_focus=true#step:4:2331

**Comment by sanket1729** [comment]
This was done because the previous `EcdsaSighashType` also had the string impls. This is likely influenced by bitcoin core RPCs where we specify sighash types from strings. 

I personally prefer numbers, but stuck to consistency when dealing with `SchnorrSigHashType`

**Comment by Kixunil** [comment]
Core RPC sounds like a good argument that it's OK.
