### ISSUE TITLE
Fast hex encoding

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1261]
Blocked by #1239 

Make a buffering hex formatter as described in https://github.com/rust-bitcoin/rust-bitcoin/pull/1250#discussion_r966793131
and use it across the codebase.

**Comment by Kixunil** [comment]
There's not allocation in the code you linked. IDK what's `Formatter` doing but clearly [it's not fast](https://github.com/rust-bitcoin/bitcoin_hashes/issues/171).

**Comment by hashmap** [comment]
I mean `to_string` allocates a string 
```
let mut buf = String::new();
```
so then if we call a buffering `fmt` we would allocate one more time. Hence my understanding that `fmt` shouldn't  make any assumptions about formatter's buffering strategy, I could be totally wrong though.
 
I saw your benchmarks, I haven't profiled it, but I've a hunch that `byte_to_hex_digits` made a serious impact. Radix format code in fmt is generic, your hex-specific code clearly beats it, it's why there are a bunch of hex formatting crates out there.

**Comment by Kixunil** [comment]
`String::new()` doesn't allocate (on heap).

> `fmt` shouldn't make any assumptions about formatter's buffering strategy, I could be totally wrong though.

I wish this was true but it isn't. `Formatter` doesn't do any buffering and adding it today would be a breaking change because it'd change the behavior of the code.

> Radix format code in fmt is generic

Wow, I looked at the code and it indeed does generic conversion. I also added non-buffered version to the benchmark:

```
test tests::thirtytwo::manual_no_buf::sink   ... bench:         236 ns/iter (+/- 110)
test tests::thirtytwo::manual_no_buf::string ... bench:         400 ns/iter (+/- 108)
test tests::thirtytwo::maybe_uninit::sink    ... bench:          36 ns/iter (+/- 11)
test tests::thirtytwo::maybe_uninit::string  ... bench:          65 ns/iter (+/- 14)
test tests::thirtytwo::trivial::sink         ... bench:       1,315 ns/iter (+/- 79)
test tests::thirtytwo::trivial::string       ... bench:       1,644 ns/iter (+/- 135)
test tests::thirtytwo::with_buf::sink        ... bench:          48 ns/iter (+/- 13)
test tests::thirtytwo::with_buf::string      ... bench:          82 ns/iter (+/- 17)
test tests::thirtytwo::with_unsafe::sink     ... bench:          41 ns/iter (+/- 14)
test tests::thirtytwo::with_unsafe::string   ... bench:          78 ns/iter (+/- 30)
```

The change from trivial to manual impl is indeed huge but I still think that going from 236/400 ns to 48/82 ns (about 5x faster) is worth adding the buffer explicitly.

**Comment by hashmap** [comment]
I think `to_string` suffers from a few re-allocations of the buffer while growing, in our particular case we do know the size so I agree it makes sense to introduce the buffer

**Comment by elichai** [comment]
We can add something like https://docs.rs/hex/latest/hex/fn.encode_to_slice.html to https://docs.rs/bitcoin_hashes/latest/bitcoin_hashes/hex/index.html and use https://github.com/rust-bitcoin/rust-secp256k1/blob/master/src/lib.rs#L507 to implement this (or just use the `hex` crate?)

**Comment by Kixunil** [comment]
@elichai I have some WIP code to add to internals crate. I will make a PR once it's ready.

**Comment by Kixunil** [comment]
@elichai the basic infrastructure was implemented in #1268, we just need to change all code (incl. hashes) to use that instead.

**Comment by tcharding** [comment]
Partially done by #1443, if that merges we can remove `ToHex` altogether and close this issue.

**Comment by Kixunil** [comment]
We need to make hashes depending on `bitcoin_internals` and refactor.

**Comment by tcharding** [comment]
This is done soon as we use `hex-conservative`, right?

https://github.com/rust-bitcoin/rust-bitcoin/pull/1833/files

**Comment by apoelstra** [comment]
I think we should close it since it becomes a general "make hex faster" issue on hex-conservative.

**Comment by Kixunil** [comment]
Yeah, this is done.
