### ISSUE TITLE
`BufEncoder` trouble

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1270]
I wanted to change #765 to use the newly added encoder but found out I made a design mistake. It's not possible to create an owned `BufEncoder`. I went ahead to redesign it but hit another design issue: `OutBytes` can not be created from `&T` making `BufEncoder::as_ref(&self)` impossible. Note that either way I have to add a special trait for converting to `OutBytes`. `From` is no longer enough because there's additional requirement for the returned reference to not depend on external state.

I see these options:

* Change the type to unsized and just use normal references, very clean but requires `unsafe` which we already determined is OK in other parts of the code.
* Make an immutable version of `OutBytes` with some conversions - annoying, adding another public type for the user to think about (even though it should be irrelevant)
* Make `as_str` and `is_full` take `&mut self` - this looks silly but probably not too limiting
* Make the special trait empty and have a method on the sealed one. Possibly use a bespoke trick to prevent calling the hidden method (not sure if it'll work). This avoids concerning users with another public item but contains hidden implementation detail as `pub` items.

Any more ideas or view which is the best? I personally like the first and last option.

**Comment by apoelstra** [comment]
I'm curious what option (a) looks like.

Alternately is there a way we could use `Cow`-like tricks (maybe this is what the first option is..) or somehow set the lifetime to `'static` for owned `BufEncoder`s?

**Comment by Kixunil** [comment]
I will make a PR to showcase it.

For `Cow` we'd have to allocate which I don't want and still have to use unsized type. The only ways to set `'static` is to allocate a `Box<[u8]>` and **leak** it or use a thread local which depends on `std`. We could also just put a fixed-length array into `BufEncoder` without giving callers any choice but that'd needlessly zero-out unused bytes[1] which would be fixable with `MaybeUninit` requiring `unsafe`, defeating the whole idea of avoiding it.

[1] actually we already needlessly zero-out bytes, which may be even worse in serde via consensus encoding for small types like `TxOut`. If this ever becomes a problem we can switch to `MaybeUninit` - the entire point of my API design.
