### ISSUE TITLE
Rename `is_satisfied_by_lock` to `is_implied_by_lock` (or similar)

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1271]
This: https://github.com/rust-bitcoin/rust-bitcoin/pull/1258#pullrequestreview-1107172605 for relative lock times

**Comment by apoelstra** [comment]
Nice!

**Comment by tcharding** [comment]
I'm not convinced, please see my comment: https://github.com/rust-bitcoin/rust-bitcoin/pull/1258#issuecomment-1247330108
