### ISSUE TITLE
Add `CalculateNextWorkRequired` Method

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-bitcoin#1289]
A (potential-)user requested that we add it, and it makes sense that we should have some utility to do it. We'd also (possibly) use this in rust-lightning's block sync logic.

**Comment by RCasatta** [comment]
Some cue code https://github.com/blockstream/gdk/blob/master/subprojects/gdk_rust/gdk_electrum/src/spv.rs#L349

**Comment by tcharding** [comment]
#1997 duplicated this issue and was closed by https://github.com/rust-bitcoin/rust-bitcoin/pull/2740
