### ISSUE TITLE
Move src/util/patricia_tree.rs to its own crate

### ISSUE THREAD

**Issue by ProgVal** [rust-bitcoin/rust-bitcoin#13]
I think most of `patricia_tree.rs` could be used by other projects.
Could you move it to a new crate, so they can use it without depending on rust-bitcoin?

**Comment by apoelstra** [comment]
cc @Gankro should patricia_tree.rs be in its own crate or is there some general collections crates I should submit it to? Agreed it should not live in rust-bitcoin.

**Comment by Gankro** [comment]
Hey sorry, I'm afraid I'm contractually barred from participating much in this sort of thing. @apasel442 is in charge now, but the group of interest is https://github.com/contain-rs

**Comment by apoelstra** [comment]
Closing this since the Patricia tree has moved to https://github.com/rust-bitcoin/rust-bitcoin-chain (which is still not really the best place for it, but at least it's not here).
