### ISSUE TITLE
Windows supported filenames are not compatible to found fuzz test cases

### ISSUE THREAD

**Issue by RCasatta** [rust-bitcoin/rust-bitcoin#1308]
[This](https://github.com/rust-bitcoin/rust-bitcoin/blob/f6d838076e162e2b4259c4d447630dd6d4d52e9f/fuzz/travis-fuzz.sh#L5) (introduced [here](https://github.com/rust-bitcoin/rust-bitcoin/pull/360)) and the following lines would exit in case there are incorrect Windows file names.

I setup my server to cycle through fuzz targets with something like this:
```sh
#!/bin/bash
while :
do
  for FILE in fuzz_targets/*; 
  do 
    TRIMMED=$(echo $FILE | cut -c 14- | cut -f 1 -d '.')
    echo $TRIMMED; 
    ./travis-fuzz.sh $TRIMMED
  done
done
```

The issues I have is that found test cases like `'SIGABRT.PC.7ffff7db900b.STACK.e5a6c9c01.CODE.-6.ADDR.0.INSTR.mov____0x108(%rsp),%rax.fuzz'` Doesn't pass the windows test, thus preventing  following iterations.

**Comment by apoelstra** [comment]
I use the following script to fuzz locally
```
#!/bin/sh
export HFUZZ_BUILD_ARGS='--features honggfuzz_fuzz'
export HFUZZ_RUN_ARGS='-N500000000 --exit_upon_crash -v'
export RUSTFLAGS='--cfg=rust_secp_fuzz'
cargo hfuzz run $1
```
You probably want to replace the `-N5000000000` with a time limit, or nothing if you want to run forever.

I find this is easier to fit into larger scripts than the travis-fuzz script is.

**Comment by RCasatta** [comment]
yeah, better to avoid to use the script meant for CI...

I opened https://github.com/rust-bitcoin/rust-bitcoin/pull/1309
