### ISSUE TITLE
Pinning down an Error type for `SimpleDecoder` and `SimpleEncoder`

### ISSUE THREAD

**Issue by dongcarl** [rust-bitcoin/rust-bitcoin#131]
Per @apoelstra's [comment](https://github.com/rust-bitcoin/rust-bitcoin/pull/103#discussion_r209456345), we should pin down an Error type for `SimpleDecoder` and `SimpleEncoder`. I believe we should define a type `network::serialize::Error` that is a variant of `util::Error`.

Why we shouldn't just use `util::Error`:

### Reason 1

It stops the overpopulation of `util::Error` variants.

### Reason 2

In files such as `script.rs`, if we did
```
use ::Error;
```
Such that we can do
```
fn consensus_decode(d: &mut D) -> Result<Script, Error> {
    ...
}
```
It would trigger a namespace conflict with `script::Error`.

Note: this is assuming that we do
```
pub use util::Error;
```
at the top-level `lib.rs`.

**Comment by apoelstra** [comment]
Sounds good to me.

Agree that I'd prefer `util::Error` to be an enum of module-specific errors and have few (if any) top level error conditions.

**Comment by dongcarl** [comment]
@apoelstra Should we differentiate `serialize::Error` into `serialize::EncodingError` and `serialize::DecodingError`?

```
pub enum Error {
    Encoding(EncodingError),
    Decoding(DecodingError),
}

pub enum EncodingError {
    ...
}

pub enum DecodingError {
    ...
}
```

**Comment by apoelstra** [comment]
I wouldn't - I think serialization errors are always `io::Error` and the deserialization error type already needs an io variant.

**Comment by dongcarl** [comment]
It seems like a lot of `util::Error` variants will now be moved to `serialize::Error`. Could people assist me in identifying which ones would make sense to move? I will move them and then attempt to appease the compiler.

```
pub enum Error {
    /// An I/O error
    Io(io::Error),
    /// Base58 encoding error
    Base58(base58::Error),
    /// Bech32 encoding error
    Bech32(bitcoin_bech32::Error),
    /// Error from the `byteorder` crate
    ByteOrder(io::Error),
    /// Network magic was not what we expected
    BadNetworkMagic(u32, u32),
    /// Network message was unrecognized
    BadNetworkMessage(String),
    /// An object was attempted to be added twice
    DuplicateHash,
    /// Some operation was attempted on a block (or blockheader) that doesn't exist
    BlockNotFound,
    /// Parsing error
    ParseFailed,
    /// An object was added but it does not link into existing history
    PrevHashNotFound,
    /// secp-related error
    Secp256k1(secp256k1::Error),
    /// The `target` field of a block header did not match the expected difficulty
    SpvBadTarget,
    /// The header hash is not below the target
    SpvBadProofOfWork,
    /// Error propagated from subsystem
    Detail(String, Box<Error>),
    /// Unsupported witness version
    UnsupportedWitnessVersion(u8),
}
```

Initial guesses:
```
    /// An I/O error
    Io(io::Error),
    /// Base58 encoding error
    Base58(base58::Error),
    /// Bech32 encoding error
    Bech32(bitcoin_bech32::Error),
    /// Error from the `byteorder` crate
    ByteOrder(io::Error),
    /// Network magic was not what we expected
    BadNetworkMagic(u32, u32),
    /// Network message was unrecognized
    BadNetworkMessage(String),
    /// Parsing error
    ParseFailed,
    /// Error propagated from subsystem
    Detail(String, Box<Error>),
```

**Comment by apoelstra** [comment]
Looks good to me. Also a few of these aren't used anywhere .. `DuplicateHash` and `PrevHashNotFound` and `BlockNotFound`. They can just be deleted.

**Comment by apoelstra** [comment]
See also #134
