### ISSUE TITLE
Completely wrong implementation of `From` in `impl_array_newtype`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1336]
NO, NO, NO, NO, NO!!!! This is completely wrong implementation of `From`. Should've been `TryFrom` or `From<[$ty; $len]>`

_Originally posted by @Kixunil in https://github.com/rust-bitcoin/rust-bitcoin/pull/1293#discussion_r1001724546_

**Comment by apoelstra** [comment]
This would be a dramatic reduction in ergonomics, because it forces people to `.unwrap()` slices that they know full well have the correct length.

**Comment by apoelstra** [comment]
cc https://github.com/rust-bitcoin/rust-bitcoin/pull/1223 for an example of what this looks like. (Which, ok, if this this the direction the Rust ecosystem is going in, I won't fight it. But there are dramatically more `.expect`s now with the stdlib API than there were with mine.)

**Comment by Kixunil** [comment]
Correctness > ergonmics IMO. You find it obvious that the size is correct but someone else somewhere misses it and gets DoS vector. I suggested to implement `From` for *arrays* which may help at least in some cases.

But maybe I shouldn't even argue about this since panicking breaks the contract of [`From`](https://doc.rust-lang.org/std/convert/trait.From.html):

> **Note: This trait must not fail.** The From trait is intended for perfect conversions. If the conversion can fail or is not perfect, use [`TryFrom`](https://doc.rust-lang.org/std/convert/trait.TryFrom.html).

Also if `try_into().expect()` is too annoying I wouldn't be opposed to a method like `unwrap_from_slice` that is documented to panic on invalid length. It's mainly that `from` MUST not.

> there are dramatically more .expects now with the stdlib API

This may be an indicator that we do something else wrong and we should think twice about that.

**Comment by tcharding** [comment]
>> there are dramatically more .expects now with the stdlib API

> This may be an indicator that we do something else wrong and we should think twice about that.
@Kixunil

I didn't think of that, the stdlib API usage code I wrote is horrible. I'll add investigating if it can be done more cleanly to my todo list.

**Comment by apoelstra** [comment]
We're allowed to break the contract if the user breaks it first. Giving an incorrectly sized slice is a breach of contract.

>This may be an indicator that we do something else wrong and we should think twice about that.

No, it's an indication that Rust's support for slices with obvious and known-at-compile-time sizes is severely lacking, and we have to compensate with panics that we hope will be optimized away.

**Comment by Kixunil** [comment]
>  Giving an incorrectly sized slice is a breach of contract.

It is not, `From` doesn't require any property of the value that is not mandated by the type of the value.

> it's an indication that Rust's support for slices with obvious and known-at-compile-time sizes is severely lacking

That is also sometimes the case. I tried playing with slice patterns but concluded it's currently unusable for our use case. However panicking must be clear at the caller site, not hidden inside something that's generally expected not to panic.
