### ISSUE TITLE
Add Witness::from_slice method.

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1371]
`Witness::from_vec` exists but there's no good reason for requiring `Vec`. `pub fn from_slice<B: AsRef<[u8]>>(slice: &[B])` would be more useful. (Or `IntoIterator<Item=B> + Clone`)

Also deprecate `from_vec` after this is done.

See https://github.com/rust-bitcoin/rust-bitcoin/pull/1323#discussion_r1014900571_

**Comment by apoelstra** [comment]
Sounds good to me. We should have a doccomment on the `Witness` type itself though explaining how to use this function to convert a `Vec<Vec<u8>>` (which is the "natural" way to represent a witness in primitive/std types) into a `Witness`.

**Comment by Kixunil** [comment]
Done.
