### ISSUE TITLE
`Witness` should impl `From<Vec<Vec<u8>>>`

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#1385]
cc #1298 #1302 which are similar issues with discussion on the merits of `From`.

**Comment by Kixunil** [comment]
I'm more open to this than the others given `Vec<Vec<u8>>` is less usual and thus less likely to be confused. I'd even consider `From<T> where T: AsRef<[U]>, U: AsRef<u8>` but I think coherence won't let us. Anyway if we have `From<Vec<Vec<u8>>` we should also have at least `From<&[&[u8]]>`, `From<&[Vec<u8>]> and `From<Vec<&[u8]>`.

**Comment by Kixunil** [comment]
This was implemented.
