### ISSUE TITLE
Bunch of doc warnings

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1403]
`cargo +nightly doc` shows a bunch of warnings. We should fix them and add a check to CI to avoid them in the future.

**Comment by tcharding** [comment]
18 minutes from issue to PR, even with devs on opposite sides of the world - oooo yes :)

**Comment by Kixunil** [comment]
Honestly, I should be already sleeping now... But my sleep schedule is completely out of whack last week so I don't mind too much. :)

**Comment by apoelstra** [comment]
Lol, sorry guys, I'm reviewing this with a 16 hour delay.

**Comment by tcharding** [comment]
Killing our run rate, you slacker :)
