### ISSUE TITLE
Add `.weight()` for transaction components

### ISSUE THREAD

**Issue by LLFourn** [rust-bitcoin/rust-bitcoin#1411]
In https://github.com/rust-bitcoin/rust-miniscript/pull/476 we're sensibly changing the definition of `max_satisfaction_weight` to "how much more weight would satisfying this input add over `TxIn::default()`" but it occurred to me that we don't have a `.weight()` function on `TxIn`. I think it would be good if `TxIn`to make this a little more concrete. 
While we're there I think we might as well add it to `TxOut` too.

Of course we should stress in the docs that adding a `TxIn` (or `TxOut`) to the transaction does not necessarily mean that only`TxIn::weight()` is being added to the total -- it might be more if (i) that `TxIn` is a segwit input and there have been no segwit inputs added so far and (ii) if it causes the varint length to increase (which is applicable to `TxOut` too).

**Comment by Kixunil** [comment]
Indeed, see also #630

**Comment by LLFourn** [comment]
It seems like I was actually mistaken about what we we decided upon for the rust miniscript PR. See https://github.com/rust-bitcoin/rust-miniscript/pull/476#discussion_r1029981112

**Comment by LLFourn** [comment]
An idea came up during a discussion that it might not make sense to have `Txin::weight` but rather think that it would make sense to have it on a list of `TxIn` as this would allow us to account for segwit witness stack lengths and segwit header.

**Comment by evanlinjin** [comment]
How about `TxIn::max_weight(&self)` which always assumes that this txin or an adjacent txin is a segwit-spend. So the definition of `<miniscript-thing>.max_weight_to_satisfy` is `txin.weight() - TxIn::default().max_weight()`.

**Comment by danielabrozzoni** [comment]
Opened #1467 to add `segwit_weight` and `legacy_weight` to txins, the naming should be clear enough :)

**Comment by LLFourn** [comment]
Fixed in https://github.com/rust-bitcoin/rust-bitcoin/pull/1467
