### ISSUE TITLE
Improve `SigHashCache` API to allow storing the cache

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1423]
## Background

I'm making a protocol that uses multisig. I need one participant to sign a PSBT, then wait for a signature from another participant and verify that signature before proceeding. Ideally these operations would reuse cached hashes since the signatures are signing the same thing. The signatures obviously need to go to relevant PSBT field.

However because the current API prevents access to `Transaction` while `SigHashCache` is being used I can not use (wrapped) `Psbt` as the parameter. Passing only `psbt.unsigned_tx` is also impossible because it'd require storing the data in a self-referential type.

## Proposed solution:

* Add `transaction()` and `transaction_mut()` accessors (possibly with `dangerous_` prefix explaining what must not be changed)
* `Deref` is ugly for this - change it to `AsRef`
* `impl As{Ref,Mut}<Transaction> for Psbt` - while it may be surprising to some people, I believe it's reasonable
* `impl As{Ref, Mut}<Transaction> for Transaction` for convenience - for people

## Alternative

Don't add `(dangerous_)transaction_mut` but accessors to `Psbt` fields that are not `unsigned_tx`. This is almost(1) fool-proof but maybe more annoying.

1: it's already not fool proof (and cannot be generically) because the reference returned from `deref` is not guaranteed to be stable - `fn deref(&sefl) -> &Self::Target { if random() { &self.tx1 } else { &self.tx2 } }`

I will happily send the PR, just making sure I'm not missing something.

**Comment by apoelstra** [comment]
I would suggest providing a `transaction` accessor and a `into_transaction` method that simply destroys the cache for users who want to mutate it.

We could also maybe add specific methods e.g. `add_input` which could selectively invalidate some parts of the cache.

I don't see how we can implement `As{Ref,Mut}<Transaction>` for `Psbt` since PSBT doesn't actually store a transaction (at least, it doesn't in PSBT2).

**Comment by Kixunil** [comment]
> destroys the cache for users who want to mutate it.

That doesn't help with the use case. I need access to `Psbt` with the implicit promise that I won't mutate `unsigned_tx` (that's why `dangerous_` prefix). It's OK to take such responsibility because the code can already be broken by bad `Deref` impl. Actually, now I realize I could make a terrible hack using `UnsafeCell` but I'd rather not.

> at least, it doesn't in PSBT2

Oh, crap, good point! So we would need something like `trait TransactionAccess` which has methods to retrieve individual parts of the transaction. We could also have blanket `impl TransactionAccess for T where T: Borrow<Transaction>`.

**Comment by apoelstra** [comment]
We may want to have the PSBT own a sighash cache, even when it doesn't have a transaction, and then have certain mutators invalidate it.

This would be the kind of thing where hopefully we could lean on the type system to keep track of the dependencies.

**Comment by Kixunil** [comment]
Oh, that's a neat idea. We could even make it near-zero cost for uses not requiring the cache by relying on empty collections not allocating or `Option<Box<Cache>>`.

**Comment by Kixunil** [comment]
I just noticed I missed `witness_mut` :man_facepalming:

Since I opened this I came to conclusion that PSBTs are too much hassle for my project and I'm using `Transaction` directly. I still think `Borrow` is better though.

**Comment by tcharding** [comment]
> Since I opened this I came to conclusion that PSBTs are too much hassle

Is this, in your opinion, because of PSBTs or because of _our_ implementation of PSBTs. I came to the same conclusion more or less when I worked on the PSBT examples.

**Comment by Kixunil** [comment]
Not entirely, the same reason I said elsewhere: they are not type safe, so they are useful as a general-purpose interchange format but not as internal data structure nor interchange format for custom protocols.

**Comment by apoelstra** [comment]
This makes sense -- I've had the same impression. That I can use the PSBT types but I have to check the docs all the time to make sure I'm coloring between the lines.

We should strive to fix this but it won't be easy.
