### ISSUE TITLE
Accellerate hashes using SIMD or SHA-NI

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#1424]
Opening this issue here from bitcoin_hashes.

We can use SIMD with stable rust 1.41. We should, to speed up our hashing computation.

**Comment by Kixunil** [comment]
For other confused people seeing `core::simd` unstable, this function and a few others are stable: https://doc.rust-lang.org/core/arch/x86_64/fn._mm_sha256msg1_epu32.html

**Comment by Kixunil** [comment]
@TheBlueMatt is it possible to compute more hashes in parallel while also using platform-native instructions? If not which is faster?

**Comment by RCasatta** [comment]
Just to add that I see sha `<bitcoin_hashes::sha256::HashEngine as bitcoin_hashes::HashEngine>::input` taking a big slice in profiling processes.

[This profile](https://share.firefox.dev/3rM10yr) is from electrs running https://github.com/romanz/electrs/blob/fae1e61946c4a837665e7bbb397ece5e313b8e6b/contrib/history.py @romanz

**Comment by apoelstra** [comment]
This recent blog post may be relevant: https://ipthomas.com/blog/2023/07/n-times-faster-than-c-where-n-128/

We should add some hashes benchmarks (or see if we already have them) and then experiment as to whether we can get some SIMD advantage just be restructuring our code to be more iterator-like.

**Comment by sanket1729** [comment]
I am taking a stab at this.

**Comment by sanket1729** [comment]
Another question about simd internsics. I don't think think rustc has runtime detection for these features. https://rust-lang.github.io/rfcs/2045-target-feature.html still is a WIP. 

Should we just support generating conditional compile time code with sufficient documentation that the generated code is not portable across machines as it uses some SIMD interensics that might not be sufficient. I think the RustCrypto folks do some sort of runtime detection of features. We can also look into that by adding a dependency on `cpufeatures` if desired.

**Comment by RCasatta** [comment]
Aren't these macros useful for runtime detection?

https://doc.rust-lang.org/std/arch/macro.is_x86_feature_detected.html
https://doc.rust-lang.org/std/arch/macro.is_aarch64_feature_detected.html

**Comment by elichai** [comment]
There's also: https://docs.rs/cpufeatures/0.2.9/cpufeatures/

**Comment by sanket1729** [comment]
I was debating intially as `cpufeatures` as it has `no-std` for x86. I think I will go without `cpufeatures` and only std support for starters.

**Comment by elichai** [comment]
> I was debating initially as cpufeatures as it has no-std for x86. I will go without cpufeatures dependency and only std support for starters.

If you really want you can do it manually similar to: https://github.com/nervosnetwork/faster-hex/pull/23/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759 ;)

**Comment by RCasatta** [comment]
https://github.com/rust-bitcoin/rust-bitcoin/pull/1962

**Comment by Kixunil** [comment]
Is this open because of merkle tree optimization? Also I wonder if optionally providing `rayon` feature to parallelize merkle tree computation would be a good idea.

**Comment by apoelstra** [comment]
I think it's worth benchmarking, but I would guess that the task management overhead would take away a lot of the benefit. Though maybe if we use rayon intelligently enough we can efficiently split trees across all processors close to the root and then easily avoid further switching.

If the complexity exceeds, say, a 20 line function, I feel like such a thing should go in another crate, since it adds another dimension to our test matrix and increases our maximum dependency footprint. But if it's really easy to do, maybe that'd be ok.

**Comment by Kixunil** [comment]
Implemented in 546c0122d73146f69a7f8d5b6bd29800fbba3119

**Comment by RCasatta** [comment]
Fyi Electrs decided to continue to use sha2 crate because we haven't acceleration also for arm yet
