### ISSUE TITLE
Parameterize hashes by whether they are known to be hashes; add trait marker to indicate this

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#1425]
In short, yes, that is my preference.

I think with some extra complexity we could do this non-invasively, by parameterizing all the hashes by a dummy type `KnownPreimage`/`UnknownPreimage` or something, which would

* Default to `UnknownPreimage`
* `KnownPreimage` would only be constructible from hash engines/`hash` method, while `UnknownPreimage` would have the full set of existing constructors (`from_slice`, serde, etc)
* There would be an explicit `_unchecked` method for going from `Unknown` to `Known` and a `From` impl for going the other way
* Only `KnownPreimage` would impl `ThirtyTwoByteHash`

I think that, because of the default type parameter, most users of hashes who are just sticking them into data structures (outpoints etc) but not directly manipulating them, would require no changes to their code. Then because `ThirtyTwoByteHash` only works with the `Known` type parameter, type inference would mean users who are hashing stuff then signing/verifying the result would **also** require no changes to their code.

Only users who are both parsing hashes directly *and* doing EC crypto with them would need to change their code -- which I expect would be rare, and would also benefit from some more explicitness about how/when the hash becomes trusted.

_Originally posted by @apoelstra in https://github.com/rust-bitcoin/rust-bitcoin/issues/1090#issuecomment-1180522293_

**Comment by tcharding** [comment]
Closing in favour of #2937
