### ISSUE TITLE
Expose an API to create tagged hashes from string?

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#1427]
I see that the current preferred way in the library to create tagged hashes is to `Impl Tag` on the struct. Would it be useful to add a simple method that takes in String and outputs a BIP340 tagged HashEngine. 

Currently, it seems there is some code bloat when what in almost all cases what we need is 

`let hasher = HashEngine::from_bip340tag(&str)`;

This is inefficient compared to precomputing the Midstate, but is really handy for more general applications of bip340 tagged hashes and some quick prototyping. 

If there are no Nacks, I can add a PR to do this.

**Comment by Kixunil** [comment]
Could we have a `const fn` that outputs midstate and then a macro to create an ad-hoc tag by compile-time-computing midstate from a string? The const fn will be annoying to write because we can't have loops or mutable references in `const fn` (in current MSRV) but I think it should be *possible*.

**Comment by apoelstra** [comment]
It'd be a huge PITA to implement hash functions without loops

**Comment by Kixunil** [comment]
Recursive macros? :)

**Comment by apoelstra** [comment]
Hah, yep, that'd work.

Do you know offhand what MSRV we'd need to get (bounded) loops in const functions? IIRC we're pretty-much ready to move to 1.48, we just need a good reason to do it.

**Comment by Kixunil** [comment]
[1.46.0](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1460-2020-08-27) :) Just note that we will have to use C-style iteration (with index). Shouldn't matter for `const`.

**Comment by apoelstra** [comment]
Ok :) let's do it in 1.48 then.
