### ISSUE TITLE
How does the CI command running bip32 example work?

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1442]
How does this work
```rust
cargo run --no-default-features --features=no-std --example bip32 7934c09359b234e076b9fa5a1abfd38e3dc2a9939745b7cc3c22a48d831d14bd
```
When in the example we use types from `std`?

Head of `examples/bip32.rs`
```rust
extern crate bitcoin;

use std::str::FromStr;
use std::{env, process};

use bitcoin::address::Address;
use bitcoin::bip32::{ChildNumber, DerivationPath, ExtendedPrivKey, ExtendedPubKey};
use bitcoin::hashes::hex::FromHex;
use bitcoin::secp256k1::ffi::types::AlignedType;
use bitcoin::secp256k1::Secp256k1;
use bitcoin::PublicKey;

fn main() {
...
```

**Comment by Kixunil** [comment]
Because the example itself doesn't deactivate std with `#![no_std]`. I wonder if you thought `--features no-std` implies removal of `std`.

**Comment by tcharding** [comment]
`--no-default-features` deactivates "std" though?

**Comment by Kixunil** [comment]
Only in `bitcoin` crate and only because the `bitcoin` crate has conditional `#[no_std]`. The `std` crate in an executable is still the usual crate provided by Rust.

**Comment by tcharding** [comment]
Ohhhh of course, thanks man.
