### ISSUE TITLE
Taproot witness parsing

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-bitcoin#1447]
I'm writing an application that needs to extract the script from taproot script-path spends. I've implemented it myself, but I'm almost certain that my implementation is buggy, because the rules are quite complicated:

- Must check that that the output being spent is a taproot witness program
- Must check for the presence of the annex
- Must check for the presence of the control block

It would be nice if there was a method which could return the taproot script-path script from a witness. Something like:

```rust
fn extract_taproot_script_path_script(witness: &Witness, previous_output_script_sig: &Script) -> Option<Script> {
   // check that previous_output_script_sig is segwit v1 witness program
   // account for presence of annex
   // check for control block
   // parse correct witness element and return script
}
```

I don't need it for my application, but a more comprehensive version of this feature might return an enum to allow for returning script path or key-path spends:

```rust
enum TaprootSpend {
  Script { script: Script, initial_stack: Vec<Vec<u8>>, annex: Option<Vec<u8>>, control_block: Vec<u8> },
  KeyPath. { pubkey: Pubkey, signature: Signature },
}
```

**Comment by Kixunil** [comment]
It's already in the unreleased version https://github.com/rust-bitcoin/rust-bitcoin/blob/52fbb043b6bcb0143978d8f2903881f98b3094ca/bitcoin/src/blockdata/witness.rs#L316 :)

**Comment by Kixunil** [comment]
Also we should change the type to `&Script` once #1155 is done.

**Comment by casey** [comment]
Nice! What do you think about taking the previous output script pubkey, to avoid inadvertently trying to take the tapscript of a non-taproot witness?

**Comment by Kixunil** [comment]
IIUC the check is literally `script_pubkey.is_v1_p2tr()`. I think the documentation is sufficiently clear that it assumes Taproot but maybe we should add "See `Script::is_v1_p2tr` to check whether this is actually Taproot." so that people don't have to think too hard? I'd definitely accept such PR.

**Comment by casey** [comment]
That seems reasonable, I just opened #1483.
