### ISSUE TITLE
Both `relative` and `absolute` `Height` and `Time` are missing standard constants

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1451]
Missing constants: `MIN`, `MAX`
For height only: `ZERO` (alias for `MIN`)

Note for implementors: make sure `MAX` of relative doesn't mess up RBF flags.

**Comment by Kixunil** [comment]
But still make them `const fn` :)

**Comment by tcharding** [comment]
Woops my bad. Will do

**Comment by tcharding** [comment]
Done in: https://github.com/rust-bitcoin/rust-bitcoin/pull/1603
