### ISSUE TITLE
Consider conversion helper functions for all keys

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1453]
Currently to get a `bitcoin::PublicKey` from a `KeyPair` one must do
```rust
// Compressed pubkey.
let pk = PublicKey::new(kp.public_key())
// Uncompressed pubkey.
let pk = PublicKey::new_uncompressed(kp.public_key())
```

We have various conversion helpers for other keys, we should audit the keys and check conversion for all possible conversions (`PublicKey::from_private_key` and `PrivateKey::public_key`).

This issue was prompted by #1452, see there for more discussion.

**Comment by Kixunil** [comment]
Also `From` trait.

**Comment by Kixunil** [comment]
> take a generic Into<PublicKey> I think.

That sounds useful.
