### ISSUE TITLE
`PackedLockTime` is missing `From<Height>` and `From<Time>`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1455]
These are obvious and should be implemented. Example where this is useful:

```rust
Transaction {
    // ... other fields
    lock_time: height.into(),
}
```

**Comment by apoelstra** [comment]
I think we should just drop this type entirely. #1330

**Comment by Kixunil** [comment]
TBH, I'm starting to warm up to this. The perf benefits are really essentially zero (I saw someone measuring cost of branches and it's close to zero) and if manual impl on `Transaction` works it shouldn't be terrible.
