### ISSUE TITLE
`Script` is missing `From<Address>`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1457]
Some libraries may want to provide the flexibility of accepting any `script_pubkey` while the consumers usually want to provide an address. Accepting `Into<Script>` in such cases is better than having multiple methods.

Do it after #1155

**Comment by tcharding** [comment]
Does this mean by way of `addr.payload.script_pubkey()`? If so perhaps this should wait till script tagging is done?

**Comment by Kixunil** [comment]
Just `address.script_pubkey()`. Tagging is not required but surely would be less of a footgun.
