### ISSUE TITLE
`Address` handling is bit of a footgun

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1460]
I almost made this bug, twice:

```rust
let addr = string.parse::<Address>().expect("invalid address");
let tx_out = TxOut {
    value,
    script_pubkey: addr.script_pubkey(),
}
```

As you can see I forgot validation. Thankfully I did remember it before even compiling the code but it could theoretically happen that I wouldn't and it'd go into production. :scream: 

However I'm not sure how to improve this without making the API too ugly. Tagging the address seems to make most sense to me:

```rust
pub struct Address<V: Validation> { // which should be the default, if any? I suspect Checked because then creating new is assumed OK
    pub payload: Payload,
    pub network: Network,
    /* pub? */ _phantom: PhantomData<V>,
}

pub mod validation {
    pub enum Checked {}
    pub enum Unchecked {}
}

pub trait Validation: sealed::Validation {}

impl FromStr for Address<validation::Unchecked> { /* ... */ }

impl Address<validation::Unchecked> {
    /// Check if the address matches the expected network and prove in the type that this check was performed
    pub fn check(self, expected_network: Network) -> Result<Address<validation::Checked>, AddressValidationError> {
        if self.network == expected_network {
            Ok(self.assume_checked())
        } else {
            Err(AddressValidationError { expected_network, address: self })
        }
    }

    /// Marks that the caller already checked that the address belongs to appropriate network.
    // Should this have `dangerous_` prefix?
    pub fn assume_checked(self) -> Address<validation::Checked> {
        Address { payload: self.payload, network: self.network, _phantom: Default::default() }
    }
}

impl Address<validation::Checked> {
    pub fn script_pubkey(&self) -> Script { /* ... */ }
}

impl From<validation::Checked> for Script /* <ScriptPubkey> */ { /* ... */ }
```

Pros/cons:

* Idiomatic API with all the traits & stuff
* Accessing the fields for always-safe operations (e.g. displaying) has the same code - generic without forcing complicated address trait
* Quite a bit of boilerplate (as opposed to e.g. removing `FromStr` and replacing it with dedicated methods)
* Usage may be a bit annoying, but probably defaulting to checked is fine since unchecked will be only from outside sources which will be rare?

**Comment by Kixunil** [comment]
I wrote a [quick demo](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=aa92c6ddda0efcb7044d0b1db9825507) to demonstrate how inference affect this. I think the burden is minimal - apart from calling `check` one only has to add `<_>` (or `<validation::Unchecked>`) to `Address` when parsing. And the compiler message is very helpful in case it's missing (try it!).

I really like this API and I think pros outweigh the cons.

**Comment by apoelstra** [comment]
Rather than using `Checked`/`Unchecked`, we could tag the address with the network, but provide an `Any` tag which could be parsed as a string, but not converted to a scriptpubkey/etc unless you called a conversion method.

Or maybe `Address<Any>` could be an enum of all the "real" address types, and the user would be forced to destructure. (So the equivalent of `.assume_checked().script_pubkey()` would be to do a giant match and call `.script_pubkey` on each branch.)

**Comment by apoelstra** [comment]
> That would likely incentivize people to hard-code the network which is very bad. 

My first thought here was "no, it'd be either correct or immediately/visibly wrong"...

>  I know of at leas one, unfortunately popular, wallet that has mainnet hard-coded and it's practically untestable

...but lol. ok. I definitely believe people have (and will do) this.

I really wish we had dependent types in Rust, which are made for this kinda thing.

**Comment by Kixunil** [comment]
> more specific `CheckedNetwork`

OK, I think that makes sense.

**Comment by jirijakes** [comment]
I started to experiment with this one, may have a PR soon (within a day). So far it's looking better than I thought.
