### ISSUE TITLE
`TaprootMerkleBranch` API improvements

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1469]
Firstly, I think we should have `From` impls for all arrays shorter than 128. That's totally doable with macros and not an unreasonable number I believe. Secondly, it allocates even when the intention is to just encode `ControlBlock` to put into `Witness`. Maybe it should just be unsized and have `ControlBlock<B: AsRef<TaprootMerkleBranch>>`.

**Comment by tcharding** [comment]
- Part 1 is done in: https://github.com/rust-bitcoin/rust-bitcoin/pull/1613
- Part 2 is re-opened as a separate [issue](https://github.com/rust-bitcoin/rust-bitcoin/issues/1614) because it is an optimization.

**Comment by tcharding** [comment]
For context on the split, I'm trying to get the release ready, this issue is marked as an "API hole", all issues thus marked are candidates for this release. I do not want to include optimizations in my current workload.

**Comment by Kixunil** [comment]
It's an optimization that changes API but I guess it's OK to do it later.
