### ISSUE TITLE
Explore mutagen

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1480]
It looks like there are bunch of things missing tests. Maybe [mutagen](https://github.com/llogiq/mutagen) would help here.

**Comment by apoelstra** [comment]
What a cool crate! I remember doing something like this in the pre-1.0 days...it did not work for long. I totally forgot to revisit this.

huge ACK from me.

**Comment by tcharding** [comment]
https://github.com/rust-bitcoin/rust-bitcoin/pull/1484

**Comment by tcharding** [comment]
`mutagen` is in now.
