### ISSUE TITLE
Split `Hash` trait in two

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1481]
The `Hash` trait provides two interfaces:

* hashing arbitrary data
* "being an output of a hash function"

While the first one seems to imply the second one, it doesn't work in reverse. If a hash newtype has semantic meaning of specific data being hashed (`TxId`, `SighashHash`... tons of them) then having the arbitrary bytes interface available is at least doc noise, at worst a foot gun. I think that "hash arbitrary data" should be only available on raw hash types - `hashes::*::Hash`. But removing `Hash` from hash newtypes completely is not good either since it provides important features such as conversion to raw byte array.

### Proposal

* Add `RawHash: Hash` trait and implement it for `hashes::*::Hash` (I'm not 100% sure about the bound but seems very likely correct)
* Remove arbitrary-bytes-hashing-related features from `Hash` (note that `from_inner` should stay)
* Make sure `hash_newtype` only implements `Hash`, not `RawHash`
* Fix any breakage this causes

**Comment by apoelstra** [comment]
I'm unsure that there's a problem here ... everything related to hashing data is exposed as a constructor (a method returning `Self`) while everything related to *being* a hash is a method that takes `self`.

If we were to separate out the traits, what would the code for computing a txid be? You'd have to first compute a `sha256d::Hash` and then convert that to a `Txid`?

**Comment by Kixunil** [comment]
> You'd have to first compute a `sha256d::Hash` and then convert that to a `Txid`?

Yes, but since that is as easy as writing `Txid(sha256d::Hash::from_engine(engine))` it should be fine. We could also have:

```rust
pub trait HashEngine {
    // ...
    #[inline]
    fn finalize<H: RawHash>(self) -> H {
        H::from_engine(self)
    }
}
```

Which would simplify the code into: `TxId(engine.finalize())`

And if `hashes::*::Hash::hash` is frequent enough we may have:

```rust
#[inline]
pub fn hash<H: RawHash>(bytes: &[u8]) -> H {
    H::hash(bytes)
}
```

So that you could write `FooHash(hashes::hash(foo))`.

**Comment by apoelstra** [comment]
Ok, yeah, I am warming up to this.

**Comment by apoelstra** [comment]
Moving to 0.31 from 0.30. I don't think we're going to get this in during this month's release -- we want to figure out the hex situation first, I think. In any case this is a bitcoin_hashes thing, not a rust-bitcoin thing, so it doesn't make sense to block a rust-bitcoin release on it.

**Comment by Kixunil** [comment]
Hex is unrealted to this. But I guess moving to 0.31 is the right thing even though I will be annoyed by the rebase.

**Comment by tcharding** [comment]
Just came across this, flagging here that my work on #2130 was not intentionally ignoring this issue, I just didn't see it.

**Comment by tcharding** [comment]
We have `GeneralHash` and `Hash` now.
