### ISSUE TITLE
`Decimal::new` can lead to panics

### ISSUE THREAD

**Issue by jeandudey** [rust-bitcoin/rust-bitcoin#149]
It allows exponents larger than 18 (makes Display impl to crash)

**Comment by apoelstra** [comment]
There are actually overflow panics all over the place: in `PartialOrd`, `Display`, `integer_value` and I think even `Add`. And in `integer_value`, which multiplies the u64 mantissa by a user-provided power of 10, you can cause an overflow no matter what the `Decimal`'s exponent is.

I think this API needs to be replaced with a "fixed 8 digit decimal" type, which is all that it was intended to be used for anyway.

**Comment by jeandudey** [comment]
https:///github.com/jeandudey/rust-bitcoin-amount

**Comment by apoelstra** [comment]
Nice :). Do you think I should just drop `Decimal` / `UDecimal` from rust-bitcoin entirely?

**Comment by jeandudey** [comment]
For simplicity, yes. Maybe re-exporting these types in rust-bitcoin (something like the `num` crate does).

**Comment by apoelstra** [comment]
Nice! I'll change this bug to being about that then.

I don't think there's any need to re-export these types; they don't really belong in `rust-bitcoin` anyway because they're shims for Core's jsonrpc, but nothing else in this library is designed to support Core or JSON or RPC. People using `rust-jsonrpc` can use your crate directly.

**Comment by stevenroose** [comment]
So can I consider `UDecimal` as soon-to-be-deprecated? :)

**Comment by stevenroose** [comment]
I would be nice to have rust-bitcoin-amount under the rust-bitcoin umbrella, though..

**Comment by stevenroose** [comment]
Also, the `UDecimal` type was also used to parse difficulty values from RPC. But I guess any big integer implementation would do instead for that purpose.

**Comment by apoelstra** [comment]
@stevenroose We can move rust-bitcoin-amount under the rust-bitcoin umbrella (I guess we should formalize what needs to be done there .. I think "builds under 1.14.0" and "Travis does fuzz testing" are our only criteria).

But if you're doing RPC stuff, you're probably already going to need to use rust-jsonrpc which won't be under rust-bitcoin anytime soon.

BTW in a pinch you can directly use `serde_json::Number` in place of `Decimal`.

**Comment by stevenroose** [comment]
Hmm, noticed that bitcoind gives amounts in BTC, not in Satoshi. So that doesn't work for the `bitcoin_amount::Amount` deseralizer.

**Comment by thomaseizinger** [comment]
PR https://github.com/rust-bitcoin/rust-bitcoin/pull/250 removed the `Decimal` type so I guess this can be closed?

**Comment by apoelstra** [comment]
Yep!
