### ISSUE TITLE
Overflow in `pow::U256::mul_u64`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1497]
Addition overflows here: https://github.com/rust-bitcoin/rust-bitcoin/blob/7fee6239e14275d395bbaa3d682ee08d399f34f7/bitcoin/src/pow.rs#L437

[Found by kani](https://github.com/rust-bitcoin/rust-bitcoin/pull/1496)

Despite feeling better rn I still can't focus enough to understand the bug so if anyone wants to analyze go ahead. I also noticed we have `rhs as u128` which could've been `u128::from(rhs)` so if anyone is fixing the bug feel free to change this one too.

**Comment by apoelstra** [comment]
Reading the code, I don't understand the bug either, but I think we can extract a failing input from kani and step through with a debugger until we're hit over the head with it.

This is awesome work by Kani.

**Comment by apoelstra** [comment]
Looks like this takes (at least) several minutes to reproduce. I guess that's OK if it's just CI time, since we're rarely doing quick merges, but it does mean that I probably won't be able to run this test locally on every PR/every commit.

**Comment by Kixunil** [comment]
Yeah, kani is slow for complex programs. I made a micro reproducer that runs in a few seconds and with a bunch of math thinking I think I figured it out: the line should've been `ret.1 = lower + ((upper & u128::from(u64::max_value())) << 64);`

**Comment by apoelstra** [comment]
Are you able to get a specific test case? It seems to me like that `&` mask should be a no-op.

**Comment by Kixunil** [comment]
`100760032231999063436245020328572485633` for `mul` argument to `mul_parts` and `15184976909136101178` for `rhs argument.

What I think it does is basically the same thing you do when you manually calculate single-digit-number * four-digit-number, just the digit is base 2^64. So it should've only added the last "digit" of `upper`.

**Comment by Kixunil** [comment]
Now I also think line 433 has the same bug, it just wasn't found yet.

**Comment by apoelstra** [comment]
Ah yep, I see it now. My confusion was in the shape of the `mul_parts` function. It looks like it has two lines, one which shifts by 64 (dropping the lower 64 bits) and the other masks (dropping the upper ones). But the shift/mask happens **before** a multiplication in both cases. So my eyes were tricked into thinking that we were returning a pair of 64-bit values but we're not.

**Comment by Kixunil** [comment]
I actually saw it pretty early but got confused by math ("OK, but *why* it overflows and what it should do instead?"). Also the code is written in reverse order of the steps I learned to do in school. :D

**Comment by apoelstra** [comment]
Surprisingly with your fix I still get an overflow panic. Investigating.

**Comment by Kixunil** [comment]
Same place or line 433?

**Comment by apoelstra** [comment]
Oh! The crash is about **adding** with overflow, not shifting with overflow.

The shift actually I think is fine. There's no reason we can't left-shift any value at all by 64 bits.

And yes, same place.

**Comment by Kixunil** [comment]
Oh, I know and the order of steps I learned has a specific reason: we must add with carry!

We need to reorder the steps then the currently-panicking line needs to do `overflowing_add`, add the carry to `upper >> 64` using `overflowing_add` and so on...

**Comment by apoelstra** [comment]
Yep, you're right. Amazing how broken this function was, even though we *did* have tests, even extreme-value ones. Also amazing that it took us both some time to grok this, even when staring directly at the code.

**Comment by Kixunil** [comment]
I'm crazy-surprised as well. I guess we will need to add magic values found by `kani` to the collection. I was also also also thinking about comparing it to some other algorithm and make `kani` generate proof but I fear it would be crazy slow. I'm running literally basic check of `Vec::IntoIter` impl as an experiment and it takes ages:

<details>
<summary>OT: example of long-time-taking kani test</summary>

```rust
// I run this for arbitrary T = Vec<u8> up to 64 items (via bolero)
pub fn test<T: IntoIterator>(val: T) {
    let iter = val.into_iter();
    let (min, max) = iter.size_hint();
    let count = iter.count();
    assert!(count >= min);
    if let Some(max) = max {
        assert!(count <= max);
    }
}
```

</details>

**Comment by tcharding** [comment]
I hacked up a minimal reproducer and a solution: https://github.com/tcharding/u256-mul64-kani
