### ISSUE TITLE
Socket locking in listener.rs

### ISSUE THREAD

**Issue by rotwatsb** [rust-bitcoin/rust-bitcoin#15]
After receiving a message, the loop in listener.rs immediately relocks the socket on the following iteration. This blocks requests to send responses, like a pong to a ping, instead delaying the sending of the response until the socket is free again, which doesn't happen until the next message is received. If no other messages are received between two pings, the pong sent will reference the nonce of the earlier ping, which doesn't seem right. Should that be fixed, or am I just missing something?

Asking the listening thread to sleep for just a millisecond before the call to sock.receive_message() allows responses to be sent immediately.

**Comment by apoelstra** [comment]
I'm happy to accept a PR to fix something small like this, but honestly I think the networking code is better suited for another library (one that uses mio or something more modern than this rust 0.6-era code), with rust-bitcoin's only job being de/serialization of the network messages.

**Comment by rotwatsb** [comment]
OK, great, I've just submitted the pull request. Thanks for getting back to me!

**Comment by apoelstra** [comment]
Thanks!

Associated PR: https://github.com/apoelstra/rust-bitcoin/pull/16

**Comment by dongcarl** [comment]
We should close this as PR is too old and low-level networking is deprecated.

**Comment by apoelstra** [comment]
Sure.
