### ISSUE TITLE
Any reason why OP_CLTV (check locktime verify) = OP_NOP2

### ISSUE THREAD

**Issue by ks** [rust-bitcoin/rust-bitcoin#150]
I would like to play with atomic swaps, they need this opcode.

Are there plans to introduce a normal OP_CHECKLOCKTIMEVERIFY opcode?

What's the reasoning for NOPing the opcode?

**Comment by delbonis** [comment]
OP_CLTV *is* OP_NOP2.  The softfork replaced the logic of OP_NOP2 ("do nothing") with the logic we now attribute to OP_CLTV ("fail if the conditions aren't met, or act like nothing happened").

**Comment by ks** [comment]
After playing with both rust-bitcoin and parity-bitcoin for a few days, I actually like rust-bitcoin more...

But I need OP_CHECKLOCKTIMEVERIFY opcode in the script, to produce 0xb1 for atomic swap experiments.

Do I understand it correctly that the reason why such opcode is not in yet is just because nobody needed it so far and a PR implementing that would get merged?

**Comment by apoelstra** [comment]
It's right here https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/blockdata/opcodes.rs#L638

**Comment by MiracleWKY** [comment]
> It's right here https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/blockdata/opcodes.rs#L638

404 not found when i opened it

**Comment by Kixunil** [comment]
@MiracleWKY we've refactored the repository since then. I think documentation is better place to look for it: https://docs.rs/bitcoin/latest/bitcoin/blockdata/opcodes/all/constant.OP_CLTV.html
