### ISSUE TITLE
`push_scriptint` is a massive, potentially-money-losing, footgun

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1517]
First of all, what is the legitimate use of this method? I see none so I prefer to remove it entirely, but if there is I want to rename it to something like `dangerous_push_non_optimal_int` with the danger documented and recommendation to use `push_int` instead.

Background: I made a script using `OP_CSV` and missed that `push_int` exists so I used `push_scriptint` (ironically it could be because I looked into script code too much). This looked fine until someone set the time lock to smaller value at which point the satoshis would become **potentially permanently frozen** because of BIP62. Thank God this was on regtest!

This is crazy dangerous.

**Comment by apoelstra** [comment]
This method appears to be present in the original commit of this library, dated July 2014 -- which post-dates BIP62's *creation* but pre-dates its activation. I don't think it has any legitimate use, and was probably added to help with testing the library. As you observe, post-BIP-62 this will kill the script, except in the cases where it's equivalent to `push_int`.

I wasn't able to find any uses in my own codebases.

We should remove it. I suppose we ought to deprecate it first, but I don't feel strongly about it.

**Comment by sanket1729** [comment]
concept ACK on removing it. Or making it private it is used internally in `push_int`

**Comment by Kixunil** [comment]
I expect very few people use it, if any and maybe the error will provide stronger signal than a warning in case someone does use it. Making it private *and renaming* it makes sense.

**Comment by casey** [comment]
I got confused about this myself and missed `push_int` and thought that `push_scriptint` was the only way to push a script.
