### ISSUE TITLE
Amount with denomination is hard to pass as a command line argument

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-bitcoin#1519]
I'm writing a command line wallet, and I'd like to be able to accept amounts as command line arguments. For clarity, I'd like to require that the user always provides a denomination.

However, `Amount::from_str_with_denomination`, requires that there be a space between the number and the denomination, which would have to be quoted if it were passed as a command line argument, e.g.:

```
wallet 1 sat # error, two arguments
wallet '1 sat' # works, but cumbersome
```

Relaxing `Amount::from_str_with_denomination` to make the space optional would make it possible to pass a denomination on the command line without quoting. Does that sound reasonable?

**Comment by Kixunil** [comment]
I happen to have a CLI application accepting `Amount` as well. Quoting didn't seem too much hassle but it is true not having to do that is nice.

This is potentially robustness principle, which is bad but I don't think there's any standard for this and what Bitcoin libraries in other languages do. Might be good to check with them and turn the format into a BIP.
