### ISSUE TITLE
Fuzzing in CI is broken

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1526]
Looks like some crap.js issue, why is it even there? Can we get rid of it?

**Comment by apoelstra** [comment]
Can you link to the broken CI job?

**Comment by Kixunil** [comment]
Oh, I think I misinterpreted something but I've definitely seen some warnings about nodejs version being update. Closing for now, if anyone sees them, please reopen with a link.
