### ISSUE TITLE
Expose a bunch of types at the crate level.

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#154]
I think we should reexport many types at the top level so that people can type `bitcoin::Address` or `bitcoin::Block`, etc. The reason is that if you want to use, say, `TxIn`, currently you're forced to either type the full path or do `blockdata::transaction::TxIn` and have a `TxIn` type which is easy to confuse with other blockchains' `TxIn` types. It's also hard to remember the full path for a lot of these things, since the module structure was designed for code separation rather than producing a sensible API.

This is a tracking issue where I want to get a complete list of everything we should expose this way. Here is my list:

* `blockdata::block::Block`
* `blockdata::block::BlockHeader`
* `blockdata::script::Script`
* `blockdata::transaction::Transaction`
* `blockdata::transaction::TxIn`
* `blockdata::transaction::TxOut`
* `blockdata::transaction::OutPoint`
* `blockdata::transaction::SigHashType`
* `network::encodable::VarInt`
* `network::serialize::BitcoinHash`
* `util::Error`
* `util::address::Address`
* `util::privkey::Privkey`
* `util::decimal::Decimal`
* `util::decimal::UDecimal`

You can grep the source code for `pub struct` and `pub trait` and `pub enum` to see a full list of exposed data structures throughout the tree. Comments are welcome about anything you feel should be added/removed.

Notably missing are
* Anything in `util::bip32` or `util::bip143` modules, since I think it's perfectly clear to import the module and use paths like `bip32::ChainCode`.
* Anything in `util::hash` because eventually these structures will be moved into the `bitcoin_hashes` crate where they can be top-level.
* most `network::serialize` and `network::encodable` stuff, since I want to restructure these modules in a future major release.

**Comment by dongcarl** [comment]
Just to be clear, this is for people who want to use `rust-bitcoin` and not for `use`s internally right?

**Comment by apoelstra** [comment]
Yes.
