### ISSUE TITLE
Rarely used hash types are reexported at crate root.

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1541]
Because of wildcard reexport these rarely-used types are reexported:

* `FilterHash`
* `FilterHeader`
* `TxMerkleNode`
* `WitnessCommitment`
* `WitnessMerkleNode`
* `Wtxid`
* `XpubIdentifier`

I think it'd be useful to reexport the used ones explicitly. Feel free to argue that some of them are not *that* rare.

Another downside with wildcard reexport is that the types are not directly visible in the doc, so if you want to find out if e.g. `Txid` is reexported CTRL+F will mislead you. (And confused me a lot working on something else.)

Loosely related: I think the whole module, "a bag of unrelated hash types", makes about as much sense as `util` and I want to separate the hashes. The hashes being in an unrelated module also interferes with #1481 which I'm working on now, so I will just submit PR for this.

**Comment by apoelstra** [comment]
I would argue that `Wtxid` is not that rare :).

For the rest I wouldn't mind exporting them at the root since they all have pretty descriptive and non-colliding names. But I agree we should do so explicitly without using a wildcard. It's bad enough that they don't appear in the source code but if they don't appear in the **docs** then we should fix it.

**Comment by dpc** [comment]
FWIW: I don't think I've ever used any of them yet.

**Comment by Kixunil** [comment]
Part of the issue here is the more things we re-export the more noisy the doc becomes. The wildcard happens to hide it (at least until someone decides to expand it) but that is not usable if we export one-by-one. The only solution that comes to my mind is to reexport the less used one into a dummy `extra_reexported_types` module and wildcard-reexport that one.

**Comment by Kixunil** [comment]
I also wonder about `Sighash`. It is returned from a function and then people should just call a method on in (`.into()` to convert into `Message` or, in the future, `sign`).

**Comment by sanket1729** [comment]
I have also never used any of them. My guess is `rust-lightning` or other network-level projects might use these.

**Comment by Kixunil** [comment]
@TheBlueMatt would it be too inconvenient to not have these at crate root but in submodule(s)?
