### ISSUE TITLE
Move `#![deny(...)]` from `lib.rs` to CI (script)

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1551]
The denies are annoying during refactoring when one wants to iterate without bothering with unimportant stuff like unused import until the design is ready. Moving these to `-D` flags would improve the situation (now I have to patch `lib.rs` every time).

**Comment by apoelstra** [comment]
Agreed. The "coding conventions" in lib.rs predate clippy (and in fact predate rust 1.0..), and really don't belong where they are.

**Comment by sanket1729** [comment]
Agreed, as long as everything that we are moving is at least displayed as a warning, I am good. Don't want to end up in a scenario where things pass locally with no warnings and then CI fails.

**Comment by Harshil-Jani** [comment]
Currently I have added the checks in test script itself. 
Do we require a new script and new event in CI ? Or it is fine to let it stay in test ?

**Comment by tcharding** [comment]
No new script of github action required, just modify the current scripts is good.
