### ISSUE TITLE
Extract transaction input and output addresses

### ISSUE THREAD

**Issue by ababo** [rust-bitcoin/rust-bitcoin#1557]
Is there a way to extract input and output addresses for a given `Transaction`?

**Comment by apoelstra** [comment]
Yes -- by using [`Address::from_script`](https://docs.rs/bitcoin/latest/bitcoin/util/address/struct.Address.html#method.from_script) on the output scriptPubKeys you can get the output addresses. Note that not all scripts correspond to some address.

For the input addresses you will need a txindex of some sort to look up the outputs that are being referenced, and do the same thing with *those* scriptPubKeys.

**Comment by ababo** [comment]
Let me summarise my understanding of input address retrieval:
* We can always get address accessing the output of a transaction mentioned in "previous_output".
* In cases when "script_sig" contains a public key (as a last component) we can directly derive the address.
Is that correct?

**Comment by sanket1729** [comment]
> In cases when "script_sig" contains a public key (as a last component) we can directly derive the address from it.

This is not always the case. There could be other transactions that are not p2pkh that might have a public key as the last component. If possible, you should go via looking at the script pubkey. This also does not work for segwit spends where you would need some other separate logic to distinguish between taproot and segwitv0 spends.

Certainly the above is possible, but things are really simple if you can access previous output.

**Comment by apoelstra** [comment]
>In cases when "script_sig" contains a public key (as a last component) we can directly derive the address from it.

No. This is probably true in 100% of cases on the existing Bitcoin chain but is not true in general. This is a really dangerous failure mode because it'd be hard to find in testing but can be adversarially triggered.

**Comment by ababo** [comment]
Thanks you guys!

**Comment by Kixunil** [comment]
Note also that deriving an address from script may *also* be wrong and dangerous. There are address schemes that seek to unlink outputs from the addresses - e.g. Stealth addresses, BIP47 and some recently proposed schemes such as silent payments. If you assume address for those you may cause privacy loss.

It may also be dangerous to present an address for internal scripts of multi-transaction smart contracts (such as LN). If a misguided user sends satoshis there thinking he's "topping up" the contract the satoshis may be lost instead.

Yes, this means that most (all?) block explorers are actually harmful.
