### ISSUE TITLE
Should `is_standard` match sending-standardness or spending-standardness

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-bitcoin#1558]
`Address::is_standard` currently considers "unassigned witness versions or non-standard program sizes" non-standard. This matches the standardness rules for *spending* the given address, but it doesn't match the standardness rules for *sending to* the given address. This isn't super obvious from the documentation, and it seems like we should maybe have a method to expose both.

**Comment by sanket1729** [comment]
Should you not send money to any address that is requested? What could be a non-standard sending address? 

Agreed that the documentation could use some clarification about spending from this address.

**Comment by sanket1729** [comment]
> Add an error variant NonStandard(Address) to Address::from_str which checks the v0 length....

This is non-standard, however really useless in practice. These outputs will fail according to BIP141. They can not even be repurposed for future soft forks. 

https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#witness-program 

> If the version byte is 0, but the witness program is neither 20 nor 32 bytes, the script must fail.

We do check for these in `Address::from_str` and `Address::from_script`. However, an Address struct can manually construct a 21-length witness program payload. This is a bug and we should fix that.

**Comment by Kixunil** [comment]
This is related to script tagging - with it it'd be obvious. But it may still be good to call it `is_spend_standard` even if tagging is implemented because if you see `foo.is_standard()` in the code you may not see the type of `foo`.

**Comment by sanket1729** [comment]
Opened #1564.

**Comment by Kixunil** [comment]
Oh, crap, I got confused, this is about `Address`, not `Script` :man_facepalming: 

But now I understand it better and I think there's no reason to parse addresses which neither can be sent to nor can be spent. Am I missing something?

**Comment by apoelstra** [comment]
@TheBlueMatt after reading the LDK discussion I'm confused about what's needed here. As I understand it, the only "receive-time nonstandard" addresses are segwit v0 addresses of the wrong length. We currently do not parse these at all. Do you want us

* to start parsing them and to provide a method allowing to check that?
* to enforce the length limit in the other constructors (it might not be enforced in `from_script`, I'd have to check)?

**Comment by apoelstra** [comment]
Gotcha! Okay, I definitely agree.

I *think* https://github.com/rust-bitcoin/rust-bitcoin/pull/1564 (the PR that Sanket just opened, above, which we quickly merged) does exactly what you want?
