### ISSUE TITLE
Segwit Address struct allows constructing invalid Address

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#1561]
Both `Address::from_str` and `Address::from_script` check constraints witness programs (len between 2 and 40 and others). But it is possible to directly construct the `Address` struct as all its member fields (`Payload` in particular) are public. 

We should make internal fields of  `Address` private and a make failing constructor that checks the invariants.

**Comment by Kixunil** [comment]
I think this is essentially a duplicate of #648 and I agree with the proposal.
