### ISSUE TITLE
Can I create an address using a public key using this library?

### ISSUE THREAD

**Issue by abbychau** [rust-bitcoin/rust-bitcoin#160]
as title.

**Comment by dongcarl** [comment]
@abbychau Yes. You can construct a `bitcoin::util::address::Address` with a `payload` of `bitcoin::util::address::Payload::Pubkey`

**Comment by jeffbarg** [comment]
Added an example of this here: https://github.com/rust-bitcoin/rust-bitcoin/pull/173

**Comment by apoelstra** [comment]
Fixed by #174

**Comment by abbychau** [comment]
thank you
