### ISSUE TITLE
`U265` implements `Mul<T>` for various integer types

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1632]
> Multiplication by various integers seems to be a bit odd. No other Rust type has it.

In `U265` (private integer type used as inner value of `Target` and `Work`) we implement `Mul` by various integer types, perhaps this was wrong?

**Comment by apoelstra** [comment]
Heh, it's a bit odd that we even have a "uint256" type at all. This seems like a design decision I copied from Core and didn't revisit.

**Comment by tcharding** [comment]
Oh I might have written a confusing issue, the `U256` is private. I updated the issue and the title.

**Comment by Kixunil** [comment]
IIRC this is because of a macro. I'm not sure if it's specifically wrong to have those multipliations but I realized the way they are implemented is very wrong: they have blanked `Into<u64>` bound. So any other newtype that implements `Into<u64>` can be multiplied by `Target` and `Work`:

```rust
#[derive(Copy, Clone /* ... */)]
struct NumberOfPotatoes(u64);

impl From<NumberOfPotatoes> for u64 { /* ... */ }

fn count_potatoes() -> NumberOfPotatoes {
    NumberOfPotatoes(42)
}

let potatoes = count_potatoes();
// no compile error
let garbage = potatoes * target;
```

**Comment by apoelstra** [comment]
Wait, do we have these `Mul` imples on `Target` and `Weight`, or just on `U256`?

They don't make sense for Target or Weight even if we were only allowing unitless numbers (maaybe `Mul<usize>` for `Weight` if you want to add up a ton of blocks that all have the same weight).

**Comment by Kixunil** [comment]
We have them on all three types. (I guess you meant `Work`, not `Weight`.) Yeah, multiplication doesn't even make sense for `Target`. We don't have `Add` on it because of the same reason.

**Comment by apoelstra** [comment]
Ok, so let's drop the impls entirely on `Target`.

On `Work` (yeah, I meant `Work` :)) we can keep a `usize` impl if people want, but IMHO we should also drop all the impls there too.

**Comment by tcharding** [comment]
Ok, I think this is my fault for thinking of wrapper types too much as general purpose integers instead of abstractions. I"ve added https://github.com/rust-bitcoin/rust-bitcoin/issues/1530 to audit all the wrapper types.

Since these abstractions are non-trivial to think about perhaps I'll do them and label with "P-low" because of the review time required?

**Comment by apoelstra** [comment]
I'm fine with calling them P-low. But in the case of simply removing existing functionality I think we could probably review that kinda thing quickly.

**Comment by Kixunil** [comment]
I prefer to remove the unneeded ops in 0.30: it's easy to do and avoids problems if people start using them.
