### ISSUE TITLE
`Builder::push_int_non_minimal` is misnamed

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1634]
The function `write_scriptint` encodes a script num in "minimal" encoding. `push_int_non_minimal` calls `write_scriptint` so it is misnamed. Was perhaps the intention "encode this without using special opcodes for small values"?

```rust
    /// Adds instructions to push an integer onto the stack without optimization.
    ///
    /// This uses the explicit encoding regardless of the availability of dedicated opcodes.
    pub(super) fn push_int_non_minimal(self, data: i64) -> Builder {
        let mut buf = [0u8; 8];
        let len = write_scriptint(&mut buf, data);
        self.push_slice(&buf[..len])
    }
```

**Comment by Kixunil** [comment]
`write_scriptint` doesn't use minimal encoding, so the name is correct.

**Comment by tcharding** [comment]
Maybe I'm not getting the definition of "minimal" correct then? Are you implying that "minimal" means use special opcodes for small values? From reading `script.h` in Core all I could work out was that "minimal" means "use signed-magnitude encoding"? Am I missing something?

**Comment by apoelstra** [comment]
"minimal" does indeed mean using special opcodes for small values. For larger values it also means avoiding extra leading 0s, as well as negative 0s, and some other edge cases.

All numbers in Script use signed-magnitude encoding internally, whether they are minimal or not.

**Comment by tcharding** [comment]
> For larger values it also means avoiding extra leading 0s

AFAICT we do not enforce this currently and I didn't see anywhere in `script.h` that enforces it. I'll look into it more.

**Comment by apoelstra** [comment]
It is enforced in `interpreter.cpp` I think when the `SCRIPT_VERIFY_MINIMALDATA` flag is set.

We don't "enforce" this anywhere because we don't ever parse scriptints out of script, so there's nothing to enforce.

**Comment by tcharding** [comment]
> We don't "enforce" this anywhere because we don't ever parse scriptints out of script, so there's nothing to enforce.

I'm confused, when in the public function `read_scriptint` expected to be used then?

**Comment by apoelstra** [comment]
Lol. That function probably should not be public or even exist. It dates back to when rust-bitcoin had a half-baked script interpreter.

If we just deleted it, it would surprise me if literally anybody noticed.

**Comment by tcharding** [comment]
Aight, this issue is resolved but I'll leave it open as a reminder to myself while I go through all the script/num/push stuff.
