### ISSUE TITLE
Not all integer wrapper types implement `core::iter::Sum`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1638]
Some of our integer types implement `Sum` but not all of them. I at least, was unaware of this trait when adding some of them (pun intended :)

A possible heuristic for which types to implement it for is "does this type implement `Add`"

An example:
```rust
impl core::iter::Sum for Amount {
    fn sum<I: Iterator<Item = Self>>(iter: I) -> Self {
        let sats: u64 = iter.map(|amt| amt.0).sum();
        Amount::from_sat(sats)
    }
}
```

ref: https://doc.rust-lang.org/stable/core/iter/trait.Sum.html

**Comment by apoelstra** [comment]
+1 to "if something implements `Add` it should implement `Sum`". I wonder if there's a clippy lint for this that we could enable..

This is certainly something we could do if we wrote a rustdoc-based linter.

**Comment by Kixunil** [comment]
Also `T: Add + Copy` => `Sum<&T> for T`
