### ISSUE TITLE
Make `hash_newtype` macro evocative of the output

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1648]
[From API guidelines](https://rust-lang.github.io/api-guidelines/macros.html):

> Aim to keep input syntax familiar and cohesive with the rest of your users' code by mirroring existing Rust syntax where possible.

Currently the macro is used like this:

```rust
hash_newtype!(Foo, sha256::Hash, 32 doc = "A foo hash");
```

We should change it to this:

```rust
hash_newtype! {
    /// A foo hash
    pub struct Foo(sha256::Hash);
}
```

There are two problems:

* What about length? I think it shouldn't be needed since it can be statically determined from `sha256::Hash`, will need to look into it more.
* How to handle reversed hashes? We could try to implement `#[hash_newtype(reversed)]` attribute, not sure if possible in declarative macro. If not, we could simply expose two macros that internally call the existing one with an appropriate parameter.

Alternatively we could use proc macros but those will hurt compile times, so I'd prefer to avoid them if possible.

**Comment by apoelstra** [comment]
I think we could be a little non-Rustic and do something like
```
hash_newtype! {
   /// A foo hash (assuming you can have these kinds of comments in macros now, you couldn't in the past)
    pub struct Foo(sha256::Hash; length = 16; reversed = true);
}
```
We could even extend `Foo` to look like a struct with multiple fields, though that may be too misleading.

**Comment by Kixunil** [comment]
That's not too bad of a fallback if we can't figure out removing length and doing reversed as an attribute.

**Comment by Kixunil** [comment]
I don't want it to be a proc macro exactly because of heavy dependencies. But if we used proc macro, I'd vote for it to be just a derive.
