### ISSUE TITLE
`TapBranchTag` identifier looks stale

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1656]
Recently we changed `TapBranchHash` to `TapNodeHash` (I think) but `TapBranchTag` didn't get changed, now it is not uniform with the other tag identifiers.

EDIT: Fixed typo as commented on below.

**Comment by Kixunil** [comment]
I think you mean `TapBranchTag`. The name is actually correct, that's the name of the tag from the BIP. (Name of result != name of algorithm)

**Comment by tcharding** [comment]
I read BIP-340 and BIP-341 and skimmed 342 and 343 but couldn't find any mention of `TapBranchTag`, am I missing something?

**Comment by Kixunil** [comment]
Search for `TapBranch` instead, in BIP-341.

**Comment by tcharding** [comment]
Ok, I was totally wrong and this code hasn't changed since it was written. Sorry for the noise.
