### ISSUE TITLE
Write upgrade guide for 0.29 -> 0.30

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1660]
We made a shitload of huge changes, we really should write a guide going over large changes.

(Maybe incomplete) list of significant changes:

- [x] moved stuff - summary of what moved where
- [x] script changes (unsized types etc)
- [x] lock types
- [x] new `hash_newtype` syntax
- [x] Taproot changes
- [x] sighash changes
- [x] `Address` changes
- [x] bunch of newtypes

BTW, looking at all that stuff, we did insane amount of work...

**Comment by apoelstra** [comment]
I really like this idea. It would be good to start a series on the website.

And yeah .. holy shit, this one is huge.

**Comment by tcharding** [comment]
Please see: https://github.com/rust-bitcoin/www.rust-bitcoin.org/pull/2

**Comment by sanket1729** [comment]
[This can be closed now](https://rust-bitcoin.org/blog/release-0.30.0/)
