### ISSUE TITLE
Rename crypto::taproot to crypto::schnorr?

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#1665]
Seems like taproot is an odd name. I would really like to write `schnorr::Signature` instead of `taproot::Signature`.

**Comment by Kixunil** [comment]
I believe the name is correct. It's not just a signature, it contains the sighash type as well so that it can be pushed to witness. This type is specifically tied to taproot. If there will be a new upgrade that still uses schnorr signature algorithm but a different sighash type having it named `schnorr` would cause conusion/name clash.

**Comment by sanket1729** [comment]
Ah, I wrote a long thing here, but I believe you are right. 
https://github.com/rust-bitcoin/rust-bitcoin/pull/1597#issuecomment-1443171863

**Comment by sanket1729** [comment]
Just one more crib:
- We have ecdsa::Signature for pre-taproot outputs vs taproot::Signature for taproot outputs?

Technically speaking, we have two more signatures, `legacy::Signature`  and `segwitv0::Signature`. But both of them have the same structure which is why we use the signature algorithm `ecdsa::Signature` to encapsulate both of them.

**Comment by sanket1729** [comment]
One slight inconvenience that I am noting in my project I cannot use `taproot::Signature` and `taproot::TaprootSpendInfo` in the same module.

```rust
use bitcoin::taproot as tap_utils; // For using taproot::NodeInfo
use bitcoin::crypto::taproot; // For using taproot::Signature
```
I don't know of a better name for either of the modules, but someone has better ideas to rename `bitcoin::crypto::taproot` or `bitcoin::taproot`. I think it can be helpful in ergonomics.

**Comment by Kixunil** [comment]
That's actually unaddressed/planned part. We'd like them to be separate types so that e.g. `LegacySignature` can't be pushed into `Witness` and the other way around.
