### ISSUE TITLE
Use different names for two taproot modules: `bitcoin::taproot` and `bitcoin::crypto::taproot`? 

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#1668]
One slight inconvenience that I am noting in my project I cannot use `taproot::Signature` and `taproot::TaprootSpendInfo` in the same module.

```rust
use bitcoin::taproot as tap_utils; // For using taproot::NodeInfo
use bitcoin::crypto::taproot; // For using taproot::Signature
```
I don't know of a better name for either of the modules, but someone has better ideas to rename `bitcoin::crypto::taproot` or `bitcoin::taproot`. I think it can be helpful in ergonomics.

**Comment by sanket1729** [comment]
Really minor issue that I can live with, but wanted to bring it up here.

**Comment by Kixunil** [comment]
Heh, I wanted to complain that it's confusing but import is also a good point. Just please no `util` word anywhere.

I'd prefer them to be the same module but not sure if it makes sense.

**Comment by apoelstra** [comment]
It looks like `crypto::Taproot` basically only contains `Signature`, and its own `Error` type. We could re-export that from `bitcoin::taproot` and even make the crypto module private.

**Comment by Kixunil** [comment]
Both ideas sound good! It may still be a bit annoying for us, the maintainers to have two files but let's see. If we make `crypto` private we can change it without causing breakage.

**Comment by tcharding** [comment]
> Really minor issue that I can live with, but wanted to bring it up here.

Thanks for raising this issue, its not a minor one in my mind, when trying to depend on this lib in `rust-miniscript` I was like "what the f***, these absolute drongos who wrote this used the same name for two modues" - and I personally added the second `taproot` module, so imagine what others think :) 

The solution I came to was re-exporting as suggested by @apoelstra, coupled with re-export of `ecdsa` at crate root this makes it ergonomic. Is `crypto` being public ok, bit weird if someone did this:
```
use bitcoin::cryto::ecdsa;
use bitcoin::taproot;
```

In general I think next (0.31.1) release we should think long and hard about _exactly_ what is exported where and come  up with some API that is intuitive, functional, and beautiful, like a new born baby :)

**Comment by Kixunil** [comment]
I still think that having the `crypto` submodule is questionable, so I would just reexport its content at top-level.

**Comment by apoelstra** [comment]
The point of having `crypto` is that we are considering making it its own crate which could be easily enabled/disabled so people who don't want to compile in rust-secp would have a clean API break.

If we're not going to do that (and I'm increasingly skeptical, given the weird division we would up having between signatures and hashes), then we should probably drop the module and fold its contents into the rest of the library.

But let's not do that for this upcoming release. Let's just re-export some things so that users aren't forced to import two same-name modules to use the library at all.

**Comment by Kixunil** [comment]
> given the weird division we would up having between signatures and hashes

Exactly, we can just condition signing and verification on the library.

> we should probably drop the module and fold its contents into the rest of the library.

Concept ACK.

> But let's not do that for this upcoming release. Let's just re-export some things so that users aren't forced to import two same-name modules to use the library at all.

OK, but let's also hide the module to not confuse people, it's a trivial change.

**Comment by apoelstra** [comment]
Sure, concept ACK hiding the module for now.
