### ISSUE TITLE
`Address::require_network` doesn't return `self` in the error case

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1677]
Errors returned from functions that consume costly-to-create (e.g. allocated) arguments should allow retrieving the original arguments in the error case if possible. `Address::require_network` doesn't do this. This is not that huge issue because people can just use `is_valid_for_network` and `assume_checked` manually but it'd be nicer to address. Possible approaches:

* Put `Address` into `Error::NetworkValidation` without anything else - annoying to match with `unreachable!`
* Make a new error type for this case with conversion - nicest but adds a type
* Return a tuple in error case - can't be trivially combined with `?`
* Give up - the use case may be nich and there exists a workaround

What do you think? I'm leaning towards adding the error type.

Adding to 0.30 milestone because I prefer not to change the API multiple times in case we agree to change it.

**Comment by apoelstra** [comment]
My feeling is that we should just give up, that it's pretty niche that you'd want to check an address against a network and then keep the address around afterward (for anything except for logging -- which may be a reason to bring it into the enum).

But let's not delay 0.30.0 over this.

**Comment by Kixunil** [comment]
Hmm, I guess you might be right. Will let it sit here for a bit and if nobody complains I'll write a quick PR for adding it to `Error`.

I don't intend to block unreasonably and would not block if this turned out to be contentious.

**Comment by apoelstra** [comment]
For sure, I'd ACK pretty-much any PR to address this I think. It's just that if we were otherwise ready to go, I'd let it miss the deadline.

**Comment by tcharding** [comment]
I've no strong opinions on the matter, hack it up!

**Comment by Kixunil** [comment]
@Subhra264 sure, go ahead. To be clear, I believe we decided the first one, please remember to modify `Display` so that the address is printed.
