### ISSUE TITLE
Remove schemars pin

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1687]
Agree, with schemars we should totally remove the pin.

Ironically, given how much I fought Jeremy over the inclusion of this crate, it actually has a pretty conservative/reasonable MSRV policy (it was 1.37, and in the latest version was bumped to 1.45). So for now, with 1.41, we should remove the pin and add a README line with `cargo update --precise` instructions. But after release when we move to 1.48 MSRV we can drop even that.

_Originally posted by @apoelstra in https://github.com/rust-bitcoin/rust-bitcoin/issues/1230#issuecomment-1453667349_

**Comment by Kixunil** [comment]
Since this is fairly easy and without it the API is essentially broken I propose we do it in the next release.

**Comment by apoelstra** [comment]
@Kixunil well, the API is only broken for *schemars users*. But that's been true since we let schemars in.

I agree we ought to get it into this release, but no urgency.
