### ISSUE TITLE
Relax rustfmt rules?

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1712]
The current rule is that all commits must pass tests. I suggest to make exception for `rustfmt` and only require that the final commit after merging passes rustfmt. There are two reasons:

* Sometimes review can be made easier by intentionally "mis-formatting" - see #1710 for an example
* If it ever happens that merge fails because of formatting only it's a bunch of wasted time. (Not sure if this can happen.)

IIUC the rule is to make bisecting reliable and I don't think anyone will ever need to bisect formatting. Bisecting is generally used to find bugs.

**Comment by tcharding** [comment]
Sounds reasonable to me.

**Comment by apoelstra** [comment]
Yes, I only ever run rustfmt on the tip commits (and I think CI does the same?).

Good to make this explicit.

I think the same should go for `cargo clippy`.

**Comment by Kixunil** [comment]
Not sure about `clippy`, it could find correctness bugs that could ultimately produce failures in obscure situations. Maybe only require correctness lints or something.
