### ISSUE TITLE
There is no SECURITY.md

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1718]
`CONTRIBUTING.md` includes the following:
```
## Security

Security is the primary focus for this library; disclosure of security
vulnerabilities helps prevent user loss of funds. If you believe a vulnerability
may affect other implementations, please disclose this information according to
the [security guidelines](./SECURITY.md), work on which is currently in progress.
Before it is completed, feel free to send disclosure to Andrew Poelstra,
apoelstra@wpsoftware.net, encrypted with his public key from
<https://www.wpsoftware.net/andrew/andrew.gpg>.
```

However there is no file `SECURITY.md` in the repo?

**Comment by Kixunil** [comment]
Yeah, it says it's WIP, and it doesn't exist and no progress was made since then.

**Comment by apoelstra** [comment]
What should our strategy be? We can leave it as "just email me", in which case I should make a SECURITY.md that includes my gpg key and email?

I don't really know how to make a mailing list, or support multiple keys, or whatever we'd need to do to have multiple points of contact.

**Comment by Kixunil** [comment]
Yeah, I think it makes sense. We might add someone as a backup though.

I suggest that we make an exception for unsound APIs that are unlikely to be used in real code (e.g. what we had recently in secp256k1) and API footguns - those can be publicly disclosed I guess? With the note: "when in doubt, send encrypted e-mail".
