### ISSUE TITLE
DisplayHex is not exported?

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#1745]
Unless I am missing something trivial, we forgot to export this?

**Comment by sanket1729** [comment]
This is kindof a blocker for rust-miniscript update. So, I would request fixing this in a point release.

**Comment by Kixunil** [comment]
We didn't, `-private` is intentionally private. I think `rust-miniscript` should be able to depend on it. Unless it's considered separate from other crates. Also we're moving to have a separate hex crate #1242

**Comment by sanket1729** [comment]
Relooking at it, the only place where rust-miniscript uses it is to display vectors in hex in error strings. No really needed for some core functionality. 

We can use `private` crate for now while hex crate is being developed.

**Comment by Kixunil** [comment]
Sounds good!
