### ISSUE TITLE
Is `ChainHash` reversed?

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1750]
Electrum protocol uses reverse of what serde impl on `ChainHash` (de)serializes.

Is this a bug or do they intentionally differ?

**Comment by apoelstra** [comment]
I thought `ChainHash` was a LN thing. What is electrum doing with it?

Also, is this a binary protocol or a human-readable thing?

**Comment by Kixunil** [comment]
Electrum identifies the network by it over Json.

**Comment by apoelstra** [comment]
According to https://github.com/lightning/bolts/blob/master/00-introduction.md it is serialized as `6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000`, which is how we serialize it.

What I suspect is that Electrum is actually encoding a `BlockHash`, not a `ChainHash`.

**Comment by Kixunil** [comment]
Ah, thanks for looking it up!

**Comment by tcharding** [comment]
Drats, I tried to make this clear when I did the `ChainHash` type, obviously not.
