### ISSUE TITLE
Guarantee memory layout of hashes and support casts?

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1756]
Being able to cast `&[u8; N]` to an `N`-byte hash type could be very helpful for fast parsing like [`bitcoin_slices`](https://github.com/RCasatta/bitcoin_slices) is doing. To enable this the hash types must be `#[repr(transparent)]` which I think we could support since I don't see any good reason  why the memory layout would ever change.

Further, we could provide these conversions:

```rust
fn ref_from_bytes(bytes: &[u8; $len]) -> &Self {
    // Sound because Self is #[repr(transparent)] containing [u8; $len]
    unsafe { &*(bytes as *const _ as *const Self) }
}

fn mut_from_bytes(bytes: &mut [u8; $len]) -> &mut Self {
    // Sound because Self is #[repr(transparent)] containing [u8; $len]
    unsafe { &*(bytes as *mut _ as *mut Self) }
}
```

`unsafe` here is even more trivial than that in `Script`, so should be OK.

**Comment by apoelstra** [comment]
For sure, ACK repr(transpanent). I think thi was an oversight.

**Comment by tcharding** [comment]
Are you convinced with your function names @Kixunil? I would have expected the `ref` and `mut` to be at the end of the function name because in both cases it refers to the parameter and the return type?

**Comment by tcharding** [comment]
ref: https://stackoverflow.com/questions/41992247/conventions-for-naming-mutable-immutable-api-functions

**Comment by Kixunil** [comment]
Oh, yes, put them at the end.

**Comment by junderw** [comment]
What about Hash types that are $reverse=true?

I think only sha256d has this set to true currently.

Seems like a potential foot gun?

Not sure exactly how, but it feels like a foot gun.

**Comment by apoelstra** [comment]
@junderw `reverse=$true` is only about hex serialization. Nothing is ever actually stored backward.
