### ISSUE TITLE
`block::Header` is annoying to use

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1788]
Perhaps I went too far with the `BlockHeader` -> `block::Header` rename. I've had some feedback that it is annoying to use and folks are using `use bitcoin::block::Header as BlockHeader`. Was the rename overly dogmatic, perhaps we should revert to `BlockHeader`

cc @stevenroose

**Comment by tcharding** [comment]
FTR what I was trying to achieve was uniforimity in our types with the idea that if the need further describing they should use the module name not have a longer identifier e.g. `taproot::Signature`, `block::Header`.

**Comment by stevenroose** [comment]
A large part of the annoyance is that it's a breaking change. In my head, modules have two functions: organizing code in clusters and structurizing the API. The whole blockdata, script, tx etc stuff to me mainly has the former function and all types are just exposed on the root of the lib, while users don't really need to know where all these types live. On the other hand, the `bip32`, `taproot`, `sighash` modules most have the latter function. They bundle some functionality that at the API level belongs together and is independent.

Anyway, I think a `pub use block::Header as BlockHeader;` in the lib.rs would be useful to make it no longer a breaking change.

But I think it would make sense to actually make this distinction hard in some way. In my mind that's what `util` mostly did. Everything inside `util` were basically independent modules, while everything outside `util` was just a way to organize all the core types and functionality of the crate.

**Comment by tcharding** [comment]
> A large part of the annoyance is that it's a breaking change. 

Yes, change sucks :)

> In my head, modules have two functions: organizing code in clusters and structurizing the API. 

This is exactly what we are trying to separate - the aim is to have the public types/modules only describe the API, all organisational modules should be private (`pub(crate)`.

> The whole blockdata, script, tx etc stuff to me mainly has the former function and all types are just exposed on the root of the lib, 

`blockdata` is done I believe, we can make it private for 0.31

> On the other hand, the bip32, taproot, sighash modules most have the latter function. 

By this release they should not have that purpose any more, there are some things in sighash that are not perfect yet (because of the ongoing ecdsa splitting)

> Anyway, I think a pub use block::Header as BlockHeader; in the lib.rs would be useful to make it no longer a breaking change.

Are you suggesting a 0.30.1 point release with this in? Or a revert of the change that will go in 0.31.0 in six months?

> But I think it would make sense to actually make this distinction hard in some way. 

The API/module separation is not totally complete, especially the re-exports but I personally made an effort to push it in this direction for 0.30.0. I think we (@apoelstra, @kixunil, @sanket1729) are on the same page, mentioning them so they can say if not.

One other related thing, we are trying to put only modules/types in the crate root that are part of the Bitcoin vernacular, so `bitcoin::PublicKey` but `bitcoin::script::PushBytes`. Also we are trying (at least this is my understanding) to use modules to disambiguate not identifiers (e.g., `script::Builder` not `ScriptBuilder`) - this is how I got to the `block::Header` change :) 

FTR its super useful to have you come back and ask these questions because it helps by having to write it down and others can read it, since I may have misconstrued things - this stuff is just to the best of my understanding from the last year.

**Comment by Kixunil** [comment]
I personally wrote `use bitcoin::blockdata::block::Header as BlockHeader` because I didn't notice we have `block` re-exported and it was minimal amount of change to get the old code working. I do like `block::Header`, I just wanted to upgrade fast.

I can't think straight about the other stuff rn.

**Comment by apoelstra** [comment]
+1 to releasing a re-export as `BlockHeader` and then cutting a point release. I also like `block::Header` but agree it's not very discoverable.

As for the wider API changes, I have been slowly chipping away at parsing the `rustdoc` JSON output into something I can use to visualize the entire API, since I've been mostly locally ACKing changes but don't have a clear coherent vision still.

**Comment by stevenroose** [comment]
If some people would be more active (yes looking at myself), it would make sense to tag a RC and then do some of the dep bump work on dependent crates like hal and core-rpc to see how the changes affect them. :roll_eyes:

**Comment by Kixunil** [comment]
> then cutting a point release

We will need to cherry pick it into a different branch since master already contains breaking changes.

> tag a RC and then do some of the dep bump work on dependent crates like hal and core-rpc to see how the changes affect them

I actually did this for a few projects and opened a few issues that got resolved before the release. I considered what was left fine, including missing `BlockHeader`.

**Comment by Kixunil** [comment]
Now thinking about it I'm not sure I like re-exporting `BlockHeader`. There's a shitload of stuff already re-exported cluttering the docs. IME `BlockHeader` is not nearly as used as `Transaction` and its parts, so not re-exporting may be better.

**Comment by DanGould** [comment]
I hear breaking changes and wonder if a pre-release would be more appropriate than a point bump to get into the new pattern

**Comment by Kixunil** [comment]
I don't think RC would help much. Either way you need to manually bump Cargo.toml. At best it'd make it easier to get `bitcoin_hashes` and `secp256k1` in sync so that possible issues could be reported. (You could do the same with `[patch...]` but it's a bit annoying.)

**Comment by tcharding** [comment]
> Now thinking about it I'm not sure I like re-exporting `BlockHeader`. There's a shitload of stuff already re-exported cluttering the docs. IME `BlockHeader` is not nearly as used as `Transaction` and its parts, so not re-exporting may be better.

I suggest the debate should be about renaming the type back to `BockHeader` as it was, not about if we should use type aliases and re-export them at the crate root (which is a slightly different debate IMO).

**Comment by apoelstra** [comment]
I do not want to rename the type if it's in the `block` module. I'm fine to re-export it as `BlockHeader` somewhere else, but if people are accessing it from its existing home they can write `block::Header`.

**Comment by tcharding** [comment]
Cool, I guess this conversation is related to https://github.com/rust-bitcoin/rust-bitcoin/pull/1792#issuecomment-1504724872 and re/re-exporting hash types.

**Comment by clarkmoody** [comment]
I am in favor of `block::Header` and not repeating module names in type names.

**Comment by tcharding** [comment]
No strong consensus one way or the other, electing to leave it as it is. Thanks all.
