### ISSUE TITLE
Compilation failure related to new sha256t_hash_newtype

### ISSUE THREAD

**Issue by stevenroose** [rust-bitcoin/rust-bitcoin#1789]
So I tried to use the cargo patch feature to patch in my rust-bitcoin dev branch in my rust-bitcoincore-rpc work. This branch is just master + two open MRs.

Somehow this broke compilation in a way that points like a problem with the macro for the TapLeafHash etc types and then resulting errors because these types are missing.

This seems to be the gist of the actual problem:
```
    Checking bitcoin v0.30.0 (https://github.com/stevenroose/rust-bitcoin?branch=dev#56737a58)
error: no rules expected the token `struct`
  --> /home/steven/.cargo/git/checkouts/rust-bitcoin-221c4b904b7f04d3/56737a5/bitcoin/src/crypto/sighash.rs:58:9
   |
58 |     pub struct TapSighashTag = hash_str("TapSighash");
   |         ^^^^^^ no rules expected this token in macro call

error: no rules expected the token `struct`
  --> /home/steven/.cargo/git/checkouts/rust-bitcoin-221c4b904b7f04d3/56737a5/bitcoin/src/taproot.rs:26:9
   |
26 |     pub struct TapLeafTag = hash_str("TapLeaf");
   |         ^^^^^^ no rules expected this token in macro call
```
I'm using rustc version 1.61.0.

Related: https://github.com/rust-bitcoin/rust-bitcoin/pull/1773, cc @Kixunil 

- [Full log of compilation failure](https://github.com/rust-bitcoin/rust-bitcoin/files/11186469/output.log)

If you want to try replicate this, checkout the `syncasync` branch of `stevenroose/rust-bitcoincore-rpc` and try to build it.

**Comment by tcharding** [comment]
Oh I wonder if this is because your use of patch overrides the patch in `rust-bitcoin` so the wrong `bitcoin_hashes` is being used?

**Comment by tcharding** [comment]
I'd say the branch you link to is using the released version of `bitcoin_hashes` not the code on master but you are using `rust-bitcoin` with code from master.

**Comment by stevenroose** [comment]
Ah you're right. I had to patch bitcoin_hashes too.
