### ISSUE TITLE
Support additional derives

### ISSUE THREAD

**Issue by gregdhill** [rust-bitcoin/rust-bitcoin#1794]
We redefine many Bitcoin types (e.g. [`Transaction`](https://github.com/interlay/interbtc/blob/b2362d4a41c10bee0786cd48b592370cb4124bfb/crates/bitcoin/src/types.rs#L333-L339)) in our parachain Rust code since the `rust-bitcoin` types do not derive [`Decode`](https://github.com/paritytech/parity-scale-codec/blob/b0099e80b1f6f09ab5cffe27794a11e134403b49/derive/src/lib.rs#L174), [`Encode`](https://github.com/paritytech/parity-scale-codec/blob/b0099e80b1f6f09ab5cffe27794a11e134403b49/derive/src/lib.rs#L124), [`MaxEncodedLen`](https://github.com/paritytech/parity-scale-codec/blob/b0099e80b1f6f09ab5cffe27794a11e134403b49/derive/src/lib.rs#L358) or [`TypeInfo`](https://github.com/paritytech/scale-info/blob/caa38cbb6256ae7ebdccc23d35a7633d4f43c2bd/derive/src/lib.rs#L52). Would you be open to supporting these dependencies via a cfg attribute? The main motivation is that we already make heavy use of `rust-bitcoin` in our [client-side code](https://github.com/interlay/interbtc-clients/blob/95f96e6aaca33406f710f612d26af439cac426f8/bitcoin/src/lib.rs#L17-L35) and we have to translate between the two sets of types.

**Comment by stevenroose** [comment]
Yeah I think these types of traits are more specific to your use case than to the ecosystem as a whole, you should specify the implementations for them in the crate that specifies the trait, IMO.

**Comment by tcharding** [comment]
Can we close this one?

**Comment by apoelstra** [comment]
I am going to close this as WONTFIX, sorry. We are even less enthusiastic about deriving new traits than we were when this issue was opened -- we are planning to replace our serde derives with hand-rolled code because `serde_derive` has caused us so much pain. And we certainly are not going to add hand-rolled implementations for other crates that we're unfamiliar with.
