### ISSUE TITLE
`Address` is incorrectly associated with `Network`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1819]
- Assumption: A Bitcoin address is tightly coupled with its string representation.
- Observation: A Bitcoin address string does not map one-to-one to an `Address` because of the use of `Network`.
- Claim: Our `Address` type is incorrect, furthermore the ambiguity caused by including the `Network` type as part of the `Address` (or `AddressInner` as it is now) is the root cause of the complexity we recently introduced (the network checked markers). 
- Idea: I think we should have an `Address` type that is an _exact_ abstraction of all valid Bitcoin address strings.

Said another way, it is currently impossible to go from an `Address` -> String -> `Address` for some addresses (eg, a segwit address to be used on signet).

**Comment by Kixunil** [comment]
Good point, so we would need something like `AddressNetwork` (possibly just `address::Network`) that can be reasonably converted to/from the usual `Network`.

**Comment by Kixunil** [comment]
`Prefix` sounds a bit like string and given the actual string prefix also depends on whether the address is P2PKH, P2SH, P2WPKH it could be confusing. Internal terminology of Core is not very beginner-friendly and frankly not even intermediate-friendly. I've seen Core code but didn't remember (or see) this. Maybe if it also encoded the kind of address it'd make more sense but it might be ugly.

Any better idea? I'm thinking `Variant` but seems too vague. `NetworkVariant` sounds weird to me. `Purpose` is close but not good enough for me.

Or maybe consider moving it inside the `Payload` enum so that `Network` is available for addresses that support it and use something else for the other addresses. This makes the representation match reality better. But we still need a name for the other thing.

**Comment by tcharding** [comment]
I have a feeling this seemingly mild abstraction fail permeates deeper than just the "prefix" - I woke up this morning chomping at the bit to work on this, I'll hack up some code and see what I uncover.

**Comment by tcharding** [comment]
I had a play with this and it was a pretty nice clean up, I want to wait till `Hrp` becomes available in `bech32` then I'll do a PR. In case anyone is interested it involved:
- Make `AddressInner` an enum (`P2pkh`, `P2sh`, `Segwit`)
- Inline `Payload` into the appropriate `AddressInner` variants
- Add `prefix` (`u8`) field to the two legacy variants and `Hrp` to the segwit variant
- Remove `AddressEncoding`

**Comment by Kixunil** [comment]
That makes sense, however: shouldn't `prefix` be an enum? And `Hrp` probably `Network` since there's 1:1 mapping between them?

**Comment by apoelstra** [comment]
Yeah, I wouldn't mind using `Network` (and separately, now that it's `#[non_exhaustive]` anyway, I think we should support a `Custom` variant of `Network`).

Then agreed, `Prefix` ought to have its own enum. Though I don't think users would often work directly with it, and this is legacy stuff anyway, so I don't feel very strongly. We should probably also support custom prefixes somehow.

**Comment by apoelstra** [comment]
@Kixunil that's a good point that now that we have the `bech32` crate people can just create their own `Address` type without much trouble.

But FWIW the value I had in mind was for bespoke test networks. (There also may be some shitcoiny, but nonetheless bitcoin-centric, value in using custom prefixes to spend airdrop forks like BCH/BSV so you can dump them without installing any software maintained by those people.) In Elements we even have arguments to elementsd that let you customize these prefixes, and I think these arguments would be accepted to Bitcoin Core if we ever got around to upstreaming them.

**Comment by tcharding** [comment]
> And Hrp probably Network since there's 1:1 mapping between them?

There is not a 1:1 mapping between hrp and network - that was the whole impetus for this work ("tb" maps to `Network::Signet` as well as `Network::Testnet`).

**Comment by apoelstra** [comment]
Oh, derp, right. For some reason I thought this was only an issue for legacy addresses.

**Comment by Kixunil** [comment]
> "tb" maps to `Network::Signet` as well as `Network::Testnet`

Crap, whyyyyy?! :man_facepalming: 

OK, we need a separate type for this. So concept ACK what you suggested above, just use an enum instead of `u8`.
