### ISSUE TITLE
"no `hex` in `internal_macros`" error in benches of downstream crate

### ISSUE THREAD

**Issue by RCasatta** [rust-bitcoin/rust-bitcoin#1830]
I got the following error in the bitcoin_slices crate ([job](https://github.com/RCasatta/bitcoin_slices/actions/runs/4859691193/jobs/8662623060))

```
error[E0432]: unresolved import `crate::internal_macros::hex`
    --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitcoin-0.30.0/src/blockdata/transaction.rs:1916:9
     |
1916 |     use crate::internal_macros::hex;
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `hex` in `internal_macros`
     |
help: consider importing one of these items instead
     |
1916 |     use bitcoin_hashes::hex;
     |         ~~~~~~~~~~~~~~~~~~~
1916 |     use bitcoin_internals::hex;
     |         ~~~~~~~~~~~~~~~~~~~~~~
1916 |     use crate::transaction::hashes::hex;
     |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

the command launched in the downstream crate is `RUSTFLAGS='--cfg=bench' cargo +nightly bench --all-features`

I can't reproduce locally with the same nightly compiler.

tracking down the line the macro should be available (it's behind `cfg(test)` which should be enabled inderectly via `--cfg=bench` 

Also, previous jobs since introducing bitcoin 0.30 went fine

**Comment by Kixunil** [comment]
Regardless, this should be just `hex_lit::hex`.
