### ISSUE TITLE
Fuzzing looks broken

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#1836]
> Invalid workflow file: .github/workflows/fuzz.yml#L57
> The workflow is not valid. .github/workflows/fuzz.yml (Line: 57, Col: 9): 'run' is already defined

IDK why we didn't get the error earlier, GH is weird and the lack of validator annoys me greatly.

**Comment by apoelstra** [comment]
I also got an error on rust-secp claiming that `matrix` was undefined or something. I wonder if GH is broken, or if we were using something deprecated that went away, or what.

**Comment by tcharding** [comment]
This can be closed, right?

**Comment by apoelstra** [comment]
Yeah, oops, this looks like something that was a problem for like, one day, and we forgot to close the issue about it.
