### ISSUE TITLE
bip21 URI scheme should be lowercased?

### ISSUE THREAD

**Issue by RCasatta** [rust-bitcoin/rust-bitcoin#1843]
https://github.com/rust-bitcoin/rust-bitcoin/blob/7c6a7c34b87fa92e6432247e3ce909333ef44d05/bitcoin/src/address.rs#L985

Even if according to the [spec](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) the scheme are case insensitive 

When scanning a bip21 URI like `BITCOIN:TB1QENTR8XV3ZEFGGYDAEDNF99AQFVD98HZW4KUWWQ` from my android generic camera, the intent is not passed to bitcoin applications like  `bitcoin:TB1QENTR8XV3ZEFGGYDAEDNF99AQFVD98HZW4KUWWQ` is doing.
So even there is a penalty in qr code dimension with the lowercase scheme, I think we have to bite the bullet and use a lowercase scheme.

Leaving here the QR code with the uppercase scheme if someone could try it from an iphone
![image](https://github.com/rust-bitcoin/rust-bitcoin/assets/6470319/7cca24f8-765b-41db-81bd-699992546f70)

**Comment by Kixunil** [comment]
Tried from Android with Blue Wallet installed and didn't get it offered. So probably iOS works correctly by treating the scheme as case-insensitive (IIUC this is the URI standard) and Android is buggy. In an ideal world Google would fix it.

I suggest let's lower case it and reserve the right to change it if the situation changes.

**Comment by stevenroose** [comment]
>     /// If the address is bech32, both the schema and the address become uppercase.
>    /// If the address is base58, the schema is lowercase and the address is left mixed case.

Where does that notion even come from? URIs should be case insensitive so sane creators would always make them lowercase..

I think we should definitely remove that and make them all lowercase.

**Comment by apoelstra** [comment]
I assume it's because in ASCII the uppercase letters have their upper two bits clear, while the lowercase ones have only the uppermost one clear.

**Comment by Kixunil** [comment]
I've looked into QR code encoding in the past and IIRC alphanuumeric is just its own encoding. And yes, I also think it's weird to encode upper case more efficiently.
