### ISSUE TITLE
DO_COV is stale?

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1853]
We don't collect any code coverage metrics in CI, right? Is `DO_COV` stale?

Discovered while setting `RUSTFLAGS` in cargo commands and wondering the effect of clobbering the value already set with
```bash
if [ "$DO_COV" = true ]
then
    export RUSTFLAGS="-C link-dead-code"
fi
```

**Comment by apoelstra** [comment]
I believe it is stale. It originates in https://www.github.com/rust-bitcoin/rust-bitcoin/pull/297 but was lost in the transition to Github Actions in https://github.com/rust-bitcoin/rust-bitcoin/pull/544/

We could try to restore it.

**Comment by tcharding** [comment]
Damn now I feel bad, that means for 18 months I've been glossing over it.

**Comment by tcharding** [comment]
I have little experience with code coverage in general and none with [codecov](https://github.com/apps/codecov) but from two minutes reading it looks like projects need to pay for the service to read reports.

Questions:
- Is it still useful on the free tier?
- Do we want to be promoting this paid service?
- Is there a free/open source equivalent we should use instead?

**Comment by tcharding** [comment]
Possible answers
1. Free tier seems useful: https://about.codecov.io/pricing/
2. ?
3. This guy thinks not: https://itnext.io/github-actions-code-coverage-without-third-parties-f1299747064d

**Comment by Kixunil** [comment]
IIUC we can run it ourselves but won't get nice outputs. IME codecov is prone to spuriously reporting decrease in coverage even when you only change comments or do trivial code changes. I have no idea how this is not considered bug and why it's not deterministic. Anyway, if we want to reintroduce it I want it to be informative. Enforcing tests is sometimes silly.

**Comment by apoelstra** [comment]
I'd be fine using the free tier of something but no, we definitely shouldn't pay for this. We can do it ourselves with `gcov` if need be, though as Kix says the output will not be so nice and we won't get a Github badge out of it.

**Comment by pool2win** [comment]
I took a quick look at the coverage by running llvm-cov locally and uploaded the coverage report to coveralls.

Here is the report for the latest master branch - https://coveralls.io/builds/65162711

Here's the screenshot for the same report:

![image](https://github.com/rust-bitcoin/rust-bitcoin/assets/78231905/d8dcdfa5-33ea-42ee-9dae-8c65b4c68f3c)

It is pretty clear which areas need from TLC for test coverage.

If there is an interest in setting up a github action for such reports, I am happy to have a go at it.

Coveralls is free for open source projects.

**Comment by apoelstra** [comment]
@pool2win I would love if you would take a shot at this.

Indeed, these numbers are pretty stark :).

**Comment by Kixunil** [comment]
I suggest you coordinate with #2353 which would conflict with this.

**Comment by tcharding** [comment]
`consenus` ouch 70.39,

**Comment by tcharding** [comment]
You go in front of me (2353) @pool2win, I'll work around you.
