### ISSUE TITLE
Discussions in person 2023

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1868]
Discussions in real life have more bandwidth. This issue tracks things that folk would like to discuss in person.

EDIT: Added list, removed/added names as per comments below.

### Folk attending

- **BTC Prague**: @kixunil, @tcharding, @stevenroose, @justinmoon, @elsirion 
- **TABConf**: @tcharding, @sanket1729, @justinmoon, @stevenroose 

### BTC Prague

- Labels 
   - how/when/why to use labels on issues/prs etc (rust-bitcoin crate)
   - come up with a set of labels that helps reviewers prioritise PRs (i.e, optimization, refactor, OCD clenup, minor/major API improvement, serious bitcoin shit)

### TABConf

- The stuff listed above that we never got to (which is all of it :)

**Comment by tcharding** [comment]
Labels: how/when/why to use labels on issues/prs etc (rust-bitcoin crate)

**Comment by romanz** [comment]
Unfortunately, I won't be able to attend TABConf :(

**Comment by apoelstra** [comment]
Unfortunately I probably will not be able to either, since I have a child due to be born very near to it. In general I'm unlikely to be able to meet up at any time this year :).

**Comment by justinmoon** [comment]
@elsirion and I will be at BTCPrague, I'll be at Tabconf

**Comment by sanket1729** [comment]
I would likely attend Tabconf, but have not made any travel plans yet.

**Comment by tcharding** [comment]
> @elsirion and I will be at BTCPrague

Oh sweet, catch you there.

**Comment by yancyribbens** [comment]
Wow there is a chess tournament at Tabconf.  That's freaking awesome.

**Comment by stevenroose** [comment]
I am pretty sure I'll also be at tabconf. Who wants to beat me at chess? :)

**Comment by tcharding** [comment]
These events are all in the past now.
