### ISSUE TITLE
Should `Network::from_str` accept different values?

### ISSUE THREAD

**Issue by RCasatta** [rust-bitcoin/rust-bitcoin#1881]
At the moment we have `"bitcoin" <-> Network::Bitcoin`, then we have `from_core_arg` to accept "main" because it's the way bitcoin core refer to mainnet.

Lately I saw umbrel use "mainnet"

Is it acceptable to accept multiple values in the from_str impl ?

```rust
fn from_str(s: &str) -> Result<Self, Self::Err> {
        use Network::*;

        let network = match s {
            "bitcoin" | "mainnet" | "main" => Bitcoin,
            "testnet" | "test" => Testnet,
            "signet" => Signet,
            "regtest" => Regtest,
            _ => return Err(ParseNetworkError(s.to_owned())),
        };
        Ok(network)
    }
```

**Comment by tcharding** [comment]
My two cents, I think it would be useful for the overall health of the library to tighten up at times like this and only do bare essentials in `rust-bitcoin`, pushing other stuff up to applications. `Display`/`FromStr` roundtripping is one place that we can have an implementation that is simple, does one thing, does it well, and does not need changing any time soon. On the other hand, allowing strings x, y, z to parse seems like something that is open to being patched a bunch.

A counter argument would be if we find duplicate code in libraries above us (miniscript, bdk, ldk) then perhaps it should be here in `rust-bitcoin`?

**Comment by Kixunil** [comment]
Agree with not over-complicating. I also don't think any downstream library should do this - only applications.

**Comment by RCasatta** [comment]
I understand and agree, thanks everyone
