### ISSUE TITLE
Docs only build cleanly for std builds

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1884]
We have a bunch of places in rustdocs that use links to std, this means if we try to build the docs using "no-std" we get a bunch of "unresolved link" warnings. We cannot trivially fix this because the links are to things that exist only in std (eg, `path::Path`).

Should we be able to build a _consistent_ set of docs for no-std?

**Comment by Kixunil** [comment]
I don't think this is needed. I use docs.rs 99% of the time and I guess most people do as well. I only locally build when there's unreleased changes and I do it with `--all-features`.

**Comment by apoelstra** [comment]
Agreed, I don't think we care about this.

It woulrd be nice to silence the warnings. I wonder if we could do a `cfg_attr(not(std), allow(doc_warnings))` or something.

**Comment by tcharding** [comment]
Cool, that wasn't too hard, now includes
```rust
// rustdocs include a bunch of links to std types, we want to keep them.
#![cfg_attr(not(feature = "std"), allow(rustdoc::broken_intra_doc_links))]
```

**Comment by tcharding** [comment]
... and ... we can't use that in Rust 1.48, we have to set it on the command line: `RUSTDOCFLAGS='-A rustdoc::broken-intra-doc-links'`

**Comment by apoelstra** [comment]
Ok, that's not so bad actually if we just set that in our API-checking script. And maybe only for the no-std variant.

**Comment by Kixunil** [comment]
I'd rather keep the warnings to alert users that they might get messed up docs when they try no-std docs.

**Comment by apoelstra** [comment]
Ok, so let's put the `-A` flag into the API-checking script (where we don't want the warnings, since our goal isn't to test the docs, it's just to get a dump of the API). And leave it enabled otherwise.

**Comment by tcharding** [comment]
Yep that's what I did, cheers. FTR we do not build docs for no-std anywhere else in CI.

**Comment by Kixunil** [comment]
Looks like this is resolved, please reopen if I missed anything.
