### ISSUE TITLE
`from_slice` vs `try_from_slice`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1894]
We have many `from_slice` functions that return `Result` - would it improve our API (by following the principle of least surprise) if these were called `try_from_slice`?

Related: #1893

**Comment by Kixunil** [comment]
Rust has many methods that don't have `try_` prefix and return `Result`. Actually most don't have the prefix and the prefix is only used when a method panicking (or behaving weirdly) on error already existed and a result-returning method was added later. So I think `from_slice` (on hashes) is completely fine. Although maybe it could be `from_byte_slice` to match `from_byte_array`.

**Comment by tcharding** [comment]
Yes, when I was afk yesterday I thought pretty much the same, there are loads of functions that return errors that don't include `try_`, thanks.
