### ISSUE TITLE
Request: Script::is_tapscript

### ISSUE THREAD

**Issue by stevenroose** [rust-bitcoin/rust-bitcoin#1902]
The `Script::to_v1_p2th` method says "assuming that the script is a tapscript". It would be nice if we could actually check that.

**Comment by junderw** [comment]
1. Iterate through all instructions, caching the previous two instructions.
2. If OP_CHECKMULTISIG* (0xae or 0xaf) is seen, fail.
3. If OP_CHECKSIG(VERIFY) is seen, make sure the pubkey is 32 length, and the signature is 64 or 65 length.
4. If OP_SIGADD is seen, make sure the signature is 64 or 65 length.

Since we don't have the entire witness stack, we can't even try to calculate the sigop budget, so that's about all we can do.

**Comment by junderw** [comment]
So the question really boils down to:

If we can't guarantee it will work, why not place the burden 100% on the caller?

We'd assume anyone messing with custom scripts will test with regtest and testnet first.

**Comment by junderw** [comment]
Or maybe instead of a bool we could have a 3 option enum, Tapscript, NotTapscript, Inconclusive... etc.

A large majority of real non-toy scripts should have a CHECKSIG, and looking at the pubkey size can tell us most of the time surely.

**Comment by sanket1729** [comment]
I don't think there is nice general way of doing. As @junderw mentioned, I am also of the opinion that we should do it.

**Comment by junderw** [comment]
> I am also of the opinion that we should do it.

Did you mean should**n't**?

**Comment by sanket1729** [comment]
yes, sorry about that. I meant  **should not** .

**Comment by stevenroose** [comment]
But.. What does the witness have to do with **the script itself** being valid tapscript or not? I mean, what the user inputs in the witness doesn't change the script itself.

From @junderw 's first post, it seems that a script `is_valid_tapscript` iff it doesn't have OP_CHECKMULTISIG* opcodes?

**Comment by stevenroose** [comment]
Hmm, I start to kinda agree, but for different reasons.

First of all the argument about what's in the witness I think is false, the witness doesn't change the script itself, whether or not it's a valid script. Witness is input.

I had made this implementation:
```rust
    pub fn is_valid_tapscript(&self) -> bool {
        self.instructions().all(|i| match i {
            Ok(Instruction::Op(op)) if op == OP_CHECKMULTISIG => false,
            Ok(Instruction::Op(op)) if op == OP_CHECKMULTISIGVERIFY => false,
            _ => true,
        })
    }
```

But looking into the bips, I realize that this is just the differentiator between tapscript and legacy script. But there are various parameters that make a script invalid **also in legacy script**. Like, we have many of illegal opcodes that if you use them, renders the script invalid. So in order to implement an `is_valid_tapscript`, we would need a regular `is_valid` and that seems like quite a non-trivial task.

So I suppose I agree that this is not a good idea, goes slightly too deep into consensus.

**Comment by apoelstra** [comment]
Agreed, this sort of script analysis is what rust-miniscript is for.
