### ISSUE TITLE
Problem running benches

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#1928]
From the docs:
> RUSTFLAGS='--cfg=bench' cargo +nightly bench

This appears to no longer work, although it did a few months ago.

**Comment by yancyribbens** [comment]
The error is with the line in transaction.rs on L:1992:
```
use crate::internal_macros::hex;
```
and the msg
```
no hex in internal_macros
```

**Comment by apoelstra** [comment]
Good catch! This can also be seen by running `RUSTFLAGS='--cfg=bench' cargo +nightly test` which we should run in CI.

We could probably fix this as part of #1833

**Comment by yancyribbens** [comment]
> We could probably fix this as part of https://github.com/rust-bitcoin/rust-bitcoin/pull/1833

SGTM

**Comment by yancyribbens** [comment]
> This can also be seen by running RUSTFLAGS='--cfg=bench' cargo +nightly test which we should run in CI

yes I noticed that also.  The `mod tests` in Transaction also use the import `hex` and break when the feature bench is set.  I guess that feature needs to be enabled for bench cfg upstream.  Also I agree we should add this to CI so the bench break happens immediately not a few months later :)

**Comment by tcharding** [comment]
Closing. The error you point towards is tracked in #1830 and the cargo bench command you give currently works on master.

**Comment by yancyribbens** [comment]
Sounds good.  Thanks!
