### ISSUE TITLE
Use `scrape-examples` in docsrs

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#1931]
See https://github.com/bitcoindevkit/bdk/pull/1011

We should figure out exactly what this option does, and probably use it.

**Comment by notmandatory** [comment]
This feature is [enabled by default on docs.rs](https://github.com/rust-lang/docs.rs/blob/65cc01d9880c1fa62009471e262f56aa616643f8/src/docbuilder/rustwide_builder.rs#L754-L756), a bit of explanation here:

https://doc.rust-lang.org/rustdoc/scraped-examples.html

**Comment by apoelstra** [comment]
Oh, thanks! If it's enabled by default then I guess we don't need to worry about it.

**Comment by notmandatory** [comment]
Still maybe worth trying to figuring out why your existing example code isn't being picked up in your docs. If I figure it out for BDK I'll add a comment here too.
