### ISSUE TITLE
Remove allocations from Debug implementation of Witness

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#1937]
In the interest of getting this in, I'll ACK this. But the allocations are really not necessary and we should file an issue to get rid of them.

_Originally posted by @apoelstra in https://github.com/rust-bitcoin/rust-bitcoin/issues/1913#issuecomment-1634509438_

**Comment by tcharding** [comment]
Thanks!

**Comment by apoelstra** [comment]
To add a bit of context:

* I tried changing the `-> String` methods to return `-> fmt::Arguments`, which would've been nice and clean, but it seems there's no way to do this. (You get a `fmt::Arguments` from `format_args!` which always caputures local variables, so you can't return the result.)
* So I think to get rid of the allocations, we would need to inline the utility functions and replace the `f.write_str`s with `write!(f`s, unfortunately.
* Oooor we could do something more elaborate involving custom types with custom `fmt::Display` impls, but I don't think that's justified for such a simple case here.

**Comment by tcharding** [comment]
I already wasted a bunch of time on this, for just formatting debugging output of one struct I'm not sure how much extra time its worth. So far it was worth it because I learned a bunch but further optimisations may not be as educational. What do you think, is there a time when this is critical, I can't imagine one, off the top of my head?

**Comment by apoelstra** [comment]
Ok, no worries, I'll PR to fix it.

No, I don't think some wasted allocations during a `Debug` implementation will ever practically matter. I just think it's grotesque.

**Comment by tcharding** [comment]
cool, that is a decent reason :)
