### ISSUE TITLE
Method to convert `DerivationPath` to `Vec<u32>`

### ISSUE THREAD

**Issue by benma** [rust-bitcoin/rust-bitcoin#1944]
Currently I use this to convert a derivation path to `Vec<u32>`:

```rust
let v: Vec<u32> = derivation_path.into_iter().map(|&el| el.into()).collect()
```

Is there a more direct way? If not it would be good if we could add a method like `fn to_u32_vec(&self) -> Vec<u32> { self.0.clone() }` or similar.

**Comment by benma** [comment]
>  I think you could do it with unsafe code

What do you mean? It can be a regular safe function.

Here is how I imagined it: https://github.com/rust-bitcoin/rust-bitcoin/pull/1946

I need this to pass it to a BitBox02 protobuf message where the keypath is passed as a list of u32 ints.

Would probably be also useful to add the reverse: `impl From<&[u32]> for DerivationPath`, though I personally have not encountered the need for it yet.

**Comment by apoelstra** [comment]
> What do you mean? It can be a regular safe function.

Not if you want to do it "more directly", which is what you asked.

>I need this to pass it to a BitBox02 protobuf message where the keypath is passed as a list of u32 ints.

Interesting. It won't let you pass lists of `ChildNum`s, or iterators of u32s, or a consensus-serialized list of u32s, or anything? This API must require a ton of allocations to use. 

> Would probably be also useful to add the reverse: `impl From<&[u32]> for DerivationPath`, though I personally have not encountered the need for it yet.

Maybe. I continue to be skeptical that this is a common need, and having it around may encourage people to use it when there is a more efficient/natural way available.
