### ISSUE TITLE
Weights cannot be added but there is no hint to stop devs doing so

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1974]
When adding an input to a transaction one cannot simply sum the weights because the `VarInt` might change size with the new added weight, thus changing the total weight. Our current API does not prevent, or sufficiently hint at this problem.

For discussion see:

- https://github.com/rust-bitcoin/rust-bitcoin/pull/1831
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1970

**Comment by yancyribbens** [comment]
Thanks for taking a go at making this more clear.  

What does it mean  " the VarInt might change size with the new added weight"?  Is it that the weight of previously added weight is now different?

**Comment by yancyribbens** [comment]
Part of my confusion with this explanation is that there isn't anything special about `VarInt`.  It's just a struct that wraps a u64 as far as I can tell: https://github.com/rust-bitcoin/rust-bitcoin/blob/master/bitcoin/src/consensus/encode.rs#L326

**Comment by yancyribbens** [comment]
Ok after a bit more digging, I see that VarInt implements `len()` here: https://github.com/rust-bitcoin/rust-bitcoin/blob/master/bitcoin/src/consensus/encode.rs#L384 

```
    pub const fn len(&self) -> usize {
        match self.0 {
            0..=0xFC => 1,
            0xFD..=0xFFFF => 3,
            0x10000..=0xFFFFFFFF => 5,
            _ => 9,
        }    
    }
```

so VarInt.len() can be either 1,3,,5 or 9 depending on the contents of script sig [script_sig](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/bitcoin/src/blockdata/transaction.rs#L227).  Although this doesn't make it any more clear why VarInt might "change size" with a new added Weight.

**Comment by RCasatta** [comment]
Suppose you have a tx with 252 outputs, if you add one output the serialized form of the varint counting outputs in the transaction will grow from 1 to 3 bytes, thus considering only the weight of the output is not sufficient.

**Comment by yancyribbens** [comment]
Thanks @RCasatta.  I wrote a test that I believe encapsulates the behavior you described.

Is this correct then?

```
    #[test]
    fn weight_sum() {
        let output = TxOut { value: Amount::ZERO, script_pubkey: ScriptBuf::default() };

        // prints 36
        println!("weight of a single output: {}", output.weight());
        let v = vec![output; 252];
        
        let mut t = Transaction {
            version: 1,
            lock_time: absolute::LockTime::ZERO,
            input: vec![],
            output: v
        };
            
        let w = t.weight();
        
        // prints 9112
        println!("transaction weight with 252 outputs: {}", w);
        
        let output = TxOut { value: Amount::ZERO, script_pubkey: ScriptBuf::default() };
        t.output.push(output.clone());
        
        // adding another output should sum to 9112 + 36 = 9148
        // fails with 9148 != 9156
        assert_eq!(9112 + 36, u64::from(t.weight()));
    } 
```

**Comment by yancyribbens** [comment]
In that case I agree that `usize` is no better or worse than `Weight` for TxOut and TxIn return types.

**Comment by tcharding** [comment]
Closing this, we now have the following function on `TxOut`:
```rust
    /// The weight of this output.
    ///
    /// Keep in mind that when adding a [`TxOut`] to a [`Transaction`] the total weight of the
    /// transaction might increase more than `TxOut::weight`. This happens when the new output added
    /// causes the output length `VarInt` to increase its encoding length.
    ///
    /// # Panics
    ///
    /// If output size * 4 overflows, this should never happen under normal conditions. Use
    /// `Weght::from_vb_checked(self.size() as u64)` if you are concerned.
    pub fn weight(&self) -> Weight {
        // Size is equivalent to virtual size since all bytes of a TxOut are non-witness bytes.
        Weight::from_vb(self.size() as u64).expect("should never happen under normal conditions")
    }
```
