### ISSUE TITLE
Feature: Add implementation of `CalculateNextWorkRequired`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#1997]
We recently made our `U256` type private and using it to expose `Target` and `Work`. Doing so stopped folks from doing arbitrary math with large numbers, one thing that is no longer possible is calculating the next difficulty target.

Add implementation of `CalculateNextWorkRequired` (incl. logic from `GetNextWorkRequired`) from Bitcoin Core (both in `bitcoin/src/pow.cpp`).

For bonus points:
- Comment the div/mul by 4 so readers of the code know _why_ that is done.
- Make it rusty instead of a direct copy of the C++.

**Comment by tcharding** [comment]
Inspired by the discussion in #1993.

**Comment by vincenzopalazzo** [comment]
OK, lets do this :) I will try to implement it

**Comment by vincenzopalazzo** [comment]
Ok maybe this is the first version that can provide a solution for this issue https://github.com/rust-bitcoin/rust-bitcoin/pull/2090

Suggestion on how to improve are welcome :)

**Comment by vincenzopalazzo** [comment]
I do not know if I am still in time for the release, but this should be ready https://github.com/rust-bitcoin/rust-bitcoin/pull/2090

**Comment by tcharding** [comment]
I called a feature freeze yesterday @vincenzopalazzo, I can't find the comment but I was under the impression that I read you post recently that you only really needed #2090 for this release and you were ok to wait for the next release for this feature? We are 6 weeks overdue to release as is and this PR will require a bunch more reviewing still I believe, I at least will need to put a chunk of time in to the C++ code before I can ack this.

Can we leave it till next release please?

**Comment by vincenzopalazzo** [comment]
>Can we leave it till next release please?

ofc 😸 I can fetch bitcoin with git for now

**Comment by tcharding** [comment]
Closed by #2740

**Comment by apoelstra** [comment]
#2740 did it.

**Comment by tcharding** [comment]
Ha! I still missed it :)  Thanks
