### ISSUE TITLE
rust-bitcoincore-rpc: `HexBytes` are not very convenient

### ISSUE THREAD

**Issue by dpc** [rust-bitcoin/rust-bitcoin#200]
In APIs like `sign_raw_transaction` taking `HexBytes` is not very convenient. The caller will either have `Transaction` or `String` or `Vec<u8>` and only the last one is somewhat easily convertible. In none of the APIs we actually return `HexBytes`, and the fact that it is serializing to hex string, should be an implementation detail.

I think we should have be taking `tx: T` where `T: AsRef<HexBytes>` or something like that, so we can `impl AsRef<HexString> for` `Transaction`, `String` and `Vec<u8>` and `&[u8]`.

We could potentially use the same technique in other places in which it's unclear which type exactly to return. Eg we could return `T : From<TxString>` and then implement it for `String`, `Vec<u8>` and `Transaction`. The downside of it, is that in some cases, it will be unclear which type is to be returned and user will have to do the turbofish.

Ping @stevenroose

**Comment by dpc** [comment]
We could also have an opaque `struct Tx` `struct Hash` `struct Address` with `into()` and `from()` implemented for stuff like `Vec<u8>` `String` and corresponding `rust-bitcoin` type, and user would just use `into` manually. These way the actuall conversions between types could sometimes be completely avoided.

**Comment by dpc** [comment]
@stevenroose https://github.com/rust-bitcoin/rust-bitcoincore-rpc has issues disabled, so I thought all issues shoud go "main" repo.

**Comment by stevenroose** [comment]
@dpc ah weird, probably initial settings or so. @apoelstra setup this repo.

**Comment by dongcarl** [comment]
See: https://github.com/rust-bitcoin/rust-bitcoincore-rpc/issues/19
