### ISSUE TITLE
The `XpubIdentifier` is not 100% correctly named

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2014]
BIP-32 defines an extended key identifier, we call this abstraction `XpubIdentifier` but this is not totally correct because it identifies xpubs and xprivs.

### Considerations

- `Identifier` is a bit generic so the prefix is useful even if not technically correct
- We could use `bip32::Identifier` outside of the bip32 module but this is not uniform with other hashes that tend to have crate wide distinct names
- `Bip32ExtendedKeyIdentifier` is more technically correct but clearly horrible.

**Comment by apoelstra** [comment]
We can use `XKey` rather than `ExtendedKey`, which matches similar naming in rust-miniscript.

**Comment by tcharding** [comment]
Nice.

**Comment by tcharding** [comment]
So what do you think, `Bip32XKeyIdentifier` or `XKeyIdentifier`?

**Comment by tcharding** [comment]
The first is kinda ugly.

**Comment by apoelstra** [comment]
I think `XKeyIdentifier` is better.
