### ISSUE TITLE
bip32 serialization/deserialization of ExtendedPrivKey

### ISSUE THREAD

**Issue by evgeniy-scherbina** [rust-bitcoin/rust-bitcoin#202]
It line of code https://github.com/rust-bitcoin/rust-bitcoin/blob/5a5158e120fb9d5dc0ef3f12dbaad2cdf63db9a6/src/util/bip32.rs#L421 confuse a little bit. I had object of ExtendedPrivKey struct and after serialize, deserialize I've got another object(Network changes from regtest to testnet). It was unexpected) probably we should use another magic for regtest. 

deserialization: https://github.com/rust-bitcoin/rust-bitcoin/blob/5a5158e120fb9d5dc0ef3f12dbaad2cdf63db9a6/src/util/bip32.rs#L452

It seems that bip32 doesn't describe regtest, but I think we can use any four bytes(probably send PR to bip32).

**Comment by dongcarl** [comment]
@TheBlueMatt Thoughts?

To me, extended keys aren't serialized for machines... So not too worried.

**Comment by stevenroose** [comment]
Fixed by #269.

**Comment by dpc** [comment]
In the bitcoin ecosystem there's this weird inconsistency where in some things there is a distinction between Testnet and Regtest, and in some others there isn't. I wonder if it's better to try to unify everything into having that distinction, or just use different `enum`s where appropriate.
