### ISSUE TITLE
Finally time to drop/fork core2?

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-bitcoin#2034]
The original intent behind using core2 was to use something that it looked like other ecosystem users may use, but it seems to not really have ended up being the case. Sadly, it recently broke MSRV (indirectly) via its (somewhat useless) `memchr` dependency. We could trivially drop the dependency (see https://github.com/technocreatives/core2/pull/23) but its not clear that upstream is particularly maintained :(.

**Comment by tcharding** [comment]
I forget what the current opinions are on how we will replace our usage of the `core2::Write` trait, are we going to add a custom `Write` trait in `rust-bitcoin` or some other solution?

**Comment by tcharding** [comment]
This issue is a real can-o-worms but I'd totally like to get to the bottom of it. Its going to be hard to tackle without @Kixunil around because of all the genio/lgio discussion elsewhere. If there are any tips on making some progress I'm open to them.

**Comment by tcharding** [comment]
I had a bit of a play with `core2` and there is nothing, AFAICT, that we can strip out (apart from the `memchr` dep that you PR'd already).
