### ISSUE TITLE
size/weight confusing and possibly buggy

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2049]
We have merged some changes recently to weight/size calculations for transaction inputs, transactions, and blocks. As discovered by @stevenroose we may have inadvertently introduce a bug by missing one mul by 4. In order to investigate I had a look at all the current API functions we have for size/weight - its a total mess. We need, IMO, to fix this before we release.

In my opinion all the size/weight functions need auditing, to check that we are using the terms "size", "virtual size", "weight" correctly. Including checking docs are inline with logic and return types.

Some investigation shows we have:

ref: https://en.bitcoin.it/wiki/Weight_units

## PRs

- https://github.com/rust-bitcoin/rust-bitcoin/pull/2010
- https://github.com/rust-bitcoin/rust-bitcoin/pull/2001

## APIs showing function name and return type

transaction::predict_weight -> Weight

TxIn 

    /// The weight of a `TxIn` excluding the `script_sig` and `witness`.
    // TODO: What are these numbers?
    pub const BASE_WEIGHT: Weight = Weight::from_wu(32 + 4 + 4);

- segwit_weight -> Weight
- legacy_weight -> Weight

TxOut

- weight -> Weight

Transaction

    pub const MAX_STANDARD_WEIGHT: Weight = Weight::from_wu(400_000);

- weight -> Weight
- size -> usize
- vsize -> usize
- strippedsize -> usize
- stripped_size -> Weight
- scaled_size -> usize

Block

- base_size -> usize
- size -> usize
- strippedsize -> usize
- stripped_size -> Weight
- weight -> Weight

**Comment by yancyribbens** [comment]
As a project, I think we probably want to decide on using Weight Unit as a standard measure.  Before these changes, we used `usize` which is ambiguous as to what the standard measurement is.  I may not have understood that `usize` was meant to meant `vbytes` and not `wu` (in at least some cases) which would cause the results to be wrong since 1 vbyte is 4 weight units.  If `usize` was meant to mean `vbytes` and no `wu` then the code was confusing to begin with, and we have an opportunity to improve the clarity by changing all return types to `wu`.

**Comment by junderw** [comment]
> /// The weight of a `TxIn` excluding the `script_sig` and `witness`.
> // TODO: What are these numbers?
> pub const BASE_WEIGHT: Weight = Weight::from_wu(32 + 4 + 4);

This is incorrect.

I think it's (trying to) represent:
1. The prev_txid (32 bytes, non-segwit region)
2. The prev_vout (4 bytes, non-segwit region)
3. The nSequence (4 bytes, non-segwit region)

So the sum should be multiplied by 4 to get the weight units (since they are not in the segwit region)

**Comment by junderw** [comment]
I think the makeup of segwit discount is valuable information, so I personally would like to see Weight contain "How much of my value is comprised of segwit (1 byte = 1 wu) and non-segwit (1 byte = 4 wu)?" be something that an instance of Weight can answer for itself.

We could then collapse it into a simple usize with methods on Weight ie. `to_virtual_size` `to_byte_size` `to_weight_units`

**Comment by yancyribbens** [comment]
> So the sum should be multiplied by 4 to get the weight units (since they are not in the segwit region).

It sounds like this should be:  `Weight::from_vb(32 + 4 + 4);` since it doesn't get the segwit weight discount.

**Comment by yancyribbens** [comment]
> I think the makeup of segwit discount is valuable information, so I personally would like to see Weight contain "How much of my value is comprised of segwit (1 byte = 1 wu) and non-segwit (1 byte = 4 wu)?" be something that an instance of Weight can answer for itself.

Maybe Weight could be changed to:

```
type wu = u64;
type vb = u64;
pub struct Weight(wu, vb);
```

That way, it could retain the information about the composition of the Weight type?

**Comment by yancyribbens** [comment]
Also, I don't see the advantage to collapsing into a `usize`.  I think we should use `Weight` or a a type that indicates size.

**Comment by apoelstra** [comment]
> I think the makeup of segwit discount is valuable information, so I personally would like to see Weight contain "How much of my value is comprised of segwit (1 byte = 1 wu) and non-segwit (1 byte = 4 wu)?" be something that an instance of Weight can answer for itself.

This is very interesting. I think this would definitely be useful for debugging (and to catch bugs like these). Would it be useful in real life?

**Comment by yancyribbens** [comment]
I started a PR here to attempt to fix my mistake: https://github.com/rust-bitcoin/rust-bitcoin/pull/2053.
