### ISSUE TITLE
CI: dependabot to automate GitHub actions updates

### ISSUE THREAD

**Issue by realeinherjar** [rust-bitcoin/rust-bitcoin#2051]
Currently there's a bunch of actions that are outdated, e.g.https://github.com/rust-bitcoin/rust-bitcoin/blob/f8d7bcfce2b301870b1df23e6f508e8dd7942d10/.github/workflows/fuzz.yml#L41C15-L41C34.

Adding a [`dependabot.yml`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) to update these on a sane interval (weekly?) could help us.
It will automatically create PRs updating the CI GitHub actions.

**Comment by apoelstra** [comment]
These are deliberately "outdated" because these represent the latest versions of our dependencies that we've tested and support. Under no circumstance are we going to automatically modify these lockfiles. If anything we should remove the github warnings, which I agree are annoying and spurious.

**Comment by apoelstra** [comment]
Oh, I misunderstood, I thought you were talking about the `Cargo.*.lock` warnings -- these are the actual github actions.

**Comment by realeinherjar** [comment]
Yes, exactly! This does not touch Rust code or Cargo stuff.
Just the CI runner versions that are tagged currently to `@vN` where `N` is the major version.

For example, it updates the Node version on these action runners.
I am not familiar with Node, but my understanding is that recent versions could address security updates on old Node versions.
Example with `checkout/releases` which is on `v4` and we are using `v2` now (in my original comment above): https://github.com/actions/checkout/releases/tag/v4.0.0

**Comment by tcharding** [comment]
We can always turn this on and see if its useful then turn it off again if its too annoying.
