### ISSUE TITLE
Restructure Weight

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#2059]
This is a follows https://github.com/rust-bitcoin/rust-bitcoin/issues/2049 and the MR comments by @stevenroose #2001 #2010. 

@junderw writes
> I think the makeup of segwit discount is valuable information, so I personally would like to see Weight contain "How much of my value is comprised of segwit (1 byte = 1 wu) and non-segwit (1 byte = 4 wu)?"

Currently methods like [stripped size](https://github.com/rust-bitcoin/rust-bitcoin/blob/b2b562d44b87d16d821e8722449e02de813077bc/bitcoin/src/blockdata/transaction.rs#L718) is ambiguous as to if the bytes are counted as witness or non-witness bytes.

One possible structure @apoelstra mentioned would be:

```
struct Weight {
    non_witness_bytes: u64,
    witness_bytes: u64,
}
```

Another idea is to use an enum since methods like stripped_size will return either `non_witness_bytes` or `witness+bytes`.
```
enum Weight {
    NON_WITNESS_BYTES,
    WITNESS_BYTES,
}
```

Stripped_size method signature:
`pub fn stripped_size(&self) -> Weight::NON_WITNESS_BYTES`

If a composition of non_witness and witness_bytes is needed, they could be wrapped in an array or vec.

Another possibility is:
```
struct SIZE {
    virtual_bytes: u64,
    weight_units: u64,
}
```

I think using an enum is better for pattern matching.

**Comment by apoelstra** [comment]
Your proposed enum is only one bit large. How can it represent a weight?

**Comment by junderw** [comment]
This seems like the proper way to do things (sans all the boilerplate this will require)

```rust
#[derive(Clone, Copy)]
struct Weight {
    non_witness_bytes: u64,
    witness_bytes: u64,
}
#[derive(Clone, Copy)]
struct WeightUnit(u64);
#[derive(Clone, Copy)]
struct ByteSize(u64);
#[derive(Clone, Copy)]
struct VirtualSize(u64);

impl Weight {
  pub fn to_weight_units(self) -> WeightUnit {
    WeightUnit(self.witness_bytes + self.non_witness_bytes * 4)
  }
  pub fn to_byte_size(self) -> ByteSize {
    ByteSize(self.witness_bytes + self.non_witness_bytes)
  }
  pub fn to_virtual_size(self) -> VirtualSize {
    VirtualSize((3 + self.witness_bytes + self.non_witness_bytes * 4) / 4)
  }
}
```

**Comment by apoelstra** [comment]
This seems like way overkll. Just having `Weight` is fine and returning `usize` or `u64` for the accessors.

**Comment by junderw** [comment]
That's fine too.

**Comment by yancyribbens** [comment]
> Your proposed enum is only one bit large. How can it represent a weight?
 
@apoelstra Good point.  I guess I was being too informal.  What I meant was:

```
enum Weight {
    NON_WITNESS_BYTES(u64),
    WITNESS_BYTES(u64),
}
```

**Comment by yancyribbens** [comment]
If a function needs to return the bytes of both non-witness and witness bytes, then what about returning Vec<Weight>?

```
    enum Weight {
        NonWitnessBytes(u64),
        WitnessBytes(u64),
    }
    
    let non_witness_bytes = Weight::NonWitnessBytes(1);
    let witness_bytes = Weight::NonWitnessBytes(1);
    
    let composite = vec![non_witness_bytes, witness_bytes];
```

**Comment by yancyribbens** [comment]
Looks like this is outdated and can be closed https://github.com/rust-bitcoin/rust-bitcoin/commit/0de8ec5b19c48984bbe94146b20efcff4d9fcf9f
