### ISSUE TITLE
[Discussion] Upgrade rustc to 1.20.0 + future upgrade requirements.

### ISSUE THREAD

**Issue by dongcarl** [rust-bitcoin/rust-bitcoin#206]
There has been discussions over IRC, and I'd like to move the discussion here for easier access.

### History
Historically, we've stuck with `rustc` 1.14.0 because it was the `min` over the versions packaged in Debian stable on all architectures.

### Delta
Currently, Debian stable has packaged `rustc` 1.24.1 for all architectures.

### Proposal

1. Upgrade our `rustc` version assumption to 1.20.0 ([release notes](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1200-2017-08-31)) now, so that we get [associated constants](https://github.com/rust-lang/rust/pull/42809). This will allow us to simplify a lot of our interfaces.
2. Determine a checklist of requirements for future proposals to upgrade `rustc`.

**Comment by sgeisler** [comment]
@real-or-random afaik bootstrapping rustc has to begin with 1.19 or earlier versions because that's the latest version supported by mrustc. Every version increase over that introduces one more step from there.

**Comment by real-or-random** [comment]
I didn't follow the discussion in IRC. Why is bootstrapping so much more secure?

**Comment by dpc** [comment]
@sgeisler Isn't that something  automatic, and that will have to be done eventually anyway? Also, does it even have to be repeated again?

I was under impression that once you do a bootstraping like this once, and then compile the compiler source code with the bootstrapped compiler bainary and then with the original compiler binary, and they produce the same output, you've prooven that the original compiler at a given checksum does not contain any backdoors, and can be used from on as a starting point. Sorry if I'm terribly mistaken here. :)

Seems like GUIX team just went to 1.28.0: https://www.gnu.org/software/guix/blog/2018/bootstrapping-rust/

**Comment by dpc** [comment]
@real-or-random https://www.schneier.com/blog/archives/2006/01/countering_trus.html is my understanding.

**Comment by real-or-random** [comment]
> I was under impression that once you do a bootstraping like this once, and then compile the compiler source code with the bootstrapped compiler binary and then with the original compiler binary, and they produce the same output, you've proven that the original compiler at a given checksum does not contain any backdoors, and can be used from now on as a starting point. Sorry if I'm terribly mistaken here. :)

I'm under the same impression.

**Comment by dongcarl** [comment]
The real thing that I want to discuss is how the whole process should look like. Without a deterministic build of the compiler, we need to trust someone to build the compiler. Who do we trust?

This might be less of a problem because we don't release binaries, so any malicious tampering would only cause discrepancies between the Travis test results.

My naive plan that's meant to draw constructive criticism:
1. I build 1.19.0, then 1.20.0
2. I upload the binaries somewhere
3. I modify travis to pull down the binaries instead of using its own rust compiler

**Comment by dongcarl** [comment]
@dpc You're right. But there are usually many complications in this process, and the original author of the diverse double compiling paper, when trying to demonstrate the process, even had to patch compilers.

**Comment by real-or-random** [comment]
For what it's worth, there is quite some progress on a mrust targeting 1.29, see https://github.com/thepowersgang/mrustc/commits/nightly-1.29 and  https://github.com/thepowersgang/mrustc/issues/95 .

**Comment by dongcarl** [comment]
I've bumped the version to `1.20.0` here: https://github.com/rust-bitcoin/rust-bitcoin/pull/210

I believe we should use this thread to discuss how we want to do the process. Perhaps we should wait until deterministic builds are easy with rustc?

**Comment by real-or-random** [comment]
In general, it may be a good idea to bump shortly after a Debian release. This is rare enough, and we then can decide which version we want.

**Comment by dongcarl** [comment]
Closed by https://github.com/rust-bitcoin/rust-bitcoin/pull/210
