### ISSUE TITLE
Feature Request: Fail-safe for absurdly high fees in Psbt.

### ISSUE THREAD

**Issue by junderw** [rust-bitcoin/rust-bitcoin#2061]
In bitcoinjs-lib, I decided to throw a runtime exception when the feerate of the transaction is 2500 sats/vByte or higher.

The 2500 value can be overridden with a constructor parameter, AND the extractTransaction method (where the exception is thrown) has an optional variadic boolean flag to ignore the fee check.

In general, if we were to add this to Psbt:

1. It should be there by default with a high enough to avoid most false positives default value.
2. It should be configurable, and calls to extract should be able to bypass it altogether.

Things that would need to be decided:

1. What is the "sane default" we set?
2. How to we represent the error? (Result? Panic?) (Keep in mind this is discovered at the end of a method that takes ownership and heavily deconstructs and modifies Self.)
3. How do we make it configurable and bypassable? (Store it in the Psbt struct? Provide multiple methods?)

My suggestions:

1. 25000 sats/vByte (10x current bitcoinjs-lib default which I picked in 2019)
2. Panic is acceptable, because it is obvious that a runtime error is about to cause a large loss of funds. The default value can be adjusted depending on whether we choose Panic or Result, too... I also think as long as we document it and offer alternative methods that allow configuring the threshold, Panic is acceptable.
3. Offering 3 methods:
    a. `fn extract_tx(self) -> Transaction // basically calls extract_with_maximum_fee_rate with a const value and unwraps`
    b. `fn extract_tx_with_maximum_fee_rate(self, max_fee_rate: f64) -> Result<Transaction, Transaction>`
    c. `fn unsafe_extract_tx_ignore_absurdly_high_fee(self) -> Transaction`

Inspiration for this issue:
- https://twitter.com/mononautical/status/1700921854184054809
- https://github.com/bitcoinjs/bitcoinjs-lib/issues/1971

**Comment by junderw** [comment]
Note: Both methods besides `unsafe_extract_tx_ignore_absurdly_high_fee` would "error" in the case where any of the inputs are missing a nonWitnessUtxo or witnessUtxo. (ie. the fee can not be calculated)

**Comment by junderw** [comment]
I am willing to work on it. (Actually I've been playing around with it a little today, but I'll wait on making a PR until we decide on something.)

**Comment by apoelstra** [comment]
> Panic is acceptable, because it is obvious that a runtime error is about to cause a large loss of funds.

Hmmmm, while I tend to agree with "DoS is better than loss of funds" I still would rather avoid a surprising panic which would become a DoS vector.

I'm not sure where this limit would be enforced but I would vote to return a `Result`, and to have a `FeeRateTooHigh` error variant or `FeeRateSanityCheck` or whatever, which contained the PSBT for the user to extract if they wanted to override it.

**Comment by sanket1729** [comment]
I don't know whether this falls in the domain of library. Guessing the fee rate seems really arbitrary. But reading your linked issue, it did provide some protection. 

We should also expose an `extract_tx_fee_unckecked` API to allow other use-cases. For example, our local rust-miniscript test CI suite pays a hard-coded 1 BTC fee per tx.

**Comment by junderw** [comment]
I think even just having the API structure (an Error that contains the extracted Transaction or the Psbt itself, etc.) that makes coders cognizant of the possibility of overpaying fees is an improvement.

The default max value being arbitrary isn't very important.

As long as there's a way to get around it, the blame falls squarely on the coder and reviewers who use `unchecked` or do something like:

```rust
match psbt.extract_tx() {
  Ok(tx) => tx,
  Err(ExtractError::AbsurdlyHighFeeRate { transaction, .. } => transaction,
  _ => todo!(),
}
```

Obviously, it's always their responsibility. But it would be nice to tip them off, since at the point of extraction we have all the info needed to calculate fee, output value, tx vsize, etc. and make some guesses at what would be absurd.

**Comment by junderw** [comment]
I went ahead an made a PR for discussion.
