### ISSUE TITLE
proc-macro2 Faling for MSRV

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#2071]
Looks like another problem with MSRV on CI.  For #2069 I'm getting the following CI failure:

```
error: failed to select a version for the requirement `proc-macro2 = "^1.0.67"`
candidate versions found which didn't match: 1.0.63
location searched: crates.io index
required by package `syn v2.0.33`
    ... which is depended on by `wasm-bindgen-macro-support v0.2.87`
    ... which is depended on by `wasm-bindgen-macro v0.2.87`
    ... which is depended on by `wasm-bindgen v0.2.87`
    ... which is depended on by `console_error_panic_hook v0.1.7`
    ... which is depended on by `wasm-bindgen-test v0.3.37`
    ... which is depended on by `bitcoin_hashes v0.13.0 (/home/runner/work/rust-bitcoin/rust-bitcoin/hashes)`
    ... which is depended on by `bitcoin v0.30.0 (/home/runner/work/rust-bitcoin/rust-bitcoin/bitcoin)`
Error: Process completed with exit code 101.
```

**Comment by yancyribbens** [comment]
Looks like `syn 2.0.33` requires `rustc +1.56`.

**Comment by yancyribbens** [comment]
yeah I saw: https://github.com/rust-bitcoin/rust-miniscript/pull/598.  Still curious where the idea to use syn 2.0.x came from.

**Comment by tcharding** [comment]
In general, for pinning MSRV build one just has to experimentally find out which patch version broke the MSRV then pin to the version before it.

**Comment by yancyribbens** [comment]
I had thought it would be possible to copy `Cargo-minimal.lock` to `Cargo.lock` and then run `cargo update` and let cargo do the dependency resolution.  For reasons I still don't fully grok this strategy fails.

**Comment by apoelstra** [comment]
Of course cargo can't do it. If cargo were able to do its own dependency resolution then we wouldn't be having issues :).

**Comment by apoelstra** [comment]
And Cargo-minimal.lock has nothing to do with the pins needed by CI. How can we document that better?

**Comment by yancyribbens** [comment]
> How can we document that better?

It's probably beyond the scope of this project to document the intricacies of cargo dependency resolution.
