### ISSUE TITLE
Consider re-exporting hash types from modules where they belong

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#2072]
1) XPubliIdentifier can also be re-exported from bip32.
2) PubkeyHash, WPubKeyHash etc from script module.
3) TxMerkleNode, WitnessMerkleNode from the network related modules.
4) Txid, WTxid from transaction module etc. 
5) Others...

**Comment by tcharding** [comment]
Of late I've been moving them to where they belong and re-exporting them at crate root (see #2021).

**Comment by apoelstra** [comment]
Thanks @tcharding :) I knew you'd been doing something similar to this but I couldn't remember where it was.

**Comment by tcharding** [comment]
No sweat, I have a feeling I've touched others too but I couldn't find them right now. Perhaps, if you agree with #2021 @sanket1729 we could re-write this issue to say "move hash definitions to where they belong and re-export at crate root". I'm also totally fine just leaving this issue as it is, it still flags the work.
