### ISSUE TITLE
CompactTarget should not be Eq, Ord, and Partial* needs more nuance

### ISSUE THREAD

**Issue by junderw** [rust-bitcoin/rust-bitcoin#2110]
https://github.com/rust-bitcoin/rust-bitcoin/blob/eab9f89779eb4b84ea8bdb5140ddc52906382250/bitcoin/src/pow.rs#L259-L262

Right now we just derive the Ord and Eq from the underlying u32.

# This causes "incorrect" Ord and Eq implementations.

## Ord

`0x1b000001` > `0x1a010000` is true, but comparing the targets expanded from them it would be false.

```
0x1b000001 -> Target(0x0000000000000001000000000000000000000000000000000000000000000000)
0x1a010000 -> Target(0x0000000000000100000000000000000000000000000000000000000000000000)
```

## Eq

`0x1b000001` != `0x1a000100` is true, but comparing the targets expanded from them it would be false.

```
Target(0x0000000000000001000000000000000000000000000000000000000000000000)
Target(0x0000000000000001000000000000000000000000000000000000000000000000)
```

# This also brings into question the validity of Eq and Ord

("window" refers to the 3 byte mantissa of the compact target. The most significant byte of the compact target tells Core where to place the last 3 bytes on the 32 byte target. (3 being the lowest window (least significant 3 bytes) and 32 being the highest window (most significant 3 bytes))

What if the 3 byte "windows" shown by the compact target don't overlap?

I think it's sane to assume "there will be no bits set to 1 above the 3 byte window of this compact target"

But we can't say the same about bits below the 3 byte window. Even if the u32 is equal, unless that value starts with 0x03 (aka the 3 byte window is the 3 least significant bytes) can we really say that "the targets are equal?"

This seems like an arbitrary decision, but I would vote for removing Eq and Ord.

**Comment by junderw** [comment]
If we want to maintain Eq and Ord, then perhaps we could define them as follows:

1. Assume bits above the "windows" are all 0.
2. If the windows overlap, assume all bits below the windows are 0, shift the value with the highest window over 8 or 16 bits to match the lower window, and compare.
3. If the windows do not overlap, they are not equal and the higher window is greater than.

**Comment by junderw** [comment]
Also, I think perhaps we should validate a few things when creating a CompactTarget from a u32.

1. Top byte (exponent) must be between 3 and 32.
2. Mantissa must not be 0 or have the most significant bit set (negative numbers aren't supported)

So `0x02010203` would be invalid for rule 1 and `0x1d000000` and `0x1d82dfe2` would be invalid (the 8 is setting the most significant bit)

**Comment by apoelstra** [comment]
I don't really follow your reasoning about "windows not overlapping". It seems to me that if the exponents differ by 3 or more, and either mantissa is nonzero, then the two compact targets represent different targets. If the exponents differ by less than 3, then the comparison is more complicated (but could be done by embedding both mantissas into u64s, shifted appropriately).

My feeling is that we should avoid all this reasoning by just implementing `Eq` and `Ord` in terms of non-compact targets. So we would call `Target::from_compact` on both operands then compare the result.

>Also, I think perhaps we should validate a few things when creating a CompactTarget from a u32.

Hmmm. What if the `bits` field of a block has an exponent >32? How does Core handle this?

**Comment by junderw** [comment]
> I don't really follow your reasoning about "windows not overlapping".

The rules of compact target representation imply that the window is showing the most significant bytes in that Target.

If we have an exponent of 25 and 15, the 25 exponent compact target must be larger.

0x19nnnnnn is always larger than 0x0fnnnnnn (no overlap)

0x10400000 is definitely larger than 0x12000020 even though the exponent is smaller (1 byte overlap)

But, importantly, 0x10400000 and 0x12000040, even though they expand to the same Target, are not necessarily equal, because we can't see the 2 bytes below the 0x40 on the latter value.

And in fact, even if two CompactTargets are exactly equal, we can't see the lower values (they could be all 0xff like the Core pow limit or all zeroes like our constant) so it becomes a gray design choice that needs consideration of the ways we use CompactTarget.

**Comment by apoelstra** [comment]
>expand to the same Target, are not necessarily equal, because we can't see the 2 bytes below the 0x40 on the latter value

Ok, I see, you are suggesting that philosophically a compact target might "be" a different target than the one it expands to. Because multiple targets have the same compact representation.

This seems like a good justification for dropping `Eq` and `PartialEq`. Users can compare the underlying u32s if they really want to do this.

But `Ord` I think we can keep because the compact representation does preserve order.

**Comment by junderw** [comment]
> My feeling is that we should avoid all this reasoning by just implementing Eq and Ord in terms of non-compact targets. So we would call Target::from_compact on both operands then compare the result.

That is probably the solution that most closely mimics Core.

**Comment by Kixunil** [comment]
Agree, let's drop them. But we can still have explicitly named comparison methods for convenience.
