### ISSUE TITLE
ci: change from `actions-rs/toolchain` to `dtolnay/rust-toolchain`

### ISSUE THREAD

**Issue by realeinherjar** [rust-bitcoin/rust-bitcoin#2113]
[`actions-rs/toolchain`](https://github.com/actions-rs/toolchain) is an "Unofficial GitHub Actions for Rust programming language" which has only one person in the organization, @svartalf, which appears to be MIA for a long time.
People are asking in vain for these fixes, check https://github.com/actions-rs/toolchain/issues/221 (almost a year long).

There are a bunch of warnings in CI, e.g. https://github.com/rust-bitcoin/rust-bitcoin/actions/runs/6440479240/job/17492350278#step:5:46.

[`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain) is by a well-established Rust developer, and it is well-maintaned (and has more stars than `actions-rs/toolchain`.

It might be an easy fix, but we need to check if the options are semantically the same.

**Comment by vincenzopalazzo** [comment]
Yeah, I agree we need something more recent. I am not sure about https://github.com/dtolnay/rust-toolchain

I have no opinion currently

**Comment by apoelstra** [comment]
I'm fine with using dtolnay's thing. Our CI setup is part of a larger QA system and the repo has no secrets or other things that CI could cause problems with. Obviously I am not thrilled with dtolnay given our ongoing difficulties with serde but this sounds like it's a step up from something which is literally unmaintained.

**Comment by vincenzopalazzo** [comment]
>dtolnay given our ongoing difficulties with Serde but this sounds like it's a step up from something which is literally unmaintained.

I did not want to say, but this was also my thought. It is not with the person itself, but more in the centralization of work done by a single person

**Comment by realeinherjar** [comment]
I will open a PR in the mean time

**Comment by tcharding** [comment]
We already replaced `actions-rs/toolchain` with `dtolnay/rust-toolchain` in most every place, seems there is only the one instance in `fuzz.yaml` left.
