### ISSUE TITLE
`hash_ty` is a bad name

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2139]
The `ecdsa::Signature` field names need some love before v1.0

- `hash_ty` is not great, `ty` so as not to use reserved keyword `type`?
- `sig` makes usage ugly: we often end up with `sig.sig`

Possible solution:

```rust
pub struct Signature {
    /// The underlying ECDSA signature.
    pub inner: secp256k1::ecdsa::Signature,
    /// The corresponding sighash type.
    pub sighash_type: EcdsaSighashType,
}
```

`inner` is not that great either, ideas?

**Comment by apoelstra** [comment]
Maybe `ecdsa_sig`? Or just `sig`? It will result in some stutterning `sig.sig` but that's fairly common with crypto types.

**Comment by dpc** [comment]
AFAIR `inner` is rather standard name to use, and stdlib is full of these: https://doc.rust-lang.org/src/std/fs.rs.html#100-102

**Comment by Kixunil** [comment]
Why not just call it `signature`? Yeah, if someone has `signature.signature` it looks a bit funny but I've done it and it's not really bad IMO. Maybe `raw_sig` if you really want to avoid it.

@dpc not that much in public API where it's `get_ref`, `get_mut` or `into_inner` - that's the closes one I've seen.

**Comment by tcharding** [comment]
Perhaps `signature` is best. Local var usage can then be `sig.signature` which looks better to me than `sig.sig`.
