### ISSUE TITLE
hashes: Stabalization - roadmap to v1.0

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2157]
Tracking issue for what is needed for us to be able to stabalize the `hashes` crate.

- All errors seem to be satisfactory (there is only one error type in this crate)

### Issues we want resolved

- All issues labelled as both "1.0" and "hashes"
- sort out #2130 vs #1555

### Issues that might apply

- Consider issues described in https://github.com/rust-bitcoin/rust-bitcoin/discussions/2160

**Comment by tcharding** [comment]
This search brings up a bunch of candidates:

 https://github.com/rust-bitcoin/rust-bitcoin/issues?q=is%3Aissue+is%3Aopen+hashes but I do not know which ones we want.

**Comment by apoelstra** [comment]
For `hashes` the big thing is that we want to create a new more-discoverable API.

**Comment by tcharding** [comment]
Is the API good to go? It looks pretty nice to me.

**Comment by apoelstra** [comment]
It might be. I'd like to get it out into enough releases that I can start upgrading my personal crates the play with it. I recall us being in an incomplete state as far as splitting up `Hash` and `GeneralHash` but maybe with your recent work on tagged hashes, we've completed that.

Without really digging in, I suspect that the set of macros we expose still kinda sucks. (But it may be that they are minimally sucky and we just want to ship them.)

**Comment by tcharding** [comment]
"Hey Tobin what do you work on?". To which I shall now reply, "I produce minimally sucky crates" - ROFL

**Comment by tcharding** [comment]
This issue has no real information in it anymore.
