### ISSUE TITLE
Per crate labels

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2174]
Any objections to adding per crate labels i.e., "hashes", "internals", (and soon "io") to help us search issues based on which crate they are associated with. I mainly want this so I can filter by "hashes" + "1.0" to find what needs doing to stabalize `hashes`. Maybe we don't need "internals"

**Comment by Kixunil** [comment]
No objection, I think I wanted it already. Go ahead.

**Comment by tcharding** [comment]
Sweet, I'm on it.

**Comment by tcharding** [comment]
@Kixunil those bright yellow crate labels were stressing me out, I made them a more gentle color.

**Comment by Kixunil** [comment]
Funny, I wanted them to stand out a bit but not be orange/red to not trigger "this is important" vibe. Yellow was unlike any other color we frequently use. The current one is a bit similar to others.

**Comment by tcharding** [comment]
Fair point, I changed a few of the other close colors, hope I've not made it worse, its a bit subjective. I tried to make labels that were action items bright yellow (ie, do this before that). I made informative ones one of the light whitish colors, and left red as they were, the important ones like bugs. That should make the crate ones stand out but not be stressfull when there is 5 one a PR.

**Comment by tcharding** [comment]
There were two docs labels 'doc' and 'documentation' - I got rid of the long one and kept the short one.
