### ISSUE TITLE
Error deserializing transaction

### ISSUE THREAD

**Issue by stevenroose** [rust-bitcoin/rust-bitcoin#219]
I'm trying to parse a transaction from the Core functional tests: 

> test fundrawtransaction with OP_RETURN and no vin

```
0100000000010000000000000000066a047465737400000000
```

I'm getting this error: `ParseFailed("data not consumed entirely when explicitly deserializing")`.

Before that error is thrown by `bitcoin::consensus::encode::deserialize`, the transaction looks like this (using `Debug`):
```
Transaction { version: 1, lock_time: 0, input: [], output: [] }
```

So the output got skipped somehow, probably because of the segwit parsing when the inputs are empty.

**Comment by TheBlueMatt** [comment]
This is expected and due to the segwit ambiguity there isn't a ton we can do about it. We should, however, have a better error message. https://docs.rs/bitcoin/0.16.0/bitcoin/blockdata/transaction/struct.Transaction.html

**Comment by stevenroose** [comment]
So you're saying no-input transactions are be definition unencodable?

**Comment by TheBlueMatt** [comment]
Well, kinda, not really. There is ambiguity for 0-input transactions due to segwit (this is not an issue for the chain, obviously, as 0-input transactions are not valid for confirmation), the easiest resolution is to fail decoding non-segwit-marker-byte-encoded-0-input transactions and to encode 0-input transactions with a segwit marker byte (despite it not being a segwit transaction by definition as it has no witnesses).

**Comment by TheBlueMatt** [comment]
If you need to decode such transactions we could add a "deserialize_non_segwit_transaction" method that only works for non-segwit txn to avoid the ambiguity.

**Comment by thomaseizinger** [comment]
Shouldn't this be solved by https://github.com/rust-bitcoin/rust-bitcoin/pull/153?

**Comment by TheBlueMatt** [comment]
Only on the serialization side (ie we will always succeed at deserializaing transactions we serialized), but on the deserialization end, you cant get away from the ambiguity.

**Comment by stevenroose** [comment]
@thomaseizinger yeah like @TheBlueMatt says. I think most software will serialize a 0-input tx with segwit nowadays anyway. This example comes from a functional test in Core. Core's `DecodeHexTx` first tries to deserialize both with segwit explicitly enabled and disabled.

I feel ok with just accepting this as a minor inconvenience that we will never bump into probably. I changed the specific tx in the Elements test with one that uses segwit, I could do the same in Core. And then we're very unlikely to bump into this ever again :)
