### ISSUE TITLE
`Script::is_provably_unspendable` is poorly documented and may be misleading

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2191]
The name suggests that the method returns `true` if there exists any proof that the script is unspendable. However that is not what the method does - it only checks the first opcode. So if the first opcode lets the script to continue and the second one makes the script unconditionally fail a proof exists ("just look at the second opcode and verify that the first one is not a condition") but the method will return `false`.

The method should probably be named `is_trivially_unspendable` or `is_trivially_provably_unspendable` (too mouthful IMO the former alternative looks fine). Further the documentation doesn't mention anything about the limitations of the method and should be extended to explain what's going on.

**Comment by junderw** [comment]
`first_op_unspendable` maybe?

**Comment by Kixunil** [comment]
That is also a possibility although operations are not spendable or unspendable so it reads a bit weird. `fisrt_op_invalid` is precise but if the intention of the code is checking spendability it's a bit less clear.

**Comment by apoelstra** [comment]
I'm fine renaming this since it's a pretty weird method (I originally wanted to use it to prune the UTXO set to fit in memory, but I found the savings were way too small to be useful). But I don't think "provably unspendable" means "true iff any proof exists".

If this were true the word "provably" would be meaningless since spendability is computable, so "a proof exists" is equivalent to "is true" and the method could just be called `is_spendable`.

We could update the docs to say "this method uses only a small set of criteria and we may extend it in the future so that the set of provably unspendable scripts may increase".

**Comment by Kixunil** [comment]
Checking a signature with unknown private key is unspendable but cannot be proven. You can prove something is not spendable if the interpreter returns false though.

> We could update the docs to say "this method uses only a small set of criteria and we may extend it in the future so that the set of provably unspendable scripts may increase".

This does make sense.

**Comment by apoelstra** [comment]
A proof may still exist. It would consist of a proof that the discrete logarithm was hard, and that the key in question was generated by a hash function (assumed to be a random oracle) such that with overwhelming probability nobody knows the discrete log.

Since the first half of such a proof would be a groundbreaking result in mathematics, I'm doubtful that anybody would interpret the name of this function in a way that would imply that it could find such a proof :).

**Comment by Kixunil** [comment]
If you previously had the key and lost it there's a discreet log but no proof.

**Comment by apoelstra** [comment]
Yes, but it's impossible to distinguish the provable case from the unprovable case. So I continue to think that your interpretation of `is_provably_unspendable` is impossible and therefore that nobody would interpret it that way :)

**Comment by Kixunil** [comment]
Yes, my interpretation is impossible, that's part of my point. (I'm *not* proposing to implement it as named.) Whether someone would interpret it that way is hard to tell but given how few people understand cryptography&co it seems likely someone would. Even if not, it's surprising "WTF, this method is claiming to do something impossible, what exactly is broken about it?" At least I have this exact reaction to any API that seem to do something impossible (or unsound in Rust) and then start reading the code.

**Comment by apoelstra** [comment]
We can rename to `is_trivially_unspendable` if you like. But it never occurred to me that somebody would interpret "not provably X" as "no proof of X exists", given that the latter phrasing is far more explicit and the claim is so strong that you'd need to be explicit to get your meaning across.

**Comment by kayabaNerve** [comment]
`is_provably_unspendable`, IMO, would exhaustively run a prover to determine if any proof it's impossible to spend can be built. While I know that's not what this function does, I strongly agree it can be better named.

`trivially` sounds good to me personally. Or `is_known_unspendable`.

**Comment by RCasatta** [comment]
`is_known_unspendable` +1

related to expand recognized scripts https://github.com/bitcoin/bitcoin/pull/28400

**Comment by Kixunil** [comment]
They have different semantics - `trivially` suggests it's fast, `known` doesn't suggest anything such and could involve curve operations. But also `known` sounds similar to `provable` to me so I'm not sure about that.

Another suggestion: remove it completely. The original purpose was to prune UTXO but the results are not great and we're not aware of other use cases. And if someone comes up with a use case picking semantics will be much easier.

**Comment by apoelstra** [comment]
We should have a method that simply checks whether it's of the form `OP_RETURN <x>`. This is easy to accurately describe and is generally useful. Also we should have a method that extracts the `<x>`. So maybe we should drop this complicated and open-ended method in place of one that just detects op-returns.

In Core such outputs are called "nulldata" but I don't think that term is widely used outside of the Core codebase.

**Comment by Kixunil** [comment]
We already have `is_op_return`. For extracting, I actually have a potentially interesting big change in the pipeline, was just waiting on `CompressedPublicKey`. :)

Concept ACK removing the method but maybe let's deprecate it first?

**Comment by apoelstra** [comment]
Sounds good. Yep, let's deprecate.
