### ISSUE TITLE
`Script::dust_value` method name disagrees with the documentation

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2192]
Dust is a value that is not economically spendable and can not be broadcasted. The method is called `dust_value` which suggest it returns a value that is too small (and always returning 0 would be a valid implementation) but the documentation says "Returns the **minimum value* an output with this script should have in order **to be broadcastable** on today’s Bitcoin network." (emphasis mine) which implies it's a non-dust value.

Since writing a method that always returns 0 is useless I assume the documentation is right but the method is named incorrectly. I was not able to verify the implementation yet.

**Comment by apoelstra** [comment]
Can you suggest a different name? I think "minimum spendable value" is more useful than "maximum unspendable value" so I don't think we should change/replace the function. But it's hard to name, and this value is known in the bitcoin-dev ecosystem as "the dust limit". As in "this output is below the dust limit".

Would `dust_limit` be ok? TBH it seems like it's just as potentially confusing as the existing name.

**Comment by Kixunil** [comment]
Just `minimal_non_dust` as we have on `TxOut`?

**Comment by apoelstra** [comment]
Yeah, I think that's fine. Though we should use the phrase "dust limit" in the doccomment so that it'll show up in search results.
