### ISSUE TITLE
from_vb in const context.

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#2205]
It's not possible use `from_vb` in const context.  Is there any object to adding a `from_vb_const` function for this?

**Comment by apoelstra** [comment]
No objection from me in principle. Though depends how ugly it is.

**Comment by yancyribbens** [comment]
https://github.com/rust-bitcoin/rust-bitcoin/pull/2206

I mean it's pretty ugly, but only until +1.57 :)

**Comment by Kixunil** [comment]
#2206 was merged but I'm keeping this open because I don't like the name.

**Comment by yancyribbens** [comment]
closing since #2228 merged
