### ISSUE TITLE
`From<Txid> for TxMerkleNode`  should exist

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2220]
Txid is a merkle node - the leaf one, so it should be directly convertible (but not the other way around). Just like `From<LeafNode> for TapNodeHash`.

Also `From<sha256d::Hashs>` looks too low-level - can someone explain why it's there? I think this is remnant from old code and should be removed.

**Comment by apoelstra** [comment]
I think `From<sha256d::Hash>` may be used with the network protocol, where the `inv` message has raw bytes which might be a txid, blockhash, or something else, and must be interpreted based on context.

But probably you're right, that this is a remnant of old code before we'd fully typed TXIDs etc., and were still thinking of them as "a kind of sha256d hash".
