### ISSUE TITLE
Helper function to calculate transaction fee

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-bitcoin#2237]
It's pretty trivial to sum the inputs and sum and subtract the outputs, but a helper function would be nice.

**Comment by casey** [comment]
Oh wait, I'm dumb. You don't know the input values just from the transaction 😅

**Comment by Kixunil** [comment]
FTR, this has annoyed me in Bitcoin for a while. I'd really love to see something like `ExtendedTransaction` with prevouts being readily available in the ecosystem. It's required almost everywhere anyway.
