### ISSUE TITLE
units: `impl TryFrom<Amount> for SignedAmount` and vice-versa

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2245]
These conversions mimic the standard library and should be naturally available. Note that `to_unsigned`/`to_signed` already exist so just call that. However the error types are unfortunate, we should have non-parsing-related ones.

**Comment by yancyribbens** [comment]
Can you add a link to the standard library that this should mimic?  I opened a somewhat relate PR here: https://github.com/rust-bitcoin/rust-bitcoin/pull/2244

**Comment by yancyribbens** [comment]
mimic this I think https://doc.rust-lang.org/std/convert/trait.TryFrom.html

**Comment by yancyribbens** [comment]
While adding TryFrom may be useful for some case, I find #2244 useful since we don't care about the error variant always, for example in the case where we know it's positive, and TryFrom returns an error variant .  Or maybe you have a different idea.

**Comment by 0xkrieger** [comment]
I would like to take this if @connormullett is not working on this.

**Comment by tcharding** [comment]
We don't really do dibs, just grab it and push up a PR. First in best dressed.
