### ISSUE TITLE
Use `arrayvec`?

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2247]
Would it be OK to (non-publicly) depend on `arrayvec`? Its MSRV is below ours, it has multiple contributors and can help in multiple places:

* serialized signatures - they currently hand-roll the same thing without `MaybeUninit` optimization
* `WitnessProgram` - has known maximum length
* Taproot branch - maximum length of 128 (OK, this one is actually pretty big, so maybe not that great idea. But it's likely mostly used when serializing into witness anyway.)
* `BufEncoder` could be revamped to use `ArrayString` instead. (Which I guess also skips UTF8 checks.)

There my be other places I didn't think about yet.

**Comment by apoelstra** [comment]
What if we brought it in, didn't expose it, and if it never broke us in a year, say, we'd be willing to expose it.

**Comment by Kixunil** [comment]
Yeah, could be something like that plus it'd have to stabilize.

**Comment by tcharding** [comment]
Sounds reasonable to me.
