### ISSUE TITLE
Should we use `everything-else*` feature for stabilization?

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2253]
Because of how default features work some crate make themselves forwards-compatible by introducing `everything-else-1` feature which is required for the crate to compile and is in default. Then if someone disables default features they are forced to pick some version of `everything-else`. Thus when the crate later wants to put *existing stuff* behind a feature it can by introducing `everything-else-2` and the crates that don't need the stuff that was just gated simply depend on `everything-else-2`. (If you still don't understand it, don't worry, took me a long time to get it, try giving it some time.)

Should we do it too? Honestly, it looks a bit annoying to me for `no_std` consumers but it gives us more flexibility to fix things up without breaking anyone.

**Comment by apoelstra** [comment]
I think I get it. But soft NACK -- it has pretty bad ergonomics and I'm skeptical that we'll want to put additional things behind feature gates after 1.0.

Maybe if we had a specific application (e.g. trying to make the rust-secp dep optional) in mind I could go along with it.

**Comment by tcharding** [comment]
Unless we have a pretty good reason to do this I"m mildly against it. I like the fact that we are now able to compile with no features, I always disliked the std/no-std requirement.

**Comment by Kixunil** [comment]
@tcharding it'd compile, the crate would be just empty. Note also that, as opposed to `no-std`, this doesn't pull in additional dependencies or activate unneeded parts of the library. Activating `no-std` from downstream *libraries* was never correct, activating `everything-else` would always be correct.

**Comment by NguyenTrongTin1107** [comment]
hi guys, sorry for annoying you. I'm looking for a channel where we can discuss with team directly, which is more efficient

**Comment by Kixunil** [comment]
Semver applies to any combination of features including the feature names themselves. We can't introduce it later because it'd break downstream crates which used `default-features = false` and depended on whichever things became feature gated. That's why other crates set it proactively.

**Comment by tcharding** [comment]
Ok, excuse my slowness, so this trick is to make it so we can _remove_ things from the public API (by changing the feature gating of them) in a minor release, but still not break downstream because of how we define featurs - that does not seem like a net win to me. (Unless I'm still missing something.)

**Comment by Kixunil** [comment]
Yes, we can put anything we want behind a feature flag and not break anything. The downside is that all `no_std` (or no-default-features) users will have to explicitly set the version of `everything-else`.

There were also proposals to improve Cargo so this trick wouldn't be needed but it didn't get enough traction.

Anyway, looks like we all agree that we probably don't want this so I'm closing this as resolved. If anyone comes up with an argument we can reopen.
