### ISSUE TITLE
ExtendedPub(Priv)Key in bitcoin 0.31.0?

### ISSUE THREAD

**Issue by tinguyen1107** [rust-bitcoin/rust-bitcoin#2256]
I am building a bitcoin wallet. We would like to construct a master account for user, where can I find the replace of ExtendedPubKey and ExtendedPrivKey jn bitcoin 0.31.0

**Comment by apoelstra** [comment]
They are `Xpub` and `Xpriv`.

But cc @tcharding can we patch in the old names somehow? I guess we cannot mark type aliases as `deprecated` but the existing situation is really non-discoverable.

**Comment by Kixunil** [comment]
IIRC *type aliases* can be deprecated, `use` items can't.

**Comment by tcharding** [comment]
This is sitting on the `0.31.x` branch, can you do a point release of that branch please @apoelstra?

**Comment by tinguyen1107** [comment]
Thankyou guys. The problem is solved. Everything is good now.

**Comment by apoelstra** [comment]
@tcharding can you do a PR to the branch bumping the version in Cargo.toml?

**Comment by tcharding** [comment]
Can do!

**Comment by tcharding** [comment]
commit: `cfa018c9 Bump version to 0.31.1`

**Comment by apoelstra** [comment]
Tagged and published.
