### ISSUE TITLE
Sha256dHash le/be misnamed?

### ISSUE THREAD

**Issue by DR-BoneZ** [rust-bitcoin/rust-bitcoin#228]
Forgive me if I'm wrong on this, but aren't the functions `into_be`/`into_le` and `be_hex_string`/`le_hex_string` misnamed? 

`be_hex_string` gives correct network format txids, however it was my understanding that bitcoin txids were little endian.

**Comment by dongcarl** [comment]
`Sha256dHash` has been removed since https://github.com/rust-bitcoin/rust-bitcoin/pull/215
