### ISSUE TITLE
units: `ParseIntError` is preventing crate smashing

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2282]
Context:

- The `ParseIntError` appears in our public API. 
- It is used by the `weight` module.
- We would like to move `Weigt` into the new `units` crate.

Where can we put the code currently in the `bitcoin::parse` module so it can be used for crate smashing? A stand alone crate, a crate in the `rust-bitcoin` repo?

**Comment by Kixunil** [comment]
I think it fits into `units`. From what I can see it's used in `pow` which might get added to `units` too, `WitnessVersion` which is a part of block data which will definitely depend on `units` and lock times which also fit into units.

**Comment by apoelstra** [comment]
Concept ACK pulling `pow` into `units` if it makes our coherency/error story simpler.

Originally I was unsure about `pow` because it feels like it's not useful without `block::Header` et al. Vs amount/fee/rates which people often do computations with independently of "real" bitcoin objects. But OTOH target/difficulty/etc *are* units so they'd fit into `units`.

**Comment by tcharding** [comment]
Moving `pow` is clunky:
- Should `CompactTarget` move as well?
- We can no longer switch on `Network` so the `difficulty` function gets ugly.
- We don't have `BlockHash` so `is_met_by` cannot be an method on `Target`.

The second two points can be solved by adding a `target` module with functions so users can call `target::is_met_by(target, block_hash)`. But doing this makes the API worse IMO.

**Comment by Kixunil** [comment]
Some ideas

* rename `bitcoin_hashes` to something like `bitcoin_hash_tools` (can't figure out a better name)
* make a new crate `bitcoin_hashes` that contains all the hash newtypes used in APIs (I know, we recently split the module :( )
* optionally depend on it from units to be able to implement `is_met_by`
* don't move `CompactTarget`

Alternatively:

```rust
pub trait BlockHash {
    fn block_hash(&self) -> [u8; 32];
}

impl Target {
    pub fn is_met_by(block_hash: &impl BlockHash) -> bool { /* ... */ }
}

// in primitives crate, which depends on units:
impl units::BlockHash for BlockHash {
    fn block_hash(&self) -> bool { self.to_byte_array() }
}
```

The former could resole other no-alloc issues, the latter is simpler and we could implement `BlockHash` for `Block` and `Header` for convenience.

**Comment by apoelstra** [comment]
> * Should `CompactTarget` move as well?

Only if we're forced to. I think `CompactTarget` is part of the block serialization more than it's part of the unit. I wonder even if it should be removed in favor of `encode_compact`/`decode_compact`/`reduce_to_compact_precision` methods.

> * We can no longer switch on `Network` so the `difficulty` function gets ugly.

There are a couple options here. One is to split `difficulty` into a `mainnet_difficulty` and `testnet_difficulty` method. Another is to copy `Network` into `units`, impl `From`/`Into` in rust-bitcoin to the real `Network`, and have difficulty take a generic `Into<Network>`.

Another is to move `Network` into `bitcoin-util` or whatever which should be a "core" crate which just defines the enums and traits that are needed for everything else to interop. (I continue to think this should be called `bitcoin-primitives`.

> * We don't have `BlockHash` so `is_met_by` cannot be an method on `Target`.

We could replace this with a `meets` method on `BlockHash` itself, or by having `Target::is_met_by` take an `Into<sha256::Hash>` (probably we don't want to do that) or by again making a copy of `BlockHash` with `From`/`Into` and being generic on that, or by moving `BlockHash` (and `Txid` probably) into bitcoin-primitives.

**Comment by Kixunil** [comment]
> I think `CompactTarget` is part of the block serialization more than it's part of the unit.

Agreed.

> We could replace this with a `meets` method on `BlockHash` itself

This looks simplest and maybe the method should be there anyway. `is_met_by` resembles Yoda condition since in verification block one verifies if block (thing on the left) satisfies conditions (on the right).

So unless there's an argument against it I prefer this.

**Comment by apoelstra** [comment]
It does feel like a Yoda condition, but OTOH if you have a `Target` you probably want a way to compare it to a `BlockHash`. While if you have a `BlockHash`, messing with `Target`s is an obscure thing to do.

So in terms of discoverability it's a loss. But I think we can make up for it by having a prominent "compare target to blockhash" example in the docs.

**Comment by Kixunil** [comment]
I think I'd personally search the method inside `Header` or `Block`. And we can add those there, it's simple and obvious.

Having a full "validate POW" example in the cookbook would be great.

**Comment by Kixunil** [comment]
FYI I tried to look at this and we're also blocked on messy error types in `absolute`. Working on it.

But the question is, maybe those fit into units too? At least `Height` and `Time`.

**Comment by apoelstra** [comment]
Yeah, I think it makes sense for the locktime types to go into `units`.
