### ISSUE TITLE
Methods on `Address` return `address::Error`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2290]
E.g. `from_script` returns it and `NetworkValidation` is one of its variants. Or other methods return it and it has `UnrecognizedScript`. We should split it up.

**Comment by Harshit933** [comment]
I'll take this up.

**Comment by tcharding** [comment]
Awesome, one suggestion for you to reduce the number of dev/review cycles. You could do this task as multiple little PRs, if you just do a couple first you can apply what you learn to others. For example
```rust
    /// Creates a pay to script hash P2SH address from a script.
    ///
    /// This address type was introduced with BIP16 and is the popular type to implement multi-sig
    /// these days.
    #[inline]
    pub fn p2sh(script: &Script, network: impl Into<NetworkKind>) -> Result<Address, Error> {
        if script.len() > MAX_SCRIPT_ELEMENT_SIZE {
            return Err(Error::ExcessiveScriptSize);
        }
        let hash = script.script_hash();
        Ok(Address::p2sh_from_hash(hash, network))
    }
```

Could be done as a single PR, just give the function an error of its own. Another idea is to do the whole module locally on your machine and just push up the changes in individual PRs.

You might then end up with a PR "remove all the unused variants" but that's ok. Anways, just an idea - do it how you think is best.

**Comment by tcharding** [comment]
This is stale.
