### ISSUE TITLE
`Script::is_op_return` doesn't validate length

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2292]
Well, strictly speaking, it's consensus-valid but non-standard to have it longer than 80B. It's not clear that this returns consensus-valid, possibly non-standard (Should it be consensus? I think so but it's also a bit annoying being unable to stack-allocate.)

At least it should be documented.

**Comment by apoelstra** [comment]
Agreed it should be documented. My feeling is that we shouldn't validate length here. We could add a method `is_standard_op_return` and explain that it matches Core's current policy and that we might change it to match future versions of Core without warning.

**Comment by shinghim** [comment]
looks like this can be closed - it was addressed in #2949
