### ISSUE TITLE
units: `Amount` doesn't parse `u64::MAX`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2297]
Test case:

```rust
assert_eq!(
    ua_str(&ua_sat(u64::MAX).to_string_in(D::Satoshi), D::Satoshi),
    Ok(Amount::MAX)
);
```

Fails with too big. This `if` looks wrong but if I comment it out other tests fail and it's hard to understand why, so if anyone can help, that'd be great.

https://github.com/rust-bitcoin/rust-bitcoin/blob/eadc6a6c9eb8c397f01f41db99b5c78bb22a437d/units/src/amount.rs#L612-L614

**Comment by junderw** [comment]
Amount is i64 in Bitcoin core.

The current code is correct.

I'm surprised the other methods don't check the u64 bounds.

**Comment by Kixunil** [comment]
That's absolutely not relevant here since this is Rust, not C++ and thus this kind of thing is very surprising for Rust developers. (We've already agreed to write Rust-idiomatic code over Core-like.) We've been discussing whether to restrict the range to 21M BTC and the consensus is no. (IIRC I was the only one who would like it but I'm not that convinced lately.)

Also given we have `MAX` equal to `u64::MAX` the code as a whole is absolutely not correct. If we wanted to restrict it artificially we have to enforce the invariant everywhere and also have the correct constants. Which at this point I don't think we want to do. And if there's a limit, I absolutely prefer 21M BTC over some arbitrary number.
