### ISSUE TITLE
Witness should have a constructor from a slice of Scripts.

### ISSUE THREAD

**Issue by junderw** [rust-bitcoin/rust-bitcoin#2300]
See: https://github.com/rust-bitcoin/rust-bitcoin/issues/2241#issuecomment-1859258868

It's fallible since not all Scripts are valid in Witness position (must be push only)...

But currently the only way to construct a Witness is through a slice of slices of u8 that are all interpreted as PUSHDATA ops.

This prevents non PUSHDATA ops like OP_1 - OP_16 from being used despite being considered push only.

**Comment by apoelstra** [comment]
Witness stack elements aren't "interpreted as PUSHDATA ops". They are slices of data which are loaded onto the stack before the script interpretation begins.

There is no way to use OP_1 or any other opcodes here.

**Comment by junderw** [comment]
I verified that Bitcoin Core deserializes the witness stack as a vector<vector<unsigned char>> and that using OP_2 etc. will fail deserialization.

Disregard this issue.
