### ISSUE TITLE
Unresolved imports

### ISSUE THREAD

**Issue by mehranj73** [rust-bitcoin/rust-bitcoin#2314]
Why do I get this error even when I imported those:

```
10 | use bitcoin::{CompressedPublicKey, Network, NetworkKind};
   |               ^^^^^^^^^^^^^^^^^^^           ^^^^^^^^^^^ no `NetworkKind` in the root
   |               |
   |               no `CompressedPublicKey` in the root
```

**Comment by Kixunil** [comment]
You're probably using a different version. Judging from `NetworkKind` you're probably using the one from crates.io but reading the documentation from `master`.

**Comment by mehranj73** [comment]
Sorry for asking another question. Is there a way to change seed phrases to seed hex and do you check for checksum?

**Comment by Kixunil** [comment]
This library doesn't have BIP39 implementation because some maintainers consider it too bad. Check out the `bip39` crate which is maintained by one of us.
