### ISSUE TITLE
Hex stuff is a bit of a mess

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2323]
Issue to track all the hex discussion in one place and come up with a solution, please add links to any stuff that I've missed.

Converting to and from hex is common in bitcoin code. We used to have `ToHex` and `FromHex`, they were brain-dead easy to use but were inefficient. In attempting to improve on this we have gotten ourselves into a bit of a mess.  The current APIs are hard to use and hard to understand _when_ to use which of the traits/functions - for library devs and also for users.

## Parsing/Deserializing

- We have `hex::FromHex` and also `bitcoin::FromHexStr`
- We use `FromStr` coupled with `Display` and also `FromHex` coupled with `DisplayHex`, which to call
  may not be obvious for users.
- We are missing `consensus::encode::deserialize_hex()` (for types that implement `Decodable`)

## Printing/Serializing

- The `hex::DisplayHex` API is difficult to use, and difficult to implement. This is based on my subjective experience as well as complaints from others (see below).
- We have a hex module in `consensus::serde` which AFAICT is currently unused.
- We have `consensus::encode::serialize_hex()` for types that implement `Encodable`

## Missing pieces

- `consensus::deserialize_hex` (https://github.com/rust-bitcoin/rust-bitcoin/pull/2039)
- Re-implement `HexWriter` (https://github.com/rust-bitcoin/rust-bitcoin/issues/1586)
- Easy way to print transactions (https://github.com/rust-bitcoin/rust-bitcoin/issues/1706)

## Complaints

Multiple people have complained about our removal of the very simple `ToHex` / `FromHex` traits (I can't find the thread where this was discussed, and the suggested solution to re-introduce them).

## My two cents

I think we have made good progress, the new hex stuff is more correct and more efficient. A large part of the problem is, I believe, that we haven't finished the work. Its in such a mess now that I don't really know what direction to push - hence this issue. Please take this issue as an attempt to pull everything together, not as a whinge about the current stuff we have done.

## Related issues/PRs

- #1400
- #2308 
- #1706 
- #2218

**Comment by tcharding** [comment]
PR where we added `FromStrHex`: https://github.com/rust-bitcoin/rust-bitcoin/issues/1112

**Comment by tcharding** [comment]
PR to add logic from `FromHexStr` to the `hex-conservative` module: https://github.com/rust-bitcoin/hex-conservative/pull/58

**Comment by tcharding** [comment]
Slightly related: https://github.com/rust-bitcoin/rust-bitcoin/issues/2218

**Comment by tcharding** [comment]
(I added "Related issues/PRs" section and deleted previous multiple comments with the same links.)

**Comment by Kixunil** [comment]
> * We have `hex::FromHex` and also `bitcoin::FromHexStr`

Originally `FromHex` was intended for hex-encoded bytes, not integers. `FromHexStr` for integers. The main difference being that hex-encoded bytes never start with `0x` prefix so trying to write that code would be silly/buggy. However as I found out this accidentally changed during the transition to the hex crate and I disagree with the change. Or at least no prefix should be the default.

> * We use `FromStr` coupled with `Display` and also `FromHex` coupled with `DisplayHex`, which to call
>       may not be obvious for users.

Regarding former: Honestly, people should learn idiomatic Rust (or any language they work with) and not chase workarounds. That being said, I propose a hex encoding chapter int the cookbook.

Regarding latter: these should be only used on raw slices/arrays/vecs, not on our types. Ideally, people shouldn't call them at all (or rather, they're not `bitcoin` problem but `hex-conservative` problem, so if people are inventing their own hex protocols that's on them). This should be prominently documented in the `hex-conservative` crate.

I think a bunch of misunderstanding stems from people thinking `hex-conservative` is meant to be a replacement for `bitcoin_hashes::hex` which strictly it isn't.

> * We are missing `consensus::encode::deserialize_hex()`

Yes. I've hit this in the past too. I think we can share the code with `consensus::serde` but it'll need some refactoring.

> * The `hex::DisplayHex` API is difficult to use

How?

> * and difficult to implement

It shouldn't be implemented on anything else then what it already is implemented on - arrays and slices. Maybe it should be sealed. Needs doc I think.

> * We have a hex module in `consensus::serde` which AFAICT is currently unused.

It is used in the tests, [`async-electrum-client`](https://github.com/Kixunil/async-electrum-client/blob/master/src/lib.rs#L100), and it might be used in Firefish in the future (we use base64 for now).

> A large part of the problem is, I believe, that we haven't finished the work.

I think that a large part is that people got used to obviously, inherently inefficient API and refuse to make their code more efficient. :) If the API was good from beginning it'd be much less noise. But sure, let's help them out. Just let's not go backwards.

**Comment by apoelstra** [comment]
> I think a bunch of misunderstanding stems from people thinking `hex-conservative` is meant to be a replacement for `bitcoin_hashes::hex` which strictly it isn't.
> 

Then what are people supposed to replace `bitcoin_hashes::hex` with?

> > * The `hex::DisplayHex` API is difficult to use

Using it is not so bad. Implementing is really weird. Usually you want to just convert your type to an array or slice and then call into the existing implementations, but if you can't do that then you've gotta implement a bunch of boilerplate. Similar problem to serde.

>It shouldn't be implemented on anything else then what it already is implemented on - arrays and slices. Maybe it should be sealed. Needs doc I think.

Lol, if it's sealed then users have literally nowhere to go to implement hex encoding for their own crates. If this is the direction that `hex-conservative` is going then I will have to create my own `bitcoin-hex` and move rust-bitcoin to that.

**Comment by Kixunil** [comment]
> Then what are people supposed to replace `bitcoin_hashes::hex` with?

`Display`/`LowerHex`/`UpperHex`/`FromStr`

> but if you can't do that then you've gotta implement a bunch of boilerplate

When you can't do that?

> users have literally nowhere to go to implement hex encoding for their own crates.

```rust
fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    fmt::LowerHex::fmt(&self.inner_raw_bytes.as_hex(), f)
}
```

Where's the problem?

**Comment by apoelstra** [comment]
>Where's the problem?

When there is no `inner_raw_bytes`, as in (for example) `bitcoin::Transaction`.

**Comment by Kixunil** [comment]
Then the trait being unsealed won't help you anyway.

But it **is** a *different* missing feature: https://github.com/rust-bitcoin/rust-bitcoin/issues/1586

**Comment by tcharding** [comment]
#1586 is the last piece for this issue, I"m closing it now because 1586 is marked as milestone 0.32.0 so won't be forgotten.
