### ISSUE TITLE
const constructors for hashes

### ISSUE THREAD

**Issue by stevenroose** [rust-bitcoin/rust-bitcoin#2377]
The hashes currently have no const constructors (not even `from_byte_array` or `all_zeros`).

I found out because I was trying to make `OutPoint::new` and `OutPoint::null` const fns, but the latter is impossible, it seems.

**Comment by apoelstra** [comment]
`from_byte_array` and `all_zeros` could be made const and we could do a point release (assuming there are no other breaking changes in the hashes pipeline yet, which I believe is true).

Actually hashing in constant time is far from trivial, though I haven't tried in a little while.

**Comment by Kixunil** [comment]
> Actually hashing in constant time is far from trivial, though I haven't tried in a little while.

[We already have that](https://docs.rs/bitcoin_hashes/latest/bitcoin_hashes/sha256/struct.Hash.html#method.const_hash) :)

**Comment by apoelstra** [comment]
Oh, lol :). So @stevenroose there *is* a const constructor.

But agreed that `all_zeros` and `from_byte_array` should also be const.

**Comment by Kixunil** [comment]
Definitely!

**Comment by tcharding** [comment]
Seems that Rust does not allow functions within traits to be marked as `const`.

ref: https://users.rust-lang.org/t/whats-the-reason-that-fn-in-a-trait-cannot-marked-as-a-const/68636

**Comment by apoelstra** [comment]
Ah, yeah, that is probably why these aren't const already. We should move those methods out of the trait into inherents.

**Comment by Kixunil** [comment]
> We should move those methods out of the trait into inherents.

Yes!

**Comment by 15IITian** [comment]
![image](https://github.com/rust-bitcoin/rust-bitcoin/assets/133089376/6cac344b-92b0-4043-9fdd-e2bfcb973033)

https://github.com/rust-bitcoin/rust-bitcoin/blob/9df59639cec214bd9363d426335923611a304119/hashes/src/sha256t.rs#L23

In  `all_zeros` and `from_byte_array` methods in `Hash<T>` impl -> what should be the value of `PhantomData` part in this struct?

**Comment by apoelstra** [comment]
`PhantomData` has only one value, called `PhantomData`. Use that.

**Comment by 15IITian** [comment]
Did anyone also getting same errors while making commits ?


![image](https://github.com/rust-bitcoin/rust-bitcoin/assets/133089376/e09952af-9211-4ae7-a1f4-636aebb4ceaf)

![image](https://github.com/rust-bitcoin/rust-bitcoin/assets/133089376/6a2cbe56-506d-4d84-9fce-1fa2488f7f85)
