### ISSUE TITLE
OP_IF usage for multisig

### ISSUE THREAD

**Issue by 3ierratango** [rust-bitcoin/rust-bitcoin#2379]
Hi, I'm trying to create a multisig taproot wallet, the goal here is either of 
1. Required_Signer +1
2. Majority signs

In this example, Bob is the required signer,
The first branch checks if Bob signature is present and one more signature
The second branch checks if 2/3 signatures are present.

The taproot script used is 

```
let wallet_script = Builder::new()
                .push_opcode(all::OP_TRUE)
		.push_opcode(all::OP_IF)
			.push_x_only_key(&bob.public_key().into())
			.push_opcode(all::OP_CHECKSIGVERIFY) // Bob key is necessary
			.push_x_only_key(&alice.public_key().into())
			.push_opcode(all::OP_CHECKSIG)
			.push_x_only_key(&charlie.public_key().into())
			.push_opcode(all::OP_CHECKSIGADD)
			.push_int(1) // since the number we are comparing is the valid sigs from alice and charlie, it should be 1
			.push_opcode(all::OP_GREATERTHANOREQUAL) // atleast one sig
		.push_opcode(all::OP_ELSE)
			.push_x_only_key(&bob.public_key().into())
			.push_opcode(all::OP_CHECKSIG)
			.push_x_only_key(&alice.public_key().into())
			.push_opcode(all::OP_CHECKSIG)
			.push_x_only_key(&charlie.public_key().into())
			.push_opcode(all::OP_CHECKSIGADD)
			.push_int(2) // since the number we are comparing is the majority, it should be 2
			.push_opcode(all::OP_GREATERTHANOREQUAL) // atleast two sigs
		.push_opcode(all::OP_ENDIF)
		.into_script();
```

The signature verification fails, the code was working prior to this so it could be related to the script construction. If someone can take a look and point out the mistake here that would be great. Thanks!

**Comment by apoelstra** [comment]
Have you considered using Miniscript for this policy? There is a crate [rust-miniscript](https://github.com/rust-bitcoin/rust-miniscript/) that can do these sorts of script constructions for you.

But to answer your specific question, it looks like you have two `CHECKSIG`s and one `CHECKSIGADD` in your second branch, and I think teh second `CHECKSIG` should be a CSA.

**Comment by apoelstra** [comment]
I'm not sure what to make of that. The code you posted does not put any non-minimal data into IF, NOTIF, or the end of the script execution.

**Comment by apoelstra** [comment]
If you're providing a different script when signing than actually goes in the transaction, then you'll get an invalid signature.

But I strongly encourage you to look at rust-miniscript which will just do this all for you.

**Comment by Kixunil** [comment]
@3ierratango I think what you're trying to achieve would be better done using taproot where you simply specify the branches individually and not worry about `OP_IF`. You'd also save a bunch of fees.

**Comment by Kixunil** [comment]
I think branch is just better at everything. The only exception I can imagine is if you had something smaller than 32 B. Like `OP_CSV`. But since all keys are at least 32B long and a transaction without a key can be spent by anyone such thing would be useless.

**Comment by 3ierratango** [comment]
Closing the issue since I got it working with branches
