### ISSUE TITLE
units: Make `amount` module not require "alloc" feature

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2389]
The `amount` module has loads of string parsing and heavily relies on types from `allloc`, however there may be no-std users that would still like to have an `Amount` type. It should be feasible to make the feature gating more fine grained so we can provide an `Amount` type in "no-std" builds.

**Comment by Kixunil** [comment]
I thought this is done already? Anyway, can look into it after #2370 merges.

**Comment by tcharding** [comment]
The whole `amount` module is feature gated on "alloc"
```rust
// TODO: Make amount module less dependent on an allocator.
#[cfg(feature = "alloc")]
pub mod amount;
```
