### ISSUE TITLE
Implement missing p2p message types

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2400]
Our `p2p::message::NetworkMessage` enum has a few fields missing for the following message types

- checkorder
- submitorder,
- reply

ref: https://en.bitcoin.it/wiki/Protocol_documentation#Block_Headers

**Comment by 0xkrieger** [comment]
@tcharding I would like to try to solve this, but the provided reference link is not working. Can you point me to some other resource for this?

**Comment by tcharding** [comment]
I just clicked on it and it worked for me?

**Comment by 0xkrieger** [comment]
> I just clicked on it and it worked for me?

DNS error, used VPN working now :)

**Comment by shinghim** [comment]
just took a look at the link and saw that message types for IP transactions [have been removed from Bitcoin core as of v0.8.0](https://en.bitcoin.it/wiki/IP_transaction). Do we still need these to be added?

**Comment by apoelstra** [comment]
Lol, yeah, I don't know why I gave you a thumbs up there.

We definitely do not need to support pay-to-IP message types.

**Comment by tcharding** [comment]
What idiot even raised this issue?
