### ISSUE TITLE
Tracking issue - MSRV post 1.56/post bookworm

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2411]
We'd like these features, which are also needed for stabilization of some crates:

- [x] weak dependencies
- [ ] GAT

Other nice to have features:

- [x] panic in `const` context #3214

**Comment by tcharding** [comment]
If we go past 1.57 we can also do:
- https://github.com/rust-bitcoin/rust-bitcoin/issues/2427
- https://github.com/rust-bitcoin/rust-bitcoin/issues/2425
- https://github.com/rust-bitcoin/rust-bitcoin/issues/2426

**Comment by Kixunil** [comment]
I already mentioned it. :)

**Comment by tcharding** [comment]
woops, so you did.

**Comment by tcharding** [comment]
Make `all_zeros` an `from_byte_array` const in tagged hashes.

**Comment by Kixunil** [comment]
I've just noticed two interesting things:

* Weak dependencies and namespaced features were stabilized in 1.60 - which is before 1.63 (I have previously though it was *after* 1.63 - the version in Debian Bookworm) 1.60 was released 7th April 2022. *Therefore we can already use weak dependencies if we bump MSRV* We had this discussion a few days ago.
* Interestingly, Debian ships `cargo` 1.65 and `rustc` .63, so if we need something newer from Cargo we can have it before the next Debian release.

Given significant advantages of using weak dependencies and namespaced features I propose to bump MSRV now. Our next release can benefit from this already. What do you think @apoelstra ?

**Comment by apoelstra** [comment]
ACK bumping to 1.63 from me. cc @TheBlueMatt any objections?

Weak dependencies are a really huge thing.

**Comment by storopoli** [comment]
For the context, BDK and LDK already have bumped their MSRV to 1.63

https://github.com/bitcoindevkit/bdk/blob/d99b3ef4b449a5c7b8facf04db3cb9be829a0ac1/.github/workflows/cont_integration.yml#L15

https://github.com/lightningdevkit/rust-lightning/blob/dee3ba7d6a4004dc9606f6c2488feceb666553b5/.github/workflows/build.yml#L21

**Comment by apoelstra** [comment]
I'm going to close this issues since we're at 1.63 now.

We can open a new one to chat about post-1.63 stuff we want.
