### ISSUE TITLE
Now that MSRV is 1.56 we ought to use the `rust-version` field in Cargo.toml

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#2415]
See https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field

This will cause cargo to emit an error if people try to use a compiler before our MSRV, rather than having users just run into whatever actual compilation error they'd hit.

Although it's only been supported since 1.56 so arguably it's a no-op right now :)

Possibly in edition 2024 or later cargo will use this information to try to find MSRV-compatible dependencies.

**Comment by tcharding** [comment]
We have that
```bash
gg rust-version
bitcoin/Cargo.toml:13: rust-version = "1.56.1"
fuzz/Cargo.toml:4:  rust-version = "1.56.1"
fuzz/generate-files.sh:15: rust-version = "1.56.1"
hashes/Cargo.toml:13: rust-version = "1.56.1"
internals/Cargo.toml:13: rust-version = "1.56.1"
io/Cargo.toml:13: rust-version = "1.56.1"
units/Cargo.toml:12: rust-version = "1.56.1"
```

**Comment by apoelstra** [comment]
Huh. I don't know how I missed this.

**Comment by tcharding** [comment]
The human brain is an ever fallible thing - don't I know it :)

**Comment by Kixunil** [comment]
I think it's because it's somewhat recent and IIRC it was added in some boring PR.
