### ISSUE TITLE
Replace with `panic!` post MSRV 1.57

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2427]
Remove the following attributes and use `panic!` once we bump MSRV greater than 1.57

- `#[allow(unconditional_panic)]`
- `#[allow(clippy::let_unit_value)]`
- `#[allow(clippy::out_of_bounds_indexing)]`

There are two instances:

- https://github.com/rust-bitcoin/rust-bitcoin/blob/8efaf4a3000e862762a765a35eb0add7c4efdb5a/bitcoin/src/blockdata/weight.rs#L65
- https://github.com/rust-bitcoin/rust-bitcoin/blob/8efaf4a3000e862762a765a35eb0add7c4efdb5a/units/src/amount.rs#L722

**Comment by yancyribbens** [comment]
I think this is the same as https://github.com/rust-bitcoin/rust-bitcoin/issues/2426.  if we call `btc.checked_mul(100_000_000).unwrap()` then it will panic.

**Comment by yancyribbens** [comment]
or not panic.

**Comment by Kixunil** [comment]
@yancyribbens yes, it is. It's also in the tracking issue.

**Comment by tcharding** [comment]
I raised #2426 separately because I don't know if `Option::unwrap` in const stabalizes first or `panic!` in const.

**Comment by Kixunil** [comment]
@tcharding What the hell, I was sure it was stabilized in the same version but checked anyway and it's not stable at all. :man_facepalming: But that tempts me to just close the other issue as unactionable.

**Comment by yancyribbens** [comment]
I can only find this issue about const panic rn https://github.com/rust-lang/rust/issues/66753

**Comment by Kixunil** [comment]
@yancyribbens I found the right one by clicking on "unstable" link at `Option::unwrap` doc.

**Comment by tcharding** [comment]
Fine with me to close the issue but since I didn't add the TODOs in code I'll leave it for someone else to close.

**Comment by Kixunil** [comment]
Ideally GH would have something like "archive issue" that jut puts it at the end of the queue because I'd still like to do it in 5 years when it's available. I'll try to make a new label for it and if it is still noisy, we will close it.

**Comment by yancyribbens** [comment]
\o/
