### ISSUE TITLE
io: Blanket impl of `Read` is not that ergonamic

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2432]
Example workflow

1. User creates a type, is building in a no-std environment, implements `bitcoin_io::Read` on it.
2. User adds a "std" feature and wants to pass their new type as a reader to some other code, implements `std::io::Read`.

At step (2) their code breaks because we have a blanket impl of `Read` for all `std::io::Read`ers.

The user can work around this but its a bit ugly. Duplicate the `Read` implementation, feature gate one on "std" and make it implement`std::io::Read`, feature gate the other on "not(std)" and make it implement `bitcoin_io::Read`.

Do we want to make this situation better before release?

**Comment by tcharding** [comment]
@apoelstra have I described your concern correctly?

**Comment by tcharding** [comment]
I added P-high, this issue has to be resolved before we can release the `io` crate. We should get that released so it doesn't hold up the `rust-bitcoin` release - I know we have two months but these things have a habit of taking ages.

**Comment by Kixunil** [comment]
I wonder if *library* crates need to bother *implementing* these traits. They are already available for basic types like `&[u8]` and a library that wants to be `no_std` shouldn't do IO. And the binary crates already know whether they are `std` or not, so they don't have to feature gate and just implement the right thing.

**Comment by apoelstra** [comment]
> I wonder if _library_ crates need to bother _implementing_ these traits. They are already available for basic types like `&[u8]` and a library that wants to be `no_std` shouldn't do IO.

rust-bitcoin wants to be `no_std` and yet we want IO enough to have 3 different crates to attempt to provide this.

> And the binary crates already know whether they are `std` or not, so they don't have to feature gate and just implement the right thing.

Not if the binary crates have optional features. My local wallet has such a thing where all the jsonrpc support is feature-gated for example.

@tcharding your example is one way compilation can break, though in this case the user can simply make their `std` feature imply the `std` feature of `bitcoin_io`, and then they'll get the blanket impl and not need their own.

Another way is that the user depends on some other crate, which pulls in `bitcoin_io` with `std` on, and now suddenly their `Read` impl is broken even though they themselves did not turn the feature on.

**Comment by Kixunil** [comment]
> rust-bitcoin wants to be `no_std` and yet we want IO enough to have 3 different crates to attempt to provide this.

I mean actually directly do actual IO, not use some IO traits that might do it themselves.

> Not if the binary crates have optional features.

This is super rare for stuff where you'd want `no_std` - embedded. "Optionally enable std on Trezor" doesn't make sense. Maybe for tests you could argue that but then you'd just use types from `std` and not need to implement anything.

> which pulls in `bitcoin_io` with `std` on, and now suddenly their `Read` impl is broken even though they themselves did not turn the feature on.

This can only happen if there's blanket impl on `&mut` in our library, so we could just remove it (but it's :vomiting_face:).

**Comment by tcharding** [comment]
I have no idea how to solve this and no idea how to move forward. This issue is holding up release of the `io` crate which is holding up hex work that I'd like to get cracking on so we can get some of it into next release. Are you able to allocate some clock cycles to this problem please @apoelstra? My personal view is  we should release it like this and iterate. We are using it in `hashes` already so we know its not a problem there.

**Comment by Kixunil** [comment]
OK, let's drop it, make impls for `&[u8]` & co, `&mut T` unconditional and add impl to `std::io::BufReader`, `std::io::BufWriter`, `std::io::Std*` and maybe some others I'm missing. I think let's not bother with unbuffered types since they aren't usable anyway.

**Comment by tcharding** [comment]
We don't have a `BufWriter`. I didn't do all of `std::io` types, just those required to get `rust-bitcoin` building.

**Comment by Kixunil** [comment]
`std` does have it.
