### ISSUE TITLE
Amount arithmetic operations are slow

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#2434]
Changing the Add trait results in a 2x performance increase in the BnB coin-selection algo.  In something like coin-selection, I sum all the utxo values, and if that doesn't panic, then no subset of utxo sums will panic, therefore the checks only slow performance.

the change:
```rust
impl ops::Add for Amount {
    type Output = Amount;

    fn add(self, rhs: Amount) -> Self::Output {
        Self(self.0 + rhs.0)
    }
}
```

with the addition check (slow)
```
Benchmarking bnb 1000: Collecting 100 samples in estimated 6.5024 s (5050 iterations)
Benchmarking bnb 1000: Analyzing
bnb 1000                time:   [1.2713 ms 1.2720 ms 1.2728 ms]
                        change: [+67.699% +67.929% +68.157%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild
```

without addition check (fast)
```
Benchmarking bnb 1000: Collecting 100 samples in estimated 7.7082 s (10k iterations)
Benchmarking bnb 1000: Analyzing
bnb 1000                time:   [760.36 µs 760.49 µs 760.64 µs]
                        change: [-40.528% -40.491% -40.450%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high severe
```

There is similar perf gains for subtract and multiply as well probably.  Is there a way with `Amount` and `SignedAmount` that the panic checks can be opted out of?

[latest coin-selection pr](https://github.com/p2pderivatives/rust-bitcoin-coin-selection/pull/30)

**Comment by Kixunil** [comment]
I think we should just add `_unchecked` methods. Note that in `std` those are `unsafe` and UB if they actualy do overflow. I'm **not** proposing to add `unsafe` but it kinda sucks it's not consistent and if someone needs them it'll be annoying (but unlikely).

**Comment by tcharding** [comment]
One can sum two amounts using `a.to_sat() + b.to_sat()` (and we could make `Amount::to_sat`  a `const` function as well).

**Comment by yancyribbens** [comment]
`to_sat()` could be used to convert to u64 and strip the type
information before entering the algotithem, and it's something I
considered.  I feel like adding `_unchecked` is a bit nicer
since the type can be retained throught and there's less clutter
without the Amount to u64 cast step.

**Comment by Kixunil** [comment]
Keeping type safety is definitely better. We could also just drop the unconditional overflow check but I think we'll want monadic handling instead.

**Comment by sanket1729** [comment]
I am surprised to learn that this addition bounds check is alone making almost **2x** difference in any piece of code. I presumed that branch predictors should amortize away the cost. 

I might try reproducing these benchmarks over the weekend for my personal curiosity.

**Comment by Kixunil** [comment]
FTR the code in question tries summing subsets of UTXO amounts. Speedup is achieved by first summing them all and checking for overflow then ignoring checking.

**Comment by dpc** [comment]
> I am surprised to learn that this addition bounds check is alone making almost **2x** difference in any piece of code. I presumed that branch predictors should amortize away the cost.

Well the ratio of of "check" vs "do" here is 1:1, because `add` is a very lightweight operation that a modern CPU can easily execute in parallel if there are other data-independent operations. Branch predictor is definitely hitting 100% here, otherwise it would be like 10x slowdown maybe more, I think.

**Comment by Kixunil** [comment]
> Branch predictor is definitely hitting 100% here, otherwise it would be like 10x slowdown maybe more, I think.

Oh, yes, good point. Miss flushes the whole pipeline and whatnot...

**Comment by yancyribbens** [comment]
> FTR the code in question tries summing subsets of UTXO amounts. Speedup is achieved by first summing them all and checking for overflow then ignoring checking.

I think there's even additional optimizations for coin-selection that can be done by doing the same thing for each waste calculation.  Although it's not as straightforward since waste can have negative values.  Something like summing all negatives, check for overflow, sum all positives check for overflow then during the search use unchecked.

**Comment by yancyribbens** [comment]
It's also interesting to note that Criterion, the crate I used to benchmark requires rustc `1.65+`, and using `1.65`, the times are much worse than the current stable `1.75`.  So whatever was done between `1.65` and `1.75` seems to be much faster :)
