### ISSUE TITLE
Don't require "m" when creating derivation path strings

### ISSUE THREAD

**Issue by josibake** [rust-bitcoin/rust-bitcoin#2449]
Small issue, but felt worth mentioning since it I observed it causing some some confusion with students reading BIP0032 and then trying to use `rust-bitcoin`.

In https://github.com/rust-bitcoin/rust-bitcoin/blob/a3c4194c3fc76778bc4af49f38b3a64d00b5fc49/bitcoin/src/bip32.rs#L335, derivation path strings are required to start with the letter "m." However, in BIP0032, `m` is used as a variable to represent the root, the master extended key to start derivations from. It's also clear from the identities section (see https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#the-key-tree) that `m` represents something that can be parsed and is not a constant.

What I would expect is for `DerivationPath` to accept something like `84h/0h/0h` as a valid derivation path for a root `m`, which would have been created separately. I would also expect to be able to parse a strings of the form `xpriv<base58>/84h/0h/0h`/`xpub<base58>/84h/0h/0h`, where `m` is provided directly.

I'd be happy to implement this if there is conceptual agreement. If there is not agreement, I'd be interested to know why and suggest adding documentation for the reason and a note that this differs from BIP0032.

**Comment by Kixunil** [comment]
> I was curious how this hasn't caused anyone issues

It actually did cause me issues but I thought parsing is correct and all paths must start with `m`. :man_facepalming: 

>  this function is basically only useful for test-vector style things

I don't think so. Electrum allows people entering the path directly which seems sensible to me. It was helpful in Firefish too.
