### ISSUE TITLE
Consider renaming `sum()` to `unchecked_sum()` for Amount and SignedAmount

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#2459]
The sum impl [here](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/units/src/amount.rs#L960) is an unchecked sum.  The other impls for Amount all default to checked and so the behavior of `sum()` not being checked may be a surprise.

Related to: https://github.com/rust-bitcoin/rust-bitcoin/issues/2434

**Comment by Kixunil** [comment]
Can't do that, it's a trait from `std`.

**Comment by dpc** [comment]
Shouldn't it then do checked add instead?

**Comment by yancyribbens** [comment]
Could do something like:

```
pub trait UncheckedSum<R>: private::SumSeal<R> {
    /// Calculate the sum over the iterator using checked arithmetic. If an over or underflow would
    /// happen it returns `None`.
    fn unchecked_sum(self) -> R;
}

impl<T> UncheckedSum<Amount> for T
where
    T: Iterator<Item = Amount>,
{
    fn unchecked_sum(mut self) -> Amount {
        let first = self.next().unwrap_or_default();

        self.fold(first, |acc, item| acc.unchecked_add(item))
    }
}
```

**Comment by yancyribbens** [comment]
it's a little bit slower this way than using `std` so not a good idea after all.

**Comment by yancyribbens** [comment]
Actually this is kinda interesting.  I've been using rust-bitcoin commit `a3c419` from feb 2nd, and if I update to use the latest version HEAD from today, the benchmarks are about 10% slower.  When I said use the `uchecked_add` trait was slower, that doesn't appear true actually, some other commit between feb 2 and now seems to have slowed the benchmarks a bit.  Sorry for the somewhat random tangent.

**Comment by Kixunil** [comment]
> it is a bit odd that `sum` does something else than `add`.

Yes, it is. And I don't like it either. But seems least bad to me since that's what `std` does.

@yancyribbens the main motivation for the trait is the `Iterator::sum` method.

**Comment by yancyribbens** [comment]
> Shouldn't it then do checked add instead?

There is already `checked_sum()`

> I guess it would be better to panic there than to overflow.

True, although it comes as a bit of surprise which may lead people to be checking for overflows not knowing there's additional checking going on and a possible panic instead of overflow.

> But seems least bad to me since that's what std does.

std will overflow instead of panic, right (in release mode)?  What else does std do?

**Comment by Kixunil** [comment]
> What else does std do?

Nothing.

**Comment by yancyribbens** [comment]
> Nothing.

Right.  It's confusing that rust-bitcoin breaks from how `std` works
imo, for example add, sub etc traits in Amount.  I can see the argument
for panic being better than overflow, but I'm guessing `std` does no
checks in release mode for performance?

**Comment by Kixunil** [comment]
The reason we do it differently is that an overflow in this library may cause catastrophic loss of funds (e.g. computing wrong value for change and burning coins into fees). That kind of risk is specific to our library and not generally in all software. Though it makes me rethink how `Sum` should really work.

But we've decide we want monadic handling, so things will change again.

**Comment by yancyribbens** [comment]
> But we've decide we want monadic handling, so things will change again.

What is monadic handling?  Where did that conversation take place?  Will
that change the unchecked semantics I have worked on in other PRs?

**Comment by Kixunil** [comment]
Try google. The conversation was in the issue about guaranteeing Amount < 21M BTC.

**Comment by yancyribbens** [comment]
Prefer duckduckgo
