### ISSUE TITLE
SHA384

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-bitcoin#2483]
I have a not-particularly-bitcoin-specific usecase for SHA256/384/512 (DNSSEC validation), and was gonna just use bitcoin_hashes, but turns out it doesn't do 384. Given its ~0 additional code compared to 512/512-256, would folks be okay with adding it?

**Comment by Kixunil** [comment]
That's a weird number. Anyway, I think it'd be fine. @tcharding had some objections against adding too many features though. So I guess it should be considered low-priority.

**Comment by apoelstra** [comment]
Fine by me to add it. It's not really any additional API surface since all hashes are basically the same, and hashing code is write-only and easy to test.

**Comment by tcharding** [comment]
Go for it.
