### ISSUE TITLE
Txid short display is weird and broken

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#2494]
Consider this unit test

```diffdiff --git a/bitcoin/src/blockdata/transaction.rs b/bitcoin/src/blockdata/transaction.rs
index 985d24541..1c519387a 100644
--- a/bitcoin/src/blockdata/transaction.rs
+++ b/bitcoin/src/blockdata/transaction.rs
@@ -1765,6 +1765,10 @@ mod tests {
             format!("{:x}", realtx.compute_txid()),
             "a6eab3c14ab5272a58a5ba91505ba1a4b6d7a3a9fcbd187b6cd99a7b6d548cb7".to_string()
         );
+        assert_eq!(
+            format!("{:10}", realtx.compute_txid()),
+            "a6eab3c14ab5272a58a5ba91505ba1a4b6d7a3a9fcbd187b6cd99a7b6d548cb7".to_string()
+        );
         assert_eq!(
             format!("{:x}", realtx.compute_wtxid()),
             "a6eab3c14ab5272a58a5ba91505ba1a4b6d7a3a9fcbd187b6cd99a7b6d548cb7".to_string()
```

This should not pass -- the `:10` display formatter is supposed to truncate it. (Maybe this is waiting on hex-conservative 0.2? Then please we need to release 0.2.) Or maybe it's the `:.10` formatter, I never remember which. But neither works right now.

**Comment by tcharding** [comment]
I believe this is fixed in commit: `8569ee8e Remove arbitrary padding limit` (on `hex-conservative`).

**Comment by apoelstra** [comment]
Ok, perfect. I'll leave it open until the release.

@tcharding can you add my unit test (fixed so that it's asserting the short string) to #2473 ?

**Comment by tcharding** [comment]
Sure thing, no sweat.

**Comment by tcharding** [comment]
Finally, a win for today, my workspace on 2473 branch was dirty already from yesterday
```dif
+
+    #[test]
+    fn txid_truncates() {
+        let txid = Txid::from_str("a6eab3c14ab5272a58a5ba91505ba1a4b6d7a3a9fcbd187b6cd99a7b6d548cb7").unwrap();
+        let want = "a6eab3c14a";
+        let got = format!("{:10}", txid);
+        assert_eq!(got, want);
+    }
```
I pushed it up.

**Comment by tcharding** [comment]
Seems I got prematurely excited this morning, I did indeed write that test yesterday but it is currently failing :)

**Comment by tcharding** [comment]
Fixed in: https://github.com/rust-bitcoin/hex-conservative/pull/81

**Comment by apoelstra** [comment]
I believe you are correct -- I checked with `String` and it matches your expectation.
