### ISSUE TITLE
We may have hash printing backwards wrong for some of the hashes

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2495]
During #1659 we might have broken backwards printing, see comments at the end of that PR.

**Comment by apoelstra** [comment]
Note that in https://github.com/rust-bitcoin/rust-bitcoin/pull/1565 we deliberately changed the sighashes to display forward, which differs from rust-bitcoin 0.29.x but was not changed in 1659.

**Comment by apoelstra** [comment]
Ok, those were the only changes. I think #1659 was a red herring.
