### ISSUE TITLE
We are pretty debug printing txids with prefix

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2505]
Recent discussion has uncovered, if I remember correctly, that hashes should not be displayed or parsed with a prefix - this implies `Txid` should not be however we currently debug print with the prefix.

For example, pretty debug printing a transaction includes:

```rust
            previous_output: OutPoint {
                txid: 0x2e307af4953fe5dc2709e93cbb00367eace5cb5aee9e6e3a504c44efa6c0cfc8,
                vout: 1,
            },
```

**Comment by Kixunil** [comment]
Whaaaat?! When did such breaking change happen?

**Comment by apoelstra** [comment]
I suspect it appears only in `Debug` output, which would explain why we didn't notice/catch it. But lol yeah, big oops.

**Comment by Kixunil** [comment]
Oh, I realized what it is (didn't look at the code though). We're calling `LowerHex::fmt` from `Debug::fmt` directly passing formatter where alternate means different things. So it seems "alternate" formatting is defined as "pretty print" in `Debug`. And I suspect this also applies to `Display`.

**Comment by apoelstra** [comment]
I think it's only for `Debug`, where the canonical way to implement `Debug` is to just dump the struct fields in a psuedo-json format.

For `Display` probably it has no canonical meaning, because there isn't a "canonical way" to `Display` things, the trait is basically "serialize as a string somehow".

**Comment by Kixunil** [comment]
Yeah, now that I think about it there's no recursive formatting in case if `Display` so that one is fine.

**Comment by 448-OG** [comment]
I would like to try to solve this issue? Currently I have identified this line of code as the one that appends the `0x` while pretty printing with `{:#x}` or with `dbg!()`
https://github.com/rust-bitcoin/hex-conservative/blob/bd9c2c7b44bc89e91ec6bb4f7164672e27a43f64/src/display.rs#L217
and line
https://github.com/rust-bitcoin/hex-conservative/blob/bd9c2c7b44bc89e91ec6bb4f7164672e27a43f64/src/display.rs#L300

And changing those lines by removing the `0x` prefix specified does ensure pretty printing does not prefix with `0x` when using the hex-conservative crate, but that is on version 0.1.0?

In version 0.2.0, this works too but it breaks code for example in the bitcoin-hashes line
https://github.com/rust-bitcoin/rust-bitcoin/blob/36aa627d8312e87204a7628a9c954ca55750c55c/hashes/src/sha256.rs#L178

I am assuming the goal would be to migrate to version 0.2.0, so do I make changes to version 0.1.0 which is the current hex-conservative used in current bitcoin release on crates.io or do I introduce breaking changes but use version 0.2.0 instead?

**Comment by apoelstra** [comment]
You should wait for #2473 to merge which updates us to hex-conservative 0.2.

**Comment by tcharding** [comment]
Remove the `P-high` because I believe that was added based on my incorrect initial issue descrition, this is only in debug output so is not critical.
