### ISSUE TITLE
Fix `Address` error mess

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2507]
This code is super common:

```rust
let address = s.parse::<Address<_>>()?
    .require_network(network)?;
```

Without having an error that would cover both this will be super annoying. Expect same shitstorm as with `Network` being `non_exhaustive` but now it will include myself. :)

_Originally posted by @Kixunil in https://github.com/rust-bitcoin/rust-bitcoin/pull/2502#pullrequestreview-1900209960_

**Comment by Kixunil** [comment]
Note: I want this to block the release. This really needs to be fixed.

**Comment by Harshit933** [comment]
Can this be solve with something like this :

```rust
pub enum Error {
    /// A network error.
    NetworkError(NetworkValidationError),
    /// A parsing error.
    ParseError(ParseError)
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        use Error::*;

        match *self {
            NetworkError(ref e) => write_err!(f, "network error"; e),
            ParseError(ref e) => write_err!(f, "parsing error"; e),
        }
    }
}

#[cfg(feature = "std")]
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        use Error::*;

        match *self {
            NetworkError(ref e) => Some(e),
            ParseError(ref e) => Some(e),
        }
    }
}

impl From<NetworkValidationError> for Error {
    fn from(e : NetworkValidationError) -> Self { Self::NetworkError(e) }
}

impl From<ParseError> for Error {
    fn from(e: ParseError) -> Self { Self::ParseError(e) }
}
```
Just a quick question : Why should not we give it to the implementors who are building applications on top of `rust-bitcoin` to deal with these stuff?

**Comment by apoelstra** [comment]
I think we should conceptually treat `require_network` as part of parsing and have it return a parse error. We can internally document that this is an exception to our usual "don't return error types unless all variants are returnable" policy.

We also ought to have a `parse_with_network` intrinsic method that wraps this pattern.

**Comment by Kixunil** [comment]
> I think we should conceptually treat `require_network` as part of parsing and have it return a parse error. We can internally document that this is an exception to our usual "don't return error types unless all variants are returnable" policy.

Yes, that's what we had before it changed under my ass without ever addressing my objection to such things.

**Comment by tcharding** [comment]
I can't remember when it got changed, I definitely had forgotten about this yesterday while reviewing #2502.

**Comment by Kixunil** [comment]
Whaaaat?!?!?! It as in August?! I remember objecting to it what feels like two months ago! I'm completely confused now. I remember that Tobin had trouble understanding why it's a problem.

So no problem it was in August especially since I likely misremember some details (though I'm pretty sure I do remember something right). If I wasn't super tired I would try to dig it out but it doesn't matter anyway. Let's just fix it.

Maybe not really related but I'm thinking maybe we should have a rule to resolve all review comments before merging. Originally I didn't understand the purpose of the rule but lately I noticed sometimes people forget. (Though it then destroys ACK with potential improvements use case...)

**Comment by tcharding** [comment]
FTR I attempt to resolve all review comments, any time I don't its because I forgot them.

> I remember objecting to it what feels like two months ago!

We definitely had this conversation recently, I believe I tried to split this error myself and close the PR IIRC. I guess I should have added a code to the function.

**Comment by apoelstra** [comment]
I suspect we did it inadvertently in August, and the discussions since then have been without realizing that the damage was already done.

In any case -- agreed we should resolve every conversation before merging, but it can sometimes be a pain to make people explicitly click "Resolve" on all their conversations. But conversely it seems wrong for the PR author to click "resolve" without letting the commenter decide whether the resolution is actually sufficient. So process-wise I'm not sure what the best solution is.

**Comment by tcharding** [comment]
On the topic of "resolve", if one writes a message in a thread then clicks resolve does the notification still show up in the reviewers notifications? And when clicking the notification is the comment shown or is the resolved thread hidden? This is something I've never worked out and is one reason I don't click resolve that much unless the last comment is from the original reviewer.

**Comment by tcharding** [comment]
Oh I remember the conversation we had now @Kixunil , you posted that example code then too and I did not see how that matters if a user is using `anyhow`. IIRC that is where the conversation ended (in my mind anyway).

**Comment by apoelstra** [comment]
>On the topic of "resolve", if one writes a message in a thread then clicks resolve does the notification still show up in the reviewers notifications?

Sorta. The thread will show up in notifications I believe...

>And when clicking the notification is the comment shown or is the resolved thread hidden?

...but the message will still be hidden.

>This is something I've never worked out and is one reason I don't click resolve that much unless the last comment is from the original reviewer.

Yeah, this is why it's something of a social convention that only the person who opns a conversation should click the "Resolve" button. But if they're not around or forget to, it can hold things up.

**Comment by tcharding** [comment]
> Yeah, this is why it's something of a social convention that only the person who opns a conversation should click the "Resolve" button. But if they're not around or forget to, it can hold things up.

ooooo, I did not know that one TIL.

**Comment by tcharding** [comment]
I have never gone over other peoples PRs and close threads (resolve) that I started.

**Comment by apoelstra** [comment]
Unfortunately we can't expect people to close their threads, since maybe they miss them, or forget, or something, and Github gives no way to warn you that you have still-open threads. All we can expect is that other people *don't* close the threads.

It's really a crappy system :/.

**Comment by tcharding** [comment]
Ok, I will not close any threads from no on that I did not start. And I will continue to not close threads I did start :)

**Comment by tcharding** [comment]
If #2508 merges you could just add a `NetworkValidation` variant to `ParseError` with some sort of docs explaining why its there. I'm still not getting the reasoning so I can't do it (because I can't write the comment).

**Comment by Kixunil** [comment]
> I suspect we did it inadvertently in August, and the discussions since then have been without realizing that the damage was already done.

Yes, I think so.

> it can sometimes be a pain to make people explicitly click "Resolve" on all their conversations. But conversely it seems wrong for the PR author to click "resolve" without letting the commenter decide whether the resolution is actually sufficient.

Yeah, I was thinking about it too. I don't think this has some magical solution, maybe we can just try it and see what happens.

> if one writes a message in a thread then clicks resolve does the notification still show up in the reviewers notifications

Yes

> And when clicking the notification is the comment shown or is the resolved thread hidden?

It is shown and you see it's marked as resolved because the button says "Unresolve conversation"

> this is why it's something of a social convention that only the person who opns a conversation should click the "Resolve

I believe it's perfectly OK for PR author to click Resolve if the thing is obviously fixed - e.g. typo or simply committing the changes suggested by reviewer.

> Github gives no way to warn you that you have still-open threads

If we require it then it says there are unresolved conversations.

> if #2508 merges you could just add a `NetworkValidation` variant to `ParseError` with some sort of docs explaining why its there.

Yeah I think so.

> I'm still not getting the reasoning so I can't do it (because I can't write the comment).

The reasoning is not everyone wants to use `anyhow` (e.g. because they want to exhaustively handle errors) and the example I wrote is super common (actually, I'm don't have any code that does *not* do that), so one definitely needs some error type that covers both errors.

**Comment by apoelstra** [comment]
Ok, I'm going to turn on "Require conversations to be resolved" with the caveats that:

* For trivial things/things that have an obvious single resolution, anybody can click "Resolve"
* If the conversation was opened by a non-maintainer, then maintainers may click "Resolve"

And we'll see how this goes.

**Comment by tcharding** [comment]
> For trivial things/things that have an obvious single resolution, anybody can click "Resolve"

To clarify, I'm going to try to implement this process:

While going over all my notifications at one time to triage them for what needs doing that day

1. Read a review suggestion, if it is trivial and non-controversial, type something affirmative  eg, "will use as suggested".
2. Once I come back to do the work, make the change locally, then before pushing, while going over the review again to check nothing was missed, click "resolve".

The definition of "trivial and non-controversial" may be a bit subjective.

For any non-trivial review suggestions leave the review thread open for original reviewer to hit "resolved".

I have a feeling we are going to be writing "needs resolve clicking" a bunch of times now ...

**Comment by apoelstra** [comment]
>Once I come back to do the work, make the change locally, then before pushing, while going over the review again to check nothing was missed, click "resolve".

Oh, yeah, please don't click "resolve" until you've actually done and pushed the work :).

>I have a feeling we are going to be writing "needs resolve clicking" a bunch of times now ...

Maybe. Let's give it a week or so.

**Comment by tcharding** [comment]
Push first then click, that means I have to go over the whole list before pushing to check I didn't miss any, then go over the whole list again to click them, and since I have to re-read to get enough context since this is reasonably important this is going to be a pain. But I'll give it a go. I've already seen "needs 2 conversations resolving" on a PR and found it useful.

**Comment by apoelstra** [comment]
Yeah, that's pretty-much it. It really is a pain. But thanks for giving it a go. I think/hope that it won't be too bad for 95% of PRs, and only on the PRs that get dozens or hundreds of comments will it become a PITA. But those are exactly the PRs where we tend to lose track of specific comments.

**Comment by tcharding** [comment]
Please note I have attempted a different solution in #2593 to what is discussed here.

**Comment by apoelstra** [comment]
> Yeah, that's pretty-much it. It really is a pain. But thanks for giving it a go. I think/hope that it won't be too bad for 95% of PRs, and only on the PRs that get dozens or hundreds of comments will it become a PITA. But those are exactly the PRs where we tend to lose track of specific comments.

For future reference: in #2564 we decided to drop this because it was indeed a PITA and we pretty-much merged nothing for a week after trying it.
