### ISSUE TITLE
`SerializedSignature` does not honour `Formatter::precision()`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2509]
See `fmt_hex_exact_fn` in `hex-conservative` for how to solve this.

This issue is similar to `#2491 but for serialized signatures, we probably want to check any other types we have that are using `pad_integral` in their `Display` impls.

**Comment by apoelstra** [comment]
Should `precision` truncate the signature?

**Comment by tcharding** [comment]
I don't know, but if txid's can be truncated why not signatures? This is mainly useful for logs and debugging, right?

**Comment by apoelstra** [comment]
Truncated hashes are still hashes. Their collision and preimage resistance are reduced proportionally to how many bytes you truncate.

Truncated signatures though are meaningless.

**Comment by tcharding** [comment]
Good enough for me, thanks.
