### ISSUE TITLE
Audit that all `non_exhaustive` error types do not derive `Copy`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2522]
Deriving `Copy` makes the type less modifiable because we cannot add non-`Copy` fields/variants.

We discussed this before but I just  realized I forgotten about this rule, would be good to check this grammatically with `semgrep` or some tool.

**Comment by 15IITian** [comment]
I found no such error types  which are marked `non_exhaustive` and have `Copy` trait implementation.

**Comment by tcharding** [comment]
Awesome, thanks!
