### ISSUE TITLE
REQUEST: how can I generate address from a descriptor use v0.31

### ISSUE THREAD

**Issue by eauxxs** [rust-bitcoin/rust-bitcoin#2529]
for example: 
descriptor `wpkh([34e0c3cf/84h/1h/0h]tpubDD55VJFXhZoFadN2rTtP4vXUkde4vxvvstx9tHhkTTo6kg5XqZG1R4ViqAzxgdmcDMfUWPybkSsWbNsbCDPjwvssg47Wv9g3VJED3n4wFsZ/1/*)#gn2rx2kk`

how to generate address from it?
and can i listunspent from a descriptor?

**Comment by apoelstra** [comment]
You want to use `rust-miniscript`. You can use `Descriptor::from_str` on your string then `.address()` on the resulting `Descriptor` object.

**Comment by eauxxs** [comment]
thank you very much @apoelstra
