### ISSUE TITLE
Incorrect Bitcoin Address From Script, maybe?

### ISSUE THREAD

**Issue by kyluke** [rust-bitcoin/rust-bitcoin#253]
Taking the following testnet transaction:
`020000000001020fd2daf6c3ebdb7aa61f8fd3b2de5bd218a0c5d7c7c6a0f9e9925a37e7eda7750100000017160014ab5281cb81cc9ff4774437bc0483043ec2123a10feffffffaaa089de7c855eea262f4e4a5da24da8105247483339443c99569a677750923f01000000171600144a1956bfd3d6b4e35a3408b1d10d6939c827fb20feffffff02f00d0c000000000017a9144ef1a2ce7d672f078354cd8a28774eb57894fb1d87b6630f000000000017a914336d82d805e393216ddcc2e6bbee622bf9679381870247304402200c7eb686d40ec0d72bcc8dc8ae4873e11f4a34b6d212ee453c14ae655de9059d02201198a694c703475234fe15edb8ef1132ec62f6821eb0b2ade18b70d4260363b3012103d63b75f870479470c6fbaa5825614a5880dc6024c4986bae660ff7edf8e4679f0247304402205204c437933cb53cb44a284e67fb9a34bc92aa018026b680bf434f4df91f5646022038f2c3ba7d43f86bbd701f5f47e44814cfd721ee0276256f57c2bf9209d245cb012102367a50f93b50a06b66522710ca98e3c461d561fd9869f7f583faaeec7aae7da100000000`

The two outputs contain the following addresses:
`0:2MzSeAQc3xrTeSXKieAbRWWXU84wfdg6W1z`
`1:2Mww9e2qhPAV358pCSZSyZocqwZkn2KiV1C`

Converting the transaction as such:
```
// Decode the Bitcoin transaction
fn txdecode() {

    // Assuming that the variable 'transaction' is the bitcoin transaction above,
    let ctx = hex_bytes(transaction).unwrap_or_default();
    let tx: Result<Transaction, Error> = deserialize(&ctx);

    if tx.is_ok() {
        let ok_tx = tx.unwrap();
        println!("[{}]", ok_tx.txid());

        let outputs = Instant::now();
        // list the outputs
        let txouts = ok_tx.output.clone();
        for out in txouts.iter() {
            checkscripttype(&out.script_pubkey);
            println!("\tValue: {}", out.value);
        }

    // println!("{}\n{:#?}", ok_tx.txid().be_hex_string(), ok_tx);
    } else {
        println!("{:?}", tx.unwrap_err());
        println!("Couldn't decode transaction data, maybe it's bad?")
    }
}

// checks what kind of a script this output is
fn checkscripttype(scr: &bitcoin::blockdata::script::Script) {
    println!("\n\n");

    if scr.is_p2sh() {
        let p2sh = bitcoin::Address::p2sh(scr, Testnet);
        println!("\tIs Pay 2 Script Hash {}", p2sh);
    }
    if scr.is_p2pkh() {
        // println!("\tIs Pay 2 Public Key Hash {}", scr);
        // let p2pkh = bitcoin::Address::p2pkh(scr, Testnet);
        let pubkey = &scr[1..24];
        println!("\tNo idea yet. is_p2pkh {:?}", pubkey);
    }
    if scr.is_p2pk() {
        // println!("\tIs Pay 2 Public Key {}", scr);
        // let p2pk = bitcoin::Address::p2pk(scr, Testnet);
        println!("\tNo idea yet. is_p2pk")
    }
    if scr.is_v0_p2wsh() {
        let p2wsh = bitcoin::Address::p2wsh(scr, Testnet);
        println!("\tIs Pay 2 Witness Script Hash {}", p2wsh);
    }
    if scr.is_v0_p2wpkh() {
        // println!("\tIs Pay 2 Witness Public Key Hash {}", scr);
        // let v0_p2wpkh = bitcoin::Address::v0_p2wpkh(scr, Testnet);
        println!("\tNo idea yet. is_v0_p2wpkh")
    }
    if scr.is_op_return() {
        // println!("\tIs Op Return {}", scr);
        // let op_return = bitcoin::Address::op_return(scr, Testnet);
        println!("\tNo idea yet. is_op_return")
    }
    if scr.is_provably_unspendable() {
        // println!("\tIs Provably Unspendable {}", scr);
        // let provably_unspendable = bitcoin::Address::provably_unspendable(scr, Testnet);
        println!("\tNo idea yet. is_provably_unspendable")
    }

    println!("\n\t\tis p2sh: {:?}", scr.is_p2sh());
    println!("\t\tis p2pkh: {:?}", scr.is_p2pkh());
    println!("\t\tis p2pk: {:?}", scr.is_p2pk());
    println!("\t\tis v0_p2wsh: {:?}", scr.is_v0_p2wsh());
    println!("\t\tis v0_p2wpkh: {:?}", scr.is_v0_p2wpkh());
    println!("\t\tis op_return: {:?}", scr.is_op_return());
    println!(
        "\t\tis provably_unspendable: {:?}\n",
        scr.is_provably_unspendable()
    );
}
```

produces:

```

[99897dbe4cb3c343e785f9bafeda2cde4c85be69d7c5431224140495249be56c]

        Is Pay 2 Script Hash 2Myn8QKJb9fNBcB94NL3cdSoYnX3MGxpiSz

                is p2sh: true
                is p2pkh: false
                is p2pk: false
                is v0_p2wsh: false
                is v0_p2wpkh: false
                is op_return: false
                is provably_unspendable: false

        Value: 790000

        Is Pay 2 Script Hash 2NAg2fVPQfmYSe2ATWnM1BaED8yEdfkCsLA

                is p2sh: true
                is p2pkh: false
                is p2pk: false
                is v0_p2wsh: false
                is v0_p2wpkh: false
                is op_return: false
                is provably_unspendable: false

        Value: 1008566
```

As you can see, the result doesn't produce the same addresses as presented here: https://tbtc.bitaps.com/99897dbe4cb3c343e785f9bafeda2cde4c85be69d7c5431224140495249be56c and decoding the tx here: https://live.blockcypher.com/btc-testnet/decodetx/.

Am I doing something wrong?

**Comment by sgeisler** [comment]
Which version of the library are you using? I tried to decode the transaction using [`hal`](https://github.com/stevenroose/hal/) which uses this library and it outputs the expected addresses:

```
  "outputs": [
    {
      "value": 790000,
      "script_pub_key": {
        "hex": "a9144ef1a2ce7d672f078354cd8a28774eb57894fb1d87",
        "asm": "OP_HASH160 OP_PUSHBYTES_20 4ef1a2ce7d672f078354cd8a28774eb57894fb1d OP_EQUAL",
        "type": "p2sh",
        "address": "2MzSeAQc3xrTeSXKieAbRWWXU84wfdg6W1z"
      }
    },
    {
      "value": 1008566,
      "script_pub_key": {
        "hex": "a914336d82d805e393216ddcc2e6bbee622bf967938187",
        "asm": "OP_HASH160 OP_PUSHBYTES_20 336d82d805e393216ddcc2e6bbee622bf9679381 OP_EQUAL",
        "type": "p2sh",
        "address": "2Mww9e2qhPAV358pCSZSyZocqwZkn2KiV1C"
      }
    }
  ]
```

Can you post the code with the appropriate `use`s or a minimal example demonstrating the malfunction please?

**Comment by kyluke** [comment]
Here is the code I'm using that reproduces the problem:
https://gist.github.com/kyluke/681f21eb2b681ac7ac64ff223e326c1a

However, building in [hal](https://github.com/stevenroose/hal)'s [address_from_script](https://github.com/stevenroose/hal/blob/master/src/address.rs#L29) has produced the correct result.

Perhaps the trick is [[2..22]](https://github.com/stevenroose/hal/blob/master/src/address.rs#L33)

**Comment by sgeisler** [comment]
That's definitely a documentation issue: the function you are using expects the inner script (the one of which the hash for the outer p2sh script can be derived). You are giving it the outer script. That should be documented way better.

Hal is doing it right by extracting the hash from the outer script. Unfortunately there doesn't seem to be a simpler way to do it, but [script descriptors](https://github.com/apoelstra/rust-miniscript/blob/master/src/descriptor/mod.rs) might help. See also #27.

**Comment by kyluke** [comment]
Yeah I figured that out now after looking through his code. This should be in the comment or something. Perhaps his function could be included in some way.

**Comment by stevenroose** [comment]
These two links might be relevant: 

- a PR for an `Address::from_script` constructor: https://github.com/rust-bitcoin/rust-bitcoin/pull/254
- a trait in `hal` that gives you information on a tx: [`hal::GetInfo`](https://docs.rs/hal/0.1.1/hal/trait.GetInfo.html) gives you a [`TransactionInfo`](https://docs.rs/hal/0.1.1/hal/tx/struct.TransactionInfo.html) object with `hal::GetInfo::get_info(&tx, bitcoin::Network::Testnet)`.
