### ISSUE TITLE
I want ` blockdata::locktime::absolute::Height` to have `Default` implementation

### ISSUE THREAD

**Issue by 15IITian** [rust-bitcoin/rust-bitcoin#2532]
https://github.com/rust-bitcoin/rust-bitcoin/blob/b93397d472fc7459cce7f60d6fe352c2959fac24/bitcoin/src/blockdata/locktime/absolute.rs#L410

The lack of a `Default` implementation on the `Height` struct creates inconvenience when integrating it into other structs that rely on this trait. As a workaround, developers often need to create a wrapper, adding extra complexity and making the task more cumbersome.

**Comment by 15IITian** [comment]
> https://github.com/rust-bitcoin/rust-bitcoin/blob/b93397d472fc7459cce7f60d6fe352c2959fac24/bitcoin/src/blockdata/locktime/absolute.rs#L410
> 
> The lack of a `Default` implementation on the `Height` struct creates inconvenience when integrating it into other structs that rely on this trait. As a workaround, developers often need to create a wrapper, adding extra complexity and making the task more cumbersome.

**Comment by apoelstra** [comment]
Yeah, I think it's reasonable for both `Height` and `Time` to both have `Default` impls that default to 0.

**Comment by Kixunil** [comment]
I disagree, see: https://github.com/rust-bitcoin/rust-bitcoin/pull/2533#issuecomment-1983216591

Also please @15IITian refrain from using "absolutist" language in the titles of issues unless you're certain something is a bug. It makes it easier to gauge the importance of an issue just from the title if the title is appropriate.
