### ISSUE TITLE
`relative::LockTime` should be convertable to `Sequence` and/or have a consensus_u32 encoder

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#2545]
Right now once you parse out a relative locktime you are stuck with it. You should be able to round-trip it from a u32 or at least a sequence number.

**Comment by Kixunil** [comment]
I think `Sequence::MAX` is excluded? But yes, it should have conversions. It appears nobody used this API yet so nobody noticed they are missing.

**Comment by apoelstra** [comment]
Agreed, it seems nobody has used it yet. I am starting to use it now in https://github.com/rust-bitcoin/rust-miniscript/pull/654
