### ISSUE TITLE
relative::LockTime should have constructors

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#2547]
I don't know why we insist on going through a sequence number to get a `relative::LockTime`. It makes it very annoying to use in the Miniscript planning API, for example.

**Comment by Kixunil** [comment]
I don't understand. It's an enum, it has built-in constructors called `Blocks` and `Time`.

**Comment by apoelstra** [comment]
@Kixunil so is `absolute::LockTime` and yet it has `from_height`, `from_time` and `from_consensus` constructors, all of which you can pass integer literals to if you want to avoid the annoyance of constructing `Time` or `Height` objects first. It also has a couple useful constants like `ZERO`.

BTW how *do* you construct the `Time` or `Height` objects? Looks like those need constructors too.

**Comment by Kixunil** [comment]
Oh, yes, those are useful.

`Time` has two constructors but `Height` has none. Oh crap!
