### ISSUE TITLE
relative::LockTime should implement ordered::ArbitraryOrd

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#2566]
Maybe worth thinking of other types that should implement ArbitraryOrd as well.

**Comment by 15IITian** [comment]
https://github.com/rust-bitcoin/rust-bitcoin/blob/6f6cc00eb7479cd302beb76574e17d2bc80afd5f/bitcoin/src/blockdata/locktime/absolute.rs#L405

why it has been disabled?

**Comment by tcharding** [comment]
Its feature gated to give users control of their dependency graph, i.e., only enable whats needed.

**Comment by tcharding** [comment]
Opened #2580 to track the "Maybe worth checking ..." bit - this issue will be closd by #2581
