### ISSUE TITLE
units: Audit all types for correct usage of `Ord` vs `ArbitraryOrd`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2580]
Not all types have an order but putting types into struct that require `Ord` is common, this is what we wrote the [ordered]() crate for.

Audit all the types in `units` and check that they correctly either derive `Ord` and `PartialOrd` or implement `ArbitraryOrd`.

**Comment by 15IITian** [comment]
I'll take this up

**Comment by tcharding** [comment]
Oh woops, I should have mentioned originally but I was thinking of after #2569 lands - there is currently only the `amount` types in `units`. My bad.

**Comment by 15IITian** [comment]
> there is currently only the amount types in units.

Yeah , I was pretty confused  initially -> but now I  see there are other types  too which are related to amounts so can check them until #2569 got merge.

**Comment by 15IITian** [comment]
and I noticed that there are some types which do not have `PartialEq` & `Eq` trait implementation  like -> https://github.com/rust-bitcoin/rust-bitcoin/blob/6f6cc00eb7479cd302beb76574e17d2bc80afd5f/units/src/amount.rs#L1205

Is there any reason for it ?

**Comment by tcharding** [comment]
FTR, as of f6287fb44542661a93aceb94cb986e8f4faf7507 `units` looks good.

**Comment by tcharding** [comment]
I just checked all the types in the `units` crate using the `testl/api.rs` file as a guide for what 'all' means.
