### ISSUE TITLE
crate  labels go stale

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2597]
We have a bot that adds crate labels to PRs but when a PR gets updated the bot does not check that the labels are valid still.

**Comment by tcharding** [comment]
We fixed this a while back.

**Comment by Kixunil** [comment]
I did this intentionally so that the bot doesn't remove other labels.

**Comment by tcharding** [comment]
Oh you did? Perhaps I'm using the labels differently to you, I use them to later filter PRs, mainly to find things or to write the release notes. I found the stale labels hindered both use cases.

**Comment by Kixunil** [comment]
OK, let's keep it and if it removing other labels gets too annoying we'll rethink.

**Comment by apoelstra** [comment]
Can the bot "own" certain labels and only remove those?

**Comment by Kixunil** [comment]
It couldn't last time I checked :(
