### ISSUE TITLE
Changes that require updating the lock files do not fail CI

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2598]
I constantly push PRs that require changing the lock files (Cargo-recent.toml, Cargo-minimal.toml) and forget to run `just update-lock-files`. We should have a CI job that fails in this case.

**Comment by apoelstra** [comment]
I believe we do -- I think #2596 had a CI failure, which is how I knew you had to update the lockfiles.

**Comment by tcharding** [comment]
Oh yeah, no worries, I thought I looked before I raised this issue but I might have force pushed the fix already.

**Comment by tcharding** [comment]
Closing without checking  - don't verify trust, right :)
