### ISSUE TITLE
Our current merge policy/script causes excessive delay and work

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2601]
In the following scenario

1. dev A raises PR 
2. dev B and C ack
3. Some problem arises breaking CI for all PRs
4. dev A must now rebase and force push, then dev B and C must re-ack

The fix for step 3 should be able to be merged and then we should be able to merge dev A's PR without needing to rebase and re-ack.

**Comment by apoelstra** [comment]
I think we should fix #3. We've made a fair bit of progress, we just have a weird msan thing right now which is the sort of thing that only happens every year or two. Clippy/rustc issues happen probably 20 times as often and those are addressed by pinning CI as well. (The msan thing I think also would have been, but I guess it's intermittent.)

But ACKs on commits which have been rebased away are meaningless.

**Comment by tcharding** [comment]
Ok, no worries, thanks. Lets see how we go now we have pinning.
