### ISSUE TITLE
deserializing network message can request arbitrary sized allocations

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#2606]
You can test the bitcoin/deser_net_msg.rs fuzztest with
```
73656e646d65726b6c65626c6f636b0080000000010000000000000003343333333333330333333333333334000000ffff000000000000002e2e2e310000000100000000312e2e2e2e2e2e2e000000000000000000000000000000000000000000000000000000000000000000ffffffffffffffff00000000000000000000000000000000000000000000000000000000000000000000002e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e6765746366636865636b70742e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e00000000000000000000000000000000000000000000b0b3e37fb13a4534caaf00ee0f777478696472656c61795b31db354aae4fdab52a9ad5255a60e2f807d72eb08893005e0d6e6f74666f756e642f21ed076bd50d250ac51fbff4268902056f11771bd47187854c252e4fda2768cd1280808080e76fbadfcdb86fa091d97c8d6c93476eb080d6d0225090a4400b046ad82937ebc7aa7c8f2e2e2e2e2e703433333333333303670000000000000100000000000000000003362c2c2c2c2c2c626f626b2c8014636b6c74190d0d
```
and it'll fail with
```
memory allocation of 576460752303423480 bytes failed
```

We need to fix this before the next release and may need to backport.

**Comment by apoelstra** [comment]
Offending line is in merkle_tree/block.rs

```
impl Decodable for PartialMerkleTree {
    fn consensus_decode_from_finite_reader<R: BufRead + ?Sized>(
        r: &mut R,
    ) -> Result<Self, encode::Error> {
        let num_transactions: u32 = Decodable::consensus_decode(r)?;
        let hashes: Vec<TxMerkleNode> = Decodable::consensus_decode(r)?;

        let nb_bytes_for_bits = encode::VarInt::consensus_decode(r)?.0 as usize;
        let mut bits = vec![false; nb_bytes_for_bits * 8]; 
        for chunk in bits.chunks_mut(8) {
            let byte = u8::consensus_decode(r)?;
            for (i, bit) in chunk.iter_mut().enumerate() {
                *bit = (byte & (1 << i)) != 0;
            }   
        }   

        Ok(PartialMerkleTree { num_transactions, hashes, bits })
    }   
}
```

the `let mut bits` line which allocates a vec with a size that it read from the above line, even though it's being called with a finite reader.

This specific line comes from https://github.com/rust-bitcoin/rust-bitcoin/pull/1991 but it's just moving a line that was in #268 (the May 2019 PR which introduced this data structure).

Oops.

Found by the fuzztest on the "introduce SHA384" PR.

I wonder if we can easily instrument our fuzzer to blow up when we hit a particular allocation limit, which we could set at 4MB or something more easily attainable.

**Comment by apoelstra** [comment]
Alternately, adding a fuzztest which tries to deserialize this type almost instantly finds a failing test (because it's easy to make the multiplication by 8 trigger an overflow).

So maybe we just need to add more fuzztests.

**Comment by tcharding** [comment]
Legend! I just, totally coincidentally, posted about this in another place.

**Comment by apoelstra** [comment]
>For my own learning how exactly did you work this out, did you just start reading code and find it or did you get a hint at where to look?

There was a CI failure on master (specifically [this one](https://github.com/rust-bitcoin/rust-bitcoin/actions/runs/8268759743/job/22622423510#step:6:1226) though the link will go dead in a week or so) which outputs the name of the failing fuzztest and a hex test vector that will trigger it. So I tried the test vector and got a "failed to allocate" crash. Which I re-ran in valgrind, which pointed me to merkle_block/block.rs.

So it was pretty-much entirely machine-guided. The longest part by far was that I kept the CI failure tab open for a week while I procrastinated on investigating it.

Also, I get github notifications on CI results and usually investigate failed ones on master. So I am aware, for example, that Kani has failed every night for the last month or so, because we never completely fixed it.

**Comment by tcharding** [comment]
Interesting, I've tried a few (a couple at least) of the failed hex vectors and never gotten one to fail locally, I wonder why? If its your smaller-memory-on-VMs idea I wonder why the vector failed on your local machine. 

> Also, I get github notifications on CI results and usually investigate failed ones on master. So I am aware, for example, that Kani has failed every night for the last month or so, because we never completely fixed it.

Oh, I don't get those. So everytime I abuse CI and push multiple times to a PR you get spammed with notifications of each failed test run?

**Comment by apoelstra** [comment]
>So every time I abuse CI and push multiple times to a PR you get spammed with notifications of each failed test run?

Not every time. I think they only show up when I do this with my own PRs. In any case they're very obvious and easy to mass-dismiss.
