### ISSUE TITLE
Can we sort `rustfmt` out once and for all

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2608]
> So you will need to override your editor or be careful about what changes you commit, for now.

Goodness gracious me - 2 years ago we realized that `rust-bitcoin` was really annoying for _normal_ devs to work on because many Rust devs have their editors configured to automatically run `rustfmt`. So we disabled it in `rustfmt.toml` and that made this project way nicer for contributors. Fastforward and we _still_ cannot get everyone to just aggree on f**cking rustfmt and now we are back to a place were casual devs cannot make changes to `rust-bitcoin` without modifying the config of their editor - this is embarrassingly stupid.

**Comment by apoelstra** [comment]
Things worked great when we had weekly fmt CI jobs These usually had 10-50 line diffs and in the intervening week usually people wouldn't run into the uncommitted changes in their own PRs.

Given that this solved a multi-year problem with several stakeholders who had incompatibly demands, we should not have been so quick to defer it indefinitely.

I think we just need to go back to that.

**Comment by tcharding** [comment]
@Kixunil do you have a specific PR that you are expecting to get in before release? Otherwise lets run the formatter and get back to merging the bot's PRs weekly like you say @apoelstra. You mention elsewhere a max number of vetos for the bot PRs, I propose n=0

**Comment by dpc** [comment]
![image](https://github.com/rust-bitcoin/rust-bitcoin/assets/9209/08786d10-9019-4c91-a6c7-d31a8aedd063)

**Comment by apoelstra** [comment]
> You mention elsewhere a max number of vetos for the bot PRs, I propose n=0

I would propose n = 2, but I'd be fine with 0. I don't think it's a big deal to miss a week or two since formatting problems don't accumulate that fast (especially if you and I are formatting our diffs).

But the last one we merged was 1-14. The moratoriam started [with 1-21](https://github.com/rust-bitcoin/rust-bitcoin/pull/2371#issuecomment-1902760655). That's 8 weeks and counting.

**Comment by tcharding** [comment]
> I would propose n = 2

I'm willing to give this a go, @Kixunil?

> especially if you and I are formatting our diffs

I've currently disabled formatting in my editor because its a PITA when there are loads of formatting issues on master. I'll turn it back on and see how we go once we merge a formatting PR.
