### ISSUE TITLE
Should `LockTime` types live in `units`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2611]
This issue is to consolidate the discussion on whether or not `LockTime` should live in `units`.

I personally think the types are more than mere units and therefore live in `primitives` not in `units`.  Some brief points to back up my position:
- The `relative::LockTime::ZERO` value abstracts more details that just plain old zero (time-lock zero is not the same as height-lock zero).
-  The fact that one can call `absolute::LockTime::from_height` and `from_time` both with a `u32` shows there is some abstraction.

**Comment by tcharding** [comment]
High priority because if I am wrong then we likely want to do the move before we release `units`.

**Comment by apoelstra** [comment]
My feeling is that they should live in `units`, though `Sequence` should stay in `primitives`. My argument is that these *are* units for measuring durations and times. They're just shitty ones that don't have total orders.

But I don't feel strongly about this and could be convinced either way.

**Comment by tcharding** [comment]
But if they go to `units` then `Sequence` has to go too if we want the new API in #2549.

**Comment by apoelstra** [comment]
Hmm, yeah, ok, then the locktimes should stay in `primitives`.

**Comment by sanket1729** [comment]
> My feeling is that they should live in units, though Sequence should stay in primitives. My argument is that these are units for measuring durations and times. They're just shitty ones that don't have total orders.

I prefer having them in `primitives`. I can also live with both of them in `units`, but I strongly oppose them in being different places. That would just create confusion even if they might technically belong in separate places, people often think of them in the same vein and expect them to belong together.

**Comment by tcharding** [comment]
Are you referring to `relative::LockTime` and `Sequence` @sanket1729 or `LockTime`s and `Height`/`Time`?

**Comment by sanket1729** [comment]
I would prefer *::LockTime and Sequence to stay in the same crate.

**Comment by tcharding** [comment]
Yep, awesome. So I think we are good to leave everything as is in `units` for now, and after next release we start on `primitives` and both `*::LockTimes` (and `Sequence`) go there.

@Kixunil is a bit quiet at the moment, mentioning you man so you see this even though I'm closing it.
