### ISSUE TITLE
Is introducing `LockTimeUnit` enum promote redundancy? 

### ISSUE THREAD

**Issue by 15IITian** [rust-bitcoin/rust-bitcoin#2616]
https://github.com/rust-bitcoin/rust-bitcoin/blob/6389d3f7fc1feddac9432ff5c65c938a1b1ca66a/units/src/locktime/absolute.rs#L239

https://github.com/rust-bitcoin/rust-bitcoin/blob/6389d3f7fc1feddac9432ff5c65c938a1b1ca66a/bitcoin/src/blockdata/locktime/absolute.rs#L60

`LockTimeUnit`  enum is similar to `LockTime` (just that its variants do not hold any data) .
I think , creating `LockTimeUnit` enum just for denoting that the given locktime value is of which type (i.e Blocks or Seconds) increases redundancy in our codebase.

Should we just remove them and use `LockTime` enum instead?

**Comment by apoelstra** [comment]
It's a non-public type, for what it's worth. It's a helper type to make the error type easier to follow.

If I were writing the code I'd have just used a boolean here, but I don't really mind having it.

**Comment by 15IITian** [comment]
> It's a non-public type, for what it's worth. It's a helper type to make the error type easier to follow.

Concept ACK

**Comment by tcharding** [comment]
The `LockTimeUnit` is more than just a boolean because of the stuff it adds by way of `Display` - which makes the public `ConversionError` code easier to read. I think it was a good addition.
