### ISSUE TITLE
Encodable not implemented for [T; 64] or ()

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#262]

**Comment by stevenroose** [comment]
What would you want `()` for?

**Comment by apoelstra** [comment]
Sometimes it's useful to say "don't serialize anything" in generic code.

**Comment by TheBlueMatt** [comment]
I really don't think we should be moving towards Encodable being a public trait to be implemented for random things, its consensus::encode, not Writable. If a client wants to encode something, they can Write it. As it is the generic Encodable implementations make introducing bugs much too easy.

**Comment by apoelstra** [comment]
Closing because after discussion in #264 I think this is the wrong direction to take these traits.
