### ISSUE TITLE
Use `Message::from`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2631]
In commit `678eee8d7388 Use Message::from_digest` we replaced `Message::from_digest_slice(hash.as_byte_array())` with `Message::from_digest(hash.to_byte_array())` however we failed to notice that we can go one step further because the sighash hash types implement `secp256k1::ThirtyTwoByteHash` and use `Message::from(hash)`.

**Comment by apoelstra** [comment]
We definitely did not "fail to notice" this. The use of the `ThirtyTwoByteHash` trait is the cause of all our "dependency hole" problems related to coordinating rust-bitcoin releases, though I can never remember the exact mechanism of our pain.

**Comment by tcharding** [comment]
I also forgot what it was exactly, linking to other discussion thread so we talk in one place. https://github.com/rust-bitcoin/rust-secp256k1/issues/673#issuecomment-2019043343

**Comment by tcharding** [comment]
I don't see anything wrong with the current code or anyway to action this issue - closing as noise.
