### ISSUE TITLE
Is the function `from_hardened_idx` correctly implemented?

### ISSUE THREAD

**Issue by ywiyogo** [rust-bitcoin/rust-bitcoin#2643]
In https://github.com/rust-bitcoin/rust-bitcoin/blob/master/bitcoin/src/bip32.rs#L149, I see that the if check is as same as the from_normal_idx. Shouldn't the implementation like this:
```
        if index & (1 << 31) == 1 {
            Ok(ChildNumber::Hardened { index })
        } else {
            Err(Error::InvalidChildNumber(index))
        }       
```

**Comment by tcharding** [comment]
The `ChildNumber` enum maintains the invariant that each value does not have the top bit set. The `from_hardened_idx` and `from_normal_idx` expect the input value to be within the range [0, 2^31 - 1]. There is also the `From<u32>` impl that accepts a `u32` with the top bit specifying hardened/normal
```rust
impl From<u32> for ChildNumber {
    fn from(number: u32) -> Self {
        if number & (1 << 31) != 0 {
            ChildNumber::Hardened { index: number ^ (1 << 31) }
        } else {
            ChildNumber::Normal { index: number }
        }
    }
}
```

**Comment by apoelstra** [comment]
Yep, this is correct. Though it could perhaps be commented better.

**Comment by ywiyogo** [comment]
Thanks for the clarification!
