### ISSUE TITLE
`base58::Vec` in error message is odd

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2653]
If one gets a compile error because of incorrect type and a `Vec` is expected the error message is odd, here is an example:
```
     = note: expected enum `psbt::SigningKeys`
              found struct `base58::Vec<crypto::key::PublicKey>`
```

Something somewhere is getting confused.

**Comment by apoelstra** [comment]
I blame https://github.com/rust-lang/rust/issues/121708 which has forced us to write increasingly arcane invocations to get `Vec` into our code, which in turn seems to be confusing rustc.

**Comment by tcharding** [comment]
Yeah I had the same feeling (although I did not have a rust-lang link). Seems like a regression and will be likely fixed upstream, we can just sit tight and not action this issue, right?

**Comment by apoelstra** [comment]
Yeah, I think it's fine to just sit tight. I definitely don't think we should try to take action by second-guessing the compiler's path resolution in error messages.
