### ISSUE TITLE
Make hex an optional dep for hashes

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-bitcoin#2654]
ISTM hex isn't really all that "required" to do hashing, and personally I'd very much like to use bitcoin_hashes with ~zero dependencies (with potentially eyeing building outside of cargo). It seems making hex an optional dependency is pretty easy, just requires actually adding the right feature tags (and maybe one or two sealed traits). Is this something folks would be open to?

**Comment by apoelstra** [comment]
Yep! I believe we had discussed this earlier. I think we want to do the hash trait splitting as part of the same effort (see #2496).

**Comment by tcharding** [comment]
I tried searching but can't find or remember why one should not feature gate trait implementations. Furthermore I don't understand why this issue mentions sealed traits.

 To make `hex` optional it seems we need to feature gate all the `FromStr` / `Display` impls - what am I missing please.

**Comment by apoelstra** [comment]
But yes, we would definitely need to feature-gate `FromStr` behind the `hex` feature. There is no reason not to do this. I think you're misremembering something.

**Comment by tcharding** [comment]
Oh that's right we literally had this conversation a week ago for `std::error::Error` and you worked out it was because of the macro I was using. Guess something was still floating around my brain unresolved.

**Comment by tcharding** [comment]
One quick and dirty thing I tried was just printing "<hexidecimal not implemented with hex feature> {:?}"

**Comment by apoelstra** [comment]
No, we should definitely either support it "properly" (ok to have crappy support for format specifiers initially but we should aim to have it complete by 1.0) or have it not compile.

**Comment by tcharding** [comment]
> or have it not compile.

I really do like this option but because of orphan rule it leaves `no_std` users with the only option of using `Debug` if they want to display a hash. I think this is too rude, if we say we support `no_std` we should put the effort in to do it properly.

**Comment by Kixunil** [comment]
What does it have to do with `no_std`?

I think removing `Display` entirely is better because we would need to avoid its represenatation changing based on that feature which is very difficult with formatting and there's no point reimplementing it completely.

**Comment by tcharding** [comment]
It has to do with `no_std` because of the interaction between `Display` and `FromStr`. I agree with you that having a different format depending on features is not good.

**Comment by Kixunil** [comment]
Both `Display` and `FromStr` are inherently `no_std`. There's no operating system involved in implementing them.

**Comment by tcharding** [comment]
Ah my bad, I got mixed up with `ToString` which is in `std` not `FromStr`.

**Comment by kayabaNerve** [comment]
I believe it's technically in `alloc`.

**Comment by Kixunil** [comment]
> I'm unsure if y'all care about that distinguishing though

I do. They are quite different features and not having these concepts messed up in our heads helps us work.

**Comment by tcharding** [comment]
Yes I definitely do still mix these things up, point noted.

**Comment by tcharding** [comment]
While seemingly simple this is non-trivial because of the trait bounds, although this can be solved with something like
```rust

// TODO: Add fmt::UpperHex
/// The string related trait bounds we put on `Hash` when `hex` feature is enabled.
#[cfg(feature = "hex")]
pub trait Bounds: fmt::Debug + fmt::Display + fmt::LowerHex + core::str::FromStr {}

/// The string related trait bounds we put on `Hash` when `hex` feature is not enabled.
#[cfg(not(feature = "hex"))]
pub trait Bounds: fmt::Debug {}
```

Next non-trivial thing is that we provide public macros that implement `fmt` traits, adding feature gates inside these macros requires the calling crate to have the feature - ugly. So we'd have to split up the macros into just the `hex` related stuff then feature gate all the callsites.

**Comment by tcharding** [comment]
Do we _really_ want to do this?

**Comment by apoelstra** [comment]
>although this can be solved with something like

I don't think this will work, unless you intend `Bounds` to be a sealed trait (which would then implicitly make everything depending on it a sealed trait) which is not what we want to do.

We have a similar issue in rust-miniscript regarding nostd and the `Error` trait, though once we get our MSRV up to 1.80 we'll be able to deal with it nicely. But for now I've been using `Box<dyn core::fmt::Display>` as an error type, which is brutal..

>adding feature gates inside these macros requires the calling crate to have the feature

Hah, strong concept NACK this idea. Every time we do this our code breaks in some MC Escher-style clusterfuck of incompatible trait bounds.
