### ISSUE TITLE
Computing witness lengths of a TxIn

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#2659]
To use the constructor for `InputWeightPrediction`, the `input_script_len` and `witness_element_lengths` is needed.  Given a TxIn and accessing the Witness field, is it possible to compute the witness_element_lengths?

For example:

```rust
    #[test]
    fn tx_in_weight_predict() {
        let tx_in = TxIn::default();
        let input_script_len = tx_in.script_sig.len();
        let witness_element_lengths = tx_in.witness.witness_element_lengths; // how to compute?
        let i = InputWeightPrediction::new(input_script_len, witness_element_lengths);
    }
```

The `Witness` struct has `content` and `witness_elements` (which are private) but not `witness_element_lengths` from what I can tell..

**Comment by sanket1729** [comment]
As discussed in `rust-minsicript` issue, you need a descriptor to do this.

**Comment by apoelstra** [comment]
If the witness is already populated then `Witness::size` gives you this.

**Comment by yancyribbens** [comment]
> If the witness is already populated then Witness::size gives you this.

@apoelstra thanks, although my confusion is that [The Witness size method](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/bitcoin/src/blockdata/witness.rs#L301) returns a usize, while [PredictIntputWeight constructor](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/bitcoin/src/blockdata/transaction.rs) requires something that can be iterable.  I mean size() could just be shoved into a vec but that doesn't feel like the intent.

**Comment by sanket1729** [comment]
In most/all cases we never know the exact witness before using `PredictInputWeight`, thus descriptors. I am somewhat confused with this flow. There are several constants [`P2PKH_MAX`](https://github.com/rust-bitcoin/rust-bitcoin/blob/bae2c75f69528a2c6218581f042c8e76bc887bc7/bitcoin/src/blockdata/transaction.rs#L1500) and more that help more most common use cases. For other use-cases involving script hash, you need some information about the descriptor and the spend path that you plan to use.

**Comment by yancyribbens** [comment]
> In most/all cases we never know the exact witness before using PredictInputWeight, thus descriptors. I am somewhat confused with this flow. There are several constants [P2PKH_MAX](https://github.com/rust-bitcoin/rust-bitcoin/blob/bae2c75f69528a2c6218581f042c8e76bc887bc7/bitcoin/src/blockdata/transaction.rs#L1500) and more that help more most common use cases. For other use-cases involving script hash, you need some information about the descriptor and the spend path that you plan to use.

@sanket1729 hmm ok.  I'll take a look at how to incorporate descriptors.  Thanks!

**Comment by yancyribbens** [comment]
Closing/not actionable.

**Comment by Kixunil** [comment]
> [The Witness size method](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/bitcoin/src/blockdata/witness.rs#L301) returns a usize, while [PredictIntputWeight constructor](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/bitcoin/src/blockdata/transaction.rs) requires something that can be iterable.

`Witness::size` returns the size of whole witness while `PredictInputWeight` requires individual sizes of the witness elements. Trying to get the value from `Witness` is completely pointless because the point of weight prediction is for you to not need `Witness`!
