### ISSUE TITLE
Is `Hmac` too generic

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2663]
We implement [HMAC](https://en.wikipedia.org/wiki/HMAC) using the `Hmac` type. The type is generic over `crate::Hash`, is this too generic? Said another way why would anyone want to use `Hmac<sha256t::Hash>` or `Hmac<hash160::Hash>`.

Should we just implement two versions of HMAC-x

- HMAC-SHA-256
- HMAC-SHA-512

We could then remove all the generic code and simplify the module.

**Comment by tcharding** [comment]
Is HMAC-SIPHASH-24 useful too?

**Comment by apoelstra** [comment]
Are you suggesting we add a `HashThatWeCanImagineSomebodyHmacing` trait which is narrower than `Hash`?

I'm not sure what this would accomplish. HMAC is defined for any cryptographic hash. If we implemented it only for specific types this would reduce its functionality and obscure the code by hiding what properties of our concrete hash function are actually needed.

In practice it is probably only used with sha2 and sha3 (which we don't have) but even within the sha2 family there is SHA512/256 which we implement but isn't in your suggested list of hashes.

**Comment by tcharding** [comment]
> In practice it is probably only used with sha2 and sha3 (which we don't have) but even within the sha2 family there is SHA512/256 which we implement but isn't in your suggested list of hashes.

This is enough to prove to me that we need some sort of generic. I'll think/code some more and see if I come up with anything.
