### ISSUE TITLE
Should document how to create a custom `Params`

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#2690]
Our `Params` structure is `#[non_exhaustive]`, which I believe is the correct way to go (because we will almost certainly want to add flags or something to it, e.g. to handle the new difficulty rule for testnet4, whatever that turns out to be). However this makes it super non-obvious how users are supposed to construct this thing, if they want to support their custom networks.

The "right" way to do this, I think, is for them to call `Params::new(Network::Regtest)` (maybe with testnet rather than regtest) and then manually edit the specific fields they want to change. This matches the typical "start with regtest then tweak the network magic or whatever" mode of creating test networks.

But the docs don't say anything about this and they should.

https://docs.rs/bitcoin/latest/bitcoin/consensus/params/struct.Params.html

**Comment by tcharding** [comment]
Since we made so much effort with `Params` and `Network` this release this should go in the release IMO. I'll prioritize it.

**Comment by tcharding** [comment]
Also we may want to add const constructors for any/all of the types that are used in `Params` so folk can create const getters (eg., `pub const fn magic` above).

**Comment by apoelstra** [comment]
Yep, this looks like what I had in mind.

> Also we may want to add const constructors for any/all of the types that are used in `Params` so folk can create const getters (eg., `pub const fn magic` above).

Yeah, ideally everything related to params should be const.
