### ISSUE TITLE
Preparing taproot script spend to be signed 

### ISSUE THREAD

**Issue by domwoe** [rust-bitcoin/rust-bitcoin#2701]
Hi,

Thus far, I've prepared the message to be signed by using the `SigHashCash` API in the following way:

```    
let mut sighasher = SighashCache::new(&mut tx);
let sighash = sighasher
  .taproot_script_spend_signature_hash(
    commit_input_index,
    &sighash::Prevouts::All(prev_tx.output.as_slice()),
    TapLeafHash::from_script(&script, LeafVersion::TapScript),
    TapSighashType::Default,
 )
 .expect("failed to construct sighash");
```

However, I now need to use a signer API that does the SHA256 hashing internally. Is there any API that allows creates the message to be signed in a similar way but minus the final hashing?

Thanks a lot for your help!

**Comment by apoelstra** [comment]
@domwoe yep! See [SighashCache::taproot_encode_signing_data_to](https://docs.rs/bitcoin/latest/bitcoin/sighash/struct.SighashCache.html#method.taproot_encode_signing_data_to). The simplest thing for you would be to pass a `&mut Vec` to this method, which will write the transaction data into your vec, and you can then do whatever you want with it.

Possibly you want to directly pass a network socket or something, but it's probably easier to start with the vec.

**Comment by domwoe** [comment]
Thank you for the quick reply @apoelstra.

I'm still struggling with an "Invalid Schnorr Signature".

Here's what I did:

```
let mut sighasher = SighashCache::new(&mut reveal_tx);
let mut signing_data = vec![];
let leaf_hash = TapLeafHash::from_script(&reveal_script, LeafVersion::TapScript);
    sighasher
        .taproot_encode_signing_data_to::<&mut Vec<u8>, TxOut>(
            &mut signing_data,
            commit_input_index,
            &sighash::Prevouts::All(commit_tx.output.as_slice()),
            None,
            Some((leaf_hash.into(), 0xFFFFFFFF)),
            TapSighashType::Default,
        )
        .expect("Failed to encode signing data");

    let sig = schnorr_api::sign_with_schnorr(key_name, derivation_path, signing_data).await;

    print(&format!("Reveal Tx Signature: {}", hex::encode(&sig)));

    let witness = sighasher
        .witness_mut(commit_input_index)
        .expect("getting mutable witness reference should work");

    witness.push(
        Signature {
            sig: schnorr::Signature::from_slice(sig.as_slice()).expect("should parse signature"),
            hash_ty: TapSighashType::Default,
        }
        .to_vec(),
    );

    witness.push(reveal_script);
    witness.push(&control_block.serialize());
```

The signer does essentially the following:

```
let digest = sha256::Hash::hash(&message).to_byte_array();
let sig = secp256k1.sign_schnorr_no_aux_rand(
  &Message::from_digest_slice(&digest).expect("should be cryptographically secure hash"),
  &key_pair,
);
```

Anything obvious that you spot glancing over it?

**Comment by sanket1729** [comment]
Can you try see if the rust signer creates the correct signature that is verified? It should help narrow down if you are using the `schnorr_signer_api` incorrectly.
The code looks correct ™️ , are you sure that `schnorr_signer_api` takes input the sighash message as raw data.

**Comment by domwoe** [comment]
@sanket1729 

I already added the following check after getting the signature back which works as expected:

```
// Verify the signature to be sure that signing works
let secp = bitcoin::secp256k1::Secp256k1::verification_only();

let sig_ = schnorr::Signature::from_slice(&sig).unwrap();

let digest = sha256::Hash::hash(&signing_data).to_byte_array();
let msg = Message::from_digest_slice(&digest).unwrap();

 assert!(secp
   .verify_schnorr(&sig_, &msg, &schnorr_public_key)
   .is_ok());
```

The signer code is [here](https://github.com/domwoe/schnorr_canister/blob/9fb5d8be5ac45b80e67919dfc20045213e4c40f9/src/lib.rs#L267).
I need to do it this way, as the signer will eventually be implemented as a threshold signing protocol.

**Comment by domwoe** [comment]
Ok. Finally figured it out. The `signing_data` above needs to be prepended with the `TapSighashTag`.

```
let tag = b"TapSighash";
let mut hashed_tag = sha256::Hash::hash(tag).to_byte_array().to_vec();
let mut prefix = hashed_tag.clone();

prefix.append(&mut hashed_tag);

let signing_data: Vec<_> = prefix.iter().chain(signing_data.iter()).cloned().collect();
```

**Comment by tcharding** [comment]
Sorry you had to work this out yourself, and sorry I didn't read the issue 2 days ago. I've literally been playing with the `hashes` API (incl. implementing `Write` for the hash types) this last few days so this is fresh in my mind. My bad.

Please see https://github.com/rust-bitcoin/rust-bitcoin/issues/2703
