### ISSUE TITLE
What are the `*_encode_signing_data_to` functions public for?

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2703]
The `sighash::*_encode_signing_data_to` functions are public but its not obvious to me why so? Said another way, its not obvious to me why someone would want to encode signing data and then hash it themself instead of just writing to a hash type. On top of that, hashing taproot signing data requires the hash to be tagged, as user @domwoe had to painfully find out for himself in #2701.

What are the `*_encode_signing_data_to` functions public for? And why do we accept a writer and not a reference to the respective sighash type?

**Comment by apoelstra** [comment]
>encode signing data and then hash it themself

This is the obvious way to send data to a hardware wallet to be signed. Or to display to a user/log so they know what is being signed. You can recompute it from a full transaction but then you need to reimplement the method.

It's also an aid for debugging.

**Comment by apoelstra** [comment]
I'm also confused about you citing #2701 which has a user asking for *exactly this functionality*.

**Comment by tcharding** [comment]
> I'm also confused about you citing #2701 which has a user asking for exactly this functionality.

Lol, its _literally_ in the original post - face palm.

> However, I now need to use a signer API that does the SHA256 hashing internally. Is there any API that allows to create the message to be signed in a similar way but minus the final hashing?

I'll add documentation to the `taproot_encode_signing_data_to` function to mention that the data has to be hashed with a tagged hash.  And while we are at it I'll document the other two to say the signing data has to be double sha256 hashed.

If you had a dollar for everytime I said something retarded you'd be rich by now @apoelstra :)

**Comment by apoelstra** [comment]
>I'll add documentation to the taproot_encode_signing_data_to function to mention that the data has to be hashed with a tagged hash. And while we are at it I'll document the other two to say the signing data has to be double sha256 hashed.

Yeah, good call. I probably would have run into exactly this issue (I haven't used the taproot variant of this function yet, I'm behind the times..)

>If you had a dollar for everytime I said something retarded you'd be rich by now @apoelstra :)

:)
