### ISSUE TITLE
How to recover address from txn witness data?

### ISSUE THREAD

**Issue by saurabhburade** [rust-bitcoin/rust-bitcoin#2733]
- I have an array of witness hex data like this
- https://mempool.space/tx/1bc6814dfab83f468e7ba4a24694974f1e33744e6b6ea0518ec6e99c80ff1016
- I want to recover the address bc1p233yer*******g8jjqgtxnxt

**Comment by tcharding** [comment]
Do you mean this?
```rust
use bitcoin::consensus::Decodable;
use bitcoin::hex::test_hex_unwrap as hex;
use bitcoin::{params, Address, Transaction};

fn main() -> anyhow::Result<()> {
    let want = "bc1p233yerwey949jkz9t7dyynw4yz84nx6m3z5uv27eq4dywpgg8jjqgtxnxt";

    let raw_tx = hex!("0200000000010102628409a0b48dcbef8f612a9ee791e797ff50f61b71616ed761875e5c9de5670000000000ffffffff0222020000000000002251209fa6f1741e417f9217bc920024be14f9528c5bdf32ce188a6689aec49ac8386b0000000000000000096a5d0614011400160001404769f48a0ee5316869132824e8ca0247c93afc0b097b2804624fdb3000fe7ef9d1ee7646ceeda115f3c0c3c8e4aeb89caac72bd4928a02b4c0bb1dcd0f8b30f900000000");

    // TODO: Finish PR #2318
    // let tx = hex.parse::<Transaction>()?;
    let tx: Transaction = Decodable::consensus_decode(&mut raw_tx.as_slice()).unwrap();

    println!("{:#?}", tx);

    // The txid copied from `tx` above.
    let prev_raw_tx = hex!("02000000000101ca8663edcc834b9a7cb919df62b61858e38eaf91207f13257fd0cf25cedc93920000000000ffffffff02863400000000000022512054624c8dd9216a5958455f9a424dd5208f599b5b88a9c62bd9055a4705083ca40000000000000000096a5d061401140016000140c90cdf10e72771592fe63cdee9a1523fef0e197480621e2d1772b1296574a6e9916b28add3934e1455fc71b53b676c51eb58a4e00d781f71b78d4bc29b04ea8f00000000");

    let prev_tx: Transaction = Decodable::consensus_decode(&mut prev_raw_tx.as_slice()).unwrap();
    println!("{:#?}", prev_tx);

    let spk = &prev_tx.output[0].script_pubkey;
    let addr = Address::from_script(&spk, &params::MAINNET)?;
    assert_eq!(addr.to_string(), want);

    println!("\n{}", addr);

    Ok(())
}
```

**Comment by saurabhburade** [comment]
I have just `witness` data, not even prev utxo data

**Comment by junderw** [comment]
You asked the same question on BitcoinJS and never told me what you need it for… now you’re writing rust?

what are you trying to do?

with the exception of key spend p2tr it is possible to recover the address just from the witness stack.

key spend p2tr is impossible. You need the previous outputs.

**Comment by junderw** [comment]
It’s not like asking someone else will get you a different answer.

This is not some subjective answer or a "I don’t know how to do it so ask someone else" answer.

This is an objective fact.

What you are trying to do is impossible.

Please accept this fact.

It’s not a skill issue. It is mathematically impossible.

**Comment by saurabhburade** [comment]
I completely get it [junderw](https://github.com/junderw), I was decoding runes data on substreams and was getting just raw txn data as regular btc txn, and looking around for any solution to fit in best.

I was trying it in any one way
Either decode data with JS sink or
Decode on Substream itself to use Subgraph

**Comment by apoelstra** [comment]
I'm going to close this issue. It has nothing to do with rust-bitcoin (or bitcoinjs) and apparently was already answered elsewhere.

**Comment by junderw** [comment]
For reference: https://github.com/bitcoinjs/bitcoinjs-lib/issues/2088
