### ISSUE TITLE
ci: Consider shellcheck for bash/shell scripts linting

### ISSUE THREAD

**Issue by storopoli** [rust-bitcoin/rust-bitcoin#2739]
Should we add [shellcheck](https://www.shellcheck.net/) in our CI since we do now a TON of stuff using bash/shell scripts?

              Yeah I try to run that on all scripts, we don't in CI though. Perhaps we should. And with all this yaml work just now I came across `yamllint` which taught me a few things.

_Originally posted by @tcharding in https://github.com/rust-bitcoin/rust-bitcoin-maintainer-tools/issues/4#issuecomment-2093676040_
            

GitHub Shellcheck CI Action: https://github.com/marketplace/actions/shellcheck-github-action

If favorable, I am volunteering to PR it across the `rust-bitcoin` repos.

**Comment by apoelstra** [comment]
Yeah, this is a great idea.

**Comment by tcharding** [comment]
A few things to note:

- We need to run in with `-x` (well that is what I've been doing) to quieten this warning

```bash
In contrib/run_task.sh line 292:
    . contrib/test_vars.sh || exit 1
      ^------------------^ SC1091 (info): Not following: contrib/test_vars.sh was not specified as input (see shellcheck -x).
```

- We need to find a solution to this warning, I think the use of `wc -l` is better than the suggestion

```bash
In contrib/run_task.sh line 231:
            | grep -v 'syn' \
              ^-----------^ SC2126 (style): Consider using grep -c instead of grep|wc -l.
```

**Comment by tcharding** [comment]
I do like the idea though.

**Comment by dpc** [comment]
Use comments like:

```
# shellcheck disable=SC2126
```

to disable particular warnings.

**Comment by tcharding** [comment]
Legend!
