### ISSUE TITLE
Implement constants for `PsbtSighashType`

### ISSUE THREAD

**Issue by storopoli** [rust-bitcoin/rust-bitcoin#2751]
This would avoid all the `unwrap`/`expect` in
`PsbtSighashType::from_str("SIGHASH_ALL").expect("valid sighash type")` for example.

**Comment by tcharding** [comment]
Agree, note that naming them could be a bit curly. This is the docs from `PsbtSighashType` just so whoever picks this up is careful.
```rust
/// A Signature hash type for the corresponding input. As of taproot upgrade, the signature hash
/// type can be either [`EcdsaSighashType`] or [`TapSighashType`] but it is not possible to know
/// directly which signature hash type the user is dealing with. Therefore, the user is responsible
/// for converting to/from [`PsbtSighashType`] from/to the desired signature hash type they need.
```

**Comment by tcharding** [comment]
I just remembered that typical usage to get a `PsbtSighashType` is
```rust
    let ty = EcdsaSighashType::All.into();
```

**Comment by apoelstra** [comment]
That's a good idiom which we should document. But I still think we should have constants directly on `PsbtSighashType`. At least, one for ALL which is by far the most common case.

**Comment by storopoli** [comment]
> That's a good idiom which we should document

You mean extending https://github.com/rust-bitcoin/rust-bitcoin/blob/594eb18728fb8a433b1045f7e9c9c507ec54349b/bitcoin/src/psbt/map/input.rs#L135-L144

with an example of the `From<[Ecdsa|Tap]SighashType>` with the `.into()` like above?

**Comment by apoelstra** [comment]
@storopoli yep
