### ISSUE TITLE
Remove shebang from all shell scripts that are not meant to be run

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2764]
If #2762 merges we should remove the shemang from the other shell scripts that are meant only to be sourced and not run e.g., `test_vars.sh`.

**Comment by apoelstra** [comment]
It would be good also to find a way to detect whether the script is being run directly, and to print an error message. I'm sure this is a common thing and we can find a stackexchange post telling us how to do it.

**Comment by tcharding** [comment]
Tip: use 

```bash

# No shebang, this file should not be executed.
# shellcheck disable=SC2148
```

**Comment by storopoli** [comment]
> It would be good also to find a way to detect whether the script is being run directly

I know that @apoelstra already mentioned and linked a StackOverflow similar answer, but we might try this:
https://stackoverflow.com/q/9850166
