### ISSUE TITLE
`difficulty_float` is hardcoded to mainnet

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2783]
We fixed `Target::difficulty` a while back to use `max_attainable_target` from `Params` (which is network specific) but we forgot to fix `Target::difficulty_float` in the same way.

**Comment by 15IITian** [comment]
I'll take this up.

**Comment by 15IITian** [comment]
https://github.com/rust-bitcoin/rust-bitcoin/blob/3c7ac53e89b23edeadfeb3b1cd5dec68bd079e7c/bitcoin/src/pow.rs#L276


here in the division part -> should I do  : 

``` rust 
  (U256_inst1 / U256_inst2).to_f64()
```

or 
``` rust
 (U256_inst1.to_f64()) / (U256_inst2.to_f64())
 ```
 ??
