### ISSUE TITLE
0.32 loses a bunch of functionality in `Address`

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#2784]
Sorry to be here six months later, I'm only now updating my bitcoin dependency to 0.32 (which was released just under a month ago).

I can now no longer create addresses from a script hash. This is marked intentional to enforce script length checks. This actually is an extremely surprising loss of functionality which I need to manually re-implement (`ScriptBuf::from_p2sh`, then `Address::from_script`, then `unwrap`).

I also can no longer enum-match addresses effectively which is a frustration (it's match type, then call the relevant getter and unwrap the `Option` it returns).

I also can't get a WitnessProgram out of an address which means I have to rip that out of the script pubkey (which is iterating to the last instruction, then unwrapping the push bytes of it, which is a mess).

All of this is a severe degradation in functionality, introduces numerous unwraps, and I'd love to see it improved. I believe it's

```
pub from_script_hash()
enum AddressData { P2pkh(_), P2sh(_), P2w(_)  } // pubkey_hash, script_hash, witness_program
pub address_data()
```

Which I'm looking for? Instead of `AddressData` (which somewhat restores Payload), at the least an additional `witness_program` getter? Any thoughts on what APIs would be eligible/rejected for restoration?

_Originally posted by @kayabaNerve in https://github.com/rust-bitcoin/rust-bitcoin/issues/1979#issuecomment-2122236571_

**Comment by apoelstra** [comment]
Agreed, and sorry about this. As mentioned in #1979 we should be able to re-add a bunch of this functionality in 0.32.

> I can now no longer create addresses from a script hash. This is marked intentional to enforce script length checks. This actually is an extremely surprising loss of functionality which I need to manually re-implement (`ScriptBuf::from_p2sh`, then `Address::from_script`, then `unwrap`).
> 

Yeah, this is super strange. You can get a `WScriptHash` *out* of an `Address` but not create an `Address` from one. Meanwhile, you can create an `Address` directly from a script (internally constructing a WScriptHash and also doing length checks, ok) *or* you can create a `WScriptHash` directly from a script (which does **not** do length checks). But then that `WScriptHash` is basically useless.

So I propose:

* In 0.32.1 we add a `Address::from_script_hash` constructor which infallibly creates an address from a scripthash.
* We also add a `WScriptHash::from_script` method and `TryFrom` impl which do length checks.
* In 0.33.0 we should possibly drop the existing `From<&Script>` for `WScriptHash` impl. I'm unsure whether we actually want to prevent users from doing this. Probably we should have a `from_script_unchecked` method rather than `From` which does not indicate "you are doing something that could result in an unspendable address".

> I also can no longer enum-match addresses effectively which is a frustration (it's match type, then call the relevant getter and unwrap the `Option` it returns).
> 

This is harder. Probably we should provide an enum for all the major script types. But this is really rust-miniscript functionality; we don't want rust-bitcoin to have an ad-hoc list of script templates that it supports and which are permanently part of the API.

At the very least, such an enum would need to be marked `#[non_exhaustive]` to handle future script output types.

> I also can't get a WitnessProgram out of an address which means I have to rip that out of the script pubkey (which is iterating to the last instruction, then unwrapping the push bytes of it, which is a mess).

Agreed this is a mess. Again, we have a conversion in one direction (`WitnessProgram` to `Address`) but not in the other direction for some reason. We should definitely add accessors to `Address` which will return the `WitnessProgram` and `WitnessVersion`.

cc #1909 which I think was our most recent "script hash API" issue.

**Comment by kayabaNerve** [comment]
... can we add a standard script object? Such an object is defined in Bitcoin proper (so it shouldn't be opinionated) and should handle all Bitcoin addresses. It's fine if you still believe that should be in miniscript, just thinking of an argument potentially sufficient for inclusion here in rust-bitcoin.

**Comment by apoelstra** [comment]
>Such an object is defined in Bitcoin proper

Yeah, that's true, there is an objective set of "Bitcoin address types" out there. So we should make an enum. But it would need to be `#[non_exhaustive]` because we may extend it.

**Comment by tcharding** [comment]
> I also can no longer enum-match addresses effectively which is a frustration (it's match type, then call the relevant getter and unwrap the Option it returns).

You can use the `AddressType` enum: https://docs.rs/bitcoin/latest/bitcoin/enum.AddressType.html

**Comment by tcharding** [comment]
I think I've addressed everything in this issue in:

- #2794 
- #2795 
- #2796

The last two should be backported.

**Comment by storopoli** [comment]
Why the first one should not be backported?
I see that is somewhat breaking, but I see as a "bug fix" that should be backported anyways, even if breaking.

**Comment by apoelstra** [comment]
@storopoli I strongly disagree. Probably nobody is hitting this limit anyway because they are using fixed scripts or Miniscript, and anyway P2SH has been deprecated for the better part of a decade.

So dropping a `From` impl would be a lot of API breakage for basically no benefit. And let's remember that this "fix" is just enforcing a network rule that we weren't previously enforcing, but that the network would've enforced for us. There are many many ways to create invalid scripts that we will not and cannot detect.

**Comment by storopoli** [comment]
@apoelstra, Good arguments, yes I agree with you.

**Comment by kayabaNerve** [comment]
@tcharding  I did acknowledge the AddressType enum.

> I also can no longer enum-match addresses effectively which is a frustration (it's match type, then call the relevant getter and unwrap the Option it returns).

My complaint was how because the AddressType enum doesn't contain the relevant data, I then need to runtime unwrap a getter (when there's not even all getters).

If AddressType is to be expanded with the relevant data, that'd be fine by me, yet then I'd question if we're back at Payload.

**Comment by apoelstra** [comment]
We should expand `AddressType`.

It's possible that it will wind up identical to `Payload` (though I don't think so) but it has the crucial distunction that `Payload` is used internally to represent the address and we may want to break or expand it in all sorts of ways. Vs `AddressType` which is purely for user consumption.

**Comment by tcharding** [comment]
> @tcharding I did acknowledge the `AddressType` enum.

My bad.

> We should expand `AddressType`.

I'll dig into it a bit deeper. Cheers

**Comment by tcharding** [comment]
What about something like this?

```rust
        /// Known address type payload.
        ///
        /// Explicitly excludes addresses that are unknown, non-standard, or related
        /// to the future witness version.
        #[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub enum Payload {
            P2pkh(PubkeyHash),
            P2sh(ScriptHash),
            Segwit(WitnessProgram),
        }

        impl Address {
            fn to_payload(&self) -> Option<Payload> {
                use AddressType::*;

                self.address_type().map(|t| match t {
                    P2pkh => Payload::P2pkh(self.pubkey_hash().expect("is p2pkh")),
                    P2sh => Payload::P2sh(self.script_hash().expect("is p2sh")),
                    // P2wpkh | P2wsh | P2tr => 
                    P2wpkh | P2wsh | P2tr => {
                        Payload::Segwit(self.witness_program().expect("is segwit"))
                    }
                })
            }
        }

        if let Some(payload) = address.to_payload() {
            match payload {
                Payload::P2pkh(pubkey_hash) => { println!("{}", pubkey_hash) },
                Payload::P2sh(script_hash) => { println!("{}", script_hash) },
                Payload::Segwit(witness_program) => { println!("{:?}", witness_program) },
            }
        }
```

**Comment by tcharding** [comment]
Could be backported to `v0.32`

**Comment by storopoli** [comment]
I think that `Payload` could be `#[non_exhaustive]` like [`AddressType`](https://docs.rs/bitcoin/latest/bitcoin/address/enum.AddressType.html).

**Comment by apoelstra** [comment]
@tcharding yeah, this is conceptually what I'm looking for. But

* The new enum should be `#[non_exhaustive]`.
* We should name the fields rather than having them directly contained in variants.
* I don't think we should return an `Option`. If we are going to interpret all segwit outputs as `Segwit` without splitting between v0 and Taproot, then we should go all the way. The user can check the `.version()` of the `WitnessProgram` if they care to distinguish these or filter for only known address types.
* I don't really like the name `Payload`. Maybe it should be `DecodedAddress` or something.
* There should be a conversion in the opposite direction. (Would be interesting to see under what circumstances this would panic or error...ideally all these types are strong enough that you can directly construct any variant of `Payload` and the result would be a valid address.)

**Comment by kayabaNerve** [comment]
The user can also perform the `matches!(kind, AddressType::P2wpkh | AddressType::P2wsh | AddressType::P2tr)` check re: witness program.

**Comment by tcharding** [comment]
> The new enum should be `#[non_exhaustive]`.

If the primary use case for this enum is to match on are we not risking the same shit storm as we found ourselves in when we added `non_exhaustive` to `Network`?

**Comment by tcharding** [comment]
> I don't really like the name `Payload`. Maybe it should be `DecodedAddress` or something.

Funny you say this, the process that got me to that name was
1. read this thread
2. add a new type
3. try to work out what to call it
4. think "hmm its kind of like the stuff in the address, perhaps `Payload`"
5. think "oh shit, that is what it was called before I removed it"

**Comment by apoelstra** [comment]
> If the primary use case for this enum is to match on are we not risking the same shit storm as we found ourselves in when we added `non_exhaustive` to `Network`?

No, for a few reasons:

* This data is far less frequently needed than `Network`, and not in places where compatibility is really that important (typically with this type you extract the data immediately then throw it away, vs trying to pass it to other functions).
* Users almost certainly already need to deal with "unsupported address type", at least to handle segwit versions greater than 1.
* Users who really want to support every conceivable address type with infallible code have a "back door" by calling `Address::script_pubkey` and then doing their own parsing on that.

>Jokes aside, its not all the info from a decoded address string because of the network/bech32 prefix. Any other ideas? This is not a new concept, right "the data that outputs that spend to this address are encumbered with"?

Yeah, good point. Maybe `AddressData`? Or maybe `Payload` is fine I guess.

**Comment by kayabaNerve** [comment]
For full context, my use case is my project defines its own `Payload` equivalent. We use a binary representation of supported addresses (due to space limitations which we are at risk of hitting), and explicitly declare what types of addresses we support. The 'new Payload' being non-exhaustive means when rust-bitcoin updates to support new address types, we'd ignore them (as we would unsupported types) until we add support (which is the exact behavior we want).

**Comment by tcharding** [comment]
I believe this will be closed by #2807 (posting this because github is currently glitching and not picking up the "Close: #2807" in that PR)

**Comment by Kixunil** [comment]
I believe the "new enum" is the `script::Template` I proposed in #2296. Or is there a difference? I'm low on time and energy to check properly rn.

**Comment by Kixunil** [comment]
You could convert an address to it though. And while there are unused variants one would need `_` match arm anyway so it shouldn't matter. The only problem would be converting from that enum to `Address` but I think methods are better for this.

**Comment by apoelstra** [comment]
Yeah, that's fair. Maybe #2296 then is the right way to go with this issue.
