### ISSUE TITLE
ASM encoding for OP_CLTV / OP_CSV

### ISSUE THREAD

**Issue by shesek** [rust-bitcoin/rust-bitcoin#280]
`OP_CLTV`/`OP_CSV` are currently encoded to asm string as `OP_NOP2`/`OP_NOP3`. This was brought up previously by #150 and now again in the context of esplora at https://github.com/Blockstream/esplora/issues/98.

Is keeping it like that an intentional decision? Should I do the conversion on esplora's side, or could this be added here?

**Comment by stevenroose** [comment]
I agree. I fixed it here: https://github.com/rust-bitcoin/rust-bitcoin/pull/282
