### ISSUE TITLE
Remove rustdocs build warnings

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2800]
If one runs `just check-api` there are loads of build warnings generated because of incorrect rustdocs. We should fix them.

**Comment by storopoli** [comment]
I'd love to work on that, what's the ETA/priority? I am off next week, but only next week.

**Comment by apoelstra** [comment]
I'm happy to let you have this @storopoli. I consider it low priority, but I have noticed these and they do annoy me.

**Comment by apoelstra** [comment]
I'll agree not to work on it for the next week or so -- but if somebody else does, I'll ACK and merge it. As a rule we can't let people "claim" work that they haven't actually finished and published yet, because nobody can physically track each other down to get status updates :).

**Comment by tcharding** [comment]
I tend to think that first person to raise an at-least-half-decent-effort PR gets to claim the issue. (But I have been known to steam roll over people's PRs if I think the are too shit :) ) I'll note that you have intention to do these, mirroring what @apoelstra said. Thanks man.

**Comment by jyap808** [comment]
Took a quick look at this. Not sure if there's anything obvious to fix.

A few warnings mentioning ```[`ordered::ArbitraryOrd`]``` which is only enabled when the "--features ordered" flag is used. No warning when the flag is enabled. Generated docs look OK.

**Comment by apoelstra** [comment]
`contrib/check-for-api-changes.sh` shows more than that.

I have also encountered these warnings in other contexts. If I remember one that doesn't require installing `cargo-public-api` and using a nightly compiler I will post it here. But the obvious candidates (`cargo +nightly clippy --all-targets` etc) don't seem to yield the warnings).

**Comment by tcharding** [comment]
These work:

- `cargo rustdoc --no-default-features`
- `cargo rustdoc --no-default-features --features=alloc`

**Comment by tcharding** [comment]
Until just now I was muddled about this issue and (at least for the feature related warnings) @jyap808 was correct, our docs do not, and need not, build without all features _and_ `rustdoc::broken_intra_doc_links`. Since docsr builds with all features this is not an issue.
