### ISSUE TITLE
The `sha256t_hash_newtype!` call in the `taproot` module is unclear

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2811]
Raising an issue instead of a PR in case I'm just being overly sensitive. The macro call in the `taproot` module declares six types in a single go, as such (and because of the rustdocs layout) its not obvious which goes with which and I find myself having to remember to pair them. It doesn't help that the hash for `TapBranchTag` is called `TapNodeHash` instead of being uniform and using `TapBranchHash` like the other two.

Should we:
- Remove the repetition in the macro and call it three times so the grouping is obvious?
- Rename the `TapNodeHash`?

**Comment by tcharding** [comment]
> I'm not sure what you mean by "remove the repitition" though.

The repetition in the macro, what allows for the current call with multiple hash/tags in a single call.

**Comment by apoelstra** [comment]
Oh, yeah. Agreed, we should remove that ability. Probably worth adding a doccomment clarifying that you can do multiple definitions in the normal newtype macro, but in the sha256t one, because there are two types per hash to define, we found it became confusing to allow multiple hashes.
