### ISSUE TITLE
Links to crate code inside `hash_newtype!` don't work

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2827]
We allow rustdocs on types in the `hash_newtype!` macro but links don't work.

In other words could not get '[\`sha256:Hash\`]' to work as expected

```rust
hashes::hash_newtype! {
    pub(crate) struct TxidEngine(sha256d);

    /// A bitcoin transaction hash/transaction ID.
    ///
    /// For compatibility with the existing Bitcoin infrastructure and historical and current
    /// versions of the Bitcoin Core software itself, this and other `sha256d::Hash` types, are
    /// serialized in reverse byte order when converted to a hex string via [`std::fmt::Display`]
    /// trait operations. See `sha256d::Hash::DISPLAY_BACKWARD` for more details.
    pub struct Txid(_);
}
```

**Comment by apoelstra** [comment]
Very interesting. I suspect it's a bug in rustdoc. But one more reason to move away from macros toward trigger traits I guess.

**Comment by Kixunil** [comment]
This appears to be caused by your change to accept module name rather than type in the parentheses. You're just not importing `sha256d`.

**Comment by tcharding** [comment]
Thanks for the comment, I disagreed with it and in checking to see who was correct I found that adding the square brackets back in on my local "epic hash rewrite" branch made made the links start working, so the issue is thing that is incorrect. No clue what state my local branch was in when I raised this issue (or what branch I based the issue on).

Closing
