### ISSUE TITLE
Rustdoc: private doc tests lint

### ISSUE THREAD

**Issue by storopoli** [rust-bitcoin/rust-bitcoin#2840]
As pointed out in #2830, we have the `-D rustdoc::private-doc-tests` deny doc tests in private things lint on in `RUSTDOCFLAGS`.
See [private_doc_test in rustdocs docs](https://doc.rust-lang.org/beta/rustdoc/lints.html#private_doc_tests) for more information.

We are testing on a private item which is the `mod block` in https://github.com/rust-bitcoin/rust-bitcoin/blob/2cfe0e204ddfc192c38a2f40909563f72e57117b/bitcoin/src/merkle_tree/mod.rs#L16

If you add a `#![allow(rustdoc::private_doc_tests)]` after the SPDX header and before the module-level docstrings in https://github.com/rust-bitcoin/rust-bitcoin/blob/2cfe0e204ddfc192c38a2f40909563f72e57117b/bitcoin/src/merkle_tree/mod.rs#L1-L14

then it gives no more errors.

This issue is to discuss how to solve this.
Are we going to add a clippy `allow` lint?
Is `-D rustdoc::private-doc-tests` lint crucial?

**Comment by apoelstra** [comment]
I think we should move the doctest on the private module out of docs and into a unit test. Having it in a doccomment sends the misleading message that it'll show up on docs.rs.

**Comment by jamillambert** [comment]
I have moved the doctest to a unit test in PR #2859.  As far as I can tell it is only this one private module that had a doctest.
