### ISSUE TITLE
Transaction version should be i32 not u32

### ISSUE THREAD

**Issue by amoskyler** [rust-bitcoin/rust-bitcoin#287]
Currently transaction version is defined as a `u32`
https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/blockdata/transaction.rs#L257

According to bitcoin source code this should be `i32` https://github.com/bitcoin/bitcoin/blob/c65c77c721b69f1782509145d62978d31c9a1d78/src/primitives/transaction.h#L289.

While the value _should_ always be 1 or 2, there are at least two notable exceptions: txid `35e79ee733fad376e76d16d1f10088273c2f4c2eaba1374a837378a88e530005` has a version of `-2130706433` and `c659729a7fea5071361c2c1a68551ca2bf77679b27086cc415adeeb03852e369` has a version of `-1703168784`.

**Comment by TheBlueMatt** [comment]
https://github.com/bitcoin/bitcoin/pull/16525 should fix the issue in Bitcoin Core, making it (effectively) unsigned.
