### ISSUE TITLE
No way to access `UnprefixedHexError` 

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2874]
We forgot to re-export a module for users to get at the `units::parse` error types.

Related, we do not re-export the `units` crate from `bitcoin` - was this by design, I can't remember right now.

**Comment by Kixunil** [comment]
I guess we were trying to avoid noise? Still it's accessible by having `units` directly in `Cargo.toml` though that's annoying, so I agree with fixing it.

**Comment by apoelstra** [comment]
Yeah, we should re-export `units` from the `bitcoin` crate root.

**Comment by shinghim** [comment]
does this mean adding the export for UnprefixedHexError specifically [to where units re-exports are currently being done](https://github.com/rust-bitcoin/rust-bitcoin/blob/9ba29b384e6f690e0a6d6c1e0b1b989a3249a58f/bitcoin/src/lib.rs#L200-L203)?
