### ISSUE TITLE
`psbt::raw::Key`'s `type_value` field should be serialized as `VarInt`

### ISSUE THREAD

**Issue by evanlinjin** [rust-bitcoin/rust-bitcoin#2891]
Refer to how `<keytype>` is defined in https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#specification

Mentioned by @brunoerg here: https://x.com/brrrunog/status/1803462216525447583

**Comment by brunoerg** [comment]
Thanks!

See: https://github.com/brunoerg/bitcoinfuzz/issues/44

**Comment by Kixunil** [comment]
Just to be perfectly clear, the serialization is VarInt but we'll use a different type (`u64` I guess). We've got rid of `VarInt` type because it was overly complicated.

**Comment by Kixunil** [comment]
I've set 0.33 milestone, however I'm in favor of doing it in a patch release, since this is a bug, if it doesn't affect the API (haven't had time to look into it yet and I won't have time for a while).

**Comment by apoelstra** [comment]
I don't think we need to backport. It is a bug but it does not affect any currently-used PSBT fields as far as I am aware, and nobody reported having trouble with it until the fuzzer did.

**Comment by Kixunil** [comment]
Looks like a potential DoS vulnerability to me? Especially with PayJoin where you get PSBTs from untrusted sources - crash the server by sending specially-crafted PSBT. But TBF most servers probably use `tokio` which limits the panic to a single task unless you compile with `unwind = "abort"`.

**Comment by apoelstra** [comment]
If the PSBTs are untrusted then you can't `unwrap` their deserialization anyway because somebody could send you actually malformed data.

The only risk here is that you fail to parse PSBTs that you should be able to.

**Comment by Kixunil** [comment]
Ah, OK, I misunderstood the issue. I wouldn't be against bundling it with other backports if we need them anyway but I agree it's not urgent.

**Comment by tcharding** [comment]
FTR this bug is only a bug in that we do not support key types greater than 0xFD - the encoding is still correct for keytypes under that value.

**Comment by tcharding** [comment]
Sorry, I did not grok this issue while it was being discussed last week. Now I have played with the code, unless I missing something, I'm confused about some parts of the discussion above

>  I don't think we need to backport. It is a bug but it does not affect any currently-used PSBT fields as far as I am aware

What do you mean by does not affect any currently-used PSBT fields? If I understand correctly, there are valid PSBTs that we cannot deserialize (ie. any psbt that uses a keytype equal or greater than 0xFD

> We've got rid of `VarInt` type because it was overly complicated.

What do you mean by this? `VarInt` still exists on `master`?

**Comment by Kixunil** [comment]
There was a PR to remove it, I thought it got merged.

**Comment by apoelstra** [comment]
> If I understand correctly, there are valid PSBTs that we cannot deserialize (ie. any psbt that uses a keytype equal or greater than 0xFD

Yes, they are valid PSBTs, but they are ones that are using proprietary fields because none of the standard fields have type >= 0xFD.

> There was a PR to remove it, I thought it got merged.

I had also thought it was merged. Lemme investigate..

**Comment by apoelstra** [comment]
Oof, it got two ACKs but then one comment from Kix which the author never followed up on (and now it is in rebase hell) https://github.com/rust-bitcoin/rust-bitcoin/pull/2133

Probably one of us should redo it.
