### ISSUE TITLE
Doc: Capitalization of proper nouns

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2913]
## Problem

- Proper nouns should always be capitalized. 
- There is more than one correct way to write "Taproot tree" ("Taproot Tree") but we should be uniform and pick one (relates to "Merkle tree" and "Huffman tree" also).

## To close this issue

- Fix the spelling of all instances of Taproot tree, Merkle tree, and Huffman tree codebase-wide (rustdocs, code comments, and error strings).
- Fix the capitalization of all instances of Taproot and Merkle (Merkle tree, Merkle root, etc)

## Suggested (slightly related) tasks

(dev free to follow these suggestions or not)

- Do not capitalize "tree", use "Merkle tree" and "Taproot tree"
- Remove "tap tree", use "Taproot tree"
- Always capitalize "Taproot" and also "Merkle"

Since rustdocs on error types match the error string closing this issue probably also needs:

- Do not capitalize error strings (or `expect` messages), unless they start with a proper noun (eg Merkle or Taproot) 

Its probably safe to just check the `taproot` module error strings (and `expect` statements) while doing closing this issue.

**Comment by tcharding** [comment]
Can you ack/nack the "To close this issue"  section please @apoelstra

**Comment by jamillambert** [comment]
I have started to fix `Taproot`, just FYI so we don't duplicate work since I am not sure how long it will take at this point.

**Comment by apoelstra** [comment]
ACK the "To close this issue".
