### ISSUE TITLE
Determine API for `sha256::Midstate`

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#2918]
Isn't midstate mainly intended for creating tags? It thus shouldn't need all the traits.

But even more seriously, didn't we agree to have length in the midstate? That'd be incompatible with serialization. Do we really want to do this?

_Originally posted by @Kixunil in https://github.com/rust-bitcoin/rust-bitcoin/pull/2861#discussion_r1652587350_

**Comment by apoelstra** [comment]
My proposal is:

```rust
struct Midstate {
    /// Raw bytes of the midstate, i.e. the already-hashed contents of the hash engine.
    bytes: [u8; 32],
    /// Number of bytes hashed to achieve this midstate. INVARIANT must always be a multiple of 64.
    length: usize,
}
```

Then we would have read-only accessors for both fields, and a way to convert the type infallible back into an `Engine`. To create this type, you must call a method on `sha256::Engine` which will return a `Result<Midstate, HashedNonMultipleOf64BytesError>` so that you can't try e.g. hashing a single byte and then extracting a midstate. (You can do this today and probably the result is not what you intended.)

All these methods should be inherents, even if we later have a `ByteArray` type trait, since midstates are special and shouldn't be fed into generic algorithms. (If users really think they want to be generic, they can write their own trait and/or cast the midstate into something else by extracting the byte array.)

I could be convinced that `length` should be in bits, but given that no other part of our sha256 API allows us to hash individual bits, I think not. I would like this functionality for rust-simplicity but it's pretty niche and probably should just go into its own new separate module.

**Comment by Kixunil** [comment]
If the length is known why multiple of 64 matters? Also possibly make the length `u64` since you can hash arbitrary number of bytes.

Whatever API we choose we must take care to not mess up tag midstate pre-computation in const context.

> midstates are special and shouldn't be fed into generic algorithms. (If users really think they want to be generic, they can write their own trait and/or cast the midstate into something else by extracting the byte array.)

I believed this to be the case for a while, I'm happy to see you agree.

**Comment by apoelstra** [comment]
>If the length is known why multiple of 64 matters? Also possibly make the length u64 since you can hash arbitrary number of bytes.

Because the midstate bytes are only updated when the compression function is run, which only happens every 64 bytes.

**Comment by apoelstra** [comment]
Right now you can try extracting a midstate from a sha256 engine, then hash another byte, and extract the midstate again. You'll find it hasn't changed. This is "expected" if you know exactly what the midstate represents (which, I suppose, you should if you're using this type..) but it's a footgun.

If users want to get the "full" state of the hash engine, we could maybe expose a `into_raw_parts` method or something on `Engine`, but that's easy to add post-1.0 so I think we should wait on it until a usecase pops up.
