### ISSUE TITLE
How to stabilize most important stuff in two weeks

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2919]
Obviously, the title is an exaggeration, however unless I'm missing something, the only steps holding us back from doing this are script tagging and hash tagging (with known/unknown preimage).

**This is a tradeoff, so I ask maintainers of various downstream projects to comment whether this would be valuable**

You get `Transaction` and its parts (probably also `Block`), various hashes (e.g. `Txid`), and keys stabilized really soon (possibly doable in half a year or so). As an effect if two libraries interact with each-other and take a type from this crate, then updating `bitcoin` in one of them **will not** break the types. Thus you'll be able to update at your own pace (at the cost of duplicated dependencies).

*However* you will have to import extension traits for all non-trivial operations you perform with those types. E.g. keys will not have sign/verify methods, `Script` might not have various accessors, to convert keys to `secp256k1` keys you'll have to serialize and deserialize them. It's quite possible wildcard imports will work OK. This situation will gradually improve until we stabilize the methods.

Is this tradeoff good for you? @romanz @dpc @TheBlueMatt @junderw @JeremyRubin @casey @DanGould @afilini @petertodd @elsirion @RCasatta @sanket1729

To remind you, the alternative is you get the types stable with (almost?) all inherent methods but later. Possibly many months later.

(End of question, you can skip the rest and just post an answer.)

How to do it:

* Make `hash_newtype_minimal_1_0` macro that's guaranteed to produce a minimal implementation of hash newtype with no traits from unstable crates implemented. Use that macro to declare to-be-stabilized hash types. This macro will never change its output in a breaking way.
* Move *just the types* (no methods) into primitives&co.
* Move trivial methods such as `from_byte_array`, `.compute_txid()`, `serialize`... to the new crate(s).
* Move stable trait impls (`From`, `AsRef`...) to the new crate(s).
* Change all impl blocks of these types located in `bitcoin` to be extension traits (there's likely a macro to do this, we could also write our own).
* Double check we're not leaking any unstable types.
* Release primitives&co as stable.
* Continue improving stuff in `bitcoin`, gradually move stable methods to inherents

I think that these steps can be done really fast.

If anyone is wondering about the cost of key conversions: if it's too much to always reserialize we can declare a "blessed version of secp" by defining a constant in `crypto`. Then have a helper that checks the version and `unsafe` casts pointers or re-serializes keys depending on whether they match. (We could also have a separate ABI versioning system if we really want to.) We'd periodically update the blessed version and as long as people update it their performance will not suffer. Maybe there are more tricks we can pull off, this is just a basic idea.

**Comment by RCasatta** [comment]
> Is this tradeoff good for you? 

Yes

**Comment by Kixunil** [comment]
@apoelstra we could possibly store the keys in the types as serialized (for now). Also see the hack I suggested above.

**Comment by apoelstra** [comment]
Ok yeah, I like the idea of storing them serialized in uncompressed 64-byte form. Then it will even be easy for us to serialize them from rust-bitcoin without any supporting rust-secp code. (Recompressing just means checking the sign of the `y` coordinate which can be read from a single bit. Or we could use the hybrid encoding lol which puts the signedness in the first byte.)

(Deserializing will continue to be hard since it will require a squaring op for uncompressed serialization and a sqrt op for compressed.)

**Comment by tcharding** [comment]
Intriguing idea @Kixunil, I have two technical concerns:

1. Testing: Unit tests have to live with the extension traits and then don't have access to the type internals.
2. Orphan Rule: Trait implementations have to live in with the type definition but may require functions defined in extension traits. 

I think the first is an annoyance that can be overcome by adding a bunch of additional functions (that may clutter the API) but the second is a show stopper unless every function called by a trait impl is also "stabalized" (put in `primitives` along with the type).

### Meta discussion

Q: What are we trying to achieve with the crate stabalization?

I think the answer is:
- Provide a `rust-bitcoin` crate that can be updated without all the ecosystem having to upgrade in sync.
- Provide smaller specific crates that downstream can use to get various benefits:
  - minimise the code they have to review
  - reduce compile time
  - hopefully reduce the upgrade cadence

If this list is correct then I think our limited engineering time would be better spent just creating `primitives` with all the code we have at the moment the focusing hard on stabalizing our crates from the bottom up. Current work on `hashes` is an example of how hard this is but how it is possible because it is a separate crate.

**Comment by Kixunil** [comment]
> 1. Testing: Unit tests have to live with the extension traits and then don't have access to the type internals.

I don't think they should access internals to begin with. Accessing internals means needless refactorings every time you change the layout. Just test the API. Being forced to use the API in tests can also uncover API problems like missing a fundamental conversion.

> 2\. Trait implementations have to live in with the type definition

Unless they are fundamental to the type (e.g `struct Foo<T: Bar>(T)`) they don't. I don't remember us having any such unstable traits. Impls will be with trait definitions.

Notice that in the issue I **do not** promise stabilizing any traits, just types. There's no incompatibility or orphan problems.

You've missed the most important benefit: if `primitives` is stable, then we can make breaking changes in `bitcoin` and people still don't need to update in sync. And the smaller a crate is the easier stabilization becomes.

> I think it is entirely acceptable to release major versions once every year

I hope the small crates won't break ever. Or like once every 5-10 years.

> are we providing enough benefit to require the whole ecosystem to upgrade.

Let's not force it in the first place

**Comment by tcharding** [comment]
> > 1. Testing: Unit tests have to live with the extension traits and then don't have access to the type internals.
> 
> I don't think they should access internals to begin with. Accessing internals means needless refactorings every time you change the layout. Just test the API. Being forced to use the API in tests can also uncover API problems like missing a fundamental conversion.

Holy fuck, that is a pretty big statement. I would need to read that in a book or from multiple places before I changed my currently held beliefs. I do not, however, claim to be a test expert, and am open to learning. I have duly noted your view but not been convinced.

> > 2. Trait implementations have to live in with the type definition
> 
> Unless they are fundamental to the type (e.g `struct Foo<T: Bar>(T)`) they don't. I don't remember us having any such unstable traits. Impls will be with trait definitions.
> 
> Notice that in the issue I **do not** promise stabilizing any traits, just types. There's no incompatibility or orphan problems.

I'm confused by these statements, the orphan rule, AFAIU, is literally "one cannot implement external traits on external types" - therefor all the external trait impls have to live in `primitives` with the types. What am I misunderstanding?

> You've missed the most important benefit: if `primitives` is stable, then we can make breaking changes in `bitcoin` and people still don't need to update in sync. 

I'm aware of this point :)

> And the smaller a crate is the easier stabilization becomes.

Facetious comment: why not just make the crate empty, then we can stabalize it today.

> > I think it is entirely acceptable to release major versions once every year
> 
> I hope the small crates won't break ever. Or like once every 5-10 years.

I think you are dreaming.

> > are we providing enough benefit to require the whole ecosystem to upgrade.
> 
> Let's not force it in the first place

Again, there is in my mind basically zero chance that we can get it perfect and not need to touch it for 10 years - zero.

**Comment by Kixunil** [comment]
> would need to read that in a book or from multiple places before I changed my currently held beliefs.

Maybe start with an article @dpc wrote: https://dpc.pw/posts/be-warned-tests-are-great-calcifiers/ :)

> all the external trait impls have to live in `primitives` with the types.

Yes and the only traits we'll implement in `primitives` are the stable ones - mostly from `std`/`serde` and a few from `primitives`. We will define our unstable traits and implement them in `bitcoin`, at least temporarily.

> why not just make the crate empty, then we can stabalize it today

Strawman :D I've specifically listed types that multiple crates frequently use in their interfaces and them being unstable is what's causing problems in the ecosystem.

> I think you are dreaming.

Why? There are multiple crates, even bigger than ours, that achieved it. What makes us unable to do it?

> zero chance that we can get it perfect

Of course, even `std` is not perfect and there's a bunch of things I'd do differently. But the commitment to stability is worth those imperfections. Once we stabilize and find something is imperfect, we'll just keep it as-is. At most provide alternatives and deprecate things. If there ever is 2.0 I'd just go with removing all deprecated things.

**Comment by junderw** [comment]
Extension traits seem a bit hairy to me... but I don't think it's too bad.

Needs to be well documented so people can discover them and how to use them properly.

**Comment by Kixunil** [comment]
@junderw do you think it's worse or less bad than being forced to update `bitcoin` version whenever you update some other crate depending on `bitcoin`?

**Comment by romanz** [comment]
> Is this tradeoff good for you?

Yes, thanks @Kixunil!

**Comment by kayabaNerve** [comment]
I don't want my opinion too heavily weighted. I do use the library, yet I was not pinged. I technically offer a library derivative of `bitcoin`, yet AFAIK, it has minimal external use (one wallet may have picked it up for one specific use case?).

`bitcoin` going the `hyper-util` route sounds incredibly annoying. While it would be bearable, I'd probably stay on my current release and wait 6 months to update (when all `bitcoin-util` traits get standardized back into `bitcoin`). I say this as someone who uses the `bitcoin` dependency directly though (and doesn't import other libs using the `bitcoin` library). I completely understand the frustration in waiting for deps to update, and getting the first few to update (starting the trend).

I'd also question if this will not just duplicate the extension crates across a variety of versions (unless those are also regularly updated).

**Comment by Kixunil** [comment]
@kayabaNerve Thanks for your input! While my impression is that so far most people prefer compatibility over a little bit of convenience we'll take in mind that you don't see it that way. And yes, it looks like `hyper-util` is doing exactly what we're trying to do.

> I'd also question if this will not just duplicate the extension crates across a variety of versions (unless those are also regularly updated).

Yes, it will unless those are updated. The argument here is that it's considered less bad than forcing whole-ecosystem update ("libcpocalypse"). Few kB of code/binary and a few seconds of compile time vs re-prioritization of *human* time.

**Comment by tcharding** [comment]
We are currently implementing this strategy, closing the issue since it is no longer needed.
