### ISSUE TITLE
fuzz.sh fails with unbound local variable

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#2924]
```
...
++ find . -type f -name '*,*' -o -name '*:*' -o -name '*<*' -o -name '*>*' -o -name '*|*' -o -name '*\?*' -o -name '*\**' -o -name '*"*'
++ wc -l
+ incorrectFilenames=0
+ '[' 0 -gt 0 ']'
./fuzz.sh: line 13: $1: unbound variable
```

removing `set -euox pipefail`works as a hack

**Comment by apoelstra** [comment]
What shell are you using? I have never seen `$1` be unbound in my life.

**Comment by apoelstra** [comment]
ooo, it's the `set -u` that's doing it. Awesome. But yes, we should fix it to have a better error message.

**Comment by yancyribbens** [comment]
> What shell are you using? I have never seen $1 be unbound in my life.

Nothing fancy, just `bash`.
