### ISSUE TITLE
What to do about our private `prelude` module

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2926]
Issue to bring together discussion on the private `prelude` modules/types.

As we create more crates this keeps coming up. Somewhere Andrew and I discussed just importing the prelude types at the crate root, I then did so in #2908 but Kix didn't like it.

I do not know the best way to proceed.

ref: 

- https://github.com/rust-bitcoin/rust-bitcoin/pull/2908#discussion_r1652239927
- #2892

**Comment by junderw** [comment]
My personal thoughts:

- Q. What should have a prelude?
    - A. Any library that when used always sees the same group of traits and structs and macros get imported at the top of every file.
- Q. What should be included in a prelude once you've decided to make one?
    - A. The cross section of "The items that almost anyone using the crate will want to import" and "Items that do not conflict with the standard edition preludes available. Even if MSRV is low, consideration for all editions currently stable and released should be made."

In our case... I am not sure there are a bunch of things that everyone using rust-bitcoin will import on every file all the time... so a public prelude for users of rust-bitcoin might not make much sense.

But for internal usage, there is probably a lot of things that can be included in a prelude that might make devloping crates in the rust-bitcoin ecosystem easier.

I think most people would agree with my assessment, and the discussion would mostly come down to deciding what goes in.

Let me know if anyone disagrees or has other thoughts.

**Comment by tcharding** [comment]
Thanks for the response @junderw, I've updated the issue description to explicitly state "private", my bad I could have done that initially - this issue is specifically about how to handle the private types we currently have in `rust-bitcoin/bitcoin/src/lib.rs`'s `prelude` module. And by implication potentially every other crate in the repo.

**Comment by Kixunil** [comment]
The reason I complained was that it was **not** private! And it wasn't even a prelude - it was dumped right into the crate root.

`pub(crate)` is fine if you just don't want to import things for `std`/`alloc`. Though I think we could just import `std::prelude::v1::*` (it's a shame `alloc` doesn't have it too).

**Comment by tcharding** [comment]
> The reason I complained was that it was **not** private! And it wasn't even a prelude - it was dumped right into the crate root.

Ah fair point, my bad.

> `pub(crate)` is fine if you just don't want to import things for `std`/`alloc`. Though I think we could just import `std::prelude::v1::*` (it's a shame `alloc` doesn't have it too).

Ahh, and not have to do the feature gate dance? That would be mad, I'll have a play. (Wildcard imports are out these days but I'll see if I can get all the types we want.)

**Comment by Kixunil** [comment]
I think wildcard-importing `std` prelude is also justified and can be another exception. Everyone knows what's there.

**Comment by tcharding** [comment]
Not my wheelhouse, @apoelstra ?

**Comment by apoelstra** [comment]
Yeah, wildcard-importing the std prelude is fine. Rustc already implicitly does something similar which is why `Vec` and `Option` and stuff are always imported.

**Comment by apoelstra** [comment]
And IMO if we can avoid the feature-gate dance with something like this, we should drop the private prelude module entirely and not replace it with anything.

**Comment by jamillambert** [comment]
The `units` crate private prelude module was only referenced by one use statement, so I have removed it entirely.

**Comment by tcharding** [comment]
Seems we are doing ok with `prelude` stuff now, closing.
