### ISSUE TITLE
Readme outdated/contrib/test.sh no longer exists

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#2934]
> To` build with the MSRV you will likely need to pin a bunch of dependencies, see ./contrib/test.sh for the current list.

`contrib/test.sh` no longer exists

**Comment by apoelstra** [comment]
I guess this text should now say something like "you will need to use the versions listed in Cargo-miminal.lock".

I think we would like to actually add a third lockfile -- one is the minimal dep versions, another is most recent MSRV-supported, and the final one would be the most recent versions of everything (and this would be bot-updated I guess).

But for now we should at least update the README.

**Comment by yancyribbens** [comment]
> and the final one would be the most recent versions of everything 

Isn't that just the Cargo.lock produced by running `cargo build` on the stable toolchain?  Is there a reason to keeping that in version control?

> But for now we should at least update the README.

Ack

**Comment by yancyribbens** [comment]
s/keeping/keep

**Comment by apoelstra** [comment]
> Isn't that just the Cargo.lock produced by running `cargo build` on the stable toolchain? Is there a reason to keeping that in version control?
> 

Ideally we'd run it in CI, in which case it needs to be pinned because "whatever you get by running `cargo build`" is constantly breaking.

**Comment by yancyribbens** [comment]
> Ideally we'd run it in CI, in which case it needs to be pinned because "whatever you get by running cargo build" is constantly breaking.

Makes sense.  Will look into it when I have a moment unless someone else does.

**Comment by Kixunil** [comment]
> another is most recent MSRV-supported

What is the purpose of this one?

**Comment by yancyribbens** [comment]
>  What is the purpose of this one?

I'm not clear on the purpose either tbh.  Although from my understanding it's the lock file that has the most recent versions of the deps that will still work with MSRV while the minimal is the oldest versions of deps that will work with MSRV.  I'm not clear on why both are maintained.

**Comment by Kixunil** [comment]
MSRRV/Minimal solves two issues: checks minimal versions and pins the crates. Recent makes sure new library versions don't break us.

**Comment by yancyribbens** [comment]
> Recent makes sure new library versions don't break us.

Don't break MSRV I think?

**Comment by apoelstra** [comment]
> What is the purpose of this one?

Noticing when our dependencies release updates that would break us.

Our current lockfile situation is nice for development, but when I go to use these crates on new projects and cargo pulls in the latest deps, I see a pile of broken dependencies and we no longer have the nice list of required pins.

Having a "actual latest deps" and a "latest MSRV-working deps" lockfile would let me diff these to infer the required pins. (Or more likely, the script that produces the "latest MSRV-working deps" lockfile would have a list of explicit pins in it).

**Comment by Kixunil** [comment]
> Don't break MSRV I think?

I mean if they accidentally release a bug (just like we test nightly).
> Noticing when our dependencies release updates that would break us.

Good point, could be useful. Though it slows down the CI by about 1/3...
