### ISSUE TITLE
Remove `Amount::fmt_value_in`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2952]
This method can now be replaced by `display_in`, which also supports non-default formatting options. This would also allow us removing `Default for FormatterOptions` hopefully preventing formatting issues.

**Comment by apoelstra** [comment]
Yep, SGTM.

**Comment by Kixunil** [comment]
In that case we should deprecate it in 0.1.3

**Comment by Kixunil** [comment]
Deprecated in #2951
