### ISSUE TITLE
Add a `just docs` command

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2965]
Consider adding a `just` command to build the docs. Can check in the `run_task` script for how we do it or base it off of:

```bash
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly rustdoc --all-features -- -D rustdoc::broken-intra-doc-links
```

(Will likely want to use the nightly config file like the rest of the commands though.)

**Comment by apoelstra** [comment]
concept ACK but maybe it should be called `just docsrs` to emphasize that it's creating the docs as they appear on docsrs. Otherwise it is hard to distinguish from `cargo doc` which is just as easy to type and doesn't require nightly.

**Comment by Kixunil** [comment]
Can just pass in the arguments? Being able to type `just docsrs --open` would be nice.
