### ISSUE TITLE
Investigate `scale_by_witness_factor`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#2966]
The function `units::weight::scale_by_witness_factor` is suspicious, see original comment: https://github.com/rust-bitcoin/rust-bitcoin/pull/2957#discussion_r1664462205

**Comment by yancyribbens** [comment]
Isn't this a duplicate of https://github.com/rust-bitcoin/rust-bitcoin/issues/2963?

**Comment by tcharding** [comment]
Duplicate of #2963
