### ISSUE TITLE
CI is failing on `master` branch (semver-checks)

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#2968]
CI is passing for PRs but failing on `master` because it's failing to find a base branch.

I believe it needs to be pulled out of `.github/workflows/rust.yml` into its own file which has `on: pull_request:` but no `on: branches:`. But this is inherently difficult/annoying to test.

**Comment by storopoli** [comment]
Yes, this is a case that we did not test and makes total sense now.
I will do a fix as soon as possible.

**Comment by apoelstra** [comment]
No worries. We hit it every time we try to do clever stuff in CI.
