### ISSUE TITLE
Make `version` in `bip152` an enum

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#2998]
OT but this should be an enum. Honestly last time I looked at this module I didn't like it at all. IIUC it's a literal transaction from C++ Core code, so that's why it's not idiomatic.

_Originally posted by @Kixunil in https://github.com/rust-bitcoin/rust-bitcoin/pull/2987#discussion_r1671571767_

**Comment by shinghim** [comment]
I agree with making this an enum, but in order to do so, it would require a change to the public API from
```rust
pub fn from_block(
        block: &Block,
        nonce: u64,
        version: u32,
        mut prefill: &[usize],
    )
```

to

```rust
pub fn from_block(
        block: &Block,
        nonce: u64,
        version: Version,
        mut prefill: &[usize],
    )
```

Just wanted to double check: Should we deprecate the function with a `u32` version and add a new one?

**Comment by Kixunil** [comment]
> Should we deprecate the function with a `u32` version and add a new one?

I don't think it's worth it.

**Comment by apoelstra** [comment]
For this module, which has never seen much love, I think it's fine to just redo the API entirely.

**Comment by shinghim** [comment]
I think we should still do it with deprecations so we don't further the pains from #3166

**Comment by Kixunil** [comment]
One way to do it is to deprecate the entire module in favor of a new crate that people can opt to use. Then at some point later replace the module with a reexport of the crate.

**Comment by shinghim** [comment]
Okay that makes sense. If someone has the time, could you please create the BIP 152 crate for me? On a related note, is the plan to eventually move BIPs to their own crates where applicable?

**Comment by shinghim** [comment]
> I'd prefer somebody (could be you) would create the repo under their personal org, get it into reasonable shape, and then request to move it into here. If I create an empty repo in the rust-bitcoin org, but I'm not prepared to steward it, there's a risk that it basically dies on the vine and pollutes the org.

Sounds good, I'll start working on that

I think this issue should be able to be closed then since we're going down that path
