### ISSUE TITLE
Semver checks: add `all-features` to `bitcoin_hashes` `bitcoin-units` and `bitcoin-io`

### ISSUE THREAD

**Issue by storopoli** [rust-bitcoin/rust-bitcoin#2999]
> It reproduces the current behavior of cargo-public-api:

Damn, I missed this during review. This claim is not correct. Its missing "all features" for `hashes`, `units`, and `io`.

```bash
# Uses `CARGO` to generate API files in the specified crate.
#
# Files:
#
# - no-features.txt
# - alloc-only.txt
# - all-features.txt
generate_api_files() {
    local crate=$1
    pushd "$REPO_DIR/$crate" > /dev/null

    run_cargo --no-default-features | $SORT | uniq > "$API_DIR/$crate/no-features.txt"
    run_cargo --no-default-features --features=alloc | $SORT | uniq > "$API_DIR/$crate/alloc-only.txt"
    run_cargo_all_features | $SORT | uniq > "$API_DIR/$crate/all-features.txt"

    popd > /dev/null
}
```

Was there a reason for this @storopoli?

_Originally posted by @tcharding in https://github.com/rust-bitcoin/rust-bitcoin/issues/2946#issuecomment-2218874937_

**Comment by apoelstra** [comment]
I had to double-check -- to be clear, this issue is quite different from #3001 which looks similar.

**Comment by Kixunil** [comment]
@apoelstra funnily enough I got the idea after seeing this issue. :)

**Comment by storopoli** [comment]
Yes, it is different. This does not cross-check the features flags against each other like #3001 but rather cross-check against target branches. This was an unfortunate mishap on my end, and it should have been fully addressed when we replaced `cargo-public-api` for `cargo-semver-checks`.
