### ISSUE TITLE
`hashes` features are confusing

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3005]
Non-urgent, slightly annoying issue. I just wasted half an hour going round in circles (TL;DR is the last line of text below).

There is a general problem with our MSRV that we can't use conditional features. This leads us to add features trying to bandaid over this problem (eg, `rand-std`) for optional features.

The `hashes` crate features are additionally confusing because of the `io` feature:
- `io` enables optional dependency `bitcoin-io`  
- `std` enables `bitcoin-io/std` - seems reasonable because if one has `std::io` then they want `bitcoin-io`
- `alloc` does not enable `io`

So are users have to add a dependency to their projects on `bitcoin-io` and enable `alloc` to use `alloc` and `io` together in `hashes` - that is ~shit~ unergonomic.

However if a user wants `hashes/alloc` _without_ io they can do so.

- Is the common use case `alloc` _with_ `io`? 
- Should we have `alloc-io`? 
- Should we change features to have `alloc` enable `io` and add `alloc-no-io`? 
- Should be throw our hands up in the air and just accept features are a total mess?

**Comment by apoelstra** [comment]
My vote is that we should exhaustively enumerate all the possibilies. It seems like there should be 6 (std/alloc/no times io/no).

In general I would not advise this but because hashes is so low-level and because the matrix is reasonably small I think it's ok.

**Comment by Kixunil** [comment]
I'd prefer we just remove our dependence on `<hashes::*::Hash as bitcoin_io::Write>` and remove the `bitcoin-io` dependency entirely. I've never liked using fallible writer API to write to hashes which cannot fail and have `.expect("hashes don't fail")` sprinkled in the code. For sighashes we can just require the `HashEngine` trait rather than `io::Write`. I think most people just hash directly anyway?

**Comment by apoelstra** [comment]
@Kixunil it's very commonly useful to want to hash exactly the set of data that you're `io::Write`ing to an actual file. Having `HashEngine` implement `io::Write` makes this possible.

Maybe we should stop doing this in rust-bitcoin (though if you try to remove this you'll see what a PITA it is to need to duplicate all your writing code) but I don't want to lose support for it.

Users can emulate this of course by making their own `HashWriter` object which holds a hash engine implements `Write` by passing through to it. What if we provided such a type in `io`, inverting the dependency?

**Comment by Kixunil** [comment]
> What if we provided such a type in `io`, inverting the dependency?

That sounds good. Also I think we can keep the `std` impl since there's no feature confusion.

**Comment by apoelstra** [comment]
Yep, I believe you're correct about `std`, which will be helpful for people who aren't steeped in our nostd stuff.

**Comment by tcharding** [comment]
With Rust 1.63 this issue became stale.
