### ISSUE TITLE
hashes: Use `u64` for hash engine length

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3016]
In hash engines the `length` field is the number of bytes hashed, since this can be any arbitrary number a `u64` might be a better type for the field.

Original comment: https://github.com/rust-bitcoin/rust-bitcoin/issues/2918#issuecomment-2189879901

**Comment by tcharding** [comment]
Also consider re-naming the field to `bytes_hashed` or something like that? (My idea, needs concept ack from others.)

**Comment by apoelstra** [comment]
Concept ACK. We should also add a public accessor.

`bytes_hashed` would definitely be clearer, because the SHA2 spec speaks in terms of bits while implemtors typically speak in terms of bytes, so there's a potential ambiguity.
