### ISSUE TITLE
semver job is failing intermittently on master

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3018]
I haven't been keeping up closely with the semver check work and I'm shit at github actions, so plesae excuse the lack of digging.

See #2981 for an example, I'm not sure what to do about it.

And the failing job run: https://github.com/rust-bitcoin/rust-bitcoin/actions/runs/9900867629/job/27356464269?pr=2991

**Comment by tcharding** [comment]
cc @storopoli

**Comment by Kixunil** [comment]
Looks like a permission problem.

**Comment by tcharding** [comment]
Cool, thanks @storopoli.
