### ISSUE TITLE
Revert #2585

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3025]
As discussed in #2922 consider reverting #2585

**Comment by yancyribbens** [comment]
Originally posted by @apoelstra  in https://github.com/rust-bitcoin/rust-bitcoin/pull/2922#issuecomment-2197572648

> On further thought I think we should just revert the deprecation and drop the new `to_bytes`, since it's so controversial.

**Comment by tcharding** [comment]
Is this issue still wanted, or are we sticking with `to_bytes`? I personally don't have a view, just going through issues trying to clean up.

**Comment by yancyribbens** [comment]
> Is this issue still wanted, or are we sticking with to_bytes? I personally don't have a view, just going through issues trying to clean up.

Yes, it seems like myself, @Kixunil and @apoelstra agreed in the linked comment above that reverting this to be `to_vec()` instead if `to_bytes()` is desired.

**Comment by tcharding** [comment]
Excuse me for being brain dead, so we want to remove all instances of `to_bytes` and use `to_vec` instead - is that what this issue implies?

**Comment by apoelstra** [comment]
Yeah. Though we should ofc do a deprecation cycle on anything that has been published (and probably backport the deprecation to the 0.32.x crates).

**Comment by tcharding** [comment]
No sweat, cheers.
