### ISSUE TITLE
Check all re-exports are as desired

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3038]
We should check and double check the re-exports in `bitcoin` and  `primitives`. Discussion/consensus will hopefully be reached on #3037

**Comment by tcharding** [comment]
For error type re-exports please also see #3068

**Comment by tcharding** [comment]
I don't know how to action this fully, may be closed by #3551.

**Comment by apoelstra** [comment]
Yeah, let's close this. It's not a big deal anyway because the only failure mode we're likely to find is that we forgot some re-exports, and we can easily add them in point releases as we find them.
