### ISSUE TITLE
Update `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by jamillambert** [rust-bitcoin/rust-bitcoin#3053]
There have been discussions in the past that get brought up again by new devs potentially causing people to have to repeat themselves or waste time doing unnecessary reviews.  For example `expect` messages in #3019.

Updating `CONTRIBUTING.md` to describe what has already been discussed and agreed will help new devs know what is accepted, and others to have somewhere to point to when saying this has been discussed before.

**Comment by tcharding** [comment]
Thanks man. To close this issue I would imagine more than just a simple text edition relating the the `expect` thing. I would expect (pun intended) some thought goes in to how do we solve this problem when it comes up again and how do we solve it in a way that is maintainable.

**Comment by storopoli** [comment]
Oh you want the long version that explain the rationale behind it?

Makes sense...

**Comment by tcharding** [comment]
I didn't mean that I meant just to say this is IMO not a matter of just writing "don't use ... use ..." . I think we should have some long term strategy for this and other policy things. I don't want to write more ideas because I don't want to think of them just now, I'm just flagging it because sometimes seemingly easy issues get picked up and just "closed" in the easiest way possible.

**Comment by Kixunil** [comment]
> Oh you want the long version that explain the rationale behind it?

I both kinda want and don't. I want because then people will know we do things for a reason and will have to bring new arguments if they want change but also it's a ton of work and ton of noise. We could write rationale in different document(s) or use `<details>` to hide it by default.

**Comment by tcharding** [comment]
To further help with this sort of thing I added a "policy" label, PRs and issues that contain discussion/consensus on policy decisions can then be labeled as such and new devs can filter by the label.
