### ISSUE TITLE
Remove `From<bitcoinconsensus::Error> for BitcoinconsensusError`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3060]
If #3039 merges and after transaction moves to `primitives`, remove the `From` impl so that `bitcoinconsensus` stays out of the public API.

**Comment by apoelstra** [comment]
concept ACK, since it looks like this is only used in one place (and IMO `.map(BitcoinconsensusError)?` would be clearer than just `?`).

Though in general, @Kixunil do you think it's ok to keep these impls if we stick `#[doc(hidden)]` on them?

**Comment by Kixunil** [comment]
> do you think it's ok to keep these impls if we stick `#[doc(hidden)]` on them?

No because using `?` by accident is too easy.

But I've wrote elsewhere that I don't think validation should go to primitives (at least not now) so this is not urgent.

**Comment by tcharding** [comment]
Oh did, damn I thought  I dug through the messages and that was what was suggested. I'll dig some more.

**Comment by tcharding** [comment]
This is stale, there is no `From` impl currently on master in the `consensus_validation` module.
