### ISSUE TITLE
Should `Hash::const_hash` be public

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3063]
`sha2561::Hash::const_hash` is only used in our repo in the function `Midstate::hash_tag`.

It is assumed (by me) that users are only using all the `Midstate` stuff to create do do tagged hashing and for that they would likely use `Midstate::hash_tag` directly.

Said another way, `Hash::const_hash` looks like its a helper function for use in `Midstate::hash_tag`, is there any real use case for it or should we make it private.

**Comment by apoelstra** [comment]
Yes, there are real usecases for people having hashes that they can compute at compile time. Defining constants for things like the genesis hash, for example.

I think that, other than maybe the name, it's fine to stabilize it.

**Comment by tcharding** [comment]
Aight, thanks.

**Comment by Kixunil** [comment]
> I think that, other than maybe the name, it's fine to stabilize it.

Ideally, `&mut` references and platform intrinsics would be `const` and we wouldn't need it at all. Maybe in 20 years.
