### ISSUE TITLE
Re-exporting error types

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3068]
What exactly is going to be our policy on re-exporting error types. This issue relates to error types return by public functions. Inner errors are explicitly out of scope for this issue.

Example:

In crate `unites` module `foo` contains a type and an error eg `units::foo::{Foo, FooError};`

In `primitives` if we decide to re-export `Foo` at the crate root should `FooError` also be re-exported?

Furthermore are any exceptions allowed or should this be a hard policy?

Note, that in d242125ae I claimed that `parse::ParseIntError` was "special" and should be re-exported. I no longer stand by this claim.

Note please I personally do not have a super strong personal opinion on this issue - I'd just like to see some clarity.

**Comment by Kixunil** [comment]
IMO `primitives` should mirror the structure of `units` and add things on top of it. Just like `alloc` is same as `core` plus some additional items and `std` is even more things on top of it.

**Comment by tcharding** [comment]
Thanks, with this in mind I did #3069,  then we can move towards the goal you describe.

**Comment by tcharding** [comment]
Consensus reached.
