### ISSUE TITLE
Use of wildcard in re-exports

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3070]
## Context

1. We have a policy to not use wildcards with allowed explicit exceptions.
2. In https://github.com/rust-bitcoin/rust-bitcoin/issues/3068#issuecomment-2231892745 it was suggested that `primitives` should mirror `units` as `std` mirrors `core`.

To achieve (2) there are at least options, assume we have `units::foo::{foo, FooError}` in `primitives/lib.rs` do:

a. Add a module
```rust
pub mod foo {
    // Re-export everything from `units::foo`
}
```

b. Use a `pub use` statement
```rust
pub use units::foo;
```

(a) is needed when we are adding additional things, (b) works when we are just re-exporting without adding anything.

## Question

This issue relates to the re-export in (a).

Should we use a wildcard?

Pros: 
- Saves us making mistakes and missing something
- Is easier to maintain when we update `units::foo`
- Saves going through `units::foo` manually and finding all the public types (error prone and annoy to do)

Cons:
- its opaque, harder to grep for things, may be confusing to editors and/or readers of the code

**Comment by tcharding** [comment]
This issue was motivated by the mistake fixed by https://github.com/rust-bitcoin/rust-bitcoin/pull/3037/commits/439813589efc2f2318b196aa5106602c495b7f83

**Comment by apoelstra** [comment]
I think that in the pattern

```
pub mod foo {
    pub use foo:*;
}
```

Wildcard imports are the least-bad solution.

**Comment by tcharding** [comment]
Locking it in! Thanks
