### ISSUE TITLE
Document `const_hash` is unfinalized

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3075]
If #3074 merges replace `const_hash` in this issue with `hash_unoptimized`.

The `Hash::const_hash` function does not finalize the hash by inputting zero bytes as done in `Hash::from_engine`, is this a big deal, should it be documented in the function docs?

**Comment by apoelstra** [comment]
Yes, it is a big deal if `const_hash` is only computing a midstate and not actually producing a hash. Its name should be changed to reflect that.

**Comment by tcharding** [comment]
Oh name change again? Not to `hash_unoptimized` but to something more outlandish like `hash_unfinalized_unoptimised` you mean?

**Comment by Kixunil** [comment]
To avoid confusion we have two `const_hash` methods. The one on `Hash` finalizes, the on on `Midstate` obviously doesn't. So we only need to change that one.

However I wander how do we reflect it naturally. `pre_hash`? `hashing_slice`? I think `unfinalized` is weird to have on `Midstate` but also the name could be slightly different, if not for other benefits, at least to avoid people having to mention which type it is. :)

**Comment by apoelstra** [comment]
I propose `hash_unoptimized` and `compute_midstate_unoptimized` .

**Comment by Kixunil** [comment]
Damn, I've just remembered I said the wrong thing. `Midstate::const_hash` has a parameter whether to finalize it or not (OK, that's quite weird) and is private. It really shouldn't be a method on `Midstate` with that argument but a free-standing one. We could add more methods to `Midstate` accepting slices of 64-byte arrays but that's probably not super important.
