### ISSUE TITLE
Rename `hash` to `hash_bytes` or just leave it as is

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3078]
We are overhauling the `hashes` API, in doing so we have done

- #3049
- #3076
- #3077

Which give use `hash_chunks`, `hash_str`, `hash_reader` functions. We also have plain old `hash` to hash bytes. In #3049 we discussed re-naming to `hash_bytes` but no consensus was reached. This issue is to ~argue~ debate the rename.

**Comment by apoelstra** [comment]
I think we should leave it as-is. This would minimize breakage; `hash` is not a bad name despite the asymmetry, and I also think that hashing a small byte-slice is the most common use case for a hash function.

**Comment by Kixunil** [comment]
> the most common

I'm not sure I'd say that but it's at least sufficiently common to justify shorter name. I agree with keeping it.

**Comment by tcharding** [comment]
Consensus!
