### ISSUE TITLE
Should we cut a release of `units`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3095]
There have been a few improvements to `units` since last release (22 days ago)

https://github.com/rust-bitcoin/rust-bitcoin/pulls?q=is%3Apr+is%3Aclosed+label%3AC-units

Specifically the new `BlockHeight` and `BlockTime` are unreleased as noticed in #3024

Should we cut a release?

**Comment by Kixunil** [comment]
I was thinking about it and I think it'd be nice. Note that I still want some breaking changes to `units` before it hits 1.0.

**Comment by apoelstra** [comment]
Sure, let's go for it. And yes, this does not indicate stabilization :).
