### ISSUE TITLE
Separate the crate into several crates

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#31]
It'd be beneficial for people to not have to download and compile whole crate if they only need to work with part (e.g. transactions).

I'm willing to help with that.

**Comment by apoelstra** [comment]
I think this is a reasonable thing to do, though I'm not sure how best to separate things. My uses tend to use pretty-much the whole crate except for the network/p2p stuff. Can you make a PR?

**Comment by Kixunil** [comment]
OK, do you want to have them in the same repository, just separate crate?

My thinking for now: Things that may be reasonable to use without the blockchain/txses (addresses, base58, coin amount - not a separate type now but it may be good idea to create one), transaction-related data, blocks, network.

**Comment by apoelstra** [comment]
Yes, same repo, just different crates.

From the network crate, the `Network` enum is constantly useful (for distinguishing between testnet and mainnet) and is used frequently with the address structures. In turn the address structures heavily depend on the script de/serialization, which depends both on transaction-related data and on the consensus serializer (which is also in the network module IIRC).

**Comment by Kixunil** [comment]
OK, I'll look at it during the weekend.

BTW any plans to add support for SegWit addresses? As far as I see it isn't there yet.

**Comment by apoelstra** [comment]
Yes, I plan to add bech32 support after Core does, both so I can be sure everything is finalized, and because it will give me an easy way to generate a ton of test vectors :)

**Comment by apoelstra** [comment]
I'm going to close this because it doesn't have any clear success condition. We have plans for some specific modules (contracthash stuff, anyway) to be pulled out of rust-bitcoin.
