### ISSUE TITLE
Contribution back witness helpers

### ISSUE THREAD

**Issue by D4nte** [rust-bitcoin/rust-bitcoin#313]
We have a [library](https://github.com/comit-network/comit-rs/tree/master/vendor/bitcoin_witness) that provides a number of helpers to facilitate the creation of transactions that spend (witness and normal) outputs, whether it [creates the witness to spend a P2WPKH Output](https://github.com/comit-network/comit-rs/blob/916b5348ed78be61b5b7a33fbc36bbec9bf6d596/vendor/bitcoin_witness/src/p2wpkh.rs#L28)
or help you [sign transactions](https://github.com/comit-network/comit-rs/blob/916b5348ed78be61b5b7a33fbc36bbec9bf6d596/vendor/bitcoin_witness/src/primed_transaction.rs#L107).

Please note that we have planned improvements for the existing code (e.g. use the new `Amount` types).

Do you think that porting this code to `rust-bitcoin/rust-bitcoin` would bring any value? Would there be a more appropriate project under the `rust-bitcoin` umbrella that could benefit from this?

**Comment by stevenroose** [comment]
Hmm, @apoelstra has been working on rust-miniscript for the last year that would probably make it a lot safer to create tx witnesses and be compatible with more script types.

The idea is that we would use rust-miniscript to finalize a PSBT that has all the signatures. Those signatures could be added to the PSBT through various means. rust-miniscript can also help figure out signatures from which keys are relevant for a PSBT input.

So I think a signing flow would involve something like this:

1. create tx you want to create (define outputs and fund with owned inputs)
2. create a psbt from this tx and provide the previous txs or outputs
3. for each of the psbt inputs, go over all the relevant keys and generate a signature if the private keys is available; add the signatures to the PSBT
4. finalize the PSBT and turn it into a signed tx

Steps 3 (the part to get the relevant keys) and 4 are currently not possible but will be with rust-miniscript.

**Comment by apoelstra** [comment]
Yes, rust-miniscript can do this. I really do not want one-off templates in rust-bitcoin.

**Comment by D4nte** [comment]
rust-miniscript it is, we'll give a try. Thanks!
