### ISSUE TITLE
Inspect uses of `vec!` macro

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#3132]
IME the `vec!` macro is abused when it's not needed way too much in this crate (and maybe in general) leading to worse code. There are often better alternatives - like using arrays or `Vec::with_capacity` without zeroing.

`rg 'vec!'` and inspect which calls make sense.

FTR there will be a bunch in tests which don't matter that much but I think it may be simpler to fix those as well so we don't have to think about it and we can almost-ban `vec!` usage. Also there's one in `Witness` which I removed in `push_decode` PR so don't waste time touching it.

**Comment by leichak** [comment]
Not sure whether I should apply for contributing (before my first contribution, have not found that information) but I opened PR for that issue.

**Comment by tcharding** [comment]
We use the system first come first served, just start hacking and raise PRs.

**Comment by shinghim** [comment]
Looks like this was fixed in #3167
