### ISSUE TITLE
`sha256t_newtype!` shouldn't implement `GeneralHash`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#3135]
`GeneralHash` is already implemented by the inner type so this is not needed and allows hashing arbitrary bytes which is not desired.

**Comment by apoelstra** [comment]
Thanks for opening the issue. This is a followup from https://github.com/rust-bitcoin/rust-bitcoin/pull/2910 but I don't think we were tracking it.

**Comment by apoelstra** [comment]
Actually, I'm unsure about this. In principle a tagged hash is just a "sha256 with a different IV". So it *is* a general hash.

We currently don't have a type for "sha256 with a different IV". This I believe would come out of https://github.com/rust-bitcoin/rust-bitcoin/issues/1552. So `sha256t_hash_newtype` is sorta doing double-duty by defining both a general-purpose tagged hash and newtyping it.

**Comment by Kixunil** [comment]
> We currently don't have a type for "sha256 with a different IV"

We do: `sha256::Hash<Tag>`

**Comment by apoelstra** [comment]
Ah, you mean `sha256t::Hash<Tag>`, but yep! Ok, great.

Now I'll need to investigate whether we even want a `sha256t_newtype` which is different from the ordinary newtype macro. It may be we want to just replace it with the new impl_bytelike_traits macro from https://github.com/rust-bitcoin/rust-bitcoin/pull/2861 or something.

**Comment by Kixunil** [comment]
It also defines the tag. Maybe we should have a separate macro for the tag and let people manually convert the bytes for now.

**Comment by apoelstra** [comment]
Yeah, I think we should separate the macro that defines the tag (and precomputed engine and anything else we might like for `sha256t::Hash<tag>`) from the macro that defines a newtype (which can just be `impl_bytelike_traits`.
