### ISSUE TITLE
Lint warnings in `msrv` job

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3149]
Running `RUSTUP_TOOLCHAIN=1.63.0 run_task msrv` (assuming you have [`run_task`](https://github.com/rust-bitcoin/rust-bitcoin-maintainer-tools/blob/master/ci/run_task.sh) in your path) gives the following warnings:

 
```bash
warning: use of deprecated associated function `crypto::ecdsa::Signature::to_vec`: Use to_bytes instead
   --> bitcoin/src/psbt/serialize.rs:156:43
    |
156 |     fn serialize(&self) -> Vec<u8> { self.to_vec() }
    |                                           ^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: use of deprecated associated function `crypto::taproot::Signature::to_vec`: Use to_bytes instead
   --> bitcoin/src/psbt/serialize.rs:250:43
    |
250 |     fn serialize(&self) -> Vec<u8> { self.to_vec() }
```

**Comment by yancyribbens** [comment]
This is the same issue I believe as: https://github.com/rust-bitcoin/rust-bitcoin/issues/3025 see also https://github.com/rust-bitcoin/rust-bitcoin/pull/2922

**Comment by yancyribbens** [comment]
In particular, I think we want to revert https://github.com/rust-bitcoin/rust-bitcoin/pull/2585

**Comment by tcharding** [comment]
Ah yes, I think you are correct.
