### ISSUE TITLE
Remove `From<T> for Target` from `pow` unit tests module

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3160]
Currently we implement a couple of `From` imlps in unit tests for `Target`, this is strange because it begs the question of why we use the `From` trait in test code only and not for real.

- Add a test specific function that is explicitly for converting a test case `u64` to a `u256` (or `Target` / `Work`).
- Remove the `From` and `Into` impls from the `tests` module

**Comment by tcharding** [comment]
I don't know why I opened this and I don't see why its a problem to have the `From` impls.

**Comment by apoelstra** [comment]
It's only a problem in that it looks super weird. I would still like to drop them.

But sure, I'm fine with leaving this issue closed if you don't think it's a big deal.

**Comment by tcharding** [comment]
We could throw a comment on them saying "working with u256s in test code is a PITA so we just use u64s in a bunch of places"

**Comment by apoelstra** [comment]
That'd be fine. Though it's still weird to use the `Into` trait for this instead of using an ad-hoc test function name.

**Comment by tcharding** [comment]
Oh I understand your position now, good point, lets stop using `From` and use a custom named function.

**Comment by tcharding** [comment]
Re-opened attempted to better describe the issue - thanks for you patience.
