### ISSUE TITLE
`bitcoin_hashes` fails to build without `std` flag if `bitcoin-io` has `std` flag

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-bitcoin#3165]
I think the bug is in bitcoin-io, but its not entirely clear how to solve it...

**Comment by tcharding** [comment]
I rekon we shouldn't bother trying to fix this, if any crate enables `std` then I rekon we leave it up to the user to realize they have to enable `std` everywhere. From my understanding, `cargo` isn't clever enough to handle this gracefully.

**Comment by apoelstra** [comment]
If we are going to take that policy then we could put the blanket impl on `io::Read` back into `bitcoin-io`. But I'm not convinced that we should. I think our features should be properly additive. Otherwise as we add more API-checking tooling we're going to need to add a bunch of special-case CI logic to deal with it.

**Comment by apoelstra** [comment]
It looks like the solution is to just feature-gate the macro calls in `bitcoin_hashes` (on the `std` feature of `bitcoin_hashes`).

Which sucks because the macro is *already* gated on the `std` feature of `io`...but such is the nature of macros.

**Comment by Kixunil** [comment]
I believe the solution is to add hidden reexport of `std` and refer to that one in the macro. And make sure the macro is itself gated on `std` to add or not add the impl and not emit any `cfg` from it. I believe this applies to all other macros involving `std` or `alloc`.

That being said "enable `std` everywhere xor nowhere" should be a general recommendation that's not unreasonable since we have weak dependencies.

**Comment by apoelstra** [comment]
> again this is literally _the_ reason `bitcoin-io` exists at all

Yes, let's please keep this in mind. If we have `bitcoin-io` but you also have weird quirks and edgecases that you have to memorize, then we have the worst of both worlds.

**Comment by Kixunil** [comment]
> its totally possible that, in the future, someone crates some half-assed platform (or mrustc does or whatever) that only supports the `std::io` parts of `std` and wants to only turn on the `bitcoin-io` `std` feature and not the `bitcoin` one.

That sounds more like `std` feature shouldn't exist and there should be only fine-grained features. That'd be definitely cleaner but I'm not happy about the blowup of features. Still it may be lesser evil. Or maybe `std` should just enable all sub-features. To be clear, I'm not really opposed to the idea. If we apply it consistently. Though hopefully we won't have many of these features.

**Comment by tcharding** [comment]
I just inadvertently fixed this while doing https://github.com/rust-bitcoin/rust-bitcoin/pull/3128

Tested with 

```
[dependencies]
bitcoin_hashes = { version = "0.14.0", default-features = false, features = ["bitcoin-io"] }
bitcoin-io = { version = "0.1.2", default-features = false, features = ["std"] }
```

```rust
use bitcoin_hashes::{sha256, GeneralHash as _};

fn main() {
    let mut engine = sha256::Hash::engine();
    bitcoin_io::Write::write(&mut engine, b"some data").expect("write failed");
    let _ = sha256::Hash::from_engine(engine);
}
```

**Comment by tcharding** [comment]
Can verify that the above fails but if we patch the manifest it works

```

[patch.crates-io.bitcoin_hashes]
path = "/home/tobin/build/github.com/tcharding/rust-bitcoin/08-06-hashes-impls/hashes"

[patch.crates-io.bitcoin-io]
path = "/home/tobin/build/github.com/tcharding/rust-bitcoin/08-06-hashes-impls/io"

[patch.crates-io.bitcoin-internals]
path = "/home/tobin/build/github.com/tcharding/rust-bitcoin/08-06-hashes-impls/internals"
```

**Comment by tcharding** [comment]
This is fixed on master, I'm going to close but wanted to flag that I don't know if we want a fix to this backported or if doing so is even possible.
