### ISSUE TITLE
`private_key_debug_is_obfuscated` test is in the wrong crate

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#3186]
This test belongs to `secp256k1`, not `bitcoin`. The current situation is fragile and annoying.

**Comment by tcharding** [comment]
We can probably delete the tests if https://github.com/rust-bitcoin/rust-secp256k1/pull/722 merges.

**Comment by mahmudsudo** [comment]
can i take on this issue ?

**Comment by diogocanut** [comment]
> We can probably delete the tests if [rust-bitcoin/rust-secp256k1#722](https://github.com/rust-bitcoin/rust-secp256k1/pull/722) merges.

It looks like the PR has been merged, so now it's just a matter of removing `private_key_debug_is_obfuscated`?

**Comment by apoelstra** [comment]
Yep, let's do it.

**Comment by shinghim** [comment]
Looks like this is can be closed - fixed by #3517

**Comment by tcharding** [comment]
Thanks man, its rad that you notice these things.
