### ISSUE TITLE
primitives: Do not enable additional features in `serde` feature

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3197]
We should ~immediately start working on~ think about removing the enabling of `alloc` feature in `serde` feature.

**Comment by shinghim** [comment]
For code that currently assumes `alloc` is enabled with `serde` such as:
```rust 
#[cfg(feature = "serde")]
use crate::prelude::ToString;
```

where `crate::prelude` is:
```rust
mod prelude {
    #[cfg(feature = "alloc")]
    pub use alloc::collections::{BTreeMap, BTreeSet, btree_map, BinaryHeap};

    #[cfg(feature = "alloc")]
    pub use alloc::{string::{String, ToString}, vec::Vec, boxed::Box, borrow::{Borrow, BorrowMut, Cow, ToOwned}, slice, rc};

    #[cfg(all(feature = "alloc", target_has_atomic = "ptr"))]
    pub use alloc::sync;
}
```

Is the goal to split `alloc` out of this, and then enable it with the `alloc` flag separately?
```rust
#[cfg(feature = "alloc")]
#[cfg(feature = "serde")]
use crate::prelude::ToString;
```

**Comment by tcharding** [comment]
No, the aim of this PR is to remove the `alloc` from the `serde` dependency

```rust
serde = ["dep:serde", "hashes/serde", "internals/serde", "units/serde", "alloc"]
```

Currently doing so makes this command fail: ` cargo check --no-default-features --features=serde`

**Comment by apoelstra** [comment]
FWIW I agree with the spirit of this PR but I'm pretty skeptical that it'll be possible. Especially getting rid of the `hex` dependency.

**Comment by tcharding** [comment]
I updated the stale issue description. `hex` is not optional now.

**Comment by apoelstra** [comment]
Sounds good -- though I still think this'll be a long haul, since we often decode hex-encoded variable-size objects and serde gives us no way to "stream" characters or bytes.

**Comment by tcharding** [comment]
I'm actually going to close this. The issue is not good for a newer contributor and I personally hate working on any serde related code (review or dev). Finally this is low priority, there are so many more important things to do.
