### ISSUE TITLE
Reduce `alloc` requirements due to `ParseIntError`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3213]
A part of the `alloc` requirements in `units` is the `ParseIntError` and its inner `String` field. Are we open to using [`arrayvec::ArrayString`](https://docs.rs/arrayvec/latest/arrayvec/struct.ArrayString.html) for the field or NIH'ing something similar into `internals`?

Or did you have a plan already @Kixunil?

**Comment by Kixunil** [comment]
We cannot use `ArrayString` as we don't know the (maximum) length of the input so for all intents and purposes it's `usize::MAX / 2` and we cannot make the array that big.

Just stick with the `InputString` design I made a long time ago. What's the problem?

**Comment by apoelstra** [comment]
Yeah, in this case `InputString` is the right way to go.

It is a litttttle tempting to try to do something like showing "up to 30 characters of context" or something. And in that case we could use a fixed array. (In fact maybe we should do this even in the `alloc` case to avoid having error displays with massive outputs?)

**Comment by apoelstra** [comment]
I think there are probably two cases where `ParseIntError` is hit:

* The user provides a legitimate number with a typo or invalid notation or something, in which case even a small-ish context window would easily show the whole number
* The user tries to accidentally tries parse something else, which might be any random crap such as a massive string, and would prefer to have enough context to recognize the bug/mistake but not be overwhelmed with data.

**Comment by Kixunil** [comment]
> It is a litttttle tempting to try to do something like showing "up to 30 characters of context" or something.

Somewhat good idea but that blows up error sizes which is undesirable for perf reasons if the type you're returning is significantly smaller. (So this makes sense to do for hashes where we can show about half of the input without perf loss.)

Maybe have an alternative to `InputString` for large types and a feature to enable large buffer (would be great if we could set it somehow) regardless for debugging purposes.

> In fact maybe we should do this even in the `alloc` case to avoid having error displays with massive outputs?

> The user tries to accidentally tries parse something else, which might be any random crap such as a massive string, and would prefer to have enough context to recognize the bug/mistake but not be overwhelmed with data.

Good point, just note that if there's a typo in a large input and we don't know if the user has several inputs that only differ in certain parts then we might not show enough.

For types which we know maximum reasonable size of this makes a lot of sense. Maybe I wouldn't do it for hex parsing of `Transaction` but in that case the only possible errors are ones we know location of - so if we're going to truncate it we should show it like this: 

```
input: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadeadbeefsatoshibbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
reported: "...deadbeefsatoshibbbbbbbb..."
input: "satoshiaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
reported: "satoshiaaaaaa..."
input: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasatoshi"
reported: "...aaaaaasatoshi"
```

(The character counts are for illustration purpose only and do not represent length constants that I'm proposing.)

I guess where this fails is when you have an application that takes multiple similar inputs and you accidentally swap parameters then you don't immediately see which parameter is the swapped one but that's likely rare. Also if you're inputting the same value to multiple parameters for some reason anyway then nothing like this will help you at all and you need help from higher layers.
