### ISSUE TITLE
`bip32` deprecated type alias naming screw up

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#3244]
The type aliases ended up being name Extende**n**d rather than Extended. :man_facepalming: 
We now need to add correct ones in addition to the incorrect.

**Comment by apoelstra** [comment]
In what repo do you see that typo?

**Comment by tcharding** [comment]
We forgot to backport #2693, done in #3246 and #3247

**Comment by Kixunil** [comment]
@apoelstra `bitcoin::bip32::ExtendendPublicKey` latest released version.

**Comment by tcharding** [comment]
Clearly the new `port-` labels didn't work as we'd hoped.

**Comment by tcharding** [comment]
Another attempt made in #3251 and #3252

**Comment by tcharding** [comment]
We fixed this and backported it already.
