### ISSUE TITLE
`signed_msg_hash` should probably accept `impl AsRef<[u8]>`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#3249]
It's really strange that the method enforces UTF-8. Maybe it's standard for message to be UTF-8 which is understandable but at least verification might want to skipt the UTF-8 check if the signature means "trusted".

Am I missing something?

**Comment by apoelstra** [comment]
Sure, we can accept non-UTF8 strings. It's a simple natural thing to support.

But honestly I doubt that there's any consistency in tooling that supports this basically-deprecated protocol, and I doubt anybody is trying to sign non-ASCII stuff because they can't assume it'll validate.
