### ISSUE TITLE
`Psbt` no longer supports decoding from reader

### ISSUE THREAD

**Issue by elsirion** [rust-bitcoin/rust-bitcoin#3250]
Before 0.30 the `Psbt` struct implemented `Decodable`, which can read the correct number of bytes from a `Read` object. [The new `deserialize` function](https://docs.rs/bitcoin/latest/bitcoin/struct.Psbt.html#method.deserialize) requires you to know the length of the data you will be decoding (takes `&[u8]` as argument) and doesn't allow direct reading anymore.

In Fedimint this breaks reading from our DB since we used the `Encodable` impl to serialize `Psbt`s and never saved the length of that field (https://github.com/fedimint/fedimint/issues/5202). We'll likely end up copying the old `Decodable` code and doing a DB migration that adds a length field.

**Comment by apoelstra** [comment]
We should fix `deserialize` to take a generic `Read` and backport that.

**Comment by apoelstra** [comment]
I guess we probably can't change `&[u8]` to a `R: Read` in a non-breaking way but we should be able to add a method somewhere.

**Comment by Kixunil** [comment]
> I guess we probably can't change `&[u8]` to a `R: Read` in a non-breaking way

We can but only in the same way the recent Rust break was allowed - you might be required to annotate types to help inference. I'm not sure if we want to do that. But moving the impl to `deserialize_from_reader` and calling directly from `deserialize` wouldn't be too bad.

**Comment by elsirion** [comment]
@tcharding after working on this for a bit now I'd much appreciate if a streaming deserialization function could be put back into rust-bitcoin. Too many of the functions used to implement `deserialize` are private, so I ended up copying and adapting many of them recursively and no end is yet in sight.

I opened #3255 as my take on the problem.

I also noticed rust-bitcoin is enforcing `BufRead` now, that will be a bit of a pain to work around/adapt to, we either create a fake buffered reader that has 1byte buffer size (to not over-read and lose bytes deep inside the deserialization tree) or need to change our own consensus encoding to use `BufRead` everywhere.

**Comment by Kixunil** [comment]
> so I ended up copying and adapting many of them recursively and no end is yet in sight.

Also why do you need these? Shouldn't just deserializing the entire PSBT be enough?

**Comment by elsirion** [comment]
> Shouldn't just deserializing the entire PSBT be enough?

The old PSBT deserialization code knew how many bytes to read, we don't know where the PSBT ends and other fields start in our serialized structs, the new code needs a byte slice as input, which we can't provide.

**Comment by apoelstra** [comment]
It sounds like we should really get #3173 in.

**Comment by Kixunil** [comment]
@apoelstra I have a plan that doesn't break the API nor destroy performance in the vast majority of cases and it's much simpler than my other PR (too lazy to find ref). I should be able to PR it in a few days at worst.
