### ISSUE TITLE
Move effective_value to amount

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#3283]
What about moving [effective_value](https://github.com/rust-bitcoin/rust-bitcoin/blob/9233eb2fa329864e9c5f5651f60f5f8cde52bc91/bitcoin/src/blockdata/transaction.rs#L1119) to Amount.rs.  I feel like it belongs there instead of in Transaction.rs.

**Comment by apoelstra** [comment]
An "effective value" is a property of a `TxIn`. I think it makes sense where it is.

**Comment by Kixunil** [comment]
No, effective value is a property of something that has both `Amount` and a known spend script length. No such type currently exists in our library. So currently it has to be a free-standing function. I'd love to see better support for standard templates in the library, which might resolve this. Perhaps related: recently I came to conclusion that descriptors are really the way to go and we should focus on them long term. Though pulling in whole `miniscript` just to get descriptors for a few known templates is excessive. I want them to be a separate well-polished library at some point.

**Comment by yancyribbens** [comment]
I agree with both of you, however I also think it could belong paired with `minimal_non_dust` because it's dependent on Script size (part of satisfaction weight) and therefore dependent on witness or non-witness like the `minimal_non_dust` calculations.

**Comment by Kixunil** [comment]
@yancyribbens you can't know the spend weight from `script_pubkey` and you dont' know the weight from `TxIn` until you actually sign the input which would be a pretty stupid approach to take.

You literally need to know the template. And even with the template, for ECDSA signatures you need to know if you will be grinding them or not.

**Comment by yancyribbens** [comment]
@Kixunil

> you can't know the spend weight from script_pubkey and you dont' know the weight from TxIn until you actually sign the input which would be a pretty stupid approach to take.

Yes, I'm aware of all this.

> You literally need to know the template. And even with the template, for ECDSA signatures you need to know if you will be grinding them or not.

What do you mean by template?

**Comment by Kixunil** [comment]
P2PK, P2PKH, P2WPKH, P2TR... are all called script templates.

**Comment by yancyribbens** [comment]
> P2PK, P2PKH, P2WPKH, P2TR... are all called script templates.

I see.  Anyway, seems like no clear direction on moving this so I'll close it.
