### ISSUE TITLE
hashes: Check if we can remove trait imports

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3304]
One can use Uniform Function Call Syntax (UFCS) and not import traits, we should check `hashes` over for other instances of this improvement.

Pointed out to me here: https://github.com/rust-bitcoin/rust-bitcoin/pull/3128#discussion_r1743138964

**Comment by apoelstra** [comment]
Within macros it's pretty-much always a good idea.

Outside of macros, if we find we're importing traits to call one function, *sometimes* it's a good idea.

A related, but more universal, win is to use `use Trait as _` whenever we import traits just to get access to their methods. This pollutes our namespace less and clearly signals that we're just using the trait for methods, and when people are trying to find the origin of methods, the `as _` is a good hint that maybe they're coming from traits.

**Comment by tcharding** [comment]
`Trait as _` still triggers lint warnings when unused so I rekon there will be less maintenance burden if we use UFCS in all macros. (I opened this issue not because I checked but because I've change the imports loads of times over the last couple years without thinking of this.)

**Comment by Kixunil** [comment]
In macros, definitely, in internal macros we don't have to use UFCS we can also import the trait but for a single function it's not relevant.

Side note: globally importing everything at the top of the file raises risk of pointless merge conflicts. Thankfully they are solvable with my merge driver but that still has some issues.

**Comment by liamaharon** [comment]
> in internal macros we don't have to use UFCS

Isn't it still better to use UFCS in internal macros so they don't leak trait imports?

**Comment by liamaharon** [comment]
Imports like https://github.com/liamaharon/rust-bitcoin/blob/25d906d936eed34cf398e1a8b1abe8176c1b7c02/hashes/src/sha512.rs#L9 are fine right because they're not necessary for the macro usage?

**Comment by apoelstra** [comment]
@Kixunil I'm also curious what you meant by this. I agree with your factual claim but "globally importing everything at the top of the file" is standard Rust practice, and alphabetizing them/reformatting them standard `rustfmt` behavior, so I think this is just something we have to live with?

**Comment by Kixunil** [comment]
Basically, if you have `Foo` that's only used in `fn bar` it's less conflict-prone to write:

```rust
fn bar() {
    use foo::Foo;

   // ...
}
```

than:

```rust
use foo::Foo;

fn bar() {
   // ...
}
```

> standard Rust practice

While there are many standard practices that are good for their own reasons I don't see how it would apply here. Though arguably my driver should just be improved to handle everything and we shouldn't worry about it in the first place.

**Comment by apoelstra** [comment]
> Basically, if you have `Foo` that's only used in `fn bar` it's less conflict-prone to write:

Right. I think it's a bit more subtle than "only used in `fn bar`". It's more like "only used in `fn bar` and unlikely to be needed elsewhere in the future".

I try to do this in my own code, and don't mind encouraging people to do it, but I think it's too murky (and uncommon) for us to try to make it a hard rule. In particular I don't think @liamaharon should be holding up his PR over this.

**Comment by Kixunil** [comment]
> and unlikely to be needed elsewhere in the future".

It's not uncommon that I duplicate an import (or avoid the entire `use` statement). Generally I tend to add global `use` when an item is used in function signatures repeatedly.

But yes, this is quite strict and makes the code a bit more annoying to write, possibly also to read. I think we would be better off reconciling our formatting rules with my merge driver so that it can do its job out-of-the-box.
