### ISSUE TITLE
from_str zero needs no denomination

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#3307]
The following panics: `Amount::from_str("0").unwrap();`

While, `Amount::from_str("0 BTC").unwrap();` does not.

It seems to that 0 is a special case that doesn't need a denomination.

**Comment by apoelstra** [comment]
Yeah, agreed, we should special-case 0.

While we are thinking about it, should we forbid leading 0s except for 0? (Maybe we already do this.)

**Comment by yancyribbens** [comment]
> While we are thinking about it, should we forbid leading 0s except for 0? (Maybe we already do this.)

Yeah I think so, `0` but not `0.*`.  Good call.

**Comment by yancyribbens** [comment]
err not `0*` I meant

**Comment by Kixunil** [comment]
Funny that this is special case exists. I think it makes sense to special case it.

I think we should allow 0000000.00000000000 for any number of zeros that fit our length for consistency. IIRC we already allow leading and trailing zeroes. This is trivial to implement: just try to call the amount parsing function with arbitrary denomination and the entire string if the denomination is not found and if the result is `Ok(0)` return `Ok(0)`, if it's anything else return error missing denomination.

**Comment by Kixunil** [comment]
With denomination no, without yes.

**Comment by yancyribbens** [comment]
I think it makes sense to also continue to support zeros with denomination, e.g `0 btc`, `0 sats` etc for consistency (and to avoid breaking changes).

so, with denomination: `00 sats` is ok?
without denomination: `00` is not ok?

**Comment by apoelstra** [comment]
@yancyribbens no, both of those are OK.

Basically, we don't do any "leading zero" detection. The only thing we're changing is that we disable the denomination check for numbers that parse to zero. (Including `00`, `000.0000`, etc.)

**Comment by yancyribbens** [comment]
> Basically, we don't do any "leading zero" detection. The only thing we're changing is that we disable the denomination check for numbers that parse to zero. (Including 00, 000.0000, etc.)

works for me.
