### ISSUE TITLE
Support from_str math operators

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#3312]
It would be neat to support something like:
`Amount::from_str("7 cBTC + 5 sats")`

as opposed to a longer form:
`Amount::from_str("7 cBTC").unwrap() + Amount::from_str("5 sats").unwrap()`

or:
`Amount::from_str("7000005 sats")`

Seems like an interesting low priority hobby project if someone wanted.

**Comment by tcharding** [comment]
I personally dislike reviewing or working on the `amount` module already because it is overly complicated, this is just begging for it to get worse.

**Comment by Kixunil** [comment]
Definitely NACK. We're not going to add an interpreter to amount parsing and eventually end up with the Rust compiler in the library...

If you want to make amounts easier, I suggest you do this:


```rust
pub trait U64Ext: Into<u64> /*I'm being lazy here */ {
    fn sat(self) -> Amount {
        Amount::from_sat(self.into())
    }

    fn cbtc(self) -> Amount {
        Amount::(self.into() * 1000000)
    }

    // ...
}

impl U64Ext for u64 {}
```

And then you write:

```rust
7.cbtc() + 5.sat()
```

**Comment by yancyribbens** [comment]
> and eventually end up with the Rust compiler in the library...

Then we could compile rust-bitcoin with rust-bitcoin :thinking:

**Comment by Kixunil** [comment]
Still missing docker in VM running on Minecraft's redstone running on Factorio's circuits.
