### ISSUE TITLE
hashes: We have an undocumented pre-condition on `BLOCK_SIZE`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3315]
See https://github.com/rust-bitcoin/rust-bitcoin/pull/3298#discussion_r1745309978

**Comment by Kixunil** [comment]
I think this is ridiculous enough to just close it.

**Comment by apoelstra** [comment]
Lol, yeah, agreed. Though I wouldn't mind adding a comment saying that we noticed it on the off-chance that it comes up again.

**Comment by tcharding** [comment]
Well this issue can act as that comment :)
