### ISSUE TITLE
Use `bitcoin_hashes::hex` instead of `crate hex`

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#332]
This creates problem with defining new hash types, since the `hash_newtype` macro from bitcoin_hash uses it's own hex mod, and rust-bitcoin uses different crate hex.

**Comment by stevenroose** [comment]
I also noticed this. We should ditch using the `hex` crate where possible in favor of our `bitcoin_hashes::hex` module.

**Comment by dr-orlovsky** [comment]
Ok, will work on that code update
