### ISSUE TITLE
Feature Request: Provide xpriv.to_xpub(&secp) API 

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#3327]
Complementary to `Xpub::from_priv(&secp)`. And similar to `Secret.public_key(&secp) -> secp2561::PublicKey`

**Comment by jirijakes** [comment]
Naming of the methods there is somewhat inconsistent:

- `Xpub::from_priv(Xpriv) -> Xpub`
- `Xpriv::to_priv -> PrivateKey`
- `Xpriv::derive_priv -> Xpriv`

Would it make sense to rename them (with deprecations) at the same time to bring some predictability? For example:

- use `private_key`/`public_key` with `PrivateKey`/`PublicKey`
- use `xpriv`/`xpub` with `Xpriv`/`Xpub`

**Comment by Kixunil** [comment]
I think `to_priv` name is not great and it should be something like `to_raw`. The others don't need `x`.

**Comment by apoelstra** [comment]
In rust-miniscript we also have `to_public` on `DescriptorPublicKey`.

All of these sound fine to me but please let's pick one :).

**Comment by Kixunil** [comment]
I think the biggest weirdness is `to_priv` on `Xpriv`. "What do you mean to private? Xpriv is already private!"
