### ISSUE TITLE
Follow up #3308 (change docs for Wtxid::COINBASE)

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3331]
https://github.com/rust-bitcoin/rust-bitcoin/pull/3308#discussion_r1748940400

**Comment by apoelstra** [comment]
Right now the docs for `Wtxid::COINBASE` say that "this is not a real wTXID". This is a confusing philosophical claim which I now disagree with, even though I originally wrote it. We should just drop that sentence.

Similarly with `OutPoint::COINBASE_PREVOUT` we say "this is not a real outpoint". It's as real as any collection of 288 bits can be. That sentence should be dropped too.

**Comment by Kixunil** [comment]
Right but in case of `OutPoint` it's not pointing to a real transaction. In case of wTXID, it points to all coinbases (or any coinbase).

**Comment by apoelstra** [comment]
I'd be fine with language that says "does not point to a real transaction".

**Comment by tcharding** [comment]
Is this a real discussion?

**Comment by tcharding** [comment]
Note this comment as well: https://github.com/rust-bitcoin/rust-bitcoin/pull/3288#discussion_r1753144921
