### ISSUE TITLE
Follow up #3310 (allow_unused flag in serde.rs can be dropped)

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3332]
https://github.com/rust-bitcoin/rust-bitcoin/pull/3310#pullrequestreview-2283171005

**Comment by tcharding** [comment]
Or `#[cfg(not(debug_assertions))] { let _ = error;`

**Comment by apoelstra** [comment]
To elaborate:

We have an `allow_unused` annotation in bitcoin/src/consensus/serde.rs. We can gate this on `not(debug_assertions)`, but probably better would be to just add a dummy line "using" the "dead code" when `debug_assertions` is off.

**Comment by jamillambert** [comment]
Fixed in #3474
