### ISSUE TITLE
On deprecation of stuff that is moving to `primitives`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3342]
PR #3288 has two patches that are on the same topic, opening this issue to discuss them

- https://github.com/rust-bitcoin/rust-bitcoin/pull/3288/commits/126131a4f0925bad1b86c481a84f2551aebe539c
- https://github.com/rust-bitcoin/rust-bitcoin/pull/3288/commits/c98b9e6fc70472e76cc1d4e6dccab1e42fa866e6

Remove `all_zeros` (and `null`, and `is_null`)

Recently we added associated consts and deprecated `all_zeros` with the intention of being gentle on upgraders. We cannot move the deprecated functions to `primitives` so we have multiple options.

1. Introduce an extension trait to hold the deprecated functions
2. Just delete the functions

(Note that doing (1) results in a trait that only holds the deprecated functions and nothing else.)

If we do (1) the upgrade workflow potentially becomes:

- compiler warns that `Txid::all_zeros` no longer exists
- dev guesses (or reads) that `TxidExt` is needed
- imports the extension trait everywhere
- compiler warns that `all_zeros` is deprecated
- dev changes every call site to use `Txid::COINBASE_PREVOUT`
- dev gets annoyed because "could have just done that in the first place"

Are we causing more damage than good?

**Comment by Kixunil** [comment]
My suggestion: backport the constants and deprecate the functions in the previous version. This is still more annoying than "keep deprecated stuff around for a while" as we wanted but solves the exact problem you're pointing out.

**Comment by apoelstra** [comment]
Agreed that where possible and reasonably convenient for users (i.e., where there's a drop-in replacement) we should backport the replacements and deprecations.

Having said that @tcharding, the workflow you describe is not nearly as annoying as you make it out to be. It is more like

* compiler errors that `Txid::all_zeros` no longer exists but that it exists on a `TxidExt` trait
* user imports this and now their code continues to work, but with a bunch of deprecation warnings
* user fixes those warnings at his leisure, across multiple commits/PRs/whatever,

So this is one extra step vs a normal deprecation cycle.

If we did this *without* the deprecations, the process is

* compiler errors that `Txid::all_zeros` no longer exists. No help. Guess you need to go read the release notes or something.
* This times 1000, and every one needs to be dealt with in a single commit before you can move on with the upgrade.

Ok, this is zero extra steps vs a normal "delete functions without deprecation" process. But "zero extra steps" doesn't compensate for how antisocial it is to just wreck the API.

**Comment by Kixunil** [comment]
@apoelstra good point but should we bother *if we can* backport things?

**Comment by apoelstra** [comment]
I vote yes because I would like to extend our deprecation timelines for as long as we can tolerate.

So I view the backport as "starting the deprecation cycle early" rather than waiting for the next release to start it, but I don't want to end the deprecation cycle any earlier.

**Comment by tcharding** [comment]
Thanks lads, I realised on waking this morning the "fix in the next commit" thing, that is enough to keep it.

**Comment by tcharding** [comment]
> backport the constants and deprecate the functions in the previous version. 

This is an interesting idea, trickle backports and deprecation back into `v0.32` as we go, I'm not totally convinced and also this is a whole new approach so if we are going to do that I think it needs thinking through fully. Its kind of unusual to get lint fails "randomly" when `cargo` pulls a new patch version isn't it? Anyways we should have a new separate issue if we want to discuss it fully.

Closing this as resolved, we keep the backports.

**Comment by apoelstra** [comment]
> Its kind of unusual to get lint fails "randomly" when cargo pulls a new patch version isn't it? 

No, I think this is reasonable and expected.

But agreed, we should have a dedicated issue to discuss it.

**Comment by Kixunil** [comment]
> I vote yes because I would like to extend our deprecation timelines for as long as we can tolerate.

Fine, but I don't want them in stable crates so they'll need to live in `bitcoin` until removed.

> Its kind of unusual to get lint fails "randomly" when `cargo` pulls a new patch version isn't it?

No, I've seen crates doing it and it's good to do whenever we can do it as cleanly as we can here.

> But agreed, we should have a dedicated issue to discuss it.

Do we? It's seems pretty obviously a good idea to me and you seem to agree, downstream consumers can slap `#![allow(deprecated)]` (or `-A deprecated`) on their stuff but really, everyone should probably pin their dependencies anyway, so I don't expect push back especially because they have to deal with these from other crates, including `std`. Of course open an issue if you want, I just don't think there's much worth discussing.

**Comment by apoelstra** [comment]
> Fine, but I don't want them in stable crates so they'll need to live in `bitcoin` until removed.

This is fine, and even more reason to extend our deprecation timespan backward.

>Do we? It's seems pretty obviously a good idea to me and you seem to agree,

Yeah, ok, let's just do it. We can have a discussion if somebody complains (but this does seem like a particularly weird hill for such a person to die on, since this is reasonable behavior and even `std` has done it).
