### ISSUE TITLE
Negative Zero denom should be treated like Zero instead of panic.

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#3343]
This is issue is related to https://github.com/rust-bitcoin/rust-bitcoin/issues/3307

I believe this should not panic:
`let _a = Amount::from_str("-0 BTC").unwrap();`

The reason being that `assert_eq!("-0".parse::<f64>(), "0".parse::<f64>());` is considered true, that 0 is equal to negative 0, and therefore parsing `-0 BTC` should be equal to `Amount::ZERO`.  Same goes for other denominations (sat etc).

**Comment by apoelstra** [comment]
I don't think we should allow negative 0. Yes, it is mathematically equal to 0 as an integer, and therefore you can argue that it's just a formatting thing, but I would argue that -0 is a signed value, and therefore of a different type than `Amount`.

**Comment by Kixunil** [comment]
FTR Rust doesn't consider `-0` valid for unsigned integers. So I think we should do the same. (Yes, we treat `Amount` more like float but also unsigned and there's no unsigned float to compare with.)

**Comment by yancyribbens** [comment]
>  I would argue that -0 is a signed value, and therefore of a different type than Amount.

A signed value is not synonymous with a negative value.

> FTR [Rust doesn't consider -0 valid for unsigned integers.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f063fb2d60e6ca6310ac4aa03ffc33fd) So I think we should do the same. (Yes, we treat Amount more like float but also unsigned and there's no unsigned float to compare with.)

Hmm that bothers me that a -0 float is value but a -0 u64 is invalid.  We actually treat the input like a float which is why I still think it makes sense to follow how Rust works with floats.

**Comment by yancyribbens** [comment]
Seems i'm the minority here so I'll work around it.

**Comment by Kixunil** [comment]
> We actually treat the input like a float

We treat it as a fictitious `uf64` so we don't carry any sign. I was speaking about unsigned numbers, not floats/integers.

Also parsing negative zero in Rust stores the sign and then [outputs negative zero](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f063fb2d60e6ca6310ac4aa03ffc33fd)

Here you could argue we're meaningfully differing from floats, however preserving the sign would be a lot of work and would be lost on conversions to/from `u64` sats, not to mention that `from_sat` would have to become fallible or we would have to *double* the type's size (because of padding we can't even add one byte). Both of these options are horrible.(1) So I conclude we really need to differ from floats here.

(1) Fallible `from_sat` would've been fine if we guaranteed something stronger, which would have additional value (e.g making it equivalent of `u63` would make conversion to `i64` infallible). I was even advocating for 21M limit but there's a strong opposition to that. So no such change is going to happen.

**Comment by apoelstra** [comment]
I would say that we're emulating a decimal type, not `f64`. And for a (typical) decimal type which can represent values exactly as the user types them, there is no distinction between 0 and -0. Unlike IEEE floats.

> A signed value is not synonymous with a negative value.

They don't need to be synonyms for negative numbers to always be signed.

**Comment by tcharding** [comment]
Unhelpful comment: Bitcoin should never have used BTC amounts, sats only, floats are a pain in the neck - period (pun intended).

**Comment by apoelstra** [comment]
Fully agreed. But yes, it's hardly helpful to say now :)

**Comment by yancyribbens** [comment]
> I would say that we're emulating a decimal type, not f64. And for a (typical) decimal type which can represent values exactly as the user types them, there is no distinction between 0 and -0. Unlike IEEE floats.

I see.  This discussion is also happening on pr 3346.  There's a crate rust_decimal that implements a decimal type, that ought to work the same as how Amount parses decimals.  Although I notice in the rust_decimal crate, if the precision can't be represented because the number is too precise, it just rounds to 0, while the Amount implementation throws a parse error.

**Comment by Kixunil** [comment]
@yancyribbens not knowing anything about `rust_decimal` crate it feels like that behavior already failed the purpose of the crate. But anyway, first and foremost we're making a *financial* application here, so all rules of it apply before anything else.

**Comment by yancyribbens** [comment]
> not knowing anything about rust_decimal crate it feels like that behavior already failed the purpose of the crate

Hmm maybe this sentence makes more sense in Slovak, or is an expression in the language, although I admit to not knowing anything about the rust_decimal crate.

**Comment by yancyribbens** [comment]
Of topic, I spent some time in Bratislava a while back (per-pandemic times).  I remember going to a place for lunch that even accepted btc, although when I tried to pay, wait staff didn't actually know how to accept btc.  Pretty par for the course though.  Anyway, Bratislava was nice, like Vienna but much more affordable and chill.

**Comment by apoelstra** [comment]
@yancyribbens Kix's point is that the point of a decimal crate is that it can represent exact decimals. If you parse stuff and then it changes what you parsed, it's not really doing that.

Having said that, I've used rust-decimal before and in practice this isn't a big deal. With Bitcoin you have only 8 digits of precision and you never encounter a serialized version of anything more than that. And then before outputting you use the `RoundingStrategy` enum to bring whatever number you computed (which will either have 8 significant figures if you were just summing, or infinitely many if you were doing any nontrivial calculation, so you have to round no matter what) in line with whatever tax software or whatever you need to match.

It's also worth noting that Excel has the same behavior - if you type something with a bajillion sig figs it'll just silently drop them. And for better or worse, half the world's accounting processes wind up using Excel for critical stuff.

**Comment by yancyribbens** [comment]
@apoelstra ah cool, that's useful information.  I'm toying with making a proptest for Amount, so that's helpful.

**Comment by Kixunil** [comment]
@apoelstra I often compute EUR <-> BTC conversion manually and then enter the amount relying on error messages to tell me where the 8th digit is so I don't have to bother counting. :D But funnily enough if it always rounded then just entering whatever would have worked for me.

@yancyribbens pre-pandemic we also had Paralelna Polis. It was absolutely awesome, shame it crumbled. But I'm no longer in Bratislava anyway.

**Comment by yancyribbens** [comment]
> pre-pandemic we also had Paralelna Polis. It was absolutely awesome, shame it crumbled. But I'm no longer in Bratislava anyway.

I went to paralelni polis in Prague which was cool I thought.  Hopefully that didn't get shuttered as well.  Goes without saying I'm not in Bratislava anymore either :P or europe for that matter.  I thought about going to Tokyo for Bitcoin Tokyo but I'm not feeling very ambitious about traveling right now.

**Comment by Kixunil** [comment]
Actually Prague got too for different reasons (though some are somewhat related to pandemic). They're restructuring it, so at least there will be something interesting happening.
