### ISSUE TITLE
Request to improve error messaging

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#3355]
Is it possible to improve the error message when casting to Amount from SignedAmount?  It's currently annoyig to debug because the error doesn't supply the reason in some cases:

```
eff value Err(OutOfRangeError { is_signed: false, is_greater_than_max: false })
```

Here is the offending line of code the produces that prints the above error:
```
let signed_amount = SignedAmount(-1210838 SAT);
let amt = signed_amount.to_unsigned();
println!(amt);
```

Is it possible to show `is_less_than_min: true` here?  Obviously in this trivial example it's easy to see, however in more complex code where it's not so clear, some time would be saved with a more precise message.

Cheers

**Comment by Kixunil** [comment]
You've printed a debug message, print using `Display` to see a more readable one.

**Comment by apoelstra** [comment]
I really wish there was an option for the `assert!` macro to use display output rather than debug output, because I have this same issue with many errors in many libraries.

**Comment by yancyribbens** [comment]
@Kixunil not that I doubt you, but I must be doing something wrong because I get an error when I try using Display.

Display uses the print marker `{}` and debug `{:?}`.  If I try with Display, here is what is "Displayed" on my screen:
```
^^^ `Result<Amount, bitcoin_units::amount::OutOfRangeError>` cannot be formatted with the default formatter `
```

Here's the exert that displays the above message
```rust
let signed_amount = SignedAmount::from_sat(-1210838);
let amount = signed_amount.to_unsigned();
println!("{}", amount);
```

**Comment by Kixunil** [comment]
@yancyribbens `Result` doesn't have `Display` but `OutOfRangeError` does. You need to match on it.

@apoelstra good point that some errors are annoying in debug representation, though I vaguely remember seeing a more informative debug impl.
