### ISSUE TITLE
Prevent unused variables/imports in documentation tests

### ISSUE THREAD

**Issue by jirijakes** [rust-bitcoin/rust-bitcoin#3362]
Documentation tests are not linted the same way as other code, therefore the means that are currently used to detect unused variables and imports do not apply. However, as the examples in documentation are often copypasted, they should contain code that does not produce this sort of warnings.

From [rustdoc](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#pre-processing-examples) regarding documentation tests:

> Some common `allow` attributes are inserted, including `unused_variables`, `unused_assignments`, `unused_mut`, `unused_attributes`, and `dead_code`. Small examples often trigger these lints.

Attributes affecting documentation tests can be configured on module level by `#![doc(test(attr(...)))]`. In case of preventing unused variables et al. in documentation tests, it gives two options (also see [rustdoc](https://doc.rust-lang.org/rustdoc/write-documentation/the-doc-attribute.html#testattr)):

1. `#![doc(test(attr(warn(unused))))]`
    - less intrusive during development
    - warnings are hidden by default when running `cargo test`, needs to explicitly add `--show-output`
    - seems there is no way to turn them into errors using command line options (e. g. for CI)

2. `#![doc(test(attr(deny(unused))))]`
    - may be annoying during development
    - stronger guarantees

Point 2 will cause that any unused item in documentation will fail test, i. e. when running `cargo test` (`build` or `doc` are not affected). That might be the preferred option.

There is currently quite a number of cases of unused variables and imports, so solving this issue will also have to address them.

**Comment by apoelstra** [comment]
If you add `#![doc(test(attr(warn(unused))))]` and then run `cargo clippy --all-targets -- -D warnings` will it error?

**Comment by jirijakes** [comment]
No, it will not. So far I could not find a way how to build the documentation tests, only `cargo test` (or `cargo test --doc`), which does not have equivalent to `--deny`.

**Comment by apoelstra** [comment]
Frustrating.

Well, we can at least put the `warn` on and then we'll notice warnings (eventually) and fix them.

**Comment by Kixunil** [comment]
I suspect we have to set `RUSTDOCFLAGS="-D warnings"`

This shit keeps biting us all the time.

**Comment by jamillambert** [comment]
`#![doc(test(attr(deny(unused))))]` can be added library wide, but a lot of the errors are due to unused variables or methods which are the whole reason for the example in the docs.  e.g. showing how to create an `Address` in `address/mod.rs` or extending extend the `Params` struct in `network/params.rs`.

Unused imports should probably be removed, but I don't think unused variables or dead code should.

**Comment by apoelstra** [comment]
>Unused imports should probably be removed, but I don't think unused variables or dead code should.

We should assert something about them.

If there's no sensible thing to assert on them we can either add a hidden line that drops them and _-prefix them (and add a comment within the doctest).
