### ISSUE TITLE
checked_mul_by_weight arithmetic

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#3368]
I think there's a subtle issue with the method `checked_mul_by_weight`.  Hopefully I'm mistaken but in my math it's off by 1.

scenario: 

```rust
FeeRate 864 sat/kwu * Weight 381 wu
FeeRate 864 sat.kwu * Weight 0.381 kwu
329.18 sat
```

However `checked_mul_by_weight` returns `330 sat`.  Removing the add by `999` matches what I calculate it should be.

**Comment by apoelstra** [comment]
Yes. Adding 999 before dividing by 1000 is how you do integer division while always rounding up. This is a deliberate design decision.

**Comment by apoelstra** [comment]
This was implemented in 2182 and explained to you here https://github.com/rust-bitcoin/rust-bitcoin/pull/2182#discussion_r1389347385

**Comment by yancyribbens** [comment]
> This was implemented in 2182 and explained to you here https://github.com/rust-bitcoin/rust-bitcoin/pull/2182#discussion_r1389347385

Ha thanks.  I should have reviewed that issue again.  Glad it's my mistake

**Comment by yancyribbens** [comment]
After reviewing this again it makes sense now that it's preferable to over-calculate the fee instead of under.  Opened a PR https://github.com/rust-bitcoin/rust-bitcoin/pull/3371 in case it's a point of confusion in the future.
