### ISSUE TITLE
Move `Witness` to `primitives`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3399]
I have no clue how we want to do this if we require an absolute bare bones API. How much API surface are we going to live with on the `Witness` in `primitives`?

**Comment by apoelstra** [comment]
I think we should just move every method that doesn't take a `Script` or a `Signature`.

From https://docs.rs/bitcoin/latest/bitcoin/struct.Witness.html it looks like all the other methods are pretty solid.

**Comment by tcharding** [comment]
Cheers, I'll hack it up.

**Comment by tcharding** [comment]
Done in #3406
