### ISSUE TITLE
Consider adding an API for converting `Work` to and from bytes

### ISSUE THREAD

**Issue by liuchengxu** [rust-bitcoin/rust-bitcoin#3405]
I'm currently working on a Rust Bitcoin Client experiment [Subcoin](https://github.com/subcoin-project/subcoin), where I aim to store the cumulative chain work of each block in the database. To do so, I need to convert `Work` to `Vec<u8>` as `Work` in rust-bitcoin does not implement the codec used in Substrate, but I didn't find an existing API that could do this conversion (see the [current workaround in subcoin here](https://github.com/subcoin-project/subcoin/blob/9f13746f14a4995eeab8fa15b3a49fcc7e999ee7/crates/sc-consensus-nakamoto/src/aux_schema.rs#L38-L40)). Would you be open to the idea of adding an API for this? If so, please let me know what kind of API is welcome and I'd be happy to send in a PR.

**Comment by apoelstra** [comment]
Yeah, this seems reasonable. We have this for `Target` but not for `Work`, and `Work` is more "useful" in that it can be sensibly accumulated to be meaningful for entire chains.

**Comment by tcharding** [comment]
I'm confused by this issue, `Work` has a couple of conversion methods `to_le_bytes` and `to_be_bytes`.

**Comment by tcharding** [comment]
https://docs.rs/bitcoin/latest/bitcoin/struct.Work.html#method.to_le_bytes

**Comment by apoelstra** [comment]
Oh, apparently I just can't read the docs.

**Comment by tcharding** [comment]
:)

**Comment by liuchengxu** [comment]
@tcharding Thanks for the link! I didn't read the docs and missed the macro `do_impl!(Work)`.

**Comment by tcharding** [comment]
No sweat, thanks for raising an issue, drop past anytime you need us!
