### ISSUE TITLE
All the `Arbitrary` impls risk going stale

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3414]
With the new approach to evenly weight enum variants returned by `Arbitrary` I noticed that we risk the impls going stale, if a new variant is added the `Arbitrary` implemenatiton will continue working without correctly and never return the new variant.

```rust
#[cfg(feature = "arbitrary")]
impl<'a> Arbitrary<'a> for TapSighashType {
    fn arbitrary(u: &mut Unstructured<'a>) -> arbitrary::Result<Self> {
        let choice = u.int_in_range(0..=6)?;
        match choice {
            0 => Ok(TapSighashType::Default),
            1 => Ok(TapSighashType::All),
            2 => Ok(TapSighashType::None),
            3 => Ok(TapSighashType::Single),
            4 => Ok(TapSighashType::AllPlusAnyoneCanPay),
            5 => Ok(TapSighashType::NonePlusAnyoneCanPay),
            _ => Ok(TapSighashType::SinglePlusAnyoneCanPay)
        }
    }
}
```

May not be important, just thought I'd flag it.

**Comment by tcharding** [comment]
cc @shinghim because he is active in the `Arbitrary` stuff.

**Comment by tcharding** [comment]
This is one case where perhaps some super obscure macro magic would be ok because one doesn't have to read the code much, we just want to have confidence that test coverage is good in a future proof way. I have no solution in mind though.

**Comment by shinghim** [comment]
I think the macro magic method may work for enums, but there are some impls, such as the one for `Witness`, where the goal is to generate things that look like witness scripts. I think in general, we should try to add test coverage along with new features and updating the `Arbitrary` impls would fall under that. 

I was actually thinking about something related earlier when writing the comments about the equally weighted test cases in each impl: should we add some documentation about this in a readme somewhere? Maybe something specific to testing like they have [here](https://github.com/bitcoin/bitcoin/tree/master/test/functional#readme) that describes (among other things) that we're weighting specific test cases and how we pick those cases

**Comment by tcharding** [comment]
Maybe to start with we could just throw some docs in `CONTRIBUTING.md`?

**Comment by yancyribbens** [comment]
I think we talked about this in the original PR for adding Arbitrary.  Using a macro or decl would allow us to keep it up to date once Arbitrary is sufficiently mature.  I opted not to introduce that complexity to start with but I think it's good to talk about how to keep it in sync.

**Comment by apoelstra** [comment]
Please no macros. As @shinghim says there is no general way that we can macro-ize these implementations. We will just fix things as we notice that they are out of date. If there are macros then we'll never notice because nobody will know what the code is doing.

**Comment by yancyribbens** [comment]
> As @shinghim says there is no general way that we can macro-ize these implementations

Ok, I haven't tried.

> We will just fix things as we notice that they are out of date

It should be possible though to write some kind of cargo check or something to validate they are in sync and create a warning or error if not (as a separate step from the build process).  It's probably not worth prioritizing now though.
