### ISSUE TITLE
Is there any guide to read the code?

### ISSUE THREAD

**Issue by huahuahu** [rust-bitcoin/rust-bitcoin#342]
Thanks for the code.
Hi, I am new to  blockchain, is there any guide about the code? For examples, the UML diagram or how to use the code?

**Comment by jonasnick** [comment]
Hi, have you had a look at the documentation (https://docs.rs/bitcoin, for example [address creation](https://docs.rs/bitcoin/0.21.0/bitcoin/util/address/index.html))? There's also this issue demonstrating how to sign a transaction: https://github.com/rust-bitcoin/rust-bitcoin/issues/294. And @stevenroose hal command line tool (https://github.com/stevenroose/hal) can also serve as an example.

**Comment by huahuahu** [comment]
> Hi, did you have a look at the documentation (https://docs.rs/bitcoin, for example [address creation](https://docs.rs/bitcoin/0.21.0/bitcoin/util/address/index.html))? There's also this issue demonstrating how to sign a transaction: https://github.com/rust-bitcoin/rust-bitcoin/issues/294. And @stevenroose hal command line tool (https://github.com/stevenroose/hal) can also serve as an example.
Thanks for the reply.
