### ISSUE TITLE
`rust-bitcoin` rolling release

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3425]
As soon as `primitives 0.101.0` releases (requires `units`, `io`, and `hashes` releases) I rekon we should do a rolling release of `bitcoin` (as new crate `bitcoin-rolling`). This was a shower thought this morning because I'd like to use #3424 and release it in `psbt-v2`.

I'm happy to take on the release work if you (@apoelstra) want, happy to raise PRs and let you do it also. My idea was release from either a separate branch on this repo or from my own fork. The idea being there should be zero changes from `rust-bitcoin` master branch. 

Then release every month in lockstep with `primitives`.

**Comment by tcharding** [comment]
We could also call it `v0.33.0-alphaX` and do it here, I suppose it makes no difference apart from if we do it as alpha you have to take on the release work.

**Comment by apoelstra** [comment]
I'd prefer to use the `alpha` naming. We can't really do "rolling releases" with crates.io.

**Comment by apoelstra** [comment]
The `alpha` naming would prevent us from doing backports or non-breaking changes. But I think if we were dutiful about releasing every mnoth, and yanking versions we thought were insecure, it'd be fine.

**Comment by tcharding** [comment]
Why would it prevent it? E.g we could release, in order:

- 0.32.2
- 0.33.0-alpha.0 (tracking master)
- 0.33.0-alpha.1
- 0.32.3 (with backported stuff)
- 0.33.0-alpha.2 (still tracking master)

**Comment by apoelstra** [comment]
0.33.0-alpha.1 to 0.33.0-alpha.2 is a major version increase. (No, this cannot be explained as a "semver variant"; it's just cargo being cargo).

**Comment by tcharding** [comment]
Excuse me for being slow, I'm still not understanding the problem. The point of the alpha is just to make the release yellow on crates.io to signal to folk not to use them unless they want bleeding edge, right? That was also my reasoning for releasing as a different crate `bitcoin-rolling`, then no one could get confused.

**Comment by apoelstra** [comment]
Yes, but a side-effect of this is that if users depend on one version of the alpha, their code will not be compatible with others' who use a different version.

**Comment by tcharding** [comment]
Yes, I imagined that the releases were basically only useful for testing, maybe its not that useful at all and we are better just patching manifests locally to test - but that is super painful once there are a bunch of crates involved.

**Comment by tcharding** [comment]
By "testing" I mean testing everything goes together correctly, for example in the `psbt-v2` crate I could use the rolling release because it only depends on `bitcoin` and `miniscript` and nothing else higher up that would cause version problems.

**Comment by tcharding** [comment]
I guess the question is how many crates are there like that for which this would be useful, or does everyone else write crates that have a bunch of dependencies that all use `bitcoin`?

**Comment by apoelstra** [comment]
Most of my binary crates depend on `bitcoin` then use the dependency re-exports from `bitcoin`. So I would use this sequence of `alpha` releases. But I wouldn't ever release a library that used an `alpha` release because it'd be too much work to keep up to date.

**Comment by tcharding** [comment]
Yep cool, that meshes with what I had in mind. So in that case it doesn't matter that each alpha release is a new major version, right?

**Comment by jaoleal** [comment]
why not naming the "alpha" as "unstable" ? Like, it says that shouldn't be used in production and may have bugs on new features and... its idiomatic, everyone who messes with rust will get the same idea of "unstable", that's what @tcharding wants to do, right ?

**Comment by apoelstra** [comment]
I am happy with that, if cargo will let us do it. It might have whitelisted the names "alpha" and "beta". @jaoleal can you find an example of another crate using `unstable`?

**Comment by jaoleal** [comment]
Only `rustc` 👍

**Comment by tcharding** [comment]
`alpha` implies that its bleeding edge and don't come whinging to us, which is what we are after, right? And it early adopters can jump right on in.

Closing this, I think we have in mind what we are doing - release as we have something that we can test. (To be explicit `0.33.0` won't be coming out for a long time.)
