### ISSUE TITLE
Wildcards problematic

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3436]
As we move things over to `primitives` we decided to use wildcard re-exports eg from `bitcoin::blockdata::block` re-export `primitives::block::*`.

Yesterday while attempting to move `script` types the compiler was getting confused and I could not get code to build that appeared correct, there must be some rules about wildcards that make them more ambiguous than is obvious from reading the code (at least for me).

Perhaps we should use explicit re-exports? Raising an issue incase there is any downside I'm not thinking of right now. 

FTR the main reason I pushed for wildcards was that explicit re-exports are slightly more maintenance and error prone because at the moment we re-export from so many places one has to remember to do all of them (eg `lib.rs`, the exact module eg `script::borrowed`, sometimes the module itself eg `script`).

**Comment by apoelstra** [comment]
Yes, let's please use explicit re-exports.

If we forget some it's easy to add them after the fact.

**Comment by jaoleal** [comment]
Explicit re-exports are good.

**Comment by tcharding** [comment]
This is done now, checked with `grep` - trust me.

**Comment by tcharding** [comment]
Ha! Never trust me. `bitcoin/scr/blockdata/script/push_bytes.rs` has wildcard re-exports as well as the `mod.rs` above it.

I'll leave this closed but because we know to remove them when we find them.
