### ISSUE TITLE
CI failures in fuzztest

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#3448]
See e.g. https://github.com/rust-bitcoin/rust-bitcoin/actions/runs/11248614157/job/31274050738

I can't reproduce these locally, though they do seem to make sense. (When `hashes_fuzz` is on we are referring to fields that no longer exist.) I'm not sure what's going on.

**Comment by jamillambert** [comment]
In #3298 `HashEngine.length` was changed to `HashEngine.bytes_hashed` and changed from `usize` to `u64`.  I have opened #3449 to fix it.
