### ISSUE TITLE
Backport (most of) #3176 to bitcoin-io 0.1

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-bitcoin#3465]
AFAICT most of  #3176 could be backported to bitcoin-io 0.1, which would be nice given most of us may be stuck on rust-bitcoin 0.32 for a while.

**Comment by apoelstra** [comment]
I stuck the "Needs backport" label onto #3176.

I guess we will need an additional "Backport Done" label, or maybe we should just remove the "Needs backport" once backports actually get done.

**Comment by shinghim** [comment]
it looks like these changes are in [io-0.1.x](https://github.com/rust-bitcoin/rust-bitcoin/commits/io-0.1.x/) but done after 0.1.2, which was released [on March 18](https://github.com/rust-bitcoin/rust-bitcoin/releases/tag/io-0.1.2). Does it make sense to release io-0.1.3?

**Comment by apoelstra** [comment]
Yes, once this issue is resolved.

**Comment by apoelstra** [comment]
I don't know what I meant by the above comment. https://github.com/rust-bitcoin/rust-bitcoin/pull/3181 was merged over 2 months ago, and crucially contains the `FromStd` wrapper. Without that `io` is super hard to use.

@tcharding can you open a PR to cut io 0.1.3 today?

**Comment by tcharding** [comment]
We release `io-0.2.0` last month and it looks like it has #3181 in it (on master `git diff io-0.2.0 io` shows only trivial lifetime changes).

 ref: https://github.com/rust-bitcoin/rust-bitcoin/pull/3376

**Comment by apoelstra** [comment]
Ok, but rust-bitcoin 0.32.x uses io-0.1.x.

**Comment by tcharding** [comment]
Ooooh, I get it. Can do.

**Comment by tcharding** [comment]
Done: https://github.com/rust-bitcoin/rust-bitcoin/pull/3566

**Comment by tcharding** [comment]
I believe this is done.
