### ISSUE TITLE
Amount parse error not exposed

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-bitcoin#3490]
`Amount` is available in the `bitcoin` crate, but the error type for `impl FromStr for Amount` isn't. The error type is `bitcoin_units::amount::ParseError`, but this isn't exported from `bitcoin`.

This can be worked around by referring to it as `<Amount as FromStr>::Err`, or by adding a dependency on `bitcoin_units` and using `bitcoin_units::amount::ParseError`.

**Comment by apoelstra** [comment]
Yeah, I think we should re-export all the error types alongside the unit types.

**Comment by tcharding** [comment]
Yep looks like an oversight, we have these re-exports but `ParseError` is missing.

```rust
    pub use units::amount::{
        Amount, CheckedSum, Denomination, Display, ParseAmountError, SignedAmount,
    };
```
