### ISSUE TITLE
`COIN_VALUE` no longer accessible in const contexts

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-bitcoin#3491]
The `COIN_VALUE` const was removed, I assume in favor of `Amount::ONE_BTC`, however, if you need a `u64` in a const context, I don't think you can get it because `Amount::to_sat` is not marked `const`. I think this could be allowed by making `Amount::to_sat` const.

**Comment by apoelstra** [comment]
Yeah, this looks like an oversight. `from_sat` has been const from the very beginning, exactly to allow replacing `COIN_VALUE` instances where they were used to construct amounts, but we didn't do `to_sat`.
