### ISSUE TITLE
Impossible to clone on Windows 10

### ISSUE THREAD

**Issue by jeandudey** [rust-bitcoin/rust-bitcoin#350]
Git output:

```
error: unable to create file fuzz/hfuzz_input/deserialize_udecimal/input/id:000244,src:000165,op:havoc,rep:4: Invalid argument
error: unable to create file fuzz/hfuzz_input/deserialize_udecimal/input/id:000245,src:000173,op:havoc,rep:2: Invalid argument
error: unable to create file fuzz/hfuzz_input/deserialize_udecimal/input/id:000246,src:000185,op:havoc,rep:2: Invalid argument
error: unable to create file fuzz/hfuzz_input/deserialize_udecimal/input/id:000247,src:000191,op:havoc,rep:4: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

As a side note, the package from crates.io compiles without problems (don't know if these files are included in the package).

**Comment by jeandudey** [comment]
Had to use [obscure tricks](https://briancoyner.github.io/2013/06/05/git-sparse-checkout.html) to not checkout `hfuzz_input` files and get the repository cloned

**Comment by TheBlueMatt** [comment]
What character is invalid in that file name? We can rename it without effect, but will need to make sure we don’t break it again in the future.

**Comment by jeandudey** [comment]
[The following reserved characters](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions):
>    < (less than)
    > (greater than)
    : (colon)
    " (double quote)
    / (forward slash)
    \ (backslash)
    | (vertical bar or pipe)
    ? (question mark)
    * (asterisk)

So:

```
id:000247,src:000191,op:havoc,rep:4
  ^          ^         ^         ^
```

**Comment by jeandudey** [comment]
It applies to that large list of files in hfuzz
