### ISSUE TITLE
Compiler warning for `script::ScriptExt` trait is misleading

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3506]
The error message when `script::ScriptExt` extension trait is not in scope is unfortunate because it mentions `borrowed` which is a private module. Same thing happens for the `ScriptBufExt` (mentions `owned`).

```bash
757 |             assert!(redeem_script.is_p2wpkh());
    |                                   ^^^^^^^^^
    |
    = help: items from traits can only be used if the trait is in scope
help: trait `ScriptExt` which provides `is_p2wpkh` is implemented but not in scope; perhaps you want to import it
    |
572 +         use crate::blockdata::script::borrowed::ScriptExt;
```

**Comment by apoelstra** [comment]
When do you get this error? If it's showing `crate::` when it means `bitcoin::` that's always wrong.

But I assume that this error is only appearing within this crate, and that users will see a different one.

**Comment by tcharding** [comment]
Ah sweeeet, my bad. I checked that `bitcoin/examples` and also `rust-bitcoind-json-rpc-types` both don't exhibit this behaviour. Its only _within_ the `bitcoin` crate, so win for `cargo`.

**Comment by apoelstra** [comment]
Awesome, thanks for checking
