### ISSUE TITLE
extendedpubkey should have a method to produce an address

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#353]
In general the mapping between xpubs and addresses could be more ergonomic. Not sure what the best way to do this, and how it interacts with potential ypub extensions.

**Comment by stevenroose** [comment]
You mean 
```rust
Address::p2wpkh(xpub.derive_pub(&secp, "m/0'/1'/15".parse()?)?, Network::Bitcoin)
```
is not ergonomic enough?

**Comment by stevenroose** [comment]
I'm personally not a big fan of ypubs and zpubs. BIP32 is about "key derivation" and doesn't specify addresses (IIRC). So I like the explicit way of converting to an address as above, using the appropriate `Address` constructor function.

**Comment by apoelstra** [comment]
Yeah, I think you're right ... in my case I already have an xpub so all I need to do is `xpub.pubkey` rather than using `derive_pub`.
