### ISSUE TITLE
Should `PushBytes::from_slice_unchecked` actually be `unsafe`?

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-bitcoin#3531]
`PushBytes::from_slice_unchecked` is `unsafe`. `unsafe` should, I think, be reserved for functions that potentially violate memory safety, however, looking around a little bit, it doesn't look like it's actually `unsafe` in that sense.

`PushBytes::from_slice_unchecked` should be safe under all circumstances, unless there is unsafe code elsewhere in the codebase which relies on the underlying slice being shorter than `2^32`.

**Comment by apoelstra** [comment]
This function has a giant `SAFETY` comment in it explaining the guarantees that the user has to uphold and why this is necessary for soundness.

**Comment by casey** [comment]
Hmm, I think I don't understand why this is unsafe, in the Rust memory unsafety sense.

```
        /// Creates `&PushBytes` without checking the length.
        ///
        /// # Safety
        ///
        /// The caller is responsible for checking that the length is less than the 2^32.
        unsafe fn from_slice_unchecked(bytes: &[u8]) -> &Self {
            // SAFETY: The caller must guarantee that bytes.len() < 2^32.
            // If that is the case the conversion is sound because &[u8] and &PushBytes
            // have the same layout (because of #[repr(transparent)] on PushBytes).
            &*(bytes as *const [u8] as *const PushBytes)
        }
```

Even if `bytes.len() >= 2^32`, isn't this still memory safe?

**Comment by tcharding** [comment]
IIUC you are proposing that we could instead have:

```rust
        /// Creates `&PushBytes` without checking the length invariant.
        fn from_slice_unchecked(bytes: &[u8]) -> &Self {
            unsafe {
                &*(bytes as *const [u8] as *const PushBytes)
            }
        }
```

I cannot see any problem with this but I'm not an experience `unsafe` guy.

**Comment by tcharding** [comment]
I'm pretty sure @Kixunil would have thought of this and have a reason for putting it on the function but I don't know what the reason is.

**Comment by apoelstra** [comment]
Can you edit your issue to say that you think we're correct about the unsafety, instead of suggesting that we knowingly marked a safe function as `unsafe` because of codebase conventions?

I think you may be correct here but the issue as described is definitely not an issue.

**Comment by casey** [comment]
Done!

**Comment by Kixunil** [comment]
I've put it in in anticipation that we might want to make use of that invariant. While it's true that didn't come up yet, the reason is that we were busy with more pressing issues not that this was useless.

**Comment by apoelstra** [comment]
I don't think we should mark things unsafe unless we have a specific idea in mind about how or when we should use it. And even then I'd be skeptical unless the performance benefits are clear.

Here, like with `Amount`, we have a type which is basically a newtype over `Vec<u8>` and whose use can be replaced by `Vec<u8>` by users who are very concerned about performance and want to write their own microoptimized code. We shouldn't make our API, which is designed to force the user to deal with common problems and guide them to sensibe flows, unnecessarily hard and scary to use.

**Comment by Kixunil** [comment]
> unnecessarily hard and scary to use.

We have perfectly safe and very reasonable alternative API. It's even infallible for short enough arrays and all objects that one could possibly want to push into script. `Vec` also has some `unsafe` methods but nobody goes around crying that `Vec` is hard to use or scary or whatever else.

For the purpose of stability it's better to mark functions `unsafe` (or not make them public).
