### ISSUE TITLE
Is the visibility of `Header` correct

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3548]
We do not re-export `Header` from `primitives`, I did this on purpose because one usually uses `block::Header` but wanted to flag it.

**Comment by tcharding** [comment]
Dose it matter that users of the lib will likely then use `BlockHeader` but when they jump to `rust-bitcoin` code they will see `Header` and be a bit confused?

**Comment by apoelstra** [comment]
I don't think "avoiding confusion for users who are reading our own codebase" should be a priority at all when considering what our public API looks like. They will already need to jump through hoops to chase all the `bitcoin` types back into `primitives` or `units` or whatever.

**Comment by tcharding** [comment]
Fair point. Its nice actually, in the HMTL docs it makes `BlockHeader` be in the struct list right along with `BlockHash` and `BlockHeight` (and `Block` of course).

**Comment by tcharding** [comment]
Done in #3562
