### ISSUE TITLE
Rename `Block::txdata` 

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3552]
The name `txdata` is unquestionably bad, it is non-descriptive, not at all Rusty, and not using the correct identifier casing conventions. Young Andrew probably winces every time someone reads and/or types `block.txdata`. Don't worry young Andrew, everyone knows that C programmers are still the baddest.

Howeeeever, this identifier has been around for years and is likely used in 6000 places and if/when we change it some dev finally rage quits because `rust-bitcoin` breaks constantly for no reason.

This is more or less the same problem with renaming `Transaction::input` but slightly less subtle/contentious.

2 questions:

1. Can we get away with renaming this field?
2. If we can/do what should it be?

Re (1): To be perfectly transparent I fall very much in the change-stuff-for-the-better-and-devs-can-deal-with-it-that-is-like-totally-their-job but I 100% feel the pain the Fedimint crew explained having to stop everything to merge a 1000 line diff just to upgrade `rust-bitcoin` - there is no good solution only trade offs.

Re (2): The obvious candidate is `Block::transactions` (but ouch 12 characters).

**Comment by tcharding** [comment]
cc @darosior and @stevenroose representing "stop changing everything you twats".

(Please take my attempted humour as indication that I realize this is a tough problem, we wish it would just go away, and talking about it sucks - but here we are.)

**Comment by apoelstra** [comment]
Because the field has invariants on it we need to make it private anyway. So we can name the accessors whatever we want, and rename the private field to whatever we want.

**Comment by tcharding** [comment]
> Because the field has invariants on it we need to make it private anyway. 

I was wondering to myself earlier if I went off half cocked writing this issue, given that you already suggested this.
