### ISSUE TITLE
Do we want `hex` to appear in the public API of `bitcoin_hashes`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3558]
Currently `hex` appears in the public API of `bitcoin_hashes` in exactly two places (I believe)

1. In the `FromStr` implementations 
2. In the `hex::FromHex` trait bound on `Hash::Bytes`

(1) is easy enough to hide, just wrap the error. (2) not so much.

**Comment by apoelstra** [comment]
We can just remove the bound in (2).

We might want to add a `str::FromStr` bound on the `Hash` trait itself though to be symmetric with `fmt::Display`.

**Comment by tcharding** [comment]
No dice

```
error[E0277]: the trait bound `[u8; 20]: FromStr` is not satisfied
   --> hashes/src/internal_macros.rs:96:26
    |
96  |               type Bytes = [u8; $bits / 8];
    |                            ^^^^^^^^^^^^^^^ the trait `FromStr` is not implemented for `[u8; 20]
````

**Comment by tcharding** [comment]
Just removing the bound all together builds fine.

**Comment by apoelstra** [comment]
>No dice

This looks like you put a `FromStr` bound on `Hash::Bytes`. I was suggesting putting the bound on `Hash`.

**Comment by tcharding** [comment]
Its hard to get good help.

**Comment by tcharding** [comment]
Tested, that works.

**Comment by tcharding** [comment]
This is a duplicate of #2654
