### ISSUE TITLE
amount: div by weight 

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3563]
Currently we support dividing an amount by a weight in two ways

1. `ops::Div<Weight> for Amount` (in the `fee_rate` module) - does truncating division
2. `Amount::checked_div_by_weight` - rounds up

Are we happy with this or should we consider using `_floor` and `_ceil` nomenclature.

Originally discussed here: https://github.com/rust-bitcoin/rust-bitcoin/pull/3539#discussion_r1825012746

**Comment by tcharding** [comment]
Same consideration applies to `checked_mul_by_weight` and `ops::Mul<Weight> for FeeRate`.

**Comment by yancyribbens** [comment]
Using `_ceil` seems like a good idea instead of `Amount::checked_div_by_weight` if `checked_div_by_weight_floor` is added which I would be in favor of.

**Comment by yancyribbens** [comment]
> Same consideration applies to checked_mul_by_weight

I don't have a preference to add this for `checked_mul_by_weight` and am happy with the behavior of being conservative on the computation by default (rounding up).

**Comment by apoelstra** [comment]
Yeah, let's split the existing method into `_floor` and `_ceil` variants. Better to be explicit.

It's fine to leave all the `Div` operators as flooring division since that's what people expect.
