### ISSUE TITLE
Should all types with `from_consensus` implement `TryFrom` / `From`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3564]
- `units::locktime::relative::Height` has an infallible constructor `from_height` and a matching `From` impl.
- `units::locktime::absolute::Height` has a fallible constructor `from_consensus` but not `TryFrom`

Should all types that implement `from_consensus` constructors all have matching `TryFrom`  or `From` impl

**Comment by apoelstra** [comment]
@Kixunil has forcefully argued "no" elsewhere and I am tired of arguing the point.

In the specific case of locktimes, we have these types `Height` and `Time` which are entirely defined by their inclusion in the locktime types. Vs something like `Sequence` which (IMO) should have `From<u32>` but Kix feels that this is too mysterious a conversion.

**Comment by tcharding** [comment]
Oh my bad, I was just trying to go over the `units` crate with a fine tooth comb and see if we missed stuff. I totally forgot about all that discussion.

**Comment by tcharding** [comment]
lol, that is pretty funny actually - we argued about that so much.
