### ISSUE TITLE
Pretty print hashes without `0x` prefix

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3570]
In https://github.com/rust-bitcoin/rust-bitcoin/pull/2861 we uncovered the fact that we are pretty printing hashes (`Txid` at least) with the `0x` prefix. See unit tests in `bitcoin/src/blockdata/transaction.rs`.

**Comment by shinghim** [comment]
Looks like this eventually calls through to hex-conservative to [add the prefix](https://github.com/rust-bitcoin/hex-conservative/blob/c7607753665b75d50fb92483f241fef8543499db/src/display.rs#L516). The method states:

```
 We support users adding `0x` prefix using "{:#}" (treating hex like an integer).
```

Seems that this was the intention to have `0x` prefixed onto the pretty prints

**Comment by apoelstra** [comment]
I don't mind adding the 0x if somebody uses `{:#}` (even if they're doing this "accidentally" by using `{:#?}` to print a multi-line debug output; I don't mind uglier debug output).

But a normal `Display` output definitely should not have the 0x.

**Comment by tcharding** [comment]
Closing, FTR this is the current tested behaviour 
```rust

    #[test]
    fn outpoint_format() {
        let outpoint = OutPoint::COINBASE_PREVOUT;

        let debug = "OutPoint { txid: 0000000000000000000000000000000000000000000000000000000000000000, vout: 4294967295 }";
        assert_eq!(debug, format!("{:?}", &outpoint));

        let display = "0000000000000000000000000000000000000000000000000000000000000000:4294967295";
        assert_eq!(display, format!("{}", &outpoint));

        let pretty_debug = "OutPoint {\n    txid: 0x0000000000000000000000000000000000000000000000000000000000000000,\n    vout: 4294967295,\n}";
        assert_eq!(pretty_debug, format!("{:#?}", &outpoint));

        let debug_txid = "0000000000000000000000000000000000000000000000000000000000000000";
        assert_eq!(debug_txid, format!("{:?}", &outpoint.txid));

        let display_txid = "0000000000000000000000000000000000000000000000000000000000000000";
        assert_eq!(display_txid, format!("{}", &outpoint.txid));

        let pretty_txid = "0x0000000000000000000000000000000000000000000000000000000000000000";
        assert_eq!(pretty_txid, format!("{:#}", &outpoint.txid));
    }
```
