### ISSUE TITLE
Creates/constructs/build etc

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3575]
How particular do we want to be on the `rustdocs` of 1.0 crates

We have various ways of saying the same thing

- `/// Creates a new Foo] ...`
- `/// Constructs a new Foo ...`
- `/// Constructs Foo ...

I accidentally scratched the surface of this issue in: https://github.com/rust-bitcoin/rust-bitcoin/pull/3565

**Comment by jamillambert** [comment]
Coming from other languages that use constructors for objects this term seems more correct to me.  In the cases in the linked PR the function is working like a constructor which initializes values of the object, as opposed to just creating the object and allocating memory but not initializing the values.

I vote `Constructs ...` but am ambivalent about what follows.

**Comment by apoelstra** [comment]
Anything sounds good to me. So +1 to @jamillambert's suggestion.

I would suggest we use "a new `Foo`" (and sometimes "an empty `Foo`" or "a `Foo` with `bar`" etc).

**Comment by tcharding** [comment]
Works for me.
