### ISSUE TITLE
Strip underscores from Amount before parsing input

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#3586]
Currently Amount errors when parsing the following:

`Amount::from_str("10_000 sats").unwrap();`

Adding underscores is common to make large numbers more readable.  I think it would be simple to support this by simply stripping them before parsing.

**Comment by tcharding** [comment]
`10_000` is a Rust thing, right? In normal language one uses `10,000`. I'm not 100% convinced we should do this.

**Comment by apoelstra** [comment]
It is a Rust thing, but this is a Rust library.... I'm weakly in favor of this.

**Comment by yancyribbens** [comment]
I was reading some C++ today which I haven't in a while, and I guess in C++ it's `10'000`.  I think Ruby like Rust uses `10_000`.

**Comment by storopoli** [comment]
Also Julia and Zig both can accept `10_000`.
So yeah it is not only a Rust thing.
Probably developers got old and got burn when counting zeros a lot...

**Comment by jirijakes** [comment]
What would be the use case? Parsing direct user input? Is there no potential risk of loss of funds in allowing to parse strings like `1_________________________________________________________________________________________________________________________________________________________________________________00`?

I don't think this would be good addition. AFAIK languages that accept this format as literals do not accept it when parsing numbers.

Rust and Scala:

```rs
>> 1_000u32
1000
>> "1_000".parse::<u32>()
Err(ParseIntError { kind: InvalidDigit })
```

```scala
scala> 10_000L
val res0: Long = 10000

scala> "10_000".toLong
java.lang.NumberFormatException: For input string: "10_000"
  at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
  at java.base/java.lang.Long.parseLong(Long.java:618)
  at java.base/java.lang.Long.parseLong(Long.java:722)
  at scala.collection.StringOps$.toLong$extension(StringOps.scala:923)
  ... 30 elided
```

> Also Julia and Zig both can accept 10_000.

Do they accept it when parsing or only as literal?

**Comment by apoelstra** [comment]
I don't believe there is any natural language which uses `_` as a semantically meaningful separator in numbers.

We already treat `.` as the decimal separator in `Amount` and offer no way to change this, nor do we accept `,` in any form. I agree that if we were to change this we'd be wading into a nasty interaction between internationalization and unambiguity for users about what they're entering. And we definitely shouldn't change that. (If users want to handle this properly for their locale, it is not hard to use a decimal crate to do so and convert to `Amount`; there's a good chance they already need to do this to handle other currencies.)

> Is there no potential risk of loss of funds in allowing to parse strings like [a ton of underscores then more digits]?

We could forbid multiple `_`s in a row. But in general, user input boxes should be length-limited to prevent this sort of thing.

**Comment by yancyribbens** [comment]
Alright, I think it's a good point to follow how library parsers work like `"1_000".parse::<u32>()` and not allow underscore or other formatting of that nature.  It's more readable to include IMO although there are other ways to make it readable.

**Comment by yancyribbens** [comment]
closing for now
