### ISSUE TITLE
0.22 release tracking issue

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#359]
What PRs do people really want in the next release? I think

* PR to bump rust-secp version (will happen in a separate 0.23 I guess)
* #284 
* #329

**Comment by thomaseizinger** [comment]
I am really looking forward to #284.

**Comment by stevenroose** [comment]
https://github.com/rust-bitcoin/rust-bitcoin/pull/357 would be dope :)

**Comment by ccdle12** [comment]
I like #284  looking through the changes, I think it really improves the readability of the codebase

**Comment by clarkmoody** [comment]
Might as well participate in the normal release process instead of just blasting an update out there myself 😉.

If there's no patch release, we can put #376 in 0.22.

**Comment by apoelstra** [comment]
Closed by #366
