### ISSUE TITLE
Example Request

### ISSUE THREAD

**Issue by zeropoid** [rust-bitcoin/rust-bitcoin#36]
Can you show me main function example where I can see how to use library to generate uncompressed main network bitcoin address from the given base58 encoded valid private key?

**Comment by apoelstra** [comment]
You're welcome to join #rust-bitcoin on Freenode for questions like this.

The answer I think is
```
use std::str::FromStr;
use bitcoin::util::privkey::Privkey;

let priv = Privkey::from_str(base58_encoded_key).expect("valid base58 key");
priv.to_address().to_string()
```
