### ISSUE TITLE
confirmations field in Transaction struct.

### ISSUE THREAD

**Issue by twosatsmaxi** [rust-bitcoin/rust-bitcoin#3629]
Possible to add confirmations field that comes from `getrawtransaction` rpc call in the Transaction struct.
It doesn't have it currently, I can raise a PR for this.
<img width="832" alt="image" src="https://github.com/user-attachments/assets/045fa08f-eaae-4dab-93d2-badd9466c4eb">

**Comment by apoelstra** [comment]
No, because the confirmations field is a property of the entire blockchain, not of a single transaction. There is no way to serialize or unserialize it.

**Comment by sanket1729** [comment]
For interacting with bitcoincore RPC, you can use rust-bitcoincore-rpc crate. For example, this field has [GetRawTransactionResult](https://github.com/rust-bitcoin/rust-bitcoincore-rpc/blob/06a6c156b4d469c60c1abe8afdc002e7e11e5d3b/json/src/lib.rs#L598-L615) that you need.
