### ISSUE TITLE
Misleading InputWeightPrediction::weight() function name

### ISSUE THREAD

**Issue by spacebear21** [rust-bitcoin/rust-bitcoin#3645]
Stumbled upon this again and although the doc string is now fixed, the function name is still misleading. I'm not sure if the correct solution would be to a) rename it to e.g. `witness_weight` or b) include the prevout + sequence weights to the return value and rename it to e.g. `total_weight` or c) do both.
              
              I would prefer `witness_weight` or something. Unsure. `signature_weight` may suggest to some users that it's specifically about EC signatures.

_Originally posted by @apoelstra in https://github.com/rust-bitcoin/rust-bitcoin/pull/3443#discussion_r1790744826_

**Comment by spacebear21** [comment]
Example usage where we have to manually add the prevout + sequence data weights in input weight calculations: https://github.com/payjoin/rust-payjoin/blob/master/payjoin/src/psbt.rs#L227

**Comment by yancyribbens** [comment]
I think a PR to deprecate this method in favor of `witness_weight` would be accepted.

**Comment by yancyribbens** [comment]
Also, i'm curious about pulling in some of the logic linked above to find the input weight for each input type.  I've been trying to do something similar for a different application.

**Comment by apoelstra** [comment]
Yeah, let's deprecate this and add a new better method. Maybe also add one that returns the 36 + 4 + 4 constant so users don't need to hardcode it.
