### ISSUE TITLE
Inconsistent phantom type on `sha256t::Hash`

### ISSUE THREAD

**Issue by bczhc** [rust-bitcoin/rust-bitcoin#3649]
Just a quick comment... I can't see why there are both `TapLeafTag` and `TapTweakTag` used on `Hash` in the following function:
https://github.com/rust-bitcoin/rust-bitcoin/blob/d662dba8b5d0f28dae1f090703761d4159f6a8d2/bitcoin/src/taproot/mod.rs#L67-L73

Looking into other functions: `from_key_and_tweak`, `combine_node_hashes`, they are all using the same phantom type inside. I know it's just a phantom type and does no actual effects, however it just gave me some confusion when I dig into the source piece here. Is this intended somewhat?

**Comment by apoelstra** [comment]
This phantom type definitely does have "actual effects". These two hashes are different tagged hashes and will have different output. Their usage is correct according to BIP-341.

**Comment by bczhc** [comment]
Nope. I know they are used to produce "tagged hash", but in this case..

```rust
fn from_script(script: &Script, ver: LeafVersion) -> TapLeafHash {
            let mut eng = sha256t::Hash::<TapLeafTag>::engine();
            ver.to_consensus()
                .consensus_encode(&mut eng)
                .expect("engines don't error");
            script
                .consensus_encode(&mut eng)
                .expect("engines don't error");
            let inner = sha256t::Hash::<TapTweakTag>::from_engine(eng);
            TapLeafHash::from_byte_array(inner.to_byte_array())
        }

        fn from_script2(script: &Script, ver: LeafVersion) -> TapLeafHash {
            let mut eng = sha256t::Hash::<TapLeafTag>::engine();
            ver.to_consensus()
                .consensus_encode(&mut eng)
                .expect("engines don't error");
            script
                .consensus_encode(&mut eng)
                .expect("engines don't error");
            // --------------------------------------- CHANGED HERE ----
            let inner = sha256t::Hash::<TapLeafTag>::from_engine(eng);
            TapLeafHash::from_byte_array(inner.to_byte_array())
        }

        let hash1 = from_script(script_hex!("5187"), LeafVersion::TapScript);
        let hash2 = from_script2(script_hex!("5187"), LeafVersion::TapScript);
        assert_eq!(hash1, hash2);
```

This code passes. The phantom type on `let inner =` statement does nothing.

From my view, `TapTweak` tagged hash is **only** used when generating the final tweak, but is not used when generating the hash of a script leaf.

Am I missing something still?

**Comment by apoelstra** [comment]
Wow, cool! Good catch. Yeah, the existing code is just wrong -- though as you say, only in a philosophical sense since `Hash::from_engine` does not use its tag in any way.

cc https://github.com/rust-bitcoin/rust-bitcoin/issues/1552 (which I also initially struggled to understand :P).

I think we should fix this in the `hashes` API before `hashes` 1.0 (and if not, we should have something in our docs saying why we couldn't do it).

**Comment by tcharding** [comment]
The mistake is mine, introduced in commit 39f7dcb816. Fortunately it has no effect, as correctly pointed out by @bczhc. Thanks for bug the report, we should definitely fix this. 

FTR the tags _are_ different, if line 68 was changed then the code would break. They just only differ when creating the engine not when finalizing the hash (calling `from_engine`). In line 72 the hash type doesn't matter as long as its a SHA256 hash (ie. `sha256::from_engine` would also be fine but still somewhat confusing).

Thanks again for finding my bugs!
