### ISSUE TITLE
Consider exporting bech32 with a feature flag

### ISSUE THREAD

**Issue by DanGould** [rust-bitcoin/rust-bitcoin#3650]
rust-payjoin is considering using bech32 encoding within bitcoin URIs. We will depend on `bech32` with `NoChecksum` to do this. We would use a `bitcoin::bech32` export if one existed as we do `bitcoin::base64` and `bitcoin::secp256k1`. 

Would exporting `bitcoin::bech32` as an extern crate be appropriate so as to prevent duplicate dependencies downstream?

**Comment by apoelstra** [comment]
I would like this as well.

I think that if we can get `bech32` to 1.0 (and there's a reasonable path toward this, though it depends on me cutting a bunch of code so I'm unsure when I can do it..) then we could/should just reexport it without even a feature gate.

Conversely, if it's *not* 1.0 then I'm hesitant to export it even behind a feature gate...even though I would personally want to use it.

**Comment by tcharding** [comment]
We removed the public re-export back in January (https://github.com/rust-bitcoin/rust-bitcoin/pull/2381) when we were thought we were doing to be able to 1.0 `rust-bitcoin` - that is currently not even on the horizon since we shifted gears to 1.0-ing `primitives` et al.

We can re-export it and still not stress @apoelstra out about finishing `bech32` because there is loads of time.

**Comment by DanGould** [comment]
To be explicit

> Conversely, if it's not 1.0 then I'm hesitant to export it even behind a feature gate...even though I would personally want to use it.

I assume that hesitation comes from not wanting to expose an unstable pre-1.0 bech32 crate API in a 1.0 rust-bitcoin since that would break the promise that everything it exposes is stable.

**Comment by DanGould** [comment]
I think downstream I can depend on `bech32 = "*"` to match the version from rust-bitcoin already in cargo.toml, so re-exporting it isn't a huge win and certainly not a necessity if it creates overhead that needs to be managed in this repo.
