### ISSUE TITLE
NodeInfo Ord should be explicitly implemented

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#3654]
In our TaprootBuilder::with_huffman_tree function we sort Taproot trees by a tuple (u32, NodeInfo). The u32 is a user-provided "weight" representing the probability a branch will be taken. In case of ties, NodeInfo is used.

This means that if Ord changes on NodeInfo, it will change the shape of Taproot trees, potentially catastrophically changing addresses out from under people. We should make Ord explicit and document this dependence on order.

**Comment by shinghim** [comment]
IIUC the `NodeInfo` struct has members that will be compared as part of the `Ord` impl on `NodeInfo`. Should the types of `NodeInfo`'s members also explicitly implement `Ord`? At least one of the members (`TapNodeHash`) is defined in a macro, so stripping that out might get a little hairy

**Comment by apoelstra** [comment]
I think it's ok to leave the derived `Ord` on `TapNodeHash`. The ordering on hashes is already a "do not change or great evil will come to you" thing.
