### ISSUE TITLE
Not able to update dependencies

### ISSUE THREAD

**Issue by Harshit933** [rust-bitcoin/rust-bitcoin#3668]
Hello, I was trying to upgrade the bitcoin dependencies namely:

`bitcoin 0.30.2 -> 0.31`
`bitcoin_hashes = 0.12.0 -> 0.15`

While doing so I noticed that `bitcoin_hashes::hex::HexIterator` does not exist. What I wanted to do is to iterate over the hex of transaction and then decode with `bitcoin::consensus::Decodable::consensus_decode()`. I was not able to find much info regarding this on docs.rs. Can anyone point me to the right direction?

Thanks.

**Comment by tcharding** [comment]
You can deserialize a `Transaction` from hex using `consensus::deserialize::<Transaction>(&hex)`.

We have an issue somewhere to make this more obvious but I can't find it right now.

**Comment by tcharding** [comment]
And in case you really want to know how to iterate over bytes of a hex string see the implementation of that function on `master`. (I did not look back at `v0.31` though when answering this question)

**Comment by Harshit933** [comment]
Thank you, `consensus::deserialize_hex::<Transaction>(&hex)` does the job!
