### ISSUE TITLE
units: Review the `amount::serde` module

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3709]
This module has a bunch of public stuff (eg `pub trait SerdeAmount`) - do we _really_ want to commit to everything in there?

**Comment by apoelstra** [comment]
We shoud review it, but my guess is that the answer is yes. serde stuff will always be inherently ugly and if it's namespaced inside the `serde` module it's mostly harmless.

If we have utility traits we ought to seal them though.

**Comment by tcharding** [comment]
- [x] All traits are sealed
- [x] Audit all public types
