### ISSUE TITLE
`hashes` manifest catagories

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3731]
While looking through the [list of catagories](https://crates.io/category_slugs) I see that there is a 'cryptography' category - should `hashes` add that?

**Comment by apoelstra** [comment]
Yes, if we can -- but I think there is a maximum limit on the number categories we can use and in at least some of our crates we've maxed out.

So if we can fit `cryptography` we should and if we still have room for `no-std` then we should.

**Comment by tcharding** [comment]
`cargo publish -p bitcoin_hashes --dry-run` works with

```
categories = ["algorithms", "a", "b", "c", "d"]
```

FWIW `keywords` is limited to max 4 - I hit this before.

**Comment by apoelstra** [comment]
It's a crates.io limitation so I don't believe `cargo publish --dry-run` will catch it.
