### ISSUE TITLE
Serializing then deserializing an OutPoint fails

### ISSUE THREAD

**Issue by canndrew** [rust-bitcoin/rust-bitcoin#374]
This is easy to reproduce:

```rust
use bitcoin::hashes::{sha256d, Hash};
use bitcoin::OutPoint;

fn main() {
    let out_point = OutPoint {
        txid: sha256d::Hash::hash(&"foobar"[..]),
        vout: 0,
    };
    let serialized = bincode::serialize(&out_point).unwrap();

    // This line panics.
    let _deserialized: OutPoint = bincode::deserialize(&serialized).unwrap();
}
```

The error message is "invalid type: sequence, expected a struct"

**Comment by canndrew** [comment]
I've PR'ed a fix for this: #375

**Comment by stevenroose** [comment]
Could you perhaps add round-trip tests with bincode for all our serde-serializable types?

**Comment by apoelstra** [comment]
Lol Steven, I just asked him to remove the bincode tests in https://github.com/rust-bitcoin/rust-bitcoin/pull/375

**Comment by stevenroose** [comment]
Lol, fair enough. I don't know how important bincode is in the ecosystem. It makes sense to explicitly support more serialization formats than JSON. But I agree that serde should have a way to test implementations that should cover all serde-based serializations.
