### ISSUE TITLE
no such command public-api

### ISSUE THREAD

**Issue by yancyribbens** [rust-bitcoin/rust-bitcoin#3764]
cargo check-api produces the following error: `error: no such command: public-api`

Is it required to install https://crates.io/crates/public-api?  I tried installing it as a dev dep to units where I'm trying to run the update but I'm still encountering the error.

**Comment by storopoli** [comment]
The error message is not helpful. Because it is a subcommand of `cargo`. You need to install https://crates.io/crates/cargo-public-api

**Comment by storopoli** [comment]
Ideally we would include a function `need_cargo_public_api` here that would check if the user has installed it or not with a `command -v` and then exiting `1` and giving a useful error message.

https://github.com/rust-bitcoin/rust-bitcoin/blob/7977231839a847aad181886240336c2eac7beacc/contrib/check-for-api-changes.sh#L23-L32

**Comment by storopoli** [comment]
It is also specified here https://github.com/rust-bitcoin/rust-bitcoin/blob/b68f2338c38bc2db48dcb879d48bbf6ac913b9be/CONTRIBUTING.md?plain=1#L148-L159

**Comment by yancyribbens** [comment]
@storopoli thanks, I was losing my patience with it.  Anyway, if anyone else needs to know, you must install this with `+nightly` like: `cargo +nightly install cargo-public-api --locked` for it to work with the script.
