### ISSUE TITLE
Use uniform capitalisation of segwit in rustdocs

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#3770]
Pick one and use it everywhere in rustdocs

1. segwit
2. Segwit
3. SegWit

Might as well bike shed the name, I personally don't care which one.

**Comment by storopoli** [comment]
I like 3 (SegWit). It's what people is already used to see:

1. https://en.wikipedia.org/wiki/SegWit
2. https://en.bitcoin.it/wiki/Segregated_Witness
3. https://learnmeabitcoin.com/beginners/guide/segwit/
4. https://www.investopedia.com/terms/s/segwit-segregated-witness.asp

Just some examples.

**Comment by apoelstra** [comment]
Yeah, seems like somebody on wikipedia spent the time uniformizing on `SegWit`. Good enough for me.
