### ISSUE TITLE
Tests: Missing tests for Merkle root calculations

### ISSUE THREAD

**Issue by elichai** [rust-bitcoin/rust-bitcoin#394]
We currently have no tests checking these functions directly or indirectly: 
https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/hash.rs

**Comment by stevenroose** [comment]
Did you get from a code coverage analyser? 

Because I think this test should cover that: https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/blockdata/block.rs#L264

It serializes a block and compares the calculated merkle root with the expected one.

**Comment by stevenroose** [comment]
Looking at this, I'm having some doubts about the `Block::merkle_root()` method calculating the merkle root. I think we should add `Block::compute_merkle_root()` and then either have `merkle_root` return `self.header.merkle_root` or just deprecate the merkle root method.

**Comment by kiminuo** [comment]
Just out of curiosity: [tarpaulin](https://crates.io/crates/cargo-tarpaulin) prints the following output on my machine:

```
test result: ok. 142 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

[INFO tarpaulin] Coverage Results:
|| Uncovered Lines:
|| src/blockdata/block.rs: 70-71, 98, 146, 154, 164, 179-180, 184-187, 189-193, 197, 199-204
|| src/blockdata/constants.rs: 52-53, 59-60, 89, 104, 133
|| src/blockdata/opcodes.rs: 749, 787, 795, 803, 805, 840-841
|| src/blockdata/script.rs: 47-50, 55-56, 70-72, 74, 107-108, 113, 115-125, 133-135, 196-199, 205, 345-346, 362-363, 367, 370-373, 375-377, 380-383, 385-387, 410-411, 462-463, 467-468, 477-478, 482-484, 488-489, 499-502, 504-508, 511-513, 515-517, 519-521, 523-526, 528-532, 535-537, 539-541, 543-545, 548, 564, 567, 599-601, 603-606, 608-613, 615, 648, 652, 656, 672, 699-700, 702-703, 706, 710-711, 714, 718, 721, 725, 729, 740, 818
|| src/blockdata/transaction.rs: 53, 99-100, 120-126, 132-138, 142-146, 335-338, 370, 378, 412, 418, 420, 433-436, 438, 441, 540, 551-552
|| src/consensus/encode.rs: 90-107, 113-125, 129-130, 272-273, 280-281, 304-307, 310-311, 384-386, 409, 431, 436, 439, 484, 504, 587, 623, 647, 679-681, 690-692, 814, 818, 822, 826, 830, 834
|| src/consensus/params.rs: 78-79, 89-90, 103-104, 117-118, 126-127
|| src/internal_macros.rs: 51-53, 58-60, 65, 69, 73, 81, 139-140, 168-169, 199-200, 583-585, 587, 592-593, 598, 603-606, 608, 610, 617-618, 711-713
|| src/network/address.rs: 44, 65, 84, 163
|| src/network/constants.rs: 71, 73-77, 162-163, 174-175, 187-191, 193-195, 224-225, 246-247
|| src/network/message.rs: 53-54, 59-60, 88, 201-202, 237, 258-260, 262, 277, 283, 324, 495, 532
|| src/network/message_blockdata.rs: 50-53, 60-61, 74-76
|| src/network/message_network.rs: 60, 119-120, 122-126
|| src/network/mod.rs: 47-50, 57-58, 63-67, 71-74
|| src/network/stream_reader.rs: 39-41, 67, 71, 167, 190, 232
|| src/util/address.rs: 74-81, 83, 85-86, 88, 95-99, 103-104, 136-141, 148-154, 186, 198, 313, 324, 327, 330, 336, 338, 349-350, 369, 372, 381, 388, 391-392, 395, 464, 468, 488, 499-500, 524, 530, 546, 575
|| src/util/amount.rs: 104-109, 115-116, 119-127, 144, 147, 352-353, 430-432, 434, 440-441, 453-454, 459-460, 465-466, 488-489, 502-503, 516-517, 530-531, 544-545, 614, 631, 649-650, 695-696, 704-705, 710-711, 763-765, 767, 773-774, 792-793, 798-799, 806-808, 924-925, 927-928, 930-931, 933, 935, 940-941, 943-944, 946-947, 949, 951
|| src/util/base58.rs: 43-50, 56-64, 135, 162, 168
|| src/util/bip143.rs: 50, 58, 66, 259, 265, 282, 296, 301, 318, 331, 344, 361
|| src/util/bip158.rs: 77-80, 86-89, 95-96, 182, 184, 251, 254, 270, 273, 295, 305, 311, 455, 493, 579
|| src/util/bip32.rs: 127-128, 143, 162, 170-173, 199, 209, 239, 314-317, 338-342, 344, 349-350, 372-379, 385-387, 389, 393-400, 406, 418, 422, 450, 455, 465, 522, 534, 582-583, 601, 609-610, 612, 622, 626-627, 639-640, 657, 666-667, 669, 705, 709, 713, 721, 730, 787     || src/util/contracthash.rs: 59-67, 73-77, 81-89, 111, 113, 138-143, 148, 231, 245-248, 258-259, 278
|| src/util/endian.rs: 64-65, 68-69
|| src/util/hash.rs: 34, 60
|| src/util/key.rs: 38-41, 47-50, 54-55, 61-62, 68-69, 94-97, 105, 167-168, 174, 203, 209, 227-228, 248-249, 255, 258-259, 261-262, 265, 269-270, 272, 276, 280, 284, 290-292, 294-295, 297, 305-306, 309-310, 312-313, 316, 320-321, 323, 327, 331, 334, 338-339, 341-342, 345, 349, 353
|| src/util/merkleblock.rs: 189, 193, 197-198, 203, 213, 218, 222, 296, 303, 323, 361, 460, 465, 467-468, 470, 481
|| src/util/misc.rs: 49-51
|| src/util/mod.rs: 76-80, 86-90, 94-99, 106-107, 113-114
|| src/util/psbt/error.rs: 54-65, 71-80, 82-84
|| src/util/psbt/map/global.rs: 44, 56-60, 62-64, 66-68, 70, 75, 83, 86, 99-101, 108-112, 116-117, 152, 155, 158, 161-163, 165, 171
|| src/util/psbt/map/input.rs: 64, 67, 72, 75, 77, 80, 82, 85, 87, 90, 92, 95, 97, 100-102, 105, 107, 110, 112, 115, 117, 131, 135, 139, 143, 147, 151, 155, 159, 163, 167-169, 176-177, 179-181, 184-186, 188-191, 193
|| src/util/psbt/map/output.rs: 43, 46, 51, 54, 56, 59, 61, 64-66, 68, 80, 84, 88, 92-94, 101-103, 105-106, 108
|| src/util/psbt/mod.rs: 56-60, 66-67, 69-71, 74, 78-79, 81-82, 85-86, 89, 126, 131, 143, 458, 505, 529
|| src/util/psbt/raw.rs: 45-47, 49-50, 66-68
|| src/util/psbt/serialize.rs: 69, 90, 100, 122-123, 135
|| src/util/uint.rs: 38-40, 83-85, 149, 197-200, 202, 212-213, 221-226, 228, 236-241, 243, 251-256, 258, 375-379, 387-389
|| Tested/Total Lines:
|| src/blockdata/block.rs: 89/113
|| src/blockdata/constants.rs: 61/68
|| src/blockdata/opcodes.rs: 440/447
|| src/blockdata/script.rs: 353/488
|| src/blockdata/transaction.rs: 438/478
|| src/consensus/encode.rs: 288/355
|| src/consensus/params.rs: 0/10
|| src/hash_types.rs: 4/4
|| src/internal_macros.rs: 42/76
|| src/network/address.rs: 66/70
|| src/network/constants.rs: 93/115
|| src/network/message.rs: 220/237
|| src/network/message_blockdata.rs: 36/45
|| src/network/message_network.rs: 19/27
|| src/network/mod.rs: 0/15
|| src/network/stream_reader.rs: 114/122
|| src/util/address.rs: 210/268
|| src/util/amount.rs: 365/447
|| src/util/base58.rs: 99/119
|| src/util/bip143.rs: 130/142
|| src/util/bip158.rs: 278/300
|| src/util/bip32.rs: 320/392
|| src/util/contracthash.rs: 132/172
|| src/util/endian.rs: 50/54
|| src/util/hash.rs: 26/28
|| src/util/key.rs: 87/153
|| src/util/merkleblock.rs: 215/233
|| src/util/misc.rs: 52/55
|| src/util/mod.rs: 0/20
|| src/util/psbt/error.rs: 0/25
|| src/util/psbt/macros.rs: 16/16
|| src/util/psbt/map/global.rs: 45/79
|| src/util/psbt/map/input.rs: 29/76
|| src/util/psbt/map/output.rs: 16/39
|| src/util/psbt/mod.rs: 216/240
|| src/util/psbt/raw.rs: 27/35
|| src/util/psbt/serialize.rs: 34/40
|| src/util/uint.rs: 232/275
||
82.37% coverage, 4842/5878 lines covered
```

**Comment by stevenroose** [comment]
> Looking at this, I'm having some doubts about the `Block::merkle_root()` method calculating the merkle root. I think we should add `Block::compute_merkle_root()` and then either have `merkle_root` return `self.header.merkle_root` or just deprecate the merkle root method.

@elichai thoughts? Thought I think your original concern for this issue has been addressed?

**Comment by elichai** [comment]
> Looking at this, I'm having some doubts about the `Block::merkle_root()` method calculating the merkle root. I think we should add `Block::compute_merkle_root()` and then either have `merkle_root` return `self.header.merkle_root` or just deprecate the merkle root method.

agreed. I think we should deprecate the current one as it collides with the field name. and we should add a `compute_merkle_root`

**Comment by elichai** [comment]
@kiminuo I will need to check again, my basis was the mutation tests changing everything without any test failing and the fact that I didn't find any tests, but @stevenroose showed one so I'll need to recheck

**Comment by nilswloewen** [comment]
Hello, I am a first time contributor and relatively new to rust. I have stepped through the debugger to confirm that `util::hash::bitcoin_merkle_root()` does get tested indirectly in both `blockdata::block::tests::block_test()` and `blockdata::block::tests::segwit_block_test()`.

 I am working on a PR to introduce `Block::compute_merkle_root()` with the exact same function as the current `Block::merkle_root()` and to add a deprecate tag to `Block::merkle_root()` . 
 
Could someone help me understand the possible benifit to making `Block::merkle_root()`  into a getter that returns `self.header.merkle_root` as `self.header.merkle_root` is already public?

**Comment by tcharding** [comment]
> Hello, I am a first time contributor and relatively new to rust. 

Welcome!

> I have stepped through the debugger to confirm that `util::hash::bitcoin_merkle_root()` does get tested indirectly in both `blockdata::block::tests::block_test()` and `blockdata::block::tests::segwit_block_test()`.

Well done, good effort.

> I am working on a PR to introduce `Block::compute_merkle_root()` with the exact same function as the current `Block::merkle_root()` and to add a deprecate tag to `Block::merkle_root()` .

Good work. I played around with this in my local tree, its only 7 green lines and one red. I'll leave the PR for you to do so you can get your first contribution.

> Could someone help me understand the possible benifit to making `Block::merkle_root()` into a getter that returns `self.header.merkle_root` as `self.header.merkle_root` is already public?

In Rust typically we don't provide getters/setters if the fields are public.

There only _small_ (subjective) benefit  is callers do not need to know that the merkle root for a block is in the `header` field. But as the comments above suggest, its probably less confusing if users just access the field instead of having two functions to try and decide between.

**Comment by nilswloewen** [comment]
Thanks for the friendly welcome @tcharding!

I believe this issue can be closed because we do indirectly test the merkle root calculations. 

In regards to @stevenroose 's idea earlier in this thread I have created a pull request to refactor `Block::merkle_root()` to `Block::compute_merkle_root()` [here](https://github.com/rust-bitcoin/rust-bitcoin/pull/775).

Please let me know if I should create a separate issue for this refactoring.

**Comment by tcharding** [comment]
Can we close this one @elichai, looks like all concerns have been addressed?

**Comment by tcharding** [comment]
No movement on this for ages, closing.
