### ISSUE TITLE
Nit: `Script::iter` could be improved

### ISSUE THREAD

**Issue by dpc** [rust-bitcoin/rust-bitcoin#396]
https://docs.rs/bitcoin/0.23.0/bitcoin/blockdata/script/struct.Script.html#method.iter

I just need to use this API and it seems to me it could be better:

* `iter` is a so-so name. `instructions()` would have been more descriptive
* `enforce_minimal: bool` is not documented, and is a "boolean trap" API; I would just make `instructions` and `instructions_enforce_min` or something, and let the flag be internal detail
* using `Instruction::Error` instead of  `Result<Instruction, script::Error>` makes it harder to work with common `Result`-iterating techniques, like collecting to `Result<Vec<_>>`. In essence: an error is not an `Instruction`.

**Comment by stevenroose** [comment]
I agree. Fixed in https://github.com/rust-bitcoin/rust-bitcoin/pull/397.

**Comment by Kixunil** [comment]
@dpc Huge thumbs up for noticing! I've got bitten once by `std` implementing `IntoIterator` on `Path` (can you guess what it does without looking?) and it thought me that using clearly named methods is superior. Also I noticed your other valuable contributions, thank you for them too!
