### ISSUE TITLE
Add `WitnessProgram` hash type instead of `WScriptHash`

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#400]
Bitcoin scripting system is a confusing one; so to align with the terminology with the standards I propose to introduce a `WitnessProgram` type, which, according to BIP-141, is a hash kept in the first push of P2WSH-type `pubkeyScript` or a second push in P2SH output with SegWit-enabled `redeemScript` in the spending `TxIn` ("legacy P2WSH-in-P2SH" format).

There is no reference to Witness script hash in any of the standards, so `WScriptHash` name is a confusing one.

**Comment by dr-orlovsky** [comment]
Related material: <https://gist.github.com/dr-orlovsky/b353be907e3e156864b75bbc854ceddf>

**Comment by apoelstra** [comment]
ACK. Today I learned that "witness program" refers only to the hash, and does not include the version byte push or the scriptPubkey where these are embedded. (Which is bizarre, because the hash by itself is not a program, the scriptPubkey is ... but okay, the BIP is the BIP.)

**Comment by dr-orlovsky** [comment]
It is really bizarre, I have spent plenty of my time sorting all these out. Some intermediate results: <https://github.com/LNP-BP/rust-lnpbp/blob/9e93ad202147f2ac34b507af3f0c3234e894a5f9/src/bp/scripts.rs#L14> (some explanations and chart on script type relations; the code underneath is still an early WIP)

**Comment by dr-orlovsky** [comment]
PR is ready: #402

**Comment by dr-orlovsky** [comment]
Actually, it appears that `WPubkeyHash` in P2WPKH is also a "witness program" according to BIP-141:

> A *scriptPubKey* (or *redeemScript* as defined in BIP16/P2SH) that consists of a 1-byte push opcode (for 0 to 16) followed by a data push between 2 and 40 bytes gets a new special meaning. The value of the first push is called the "version byte". The following byte vector pushed is called the "witness program". 

So everything in SegWit-enabled *scriptPubKey* after the first byte is the `WitnessProgram`, it could be a hash of the script, a hash of the public key, a taproot key - or whoever knows what it can be in the future. Seems `WitnessProgram` hash to become an enum, `WScriptHash` has to come back, and `WitnessProgram` must be constructed of `V0Script(WScriptHash)`, `V0Pubkey(PubkeyHash)`, plus `V1Pubkey(taproot::PublicKey)` options, once Taproot will be out there.

Now, regarding `WPubkeyHash`, currently it does appear in the code only twice. The first time when P2WPKH is created (and I propose above it must become an enum option under WitnessProgram). And when it does appear in our code the second time, in P2WPKH-within-P2SH format, it is actually should be named `PubkeyHash`... So seems we have to get rid of `WPubkeyHash` as the hash type!

Such a mess...

**Comment by dr-orlovsky** [comment]
After discussion under the PR #402 it was decided not to introduce scriptPubkey templates at the level of the library
