### ISSUE TITLE
amount.rs code duplication – proposed custom derive macro

### ISSUE THREAD

**Issue by murtyjones** [rust-bitcoin/rust-bitcoin#405]
There's a lot of code duplication in `amount.rs` between `Amount` and `SignedAmount` e.g.:

```rust
impl ops::RemAssign<u64> for Amount {
    fn rem_assign(&mut self, other: u64) {
        *self = *self % other
    }
}

impl ops::RemAssign<i64> for SignedAmount {
    fn rem_assign(&mut self, other: i64) {
        *self = *self % other
    }
}
```

which is solvable in a simple enough way using a procedural macro that generates the various duplicated implementations:

```rust
#[derive(Copy, Clone, Hash, SatoshiArithmetic)]
pub struct Amount(u64);

#[derive(Copy, Clone, Hash, SatoshiArithmetic)]
pub struct SignedAmount(i64);
```

```rust
impl ops::RemAssign<#num_type> for #struct_name {
    fn rem_assign(&mut self, other: #num_type) {
        *self = *self % other
    }
}
```

I have a working version of this macro that passes the `amount.rs` test suite, but wanted to check here to see whether it's worth the effort to clean up and PR, or see if there's a good reason why this type of abstraction shouldn't be included in this library.

**Comment by stevenroose** [comment]
I'm interested in this, but I'm not super worried about the code duplication. I'd like to avoid making the code less readable by doing this.
