### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#409]
With the `alloc` crate we shoud be able to make this lib no_std even though we've got `Vec` and other stuff everywhere.

**Comment by elichai** [comment]
That still requires a global allocator.
So there's still usecases like @laanwj where he uses bare metal stack only without implementing a global allocator

**Comment by TheBlueMatt** [comment]
Implementing a global allocator is pretty doable, even though it’s annoying, as long as you have enough memory to build a heap.

**Comment by apoelstra** [comment]
@elichai this would be super useful also for @stepansnigirev who would eventually like to use rust-miniscript on his hardware wallet. There are other things that need to be fixed in rust-miniscript for this, but certainly a first step is to get rust-bitcoin to be no_std.

**Comment by elichai** [comment]
For some reason I thought we were talking about rust-secp256k1.
Yes, making rust-bitcoin use alloc only would be great.

**Comment by apoelstra** [comment]
If we have to break msrv to get the alloc feature, we'll need to do that unfortunately ... but I don't think we'll need to do anything further.

**Comment by reardencode** [comment]
I was looking at trying to get the various parts of rust-bitcoin no_std. Other than alloc, there are also some uses of io (in PSBT) and error.

**Comment by elichai** [comment]
> I was looking at trying to get the various parts of rust-bitcoin no_std. Other than alloc, there are also some uses of io (in PSBT) and error.

Yeah that's an issue.
We use Read/Write/Cursor/BufReader quite extensively.
I don't really get why they're even in libstd. but we could either implement them ourselves or use https://github.com/jethrogb/rust-core_io

**Comment by Kevingislason** [comment]
What would it take to reimplement Read, Write, Cursor, and BufReader for the purposes of this? Would it be sufficient to write (e.g.) a Cursor replacement that only implements the methods rust-bitcoin currently uses? Or would it be necessary to write a 1-to-1 drop-in replacement in case someone eventually wants to use (e.g.) "write_vectored"?

**Comment by Kixunil** [comment]
FYI, I made a crate called [`genio`](https://crates.io/crates/genio) which aims to bring IO traits to `no_std`. It has some old concepts (doesn't use `MaybeUninit` nor vectored operations) and I wanted to update it recently, but It's not an entirely easy task to do **well**. I think that after redesign it would become even less like `std::io`, but I believe it'd be better.

**Comment by justinmoon** [comment]
Another crate that might be useful: [bar-io](https://github.com/bbqsrc/bare-io)
