### ISSUE TITLE
Support for Tor addresses

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#421]
Right now the library fails if there is an attempt to use Tor address: https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/network/address.rs#L56

I propose to add support for the Tor to the library. I have made a draft implementation of a generic address code that supports IPv4, IPv6 and Tor with a compact data structure (`union`) type and some convenience layer on top of it: https://github.com/LNP-BP/rust-lnpbp/pull/24/files

I think it may be worth adding to `rust-bitcoin`

**Comment by apoelstra** [comment]
What would the scope of adding Tor to the library be? Actual Tor support? or just parsing / serializing addresses?

**Comment by dr-orlovsky** [comment]
I assume both. At least I need Tor addresses in rest-lightning (for addressing other nodes and connecting to them, so both parsing & actual support), but it seems reasonable to push them all the way up to rust-bitcoin.

**Comment by apoelstra** [comment]
rust-bitcoin currently has no real networking support (it supports parsing and serializing network messages, but is transport-agnostic).

I wouldn't mind supporting Tor addresses analogously to our current network address support, but meaningful Tor support seems like it might multiple the complexity of the library severalfold.

It might be okay if it were feature gated I suppose.

**Comment by elichai** [comment]
@dr-orlovsky Why an enum+union instead of a rust enum with the data in it?

It seems this adds 1 byte of overhead because rust store's it as a union of structs each struct like this: `struct VariantA(Tag, Data)` the tag is u8 aligned, and here IPv6 will be aligned for u16 so it will require a single padding byte.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ecd4159358d2d8960b8f9c1e7087e67f

**Comment by dr-orlovsky** [comment]
@elichai agree, just come to the same conclusion in this comment: https://github.com/LNP-BP/rust-lnpbp/pull/24#issuecomment-609375435

**Comment by dpc** [comment]
Please see my follow-up. [I think everything can fit in 16B, which might worth some `unsafe`.](https://github.com/LNP-BP/rust-lnpbp/pull/24#issuecomment-609465971)

**Comment by dr-orlovsky** [comment]
I think what we need is a simple way of serializing addresses (IPv4, IPv6 & TORv3) for sending over network or in IPCs. Also it will be good to have a string parser, that is able to take these addresses from command-line arguments. The third option which we might consider is simple storage in SQL databases (like SQLite) for state persistence (like in LN nodes) for peer address lists.

Here my analysis for the possible options
Use case |  Needs fixed length | Box'ed pointers
* function arguments | no | will fail with multithreads
* network setialization | maybe | more serialization steps
* command-line agrument parsing | no | no advantage
* SQL column storage | yes | more serialization steps

My original idea was to fit all the data into [u8; 32] (minimum requirement for TORv3) and use `unit` for accessing parts of this storage w/o the need to ignore non-occupied bytes in code each time. However it leads to `unsafe` code.

The other option is to use `enum` and just have a special 32-byte fixed serializer which can be used in case of SQL storage.

I do not see benefits of having `Box`ed TOR addresses; it will increase number of the required serialization steps and may create issues with multithreading.

As a side note, `rust-lightning` was also experimenting with universal Tor-supporting addresses https://github.com/rust-bitcoin/rust-lightning/blob/master/lightning/src/ln/msgs.rs#L250, however they intermixed port in there, and I'd prefer to have pure internet addresses with the ability to add port at another layer.

**Comment by dr-orlovsky** [comment]
FYI: have refreshed the original sample PR https://github.com/LNP-BP/rust-lnpbp/pull/24 according to our discussion and the analysis above ^^^

If you are ok with the code, I will just migrate it to `rust-bitcoin` and make a PR here

**Comment by Kixunil** [comment]
I'm not sure if this is the right layer, but wouldn't it be better to support arbitrary domain names?

**Comment by dr-orlovsky** [comment]
It's another layer, yes. We would need to integrate DNS services, it's non-required dependency for the library. This is usually done at app level.

**Comment by stevenroose** [comment]
Would it make sense to wait for full [BIP-155](https://github.com/bitcoin/bips/blob/master/bip-0155.mediawiki) support to include Torv3 addresses?

**Comment by dr-orlovsky** [comment]
It would. Meanwhile we are finalizing this part within LNP/BP library and will be happy to move it to rust-bitcoin once BIP-155 will be out

**Comment by dr-orlovsky** [comment]
Just as an update, here is our types impl supporting both Onion v2 and v3 addresses: https://github.com/LNP-BP/rust-amplify/blob/master/src/internet.rs

**Comment by jrawsthorne** [comment]
If we decide to add tor parsing it can be added to https://github.com/rust-bitcoin/rust-bitcoin/pull/449

**Comment by sgeisler** [comment]
Can this be closed? After #499 got merged we now have a consensus-encodable address type. It doesn't have a human readable representation, but that would be hard given that it has to support unknown address types. I think if there were another crate implementing a BTC network stack it could/should have its own address enum, only containing the addr types it actually supports, and that can be constructed from ours.

**Comment by dr-orlovsky** [comment]
Seems like we do not need this issue anymore
