### ISSUE TITLE
P2WPKH address generation accepts PublicKey where compressed = false

### ISSUE THREAD

**Issue by junderw** [rust-bitcoin/rust-bitcoin#427]
All public keys in the witness stack are required to be compressed.

I can generate a P2WPKH address by passing an uncompressed key.

Example:

```
[dependencies]
rand = "0.6"
bitcoin = { version = "0.23.0", features = ["rand"] }
```

```rust
use rand::rngs::OsRng;
use bitcoin::secp256k1::Secp256k1;
use bitcoin::util::key::PrivateKey;
use bitcoin::network::constants::Network::Bitcoin;
use bitcoin::Address;

fn get_new_key() -> PrivateKey {
    let secp = Secp256k1::new();
    let mut rng = OsRng::new().expect("OsRng");
    let (secret_key, _) = secp.generate_keypair(&mut rng);
    return PrivateKey{
        compressed: false,
        key: secret_key,
        network: Bitcoin,
    };
}

fn main() {
    let privkey = get_new_key();
    let secp = Secp256k1::new();
    let pubkkey = privkey.public_key(&secp);

    assert!(pubkkey.compressed == false);
    let address = Address::p2wpkh(&pubkkey, Bitcoin);

    println!("WIF: {}\nAddress (p2wpkh): {}", privkey.to_wif(), address);
}

```

**Comment by elichai** [comment]
Hmm that's interesting, we don't currently return a Result/Option from these functions, so we probably need to change that

**Comment by junderw** [comment]
Checking p2wpkh and p2shwpkh should be straight forward, just check compressed == true.

p2wsh however... I think parsing the witnessScript and checking for any 65 byte pushes that start with 0x04, and if any, check to make sure it's a valid pubkey (instead of some random 65 byte piece of data that's not a pubkey that just happens to have a 0x04 at the beginning) and if it is return an error.

Though I can't really think of a use case that would use a 65 byte push besides an uncompressed pubkey, so maybe checking if it's a valid pubkey isn't worth it. Checking the 0x04 byte seems costless once you've already parsed the witnessScript.

**Comment by junderw** [comment]
Finding this issue lead me to fix it in our library:

https://github.com/bitcoinjs/bitcoinjs-lib/pull/1573

We had checks inside TransactionBuilder and Psbt classes for creating transactions, but by the time you've generated an address (we use our Payments API for that) and sent money to it it's too late...

**Comment by stevenroose** [comment]
Solved this here: https://github.com/rust-bitcoin/rust-bitcoin/pull/428.

**Comment by tcharding** [comment]
Is there anything else you wanted to highlight with this issue @junderw? Looks to me like it can be closed.

**Comment by tcharding** [comment]
thanks @junderw
