### ISSUE TITLE
Address cannot be built from coinbase tx script

### ISSUE THREAD

**Issue by gcarq** [rust-bitcoin/rust-bitcoin#441]
Hi, I'm having an issue with parsing coinbase transactions. They seem to be recognized as `p2pk` but the address is `None`.
This is reproducible for coinbase txs until height ~900 including the genesis block.

```
    // height: 0
    // txid: 4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b
    // script: 4104678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5fac
    let bytes: &[u8] = &[
        65, 4, 103, 138, 253, 176, 254, 85, 72, 39, 25, 103, 241, 166, 113, 48, 183, 16, 92, 214,
        168, 40, 224, 57, 9, 166, 121, 98, 224, 234, 31, 97, 222, 182, 73, 246, 188, 63, 76, 239,
        56, 196, 243, 85, 4, 229, 30, 193, 18, 222, 92, 56, 77, 247, 186, 11, 141, 87, 138, 76,
        112, 43, 107, 241, 29, 95, 172,
    ];
    let script: Script = Script::from(Vec::from(bytes));
    let address = Address::from_script(&script, Network::Bitcoin);
    assert!(&script.is_p2pk());
    println!("address: {:?}", &address); // None
```

**Comment by sgeisler** [comment]
This behavior is intentional. There never was an address standard for p2pk scripts. Somehow someone just used the p2pkh scheme for p2pk scripts too, which is a bit silly as you can't reconstruct the script from the address. Bitcoin Core still shows these addresses in some cases, but doesn't recognize them when [searching for UTXOs](https://mobile.twitter.com/sebx2a/status/1264878550160728075).

**Comment by gcarq** [comment]
@sgeisler I didn't know that, thanks. Does the `Builder` or `Script` API allow replicating this behaviour in its current state? I'm in the process of replacing my code with this library and I don't want to break things that were working before. Any pointer is appreciated

**Comment by sgeisler** [comment]
You could probably just build a little helper serialization function that uses the `Address` type for all but p2pk addresses and if a script is p2pk you use your [own implementation like this](https://gist.github.com/sgeisler/84448bf71eadb17f5b2b34cce7045754) for serialization.

**Comment by gcarq** [comment]
Awesome, thank you!

**Comment by sgeisler** [comment]
Idk if the ergonomics would be any better, but you might also use the `iter` method of `Script` and get the first `Instruction` which should always be a `PushBytes`. That would avoid the branching for compressed/uncompressed keys.
