### ISSUE TITLE
ChainHash type: best location

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#481]
Lightning network has defined a `ChainHash`: a u32 number identifying network version, which is the hash of genesis block (https://github.com/lightningnetwork/lightning-rfc/blob/ffeece3dab1c52efdb9b53ae476539320fa44938/00-introduction.md#chain_hash)

However, now ChainHash is not anymore just a Lightning feature: it will be used in on-chain part of DLCs (https://github.com/discreetlogcontracts/dlcspecs/blob/master/Protocol.md#the-offer_dlc-message) and we plan to move to it in RGB. This type is useful, since it allows support of an open set of network; for instance it's quite simple to add support for Liquid w/o data structure modifications. I was planning to implement this type in LNP/BP library (library for L2/L3 applications), but taking the fact that rust-lightning uses this type, I think it worth putting it into rust-bitcoin.

Right now rust-bitcoin provide "Network" type; I propose to introduce this second type `ChainHash` as a part of `util` mod.

**Comment by apoelstra** [comment]
Yeah this seems reasonable to me

**Comment by tcharding** [comment]
Is this still under discussion?

**Comment by dr-orlovsky** [comment]
@tcharding it seems that it just awaits implementation, and I simply forgot about it. Will do in the next week or so
