### ISSUE TITLE
Exposing serialized data for transaction signatures

### ISSUE THREAD

**Issue by ipaljak-tbtl** [rust-bitcoin/rust-bitcoin#483]
Hi,

my name is Ivan and I'm a software engineer at TBTL. We are working on integrating bitcoin into one of our products and are considering using your crate to do most of the heavy lifting. While reviewing your crate, I wasn't able to find whether you expose serialized data from which transaction signatures should be produced.

From what I understand, you expose the hash of that data (e.g. `signature_hash` function in `src/util/bip143.rs`). Is there a way for us to retrieve the bytes before the hashing takes place? It's important for our use-case that the signature (including the hash) is produced by an HSM device.

**Comment by dr-orlovsky** [comment]
Hi,

All the data are serialized directly into SigHash engine, which means that there is no place where you can take unserialized data.

So yes, having unserialized data will require a PR

**Comment by ipaljak-tbtl** [comment]
Understood, thanks. 

I'll discuss this further with the team and most likely open a PR linked to this issue. In case we decide to pursue a different approach or find another workaround, I'll let you know and close the issue.

**Comment by dpc** [comment]
I'm not sure if I understand correctly, but you could probably extract the code from https://github.com/rust-bitcoin/rust-bitcoin/blob/addb54ffc737508b446d48f9092914d69868050e/src/blockdata/transaction.rs#L323 iinto a new function to allow passing a custom `w : Write`, and make the current `fn signature_hash` call it with `let mut engine = SigHash::engine();`. This way people can plug their own custom `w : Write` if they want to capture it for some reason.

**Comment by ipaljak-tbtl** [comment]
Yeah, that sounds like the way to go.

**Comment by apoelstra** [comment]
We ought to expose this, let's target that for the next release. It's really helpful for debugging.

**Comment by ipaljak-tbtl** [comment]
This is already [done](https://github.com/rust-bitcoin/rust-bitcoin/pull/485) and released. The issue can be closed in my opinion.

**Comment by apoelstra** [comment]
Lol! I totally forgot about that PR. Awesome.
