### ISSUE TITLE
We should forbid hybrid pubkeys

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#520]
We are having a roundtrip failure in our miniscript fuzztests because rust-bitcoin reads a hybrid pubkey, interprets it as "uncompressed" because it's 65 bytes in length, then re-serializes it using the compressed flag rather than the hybrid one.

https://github.com/rust-bitcoin/rust-miniscript/pull/167/checks?check_run_id=1415963534

There is no base58 encoding for privkeys corresponding to hybrid keys, and probably nobody remembers that this kind of key exists (although it is legal to use them on the network, pre-segwit). I think we should just refuse to parse them in this library.

**Comment by tcharding** [comment]
Can you provide more context please, I don't know what a hybrid key is and could not find reference to this term via a web search. This link is broken also.

**Comment by apoelstra** [comment]
I am troube finding the correct citation. But hybrid keys are 65-byte keys prefixed with hex 6 or 7, where the choice of value indicates the parity of the key. (This is strictly redundant because the key contains the entire y coordinate, so the parity does not need to be communicated separately.)

**Comment by Kixunil** [comment]
Are they present in any blocks? If not then I don't think we should forbid them.

**Comment by apoelstra** [comment]
I don't think they are, but they are legal (not standard) in pre-segwit transactions.

**Comment by apoelstra** [comment]
Having said this, keys only appear in blocks as parts of scripts .... and nothing in this library ever parses keys out of scripts ... so I am not sure what benefit we would have from continuing to allow them to be parsed as keys in this library.

**Comment by TheBlueMatt** [comment]
It does feel very unexpected that you can see a "<bytes> OP_CHECKSIG" as a script and then fail to parse the bytes as a public key, whether the library does it for you or not. I suppose documentation could suffice, but maybe we'd want a parse_pk_consensus or something else dumb like that?

**Comment by Kixunil** [comment]
We could also support them with minimal runtime cost - just another branch when serializing. The `PublicKey` type already "wastes" 7 bits, so changing `compressed: bool` to `encoding: KeyEncoding` would be mostly fine. Adding `fn compressed(&self) -> bool` would cause a helpful compiler message that it's a method and needs to be called, although, `is_compressed()` is the idiomatic name. Maybe we could deprecate it immediately which would guide people through the refactoring.

Or we could have `struct ConsensusPublicKey` and appropriate conversions.

Not sure if worth the effort. If `compressed` was a method from the beginning it'd be much less pain I guess.

**Comment by apoelstra** [comment]
@TheBlueMatt `secp256k1::PublicKey::from_slice` will parse the key, if you need to parse it for some reason. But if you are doing consensus stuff you should just use libbitcoinconsensus, which will do the right thing (treating the key as a byte vector, until it hits a CHECKSIG, in which case it asks libsecp to parse it).

@Kixunil we absolutely should not give any actual API support to hybrid keys. They have no reason to exist, (probably) have never been used, and are not legal post-segwit.

**Comment by TheBlueMatt** [comment]
Fair enough. We'll want to document this, then, noting that public keys in consensus may appear without the ability to derive an address for them.

**Comment by apoelstra** [comment]
I don't think it's rust-bitcoin's job to document that. It should maybe be on the Bitcoin Wiki or something.

**Comment by RCasatta** [comment]
I checked on main chain and pubkeys always starts with hex 2,3 or 4

**Comment by dr-orlovsky** [comment]
@RCasatta we will never known which P2SH scripts in UTXOs contain them - so we do not know were they used in fact or not. @apoelstra am I right that such P2SH UTXO may be spent post-SegWit in a non-SegWit tx?

**Comment by apoelstra** [comment]
@dr-orlovsky yes, you are correct. But this continues to have nothing to do with this library, which never parses keys out of scripts except by using fixed templates, none of which allow hybrid keys.

**Comment by sanket1729** [comment]
concept ACK. `bitcoin::PublicKey` should not allow parsing non-standard keys.

**Comment by sanket1729** [comment]
Adding a good first issue label. Only Uncompressed keys with 0x04 prefix should be valid. Everything else should be treated as invalid.

**Comment by tcharding** [comment]
Looks like this was resolved by https://github.com/rust-bitcoin/rust-bitcoin/pull/829, any reason not to close this?

**Comment by Kixunil** [comment]
For the error message thing we should have a separate one.
