### ISSUE TITLE
scripts should be a copy-on-write type rather than always owning their vec

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#522]
Scripts are already read-only (we have the `Builder` type for modifying them) so it's quite limiting that there's no way to cheaply convert a byteslice as a script. For example you can't directly take a witness script off the witness stack to use it as a script_code in sighashcache.

**Comment by dpc** [comment]
Could that lead to lifetime pollution of all structs owning `Script` (which would now be more like `Script<'a>`). ? Maybe it would be better to have a `ScriptRef<'a>` with some conversion and such, and then `Cow` can be used by combining them where useful?

**Comment by apoelstra** [comment]
Yeah, good point, it would result in a ton of pollution in `TxOut` etc. I like this `ScriptRef` idea.

**Comment by dpc** [comment]
BTW. Maybe there's an existing macro to help with this use case. I did this many times before manually, and it seems clear to me that it's very common.
