### ISSUE TITLE
PSBT key vs bitcoin key naming confusion

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#532]
Very strange bug which I am trying to narrow down to the source. Origins & details: https://github.com/LNP-BP/rgb-node/issues/102#issuecomment-747308893

**Comment by dr-orlovsky** [comment]
This happened to be not an issue of this library, however the issue was caused by a naming ambiguity, which will be nice to fix. Renaming issue description. For more details pls check https://github.com/LNP-BP/rgb-node/commit/2e549cd3491db2e412a5f0543d9495b750d2d3ae#r45253641

**Comment by apoelstra** [comment]
What is the proposed solution here?

Given that the rgb bug turns out to have been caused by somebody using trait magic (with an external trait no less) to bypass typechecking between keys and byte vectors, I don't think there's anything sane that this library could do to prevent that.

**Comment by dr-orlovsky** [comment]
What about renaming `bitcoin::PublicKey::key` field into `secp_key` or `inner`? While you are right that the referenced bug is not a problem of `rust-bitcoin` API, two kinds of unrelated things sharing the same name (Secp key inside bitcoin key and PSBT key) are still confusing.

**Comment by apoelstra** [comment]
Yeah renaming to `inner` sounds good to me.

**Comment by apoelstra** [comment]
I agree that writing `key.key` is pretty weird feeling, especially when these are included in some more featureful miniscript key and then it's `key.key.key`..

**Comment by dr-orlovsky** [comment]
Will do this as a part of larger `bitcoin::PublicKey` refactoring discussed before (required for creating umbrella type for all public key forms including xcoord-only)
