### ISSUE TITLE
Doing `#[repr(C)]` for the main data structs

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#534]
I have plans of using rust-bitocoin structures - like `OutPoint`, `Transaction`, `TxIn` etc through C FFI in other languages (since Bitcoin Core can't be easily compiled as a library). What do you think, can we add `#[repr(C)]` to these structures?

**Comment by elichai** [comment]
Not really, because they use Vec`<T>` which isn't repr(C), you could export your own types that will have a C-like layout using pointers etc.

**Comment by apoelstra** [comment]
I can see the value here for `OutPoint` ... but are there any other structures that don't have `Vec`s inside of them?

This is somewhat related to our libstd dependency.

**Comment by dr-orlovsky** [comment]
@apoelstra agree, `OutPoint` is the main need. I see the problem with Vec, yes...

**Comment by dpc** [comment]
Maybe each type should just have a a C-abi accessors to its internals? Could probably be `derive`d, could work with arrays by returning a pointer and length and possibly avoid any copies (not sure how well cross-package linker level optimizations work in a presence of Rust/C FFI).

**Comment by dr-orlovsky** [comment]
@dpc not sure how this can work w/o creating other struct; otherwise if FFI is **unstable** for in-memory data representation, accessors would not help

**Comment by dr-orlovsky** [comment]
Did `repr(C)` for `OutPoint` and `SigHashType`: https://github.com/rust-bitcoin/rust-bitcoin/pull/535

This also required modifying `bitcoin_hashes`: https://github.com/rust-bitcoin/bitcoin_hashes/pull/108

**Comment by TheBlueMatt** [comment]
Another option is to auto-generate a wrapper crate which just exposes a struct that is a copy with `#[repr(C)]` and has appropriate conversion functions. In the common case, once LTO'd the conversion functions will go away. We do this for rust-lightning, not sure if our generator would work for rust-bitcoin, but its probably not too far off.

**Comment by apoelstra** [comment]
@TheBlueMatt that sounds extremely useful for interoperating rust-bitcoin with existing C projects

**Comment by Kixunil** [comment]
> not sure how this can work w/o creating other struct; 

That's actually easy if the returned data types are simple enough:

```rust
// Callable from C
// The caller is only allowed to pass a valid pointer obtained by INSERT_SOME_OTHER_FN
// Returned pointer always points at the beginning of 32 byte-long array
// The returned pointer is never NULL
pub extern "C" fn outpoint_txid(this: *const Self) -> *const u8 {
    unsafe {
        (*this).txid.as_ptr()
    }
}
```

A nice thing about this approach is it could actually allow access to non-`repr(C)` fields. For instance returning a pointer to contents of `Vec` is possible if the items are primitive.

Note that `repr(C)` will deactivate Rust-specific optimizations such as reordering of the fields. To keep them, they need to be implemented manually before adding `repr(C)`. This will also prevent any optimizations that would appear in the future.

I think it's much nicer to not add `repr(C)` and instead create a separate API for C. This APi will be stable but not guaranteed to be as efficient as if written in Rust.

Not an expert on LTO, so IDK if it removing conversion @TheBlueMatt suggests is realistic but if someone cares about copying a few bytes perhaps it'd be more sensible to write such performance-sensitive code in Rust in the first place. Also, would be nice if the auto-generator could optimize those `repr(C)` structs.

**Comment by TheBlueMatt** [comment]
Seems like the consensus is not to do this, gonna close, can discuss further if needed.

**Comment by Kixunil** [comment]
Note that I would ACK a correctly written `librustbitcoin` c lib crate as a subdirectory of this project that implements accessors. :)
