### ISSUE TITLE
Documentation outdated?

### ISSUE THREAD

**Issue by omarabid** [rust-bitcoin/rust-bitcoin#556]
I'm a bit confused whether documentation is outdated or I'm using this the wrong way.

Link: https://docs.rs/bitcoin/0.26.0/bitcoin/util/address/index.html

1. Apparently `secp256k1` doesn't have the `rand` library anymore

`use bitcoin::secp256k1::rand::thread_rng;`

2. Using s.generate_keypair throws the following error

```
   |
11 |             key: s.generate_keypair(&mut thread_rng()).1,
   |                    ^^^^^^^^^^^^^^^^ method not found in `bitcoin::secp256k1::Secp256k1<bitcoin::secp256k1::All>`
```

**Comment by shesek** [comment]
You need to enable the `rand` feature.
