### ISSUE TITLE
Sanity check scripts before converting from Vec? 

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#571]
It is currently possible to create `Script` objects that are invalid bitcoin scripts. For example, having `OP_PUSHBYTES72 <50 byte object>`. Should have change the method 

https://github.com/rust-bitcoin/rust-bitcoin/blob/5bd61967b231939626dd847fd82cc5da33052dc1/src/blockdata/script.rs#L533-L536

to return a Result instead? This will affect all projects downstream. 

We don't have TryFrom(1.34 MSRV), so changing this to a method will allow us to return a Result

**Comment by sgeisler** [comment]
I think not guaranteeing any invariants was a conscious decision. Otherwise you had to decode the entire thing, e.g. calling the `Script::instructions` method and consuming all elements, checking for an error, just to construct a `Script`. It might avoid some errors in member functions, but probably not all. I'm not sure which API is more useful in practice, but having a lazy API doesn't seem obviously bad (as much as I like types with strong invariants).

Would such a change make your life easier somewhere?

**Comment by apoelstra** [comment]
You can put invalid scripts on the blockchain. If we tried enforcing this invariant we'd have to change the type of `TxOut::script_pubkey`.

**Comment by thomaseizinger** [comment]
I am using this function to correctly compute the fee needed for a transaction where I know the _size_ of the locking script already but not the actual script. It is convenient to construct a dummy script in the form of `Script::from(vec![0u8; length])`.

For my usecase, I could work around it by constructing the actual script with dummy keys etc but it is quite convenient that I can just do it based on the size.

**Comment by sanket1729** [comment]
Based on comments by Thomas Eizinger and Andrew, I am convinced that we should not change it. 

@sgeisler, it would make using the `.instructions_minimal()` return an `Item = Instruction` instead of `Item=Result<Instruction, Error>` which is much more convenient.

**Comment by thomaseizinger** [comment]
> @sgeisler, it would make using the `.instructions()` iterator return an `Item = Instruction` instead of `Item=Result<Instruction, Error>` which is much more convenient.

Before you do that, take a look at [this](https://github.com/rust-bitcoin/rust-bitcoin/pull/397) PR :)

**Comment by thomaseizinger** [comment]
In particular, having `Item = Result<Instruction, Error>` plays nicely with the [`FromIterator` implementation](https://doc.rust-lang.org/std/iter/trait.FromIterator.html#impl-FromIterator%3CResult%3CA%2C%20E%3E%3E) where you can turn an iterator of `Result<T, Error>` into a `Result<Vec<T>, Error>`.
