### ISSUE TITLE
Default Display of `ChildNumber` changed with `0.26.1`

### ISSUE THREAD

**Issue by afilini** [rust-bitcoin/rust-bitcoin#608]
The default Display fmt of `ChildNumber` was changed in this commit https://github.com/rust-bitcoin/rust-bitcoin/commit/017cd71ca7330aa557626a7083dbd517bf8b983f and it's causing test failures in BDK because the descriptors we print have a different format.

Originally hardened ChildNumbers were always printed with `'`, but now that's only done when the "alternate" form is explicitly enabled, which means that just printing a path with the standard `{}` results in a different string compared to the previous releases.

**Comment by RCasatta** [comment]
Even if I a prefer the `h` over the apex I think we should stick to the apex as default, for example, if you give core a descriptor with `h` to `getdescriptorinfo` the returned descriptor contain the apex

**Comment by afilini** [comment]
Considering that the descriptor checksum is computed on the string I wonder if this breaks checksum compatibility with Core in rust-miniscript

**Comment by dr-orlovsky** [comment]
Just for the history record, this was discussed and everyone in discussion agreed that this was acceptable for minor version change: https://github.com/rust-bitcoin/rust-bitcoin/pull/567#issuecomment-797598357

If it breaks Bitcoin Core checksum compatibility this is still an issue I believe and should be fixed.

**Comment by sgeisler** [comment]
Damn it, that shows again: no matter how clever we feel about our reasons for breaking semver, we just shouldn't :grimacing:

**Comment by afilini** [comment]
I'd argue that this kind of breaking change is even worse that straight up breaking the API in a patch release: at least API changes are caught at compile time, this one just breaks the code silently

**Comment by apoelstra** [comment]
Yeah :( it breaks my heart to revert this but if we break checksums at runtime then we definitley need to fix it.

Sorry guys.
