### ISSUE TITLE
Make UInt arithmetic overflow rust-ideomatic

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#619]
From https://github.com/rust-bitcoin/rust-bitcoin/pull/578#pullrequestreview-628837994

We should follow Rust API and have different addition etc operations for UInt256 type which will at least match add (panicking) , saturating_add, wrapping_add and checked_add functions? Otherwise it's really strange that u32::add panics and UInt256 does wrapping

**Comment by dr-orlovsky** [comment]
I had to update/extend current UInt* implementations in https://docs.rs/amplify_num/0.1.1/amplify_num/ crate, and did all those arithmetic methods there, so they can be taken from it if needed here (or just use it since it is MSRV compatible)

**Comment by apoelstra** [comment]
Agreed, concept ACK.

Would also be ok with renaming `Uint` to `WrappingUint` or something and always wrapping ... but we should definitely be consistent.

**Comment by Kixunil** [comment]
I think it should be possible to impl relevant operations for `core::num::Wrapping<UInt256>`. Although some may have to be extension traits.

**Comment by dr-orlovsky** [comment]
Related: https://github.com/rust-bitcoin/rust-bitcoin/issues/620#issuecomment-950283451

**Comment by apoelstra** [comment]
I believe this is fixed by #1197
