### ISSUE TITLE
Docs.rs typo

### ISSUE THREAD

**Issue by vmenond** [rust-bitcoin/rust-bitcoin#622]
hello rust-bitcoin 

https://docs.rs/bitcoin/0.26.2/bitcoin/util/taproot/struct.TapTweakHash.html

The `Methods from Deref` part seems to not supposed to be there.

**Comment by sgeisler** [comment]
Can you go into more detail pleas? I'm not sure what's wrong with the docs. If it implements `Deref` (idk if _that_ is wise, but beyond the point) I think that should be documented?

**Comment by vmenond** [comment]
I'm newish to rust and im not sure what the Methods from Deref part is exactly for but the examples looked like examples for [u8] and not the specific TapTweakHash struct. I guess thhe examples are saying that this type can be used just like a [u8] ?

**Comment by vmenond** [comment]
And it made up nearly 90% of the content of that page, which felt odd.

**Comment by apoelstra** [comment]
Yes, you can use all the methods from `[u8]`. I think this `Deref` impl is used on all of our hash types (in fact I think the implementation is hidden inside a macro from the `bitcoin_hashes` crate). The docs are also auto-generated and we have very little control over how this impl is handled.

I agree this is confusing, but it's a confusion inherent to the Rust language, and there's not much we can do to clarify the docs here.

**Comment by vmenond** [comment]
Makes sense. Thanks for clarifying!
