### ISSUE TITLE
rust-bitcoin on a 64-bit big-endian machine (s390x) fails 50 of the 168 tests

### ISSUE THREAD

**Issue by jlatone** [rust-bitcoin/rust-bitcoin#624]
Hi, I'm using rust-bitcoin on a `s390x` (64-bit big-endian IBM Z mainframe) as a part of other projects (e.g., electrs) and I've been running into what appear to be byte-order issues. I'm wondering if the issues are with the use of rust-bitcoin, or rust-bitcoin itself, or perhaps the way I built it. I searched around and didn't find anything obvious, and I did read through #550 and it seems the way to deal with endian-ness may be unresolved--I could see this being the case since this library may not have been tested/used on a big endian machine since they're not all that accessible, unless you emulate on qemu...or work for IBM. :)

I'm only looking for acknowledgement this is an open issue, in which case I'll move away from rust for now for dealing with bitcoin, or whether I may be doing something more fundamentally wrong.

In any case, when I do the following:
```
git clone git@github.com:rust-bitcoin/rust-bitcoin.git
cd rust-bitcoin
cargo build
cargo test
```
I get these results (full output in the attached file).

`test result: FAILED. 118 passed; 50 failed; 0 ignored; 0 measured; 0 filtered out`

[New Text Document.txt](https://github.com/rust-bitcoin/rust-bitcoin/files/6717868/New.Text.Document.txt)

**Comment by Kixunil** [comment]
I was curious to see why it happens and I don't see how it could possibly fail. E.g. `serialize_checkeddata_test` transitively calls [`u32_to_array_le`](https://github.com/rust-bitcoin/rust-bitcoin/blob/e99177c4fba9ece1eb219e7980981c099bc6f2d5/src/util/endian.rs#L42-L50) which seems to be correct. The `>>` operator works on integers not memory, right? Same with `& 0xff`.

Perhaps you could test this code to see if I'm right:

```rust
fn main() {
    let mut res = [0; 4];
    for i in 0..4 {
        res[i] = ((42 >> i*8) & 0xff) as u8;
    }
     assert_eq!(res, [0, 0, 0, 42]);
}
```

**Comment by jlatone** [comment]
```
./test
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[42, 0, 0, 0]`,
 right: `[0, 0, 0, 42]`', test.rs:6:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Your test failed, and it failed in an equivalent way as the test case in the code (i.e., you could reverse the order of [0,0,0,42] and then `to_le()` the 42).

> The >> operator works on integers not memory, right?

Right, and in fact, that's the problem here. See below if you agree...or if I've been staring at byte orders too long. :)

I'm not a rust dev and I'm trying to work my way through through **gdb-rust** for `serialize_checkeddata_test`, and I'm in the following code and I think I see the issue (but it's time for a beer and I'll get back to it tonight).

At this point (see the **<<<** comment in the code), `val` is a _little-endian_ value of 5

```
macro_rules! define_le_to_array {
    ($name: ident, $type: ty, $byte_len: expr) => {
        #[inline]
        pub fn $name(val: $type) -> [u8; $byte_len] {
            debug_assert_eq!(::core::mem::size_of::<$type>(), $byte_len); // size_of isn't a constfn in 1.22
            let mut res = [0; $byte_len];
            for i in 0..$byte_len {
                res[i] = ((val >> i*8) & 0xff) as u8;   <<<<<<<< val is 5, but in little-endian <<<<<<<<
            }
            res
        }
    }
}
```

because of this 

```
        impl Encodable for $ty {
            #[inline]
            fn consensus_encode<S: WriteExt>(
                &self,
                mut s: S,
            ) -> Result<usize, io::Error> {
                s.$meth_enc(self.to_le())?;   <<<<<<<<  and here's why it's little-endian <<<<<<<< 
                Ok(mem::size_of::<$ty>())
            }
        }
```

so I see why it's serialized as [0,0,0,5], which doesn't match the test case, [5,0,0,0,...], i.e., the byte-order (from lowest memory to highest memory) of `5.to_le()` on a big-endian machine is 05 00 00 00, and the `define_le_to_array` serializer is interpreting the memory as a 32-bit int, serializing this 32-bit big-endian representation of a little-endian 5 from right-to-left (fromm highest memory to lowest memory).

**Comment by apoelstra** [comment]
Great catch, thank you! It took me a while to see this even with your code example, but I get it now. We call a `.to_le()` method in one place (which swaps bytes on BE systems and is a no-op on LE systems), and then incorrectly follow this up with manual "encode in little endian" code.

I wonder how we can fit this into CI.

**Comment by TheBlueMatt** [comment]
> I wonder how we can fit this into CI.

My immediate response to this issue was to check if Github CI supports any BE systems (it does not, ugh). We could probably leverage the new embedded test in https://github.com/rust-bitcoin/rust-bitcoin/pull/603/files#diff-e450475e0fd6a583e7a42a90988851a6c2334abc4dc1d7de83c50359662b8933 to run our test suite in some arm-be thing in qemu, though I dunno how we'd get std in there. Its better than nothing, but installing a full linux host in qemu in fully-emulated mode would be rather painfully slow.

**Comment by dpc** [comment]
> I wonder how we can fit this into CI.

I'm not how helpful it is, and there might be better examples out there, but I had a project that was aarch64 toy kernel, and I just built it for aarch64 and executed in qemu. I guess bitcoin-core could do something similar for multiple architectures, and as long as one of them is big-endian, it would cover all BE archs.

https://github.com/dpc/titanos/blob/36e255dbef22274c43b55e8e35244b1e6f48daa1/.travis.yml#L27

**Comment by dpc** [comment]
https://github.com/marketplace/actions/run-on-architecture maybe

**Comment by dpc** [comment]
> though I dunno how we'd get std in there. 

s390x-unknown-linux-gnu is a tier2 platform. Seems like BE and with Linux support.

>  installing a full linux host in qemu in fully-emulated mode would be rather painfully slow.

I haven't done it in ages, but qemu used to support userspace emulation. One can just run different arch linux elf binary, directly on a host.

* https://www.zerodayinitiative.com/blog/2020/5/27/mindshare-how-to-just-emulate-it-with-qemu
* https://rwmj.wordpress.com/2013/12/22/how-to-run-aarch64-binaries-on-an-x86-64-host-using-qemu-userspace-emulation/

**Comment by TheBlueMatt** [comment]
> I haven't done it in ages, but qemu used to support userspace emulation

Ah, true, I believe on Debian you can just install the relevant libc and then we could cross-compile and run. Good point, we should just do that.

**Comment by jlatone** [comment]
Is one approach to fix this, at least for now, to go through the test failures 1-by-1--assuming the tests check all cases--and deal with le/be by using `if cfg!(target_endian = "big") ...`?

**Comment by apoelstra** [comment]
I think the appropriate fix is probably to remove all the instances of `to_be`/`to_le` and exclusively use the manual endianness encoding. Then we're running exactly the same code on BE/LE systems, and since we don't do any direct memory access on integers (this is easy to check since it would require `unsafe` code) that should give us some assurance that our library does not have any endianness-dependent behavior.

Our test coverage is not spectactular but I think we do hit 100% of the integer encoding functions and cryptographic object encoding functions, which are the most likely location for these sorts of issues.
