### ISSUE TITLE
Consider flattening util module?

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#639]
The word `util` adds very little additional information for the reader and introduces possibly annoying `util::` part to paths. I think some things there deserve to be at top level or in better-named module.

Draft initial idea:

* `address`, `amount`, `bip32`, `key`, `psbt` could go to top-level
* `ecdsa`, `schnorr`, `taproot` within `key` or `crypto` module together with `hash`
* `merkleblock` maybe within `hash`
* `base58` probably to its own crate, or `encoding` module
* `misc` contains only signature stuff - rename to `signature` and put in top level
* `uint` - its own crate or `primitives` module

Unsure about the rest right now, I mainly want to see if people agree with general direction of this.

From my experience "util" or "misc" module may mean "a place to dump all kinds of disorganized stuff". Thankfully it doesn't mean it here yet. Would be nice if we avoided it in the future. :)

**Comment by RCasatta** [comment]
related https://github.com/rust-bitcoin/rust-bitcoin/pull/525

**Comment by dr-orlovsky** [comment]
Concept ACK, was going to propose the same for a long time...

**Comment by thomaseizinger** [comment]
I would like to add that - for the sake of API stability and ease of use - it would be nice to decouple the public API of rust-bitcoin from its internal module structure by making most of our modules private by default.

From Rust 2018 onwards, crates can be referenced everywhere by their name without any additional declaration. Hence, where possible, I would suggest flattening the public API such that most types are accessible via `bitcoin::XYZ`.

For example, I never use the `blockdata` module directly. I either import a symbol from within it directly, or reference it as a full-qualified path in my code. Having the FQP contain `blockdata` is quite noisy though and importing some symbols directly may lead to nameclashes or ambiguities.

**Comment by Kixunil** [comment]
@thomaseizinger I remember importing through `blockdata` some time ago before I noticed things I used are re-exported. :laughing: That may be another argument for doing it because the API could be less confusing.

**Comment by tcharding** [comment]
Should `util::sighash` go into `crate::crypto` or into `crate::signature`? 

- https://github.com/rust-bitcoin/rust-bitcoin/pull/1260
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1259

**Comment by tcharding** [comment]
This issue is almost resolved by the 11 open PRs in the "refactoring" project 

https://github.com/rust-bitcoin/rust-bitcoin/projects/2#card-66529916

The only things left are working out where `sighash` goes and making base58 a crate.

**Comment by tcharding** [comment]
This is done now, the only thing left in `util` is a deprecated function.
