### ISSUE TITLE
Remove feature gate from enum Error

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#645]
Feature gating enum variants of public **not** `non_exhaustive` enum is compatibility hazard as it makes Cargo features non-additive. See https://github.com/rust-bitcoin/rust-bitcoin/pull/633/files#r704806113

Suggested solution:

```rust
enum Uninhabited {}

#[cfg(bitcoinconsensus)]
type BitcoinConsensusError = bitcoinconsensus::Error;

#[cfg(not(bitcoinconsensus))]
pub struct BitcoinConsensusError {
    _uninhabited: Uninhabited,
}

// perhaps implement a few things `bitcoinconsensus::Error` implements using match self._uninhabited {}

enum Error {
    // ...
   BitcoinConsensus(BitcoinConsensusError),
}
```

This way we can get quite clean code matching on enums, we guarantee that no crate importing `BitcoinConsensusError` can do anything interesting with it unless the feature is turned on. We also prove to the compiler that we never actually construct that variant if the feature is off, so performance doesn't change (uninhabited variants are optimized-out automatically) and we avoid accidentally creating it.

**Alternative**

Make the `Error` enum `non_exhaustive` and keep the gate. AFAIR this requires MSRV bump.

**Comment by apoelstra** [comment]
Neat! I like this a lot.

And yep, we can cut a new major version. I'd like to try to get all the taproot stuff in ASAP.
