### ISSUE TITLE
Stabilization roadmap?

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#649]
Lack of stability of this crate may be a deterrent from using it (and consequently Rust) in Bitcoin applications. Is there any desire to stabilize it?

If yes, what are the things that should be changed/done before going stable?

What I can think of right now:

* Stabilize `secp256k1`
* #550
* #510
* #645 
* `#[non_exhaustive]` on `Error`, `AddressType` and possibly more
* #639 
* Go over whole crate and figure out what APIs can be future-proofed
* Perhaps rename `Transaction.{input,output}` to use plural? :)
* Taproot
* Change version to `1.0.0` which is considered API break (should be last one at least for a long period of time)

**Comment by dr-orlovsky** [comment]
Clearly, the first and foremost - complete taproot implementation, which will take a while

> Rust 2018
> #[non_exhaustive] on Error, AddressType and possibly more

Requires MSRV version bump, which is also an API break and should be probably stated separately

**Comment by Kixunil** [comment]
I felt that going to to 1.0 is pretty obvious break but no harm in writing it down. :)

**Comment by sanket1729** [comment]
I think we can think of this only after we stabilize rust-secp256k1. Because every major version change in rust-secp256k1 would require a version change here.

**Comment by Kixunil** [comment]
I've created `1.0` label for labeling things that are required or should be done before 1.0. This can help people who would like to focus on stabilizing the crate.

**Comment by tcharding** [comment]
Stabalization of all crates in our stack is the primary focus right now (and for the last year or so). This issue adds no additional information now. Closing.
