### ISSUE TITLE
Error in `Address:p2sh` if the script is more than MAX_SCRIPT_ELEMENT_SIZE

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#650]
Spotted here: https://github.com/rust-bitcoin/rust-bitcoin/pull/643#discussion_r703293794

**Comment by vss96** [comment]
@dr-orlovsky Hi, I'm interested in contributing. Is this a good first issue for someone who hasn't contributed here before?

**Comment by dr-orlovsky** [comment]
@vss96, yes, you are welcome!

**Comment by dr-orlovsky** [comment]
Closed with #655
