### ISSUE TITLE
Why PSBT needs separate Global struct?

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#652]
Currently PSBT uses sub-structure `Global` to contain the global map. However IMO this is unnecessary complixification, since all `Global` fields can be just a part of PSBT structure (and we can implement `Map for Psbt` directly)

**Comment by sanket1729** [comment]
+1, it is annoying to write .global every time.

**Comment by Kixunil** [comment]
I also found it tedious without clear benefit. IMO PSBTs could have a bunch of improvements. Such as maintaining invariant that number of PSBT inputs/outputs equals to the number of transaction input/outputs. I could send a few PRs if people agree but **not** PSBT 2 which we discussed with @dr-orlovsky recently. :D

**Comment by apoelstra** [comment]
Agreed, it would be great to clean up the PSBT struct.

I think PSBT2 is still a ways away from being merged into Core (just yesterday they released a new version which does not include it, so we have at least six months..)
