### ISSUE TITLE
Architecture support documentation (pointer sizes < 64)

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#660]
This library does **not** document whether 16 bit architectures are considered supported, yet `blockdata::script::read_uint` returns `usize` for what can go above 2^16.

Either it should be documented that 16-bit platforms are not supported or the above mentioned function should be fixed - return a different type or an error. I'm not sure which one it should be, so I'm asking here.

Same could go for 32-bit although there I would b surprised if it was unsupported and I don't know of any code that breaks besides #658 which has an easy, obvious fix.

**Comment by elichai** [comment]
Does rust currently have support for any 16bit architectures?

**Comment by Kixunil** [comment]
It does! AVR for instance. Note that it will never support less than 16 bits (`impl From<u16> for usize`).

**Comment by TheBlueMatt** [comment]
Unless there's strong demand for it, I feel like we should compile-file for 16-bit architectures. I'd love to support them, but we'd probably need a very careful read of the current codebase to do so, and add it to CI as well as make sure reviewers are cognizant of it.

**Comment by Kixunil** [comment]
> compile-file

Is it some term I don't know or a typo? I don't understand.

I feel same about the rest. Nice to have but hard to justify.

**Comment by TheBlueMatt** [comment]
Sorry, meant compile-fail.

I believe
```
const _UNUSED: usize = core::mem::size_of::<usize> - 17;
```
will suffice.

**Comment by Kixunil** [comment]
Ah, I agree.

```rust
#[cfg(target_pointer_width = "16")]
compile_error!("rust-bitcoin currently only supports architectures with pointers wider than 16 bits, let us know if you want 16-bit support");
```

Seems cleaner and I can't see any disadvantage

**Comment by TheBlueMatt** [comment]
> Seems cleaner and I can't see any disadvantage

Heh, yea, I forgot about that cfg.

**Comment by sanket1729** [comment]
> ... let us know if you want 16-bit support");

We are already compile-failing on 16-bit machines, but we should do it in a cleaner way as suggested above. I don't mind if others are interested in reviewing/rewriting the codebase for supporting it, but I don't think it's worth the effort even if someone comes asking for it.
 
```
pub const MAX_VEC_SIZE: usize = 4_000_000;
```

**Comment by Kixunil** [comment]
>  I don't think it's worth the effort even if someone comes asking for it.

That message was not intended to be a commitment that we will do all the work. :) I meant it more as a way to get feedback and if there are many independent requests (or perhaps a reward for maintainers?) then we may consider it.

**Comment by Kixunil** [comment]
Also found a way to reasonably implement what I needed in a way that doesn't break 16-bit (but it's still a bad idea to try to validate scripts on 16-bit because of size constraints).
