### ISSUE TITLE
CI fuzz tests are broken

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#667]
In two PRs nightly build report strange error on fuzzy tests which is (a) unrelated to the code changes and (b) I can't understand. I assume master also got broken.

- https://github.com/rust-bitcoin/rust-bitcoin/pull/666/checks?check_run_id=3718558662#step:5:2501
- https://github.com/rust-bitcoin/rust-bitcoin/pull/646/checks?check_run_id=3717024631#step:5:2501

**Comment by apoelstra** [comment]
Frustrating. Hopefully it resolves itself in a couple days. It looks like a honggfuzz/nightly thing out of our control.

**Comment by TheBlueMatt** [comment]
We probably shouldn't be running fuzzing on nightly. One of the reasons why honggfuzz-rs is great is we don't have to use nightly on it, so can just run fuzzing on stable and not have to deal with these things :)

In any case, looks like nightly broke things: https://github.com/rust-fuzz/honggfuzz-rs/issues/61
