### ISSUE TITLE
Using serde arbitrary-precision numerics

### ISSUE THREAD

**Issue by alexreg** [rust-bitcoin/rust-bitcoin#67]
Serde (well, really just serde-json for now) now has arbitrary-precision numerics support in its latest release! 🎊 It might thus be time to migrate to using the latest version of serde, removing the dependency on strson, and thus bringing everything up-to-date?

You may also be interested in knowing that I'm currently working on an IEEE floating-point decimal implementation for Rust, which will support serde arbitrary-precision numerics.

**Comment by apoelstra** [comment]
Unfortunately https://github.com/serde-rs/json/pull/332/files breaks compatibility with 1.14, which violates our policy of supporting whatever version of rustc debian stable ships.

Though I commend serde_json for having a policy at all about compiler support :).

**Comment by alexreg** [comment]
That’s a shame. Because you really are using an ancient version of serde here! 😉 Reconsider when the next Debian stable is released?

(I’m not sure it’s a good idea to be so conservative as to depend on Debian’s latest stable version if Rust, but I suppose you gave your reasons.)

**Comment by alexreg** [comment]
It's not even a version of Rust supported by the Rust team, it's so out of date heh. Why can't rustup be used on Debian to install a more recent stable/nightly version?

**Comment by TheBlueMatt** [comment]
I don't think "people should just be downloading binaries from a third party" is a reasonable response to "people using a distro that has focused a bunch on deterministic builds recently can't use Rust".

**Comment by alexreg** [comment]
Hardly a third party here. It's the official way to get Rust, in fact! Debian should just have a rustup package. Anyway, what's your reasoning?

**Comment by TheBlueMatt** [comment]
Yes, it is a third party. If you choose to trust Debian's folks to faithfully upload source, saying "sorry, you can't use Rust without *also* trusting the Rust folks to do the same, as well as their build servers" is kinda a shitty position. I get that rust is still moving fast and maybe doesn't make sense in a production environment outside of controlled build environments yet, but it seems overdue.

**Comment by alexreg** [comment]
Depends on your point of view, but I would consider Debian the distributor, so no, not really third party. :-P In any case, like I said, the solution is just to distribute rustup via Debian.

**Comment by TheBlueMatt** [comment]
Hmm, I think you missed my point. If you goal is to avoid trusting random build servers, Debian (well, and others) is rapidly becoming an option. rustup is not. Maybe if rustup had a better story around securing updates, though the weird "users install the software in random places instead of the 'normal' install locations" thing (correctly) frustrates some people as well. Ultimately even a Debian-distributed rustup just isn't an option for many people either.

**Comment by alexreg** [comment]
Well, you have a point about the non-standard install locations...

**Comment by TheBlueMatt** [comment]
We're not building utilities here, this is a Bitcoin library, designed to interact directly with peoples' money. Security concerns aren't something to snicker at, nor are deterministic builds and toolchain security. Sorry you feel differently.

**Comment by alexreg** [comment]
Since when does security have anything to do with this? You’re going off-track now.

**Comment by TheBlueMatt** [comment]
The point of "avoiding trusting random build servers" (ie deterministic builds, something several major Linux distros have put a ton of work into recently) is security, not to mention minimization of additional trust in yet more binary-vendors. Suggesting that Debian users be forced to use rustup is suggesting Debian users be forced to reduce their security model just to use Rust, and that sucks.

**Comment by alexreg** [comment]
Ah, okay. I don't know a lot about Linux, since I don't use it. The convention on macOS is more relaxed. Homebrew for example has a formula (package) for rust stable (updated on time) and nightly, but also one for rustup. I just use the rustup one.

**Comment by alekseysidorov** [comment]
In my opinion data types in the crate should implement `Serialize` and `Deserialize` via `consensus_encode` and `consensus_decode`, so then these types will be encoded as hex strings in string formats.
Thus problems with the accuracy of u64 in json will not arise.
And problems with json rpc will become problems of the `bitcoinrpc-crate`.

**Comment by jeandudey** [comment]
@alekseysidorov

> In my opinion data types in the crate should implement Serialize and Deserialize via consensus_encode and consensus_decode, so then these types will be encoded as hex strings in string formats.

Now that #125 is merged if you need this functionality (decoding a block or a tx from hex with `Serialize`/`Deserialize`), you can do it with `serde_derive` as the serde documentation explains in [*Deriving De/Serialize for type in a different crate*](https://serde.rs/remote-derive.html).

The *standard* way to is to implement De/Serialize for a struct is like a map (key-value pairs).

**Comment by apoelstra** [comment]
Closing, this is way out of date :)
