### ISSUE TITLE
Why do we have two `SigHashType`s?

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#670]
First one: 

https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/blockdata/transaction.rs#L676-L695

Second one:

https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/sighash.rs#L102-L126

**Comment by RCasatta** [comment]
The second one has the `Reserved` variant, here are some comments about it:

https://github.com/rust-bitcoin/rust-bitcoin/pull/628#discussion_r670280342

Nobody was super-sure about it, we can decide to remove it before release

**Comment by RCasatta** [comment]
Sorry, my previous comment was pertinent but not the real reason, the real reason it's the `Default` variant added in Bip341

**Comment by dr-orlovsky** [comment]
Can we somehow differentiate them by name, do a deprecated stuff on the old one or add necessary doc explanations on the choice of the structure?

**Comment by apoelstra** [comment]
Lol, let's just remove the one in `transaction.rs`

**Comment by sanket1729** [comment]
> Lol, let's just remove the one in transaction.rs

If we do so, we would have to add checks to existing methods to not use the new variants. At which I think that having two separate types is the correct thing.

**Comment by dr-orlovsky** [comment]
If we have to maintain both structures we need to differentiate them by name and clearly describe the purpose of both in the docs

**Comment by RCasatta** [comment]
Also, I think we are re-exporting the legacy one https://github.com/rust-bitcoin/rust-bitcoin/blob/a961ab452657a2e94925632747a1794b768c17a6/src/lib.rs#L125
