### ISSUE TITLE
Update taproot huffman tree construction to have a fallback when optimal depth > 128

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#693]
The current new_huffman_tree function fails when the optimal tree depth is greater than 128. But with a clever trick as mentioned by @JeremyRubin (https://github.com/rust-bitcoin/rust-bitcoin/pull/677#discussion_r747899503) it is possible to obtain a near-optimal tree.

Some further analysis about the approach:
- Does the above result in an optimal tree given that we are not allowed to exceed depth beyond 128?

Requires:
- Basic knowledge of tree algorithms. 
- Taproot

Can serve as an interesting beginner issue for students interested in algorithms, but anyone is welcome to take a stab at it.

**Comment by apoelstra** [comment]
I don't really like this approach. If the user expects an optimal tree then we should give them one. If an optimal tree would result in depth 128 then their weights must be wildly crazy (I'm not even certain if you can do this with `u64` weights... a good exercise for an algorithms student might be to construct a unit test which triggers this case).

**Comment by Kixunil** [comment]
If I understand correctly, if the weights are actually correct then deeper tree implies probability lower than 1:2^128 which is assumed impossible. Therefore error makes most sense.

**Comment by sanket1729** [comment]
> If I understand correctly, if the weights are actually correct then deeper tree implies probability lower than 1:2^128 which is assumed impossible. Therefore error makes most sense.

I think you are right.

**Comment by JeremyRubin** [comment]
with u64s as relative weights types maybe less than 1:2**128 is actually literally impossible?
