### ISSUE TITLE
Amount does not use minimal representation when displaying

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#709]
```rust
pritnln!("{}", Amount::from_sat(50_00_000_000).to_string_in(Denomination::Bitcoin));
```

Expected string: `50`
Got: `50.00000000`

This needlessly burdens users with meaningless zeros and causes BIP21 URIs to be longer, wasting QR space.

Ideally we would have `struct DisplayInDenomination(Amount, Denomination)` that impls `Display` with all the bells and whistles but for starters making representation minimal is fine.

I think this is easy enough for good first issue.

**Comment by vi519** [comment]
use toFixed(2)

**Comment by RCasatta** [comment]
> Got: 50.00000000

I don't think this is a bug, there are places where this visualization is recommended, for example when you show value in columns. 

As you said just `50` is more suitable for example in a QR code, so I think we need different formatting

**Comment by Kixunil** [comment]
> for example when you show value in columns

We have `Formatter` for exactly this. The way it's written now it can't be used though.

**Comment by dr-orlovsky** [comment]
Why not just to have 	`Amount` to properly implement `Display` with all bells and wissels?

**Comment by Kixunil** [comment]
I believe because of ambiguity - which denomination it should be? Should it have suffix? These things can't be configured with `Formatter` so I agree with the current design of not implementing it.

**Comment by Kixunil** [comment]
Thinking about it again, I'd like builder-pattern-like design:

```rust
impl Amount {
    pub fn display_in(self, denomination: Denomination) -> DisplayAmount { ... }
}

pub struct DisplayAmount {
    amount: Amount,
    display_style: DisplayStyle,
}

enum DisplayStyle {
    FixedDenomination { denomination: Denomination, show_denomination: bool, },
    DynamicDenomination // determines denomination based on what is more appropriate and shows it; thanks to non-pub fields this can be developed later
}

impl DisplayAmount {
    pub fn show_denomination(self) -> Self { ... }
}

impl Display for DisplayAmount { ... }
```

**Comment by dpc** [comment]
IMO, some explicit method for displaying like above is most idiomatic approach, and reminds me a bit of https://doc.rust-lang.org/std/path/struct.Path.html#method.display .

There is no clear & and good default in all context. Personally if I was to pick, I would expect number of satoshis as a default display format, but really there's no obvious cut. If `Amount` should have built-in `Display`and indeed "implement `Display` with all the bells and wistles" it should make these decisions early and stick with it, as changing anything there creates a non-trivial, sneaky and easy to overlook "functionally breaking change".

**Comment by thomaseizinger** [comment]
We could use the alternate sigil `#` to switch between:

1. sats, with no leading zeros as you would expect from a u64
2. BTC with a minimal representation, ie:

- 50 BTC
- 1.0003 BTC
- 0.01 BTC

**Comment by Kixunil** [comment]
I'm not convinced `#` sigil is good. People may want a different denomination (although most people probably want sat or BTC) or other settings. It's also not very readable `amount.display_in(Denomination::Satoshi)` is much more obvious.
