### ISSUE TITLE
consensus_encode uses unwrap

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#714]
We have many calls to `consensus_encode` that are followed by `unwrap`. IIUC `consensus_encode` can error if the writer errors. Shouldn't we be bubbling theses errors up to users?

Draft PR showing one method of removing `unwrap` from calls to `consensus_encode` for `WitnessCommitment`: https://github.com/rust-bitcoin/rust-bitcoin/pull/713

**Comment by Kixunil** [comment]
Some writers (e.g. `Vec<u8>`, hash engines...) can not fail. Thus those `unwrap()`s are correct. However I do agree they are ugly and I do think that ideally we would have some `Write` trait generic over error type so we could prove it being the case.

**Comment by dpc** [comment]
Generally it's more idiomatic to use `expect` for places that can not actually fail. `unwrap` is more of a "I don't care about handling errors" (e.g. in a test) while `expect` an assertion with a custom message "unless there's a bug, this does not fail".

**Comment by tcharding** [comment]
Done as suggested by @dpc and used `expect`. 

FTR @Kixunil I didn't really understand your suggested idea (also on #713). I figured that its an improvement on top of usage of expect anyways so I went ahead with the unwrap -> expect change.

**Comment by Kixunil** [comment]
@tcharding basically adding a trait like this:

```rust
trait Write {
    type Error;

    fn write(&mut self, bytes: &[u8]) -> Result<usize, Self::Error>;
}
```

And use it in `consensus_encode`.

It'd be obviously API-breaking but shouldn't be a huge deal. Maybe it could be mitigated by writing blanket impl. (But then hashers can't impl `io::Write`.)

**Comment by tcharding** [comment]
Oh, I think I finally get it. Then for the writers that don't error we can use `type Error = !` (or what ever we do in 1.29 to show this).

Thanks for explanation, still took me a minute to figure it out :)

**Comment by Kixunil** [comment]
Correct, old versions can just use an empty enum like this: `enum Infallible {}` and then you can write `.unwrap_or_else(|infallible| match infallible {})` to prove it won't happen. (Possibly have convenience method for this.)
