### ISSUE TITLE
Yoda conditions in tests

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#715]
I just found there's a bunch of Yoda conditions in the tests (`amount`, maybe others as well). I'd prefer to swap them but do others agree with this?

**Comment by apoelstra** [comment]
lol! Yeah, I'd like to swap them. Rust has no need for yoda conditions.

**Comment by Shatnerz** [comment]
Is this still an issue? I just grepped `src/util/amount.rs` for yoda conditionals and asserts and couldn't see anything obvious. Can you link to a specific example just to clarify?

**Comment by Kixunil** [comment]
Hmm, don't see it in `amount` anymore. Which regex did you use for grepping?

**Comment by Shatnerz** [comment]
Nothing fancy, I just manually reviewed all the `if `s (~60) and `assert` (~180) and didn't see any yoda-like statements

**Comment by Kixunil** [comment]
Ah, great, thanks for researching! I tried a few regexes to look for suspects and found nothing, so I guess this is resolved.
