### ISSUE TITLE
Strange BlockHeader fields data types

### ISSUE THREAD

**Issue by incker** [rust-bitcoin/rust-bitcoin#732]
Hello, I have took this 2 lines from tests bitcoin crates

    let some_header = Vec::from_hex("010000004ddccd549d28f385ab457e98d1b11ce80bfea2c5ab93015ade4973e400000000bf4473e53794beae34e64fccc471dace6ae544180816f89591894e0f417a914cd74d6e49ffff001d323b3a7b").unwrap();
    let mut some_header: BlockHeader = deserialize(&some_header).expect("Can't deserialize correct block header");

If I will print `some_header` I will have such result:

    BlockHeader {
        version: 1,
        prev_blockhash: 00000000e47349de5a0193abc5a2fe0be81cb1d1987e45ab85f3289d54cddc4d,
        merkle_root: 4c917a410f4e899195f816081844e56aceda71c4cc4fe634aebe9437e57344bf,
        time: 1231965655,
        bits: 486604799,
        nonce: 2067413810
    }

And when I get bitcoin block `00000000e47349de5a0193abc5a2fe0be81cb1d1987e45ab85f3289d54cddc4d` data from this [site](https://chainquery.com/bitcoin-cli/getblockheader)

I reseive complitelly different `merkle_root`, `time`, `bits` and even `nonce` !!!! 

    "result": {
        "hash": "00000000e47349de5a0193abc5a2fe0be81cb1d1987e45ab85f3289d54cddc4d",
        "confirmations": 711566,
        "height": 495,
        "version": 1,
        "versionHex": "00000001",
        "merkleroot": "d2a17dd46af545946132b7b6107b93f534483d79460c3dd23a26c68b498fe0c4",
        "time": 1231964596,
        "mediantime": 1231962298,
        "nonce": 883307825,
        "bits": "1d00ffff",
        "difficulty": 1,
        "chainwork": "000000000000000000000000000000000000000000000000000001f001f001f0",
        "nTx": 1,
        "previousblockhash": "000000004fb61ae8e99040c4e1e3b4d333dbe867f97f63ab4238cba80f59204a",
        "nextblockhash": "00000000b0c5a240b2a61d2e75692224efd4cbecdf6eaf4cc2cf477ca7c270e7"
    },

For a moment I thought it is just a dummy data in `bitcoin` crate tests... But 

    assert_eq!(&some_header.block_hash(), &next_blockhash);

But next_blockhash is correct. How? Why?
How can I validate block using data from  this [site](https://chainquery.com/bitcoin-cli/getblockheader) ? `some_header.block_hash()` never gives me adequate results. I am already tired experimenting with big/little endian, `sha256d`/`sha256` hashes.

I can not understand why block time from getblockheader 1231964596 is 1231965655 your crate time.. 
Do you have documentation, pleassssseeee?

**Comment by RCasatta** [comment]
> I reseive complitelly different merkle_root, time, bits and even nonce !!!!

That's because you are comparing different headers, `some_header` is block 496 with hash `00000000b0c5a240b2a61d2e75692224efd4cbecdf6eaf4cc2cf477ca7c270e7`.
call `block_hash()` on a header to see the hash of that header, `prev_blockhash ` is the hash of the previous header

**Comment by Kixunil** [comment]
It looks like you're confusing block hash with **previous** block hash.

Block `00000000e47349de5a0193abc5a2fe0be81cb1d1987e45ab85f3289d54cddc4d` is the one *before* what you mentioned at the top of your issue.

**Comment by Kixunil** [comment]
LOL, @RCasatta saw your comment pop up right at the moment I clicked "comment" :D

**Comment by RCasatta** [comment]
> LOL, @RCasatta saw your comment pop up right at the moment I clicked "comment" :D

same same

**Comment by incker** [comment]
Thank you! My fault
