### ISSUE TITLE
"Trivial" label

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#734]
I suggest adding the "trivial" label used for PRs that should be obvious, take under one minute to review and take very little mental effort. The idea is to quickly filter such tasks when one has a little bit of extra time and wants to use it productively. This way we can progress little improvements faster.

**Comment by sanket1729** [comment]
I think we should be super liberal in adding labels. If any collaborator needs to add a few labels here and there, they can go ahead and just do it. If it aids a review of a single reviewer, I think we should add it. If we end up with a lot of labels, we can clean up a few that are not used at all.

**Comment by Kixunil** [comment]
Good point, added.
