### ISSUE TITLE
Waiting for Author label might slow review

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#738]
No everyone can remove labels, so if those with write access to the repo add the 'waiting for author' label then when the author responds the author is unable to remove it. This may lead other reviewers to skip over the PR, if so this will not be a good experience for contributors.

cc @Kixunil am I missing something in the labels intended usage?

**Comment by Kixunil** [comment]
I was just assuming whoever adds the label is presumably subscribed and will get notification and remove it. However, I now realize whoever added the label can be unavailable for a while after the author responds. A bot would help.
