### ISSUE TITLE
Missing BOLT 11 multipliers in `Denomination`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#741]
[BOLT 11](https://github.com/lightning/bolts/blob/master/11-payment-encoding.md#human-readable-part) specifies a set of multipliers for usage with BTC denomination. We have not implemented nano or pico.

**Comment by tcharding** [comment]
Potential label: good-first-issue

**Comment by Kixunil** [comment]
I'm not sure it's entirely relevant here but shouldn't hurt and potentially makes LN implementations cleaner/easier. Maybe @TheBlueMatt can confirm?
