### ISSUE TITLE
BIP47 (Payment Codes) integration

### ISSUE THREAD

**Issue by straylight-orbit** [rust-bitcoin/rust-bitcoin#746]
Hi,

I have a [Rust implementation of the BIP47 standard](https://github.com/straylight-orbit/rust-bip47) and I was wondering if rust-bitcoin would be interested in taking ownership of the project and bringing it under its umbrella (probably as a separate repository, it doesn't need to be in the core bitcoin library). The original specification is [here](https://github.com/bitcoin/bips/blob/master/bip-0047.mediawiki).

The library has only one dependency, which is `rust-bitcoin`.

For those unfamiliar with the BIP, the premise is that two extended public keys can use ECDH to derive a private address space between them. This then enables any number of participants to have static payment codes that allow each pair of participants to pay each other in private, without anyone else being able to see the address space or link such addresses to individual wallets. It's essentially an improved take on the stealth addresses concept.

Several wallets already implement the standard and it is used by certain privacy related projects, such as Whirlpool.

Happy to discuss further and answer any questions.

**Comment by Kixunil** [comment]
Cool, maybe publish it on crates.io?

FYI, AFAIK all projects here must have MSRV 1.29.

**Comment by straylight-orbit** [comment]
Thanks for the input.

I made the project MSRV 1.29 compatible. Crates.io publishing should take place soon.

**Comment by apoelstra** [comment]
Neat! I'm not familiar with BIP47 but it looks pretty neat.

And this crate checks all our boxes -- a minimal dep tree (only `rust-bitcoin` lol) and MSRV of 1.29.

I'd be fine with bringing it under the rust-bitcoin org.

**Comment by straylight-orbit** [comment]
Glad to hear that. What's the best way to go about it? I could simply transfer the ownership but I don't have the requisite permissions.

**Comment by apoelstra** [comment]
Are you able/willing to add me an admin so that I can do the transferL

**Comment by straylight-orbit** [comment]
I've initiated a transfer to your github handle, you should be able to take it from there.

**Comment by apoelstra** [comment]
Ah, nice! Got it.

**Comment by apoelstra** [comment]
It is now at https://github.com/rust-bitcoin/rust-bip47

You and I are admins on this project but nobody else has permissions yet.

**Comment by straylight-orbit** [comment]
Excellent, closing this issue.
