### ISSUE TITLE
Thank you for this repo!

### ISSUE THREAD

**Issue by aminroosta** [rust-bitcoin/rust-bitcoin#747]
I just want to thank everyone contributing to this repository.
To me, it's an awesome way of learning how bitcoin works.

The code is well structured, there are perfect documentation for each module and It's a joy to read the source code.

Thank you all!

**Comment by Kixunil** [comment]
Happy to be a small part of helpful people! :)

There's still a lot of work ahead of us so if you enjoy Rust Bitcoin development feel free to send PRs!
If you happen to be a Rust beginner I'm willing to mentor your contributions to `rust-bitcoin` or related libraries.
