### ISSUE TITLE
`verify` fails on the correct segwit transaction

### ISSUE THREAD

**Issue by alekseysidorov** [rust-bitcoin/rust-bitcoin#78]
I try to verify transaction by `Transaction::verify` method and then I recieve an error "value: BitcoinConsensus(ERR_TX_INDEX)", but the transaction was successfully committed to the testnet blockchain.

https://testnet.blockchain.info/tx/b4abeb70c3b38f50a38adf511394cfae9c04650bcd6cbf7d484d61559e2045bd?show_adv=true

Here is code of failed test. 
https://github.com/exonum/btc-transaction-utils/blob/tx_verify_bug/src/p2wsh.rs#L180
What could have gone wrong?

**Comment by TheBlueMatt** [comment]
Can you re-test with version 0.13? This may be #71.

**Comment by alekseysidorov** [comment]
Yes, with the `0.13` works fine, thanks.

**Comment by TheBlueMatt** [comment]
Closing as "fixed in latest version", dont think we currently do any backports and upgrading to 0.13 should be relatively painless.
