### ISSUE TITLE
rust-bicoin community tagline contains freenode

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#780]
Tag line contains:

#rust-bitcoin on freenode

This is stale, probably should be updated to say librechat

**Comment by apoelstra** [comment]
Ah, I think this has come up in the past ... the issue is that Github no longer lets us choose a location that is outside of its fixed list of countries (I guess if you have a geopolitical disagreement with GIthub you can go to hell..), so I can't figure out how to update this.

**Comment by dpc** [comment]
Remove altogether then?

**Comment by apoelstra** [comment]
Yeah, I'll just do that.

**Comment by apoelstra** [comment]
Ok, removed. Ok to close this issue?

**Comment by tcharding** [comment]
Thanks
