### ISSUE TITLE
Avoid closure in `s.starts_with();`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#783]
Post-merge nit for a follow-up PR: `s.starts_with(char::is_uppercase);`

_Originally posted by @dr-orlovsky in https://github.com/rust-bitcoin/rust-bitcoin/pull/768#discussion_r784684641_

Note: there's a clippy lint for this.

**Comment by dr-orlovsky** [comment]
Closed by #784
