### ISSUE TITLE
Epics and champions

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#787]
Issue to maintain the list of the ongoing epics in `rust-bitcoin`: long-lasting projects achieving well-defined goals, requiring cooperation of multiple contributors and many PRs.

Each of the epics has 
- a dedicated project (org level for epics involving multiple repos, or repo-level for a single-repo epics);
- a tracking issue, one per repository participating the epic;
- a champion - maintainer or a contributor driving the implementation forward, pinging reviewers and authors for stalled PRs, keeping the project and track issues updated;

The initial draft to start from (includes both historical and current epics, since historical epics may be revived)

Epic | Repos | Project | Tracking issue in rust-bitcoin | Target rust-bitcoin version | Champion(s)
------ | -------- | --------- | -------------------------------------- | ----------------------------------- | ------------------
✅ Derive unification | all | https://github.com/orgs/rust-bitcoin/projects/2 | #555 | 0.26.2 | @dr-orlovsky 
✅ `no_std` support | all | n/a | n/a | 0.27.0 | @devrandom 
✅ Taproot implementation | all | https://github.com/orgs/rust-bitcoin/projects/3 | #503 | 0.28.0 | @dr-orlovsky & @sanket1729
✅ Rust 2018 and MSRV 1.41.1 | all | n/a | #510 | 0.29.0 | @tcharding,
Error improvements | all | n/a | #820 | ? | @Kixunil 
PSBT refactoring & PSBTv2 | `bitcoin`, `miniscript` | https://github.com/rust-bitcoin/rust-bitcoin/projects/1 |  #1055 | ? | @DanGould 
Documentation improvements | all | n/a | n/a  | ongoing |  @tcharding
✅ Code formatting | all | n/a | #788 | ? | @tcharding
Multi-crate refactoring | `bitcoin` | https://github.com/rust-bitcoin/rust-bitcoin/projects/2 | #550 | 0.30.0 | @tcharding
Script types refactoring | `bitcoin`, `miniscript` | n/a | n/a (but see #653) | ? | vacant (@sanket1729 ?) 

Please feel free to directly edit this description, add your epics etc. The discussion will happen in comments

**Comment by dr-orlovsky** [comment]
Notes on championship: In vacant positions I proposed those who already did some PRs under these topics or expressed interest in getting that done. Please let know are you willing to take the championship - or, if anyone else is willing.

I am willing to champion PSBTv2 (since I have worked in PSBT refactoring for the last year and really need this feature) - but if everyone else want to champion that I will be happy to have less work :)

**Comment by dr-orlovsky** [comment]
I also propose to discuss priorities between different epics.

My own preferences are:
- PSBTv2 (v0.29.0)
- Rust MSRV / edition 2018 (v0.29.0)
- Multi-crate refactoring (v0.30.0)
- Script type refactoring (v0.31.0)

Docs, lints, errors imo should be ongoing

**Comment by tcharding** [comment]
Thanks, this issue is super useful. I'm not sure linting should be part of rustfmt. Enabling linting in CI should be pretty easily possible as soon as edition 2018 work goes in. `rustfmt` is going to be a _massive_ head ache to do. I've created a new tracking issue for rustfmt (could you please edit the original posted table changing #692 for #788).

**Comment by dr-orlovsky** [comment]
I agree with @tcharding that linting is not a part of formatting epic, and probably does not deserves an epic of its own; it will be a part of 2018 edition work.

I updated tracking issue number. @tcharding pls also indicate where you'd like to volunteer for the championship.

**Comment by tcharding** [comment]
I took docs, I don't think anyone is going to fight me for that one :)

First pick at edition-2018/MSRV should go to @Kixunil or @elichai, they both did work in this area before me. I'm happy to take it if they say so.

I'm happy to take crate smashing if that's ok with @apoelstra.

4 is probably being greedy but if no-one else takes rustfmt I can take that one too.

**Comment by tcharding** [comment]
I set MSRV to 0.29, I don't think this is contentious.

**Comment by Kixunil** [comment]
Interesting idea but TBH I don't care much who's champion as long as the things I'd like to see are done. My main interests lately are using important new language features to improve code/API quality and making stabilization a realistic goal by splitting it up and stabilizing components on-by-one with idiomatic well documented Rust APIs.

**Comment by apoelstra** [comment]
@tcharding go ahead and take everything you want :)

**Comment by tcharding** [comment]
> My main interests lately are using important new language features to improve code/API quality and making stabilization a realistic goal by splitting it up and stabilizing components on-by-one with idiomatic well documented Rust APIs.

Cool. Well let me take on the softer work of championing so you can focus on more complex tasks, keep poking and prodding me with those good suggestions :)

**Comment by sanket1729** [comment]
Sounds good to me. I think we should also add "cleanup secp verification context from rust-secp, rust-bitcoin and rust-miniscript". This will significantly simplify the usage of all projects downstream. It is not a super big task but still would require over API name bikeshedding. 

On a similar note, feel free to assign any PR to me review code that deals with script, psbt, keys, taproot, sighashes. On the other hand, I am not that interested/knowledgeable about network-related code, or no-std.

**Comment by Kixunil** [comment]
I've conservatively taken errors, we will see if I will have time to do other things.

**Comment by tcharding** [comment]
@DanGould has put his hand up to be champion for the PSBT epic. I've had some email chats about it with him, flagging this for other maintainers to see. Dan is relatively new to Rust but seems to know his way around PSBTs, I thought this would be a great way for him to help out with `rust-bitcoin`. Please speak up and help him out during his efforts. Cheers Dan.

**Comment by DanGould** [comment]
Stoked to contribute. May an owner/admin grant me [psbt project board](https://github.com/rust-bitcoin/rust-bitcoin/projects/1) permission? I've read only access.

**Comment by tcharding** [comment]
We need @apoelstra to do that it seems, here is a post about it since I looked it up anyways: https://docs.github.com/en/organizations/managing-access-to-your-organizations-project-boards/project-board-permissions-for-an-organization

**Comment by apoelstra** [comment]
Hmm, I don't have the "Settings" menu option there that the docs say I should ... maybe it's someone else?

Weird because I am an admin across the whole rust-bitcoin org..

I've never heard of this project board and don't know who set it up.

In any case, you can certainly have write access @DanGould if we can figure out how..

**Comment by apoelstra** [comment]
I think maybe because the project is part of the repo rather than part of the org, I can't set fine-grained permissions?

**Comment by tcharding** [comment]
The projects were, as I understand it, set up by @dr-orlovsky. The columns are autogenerated and github populates them, I think, based on milestones. I'm not an expert on project management (it hurts a little bit just writing that) or github.

Perhaps you could just open a 'PSBT tracking issue' @DanGould. If we are lucky, if you open it you might even be able to edit it also (other maintainers can edit it as well)?

**Comment by sanket1729** [comment]
> I think maybe because the project is part of the repo rather than part of the org, I can't set fine-grained permissions?

I can create a new project inside the whole org and give permissions specifically for writing to that project. It's only 9 cards, so should not be too much effort in copying things.

**Comment by tcharding** [comment]
This is not being used, shall we close it?

**Comment by Kixunil** [comment]
I think so. We've also shifted priorities a bit.
