### ISSUE TITLE
BIP39 discussion issue

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#812]
> This is totally off-topic but if someone could explain to me why we don't want to support BIP39 (in email/other place issue to not spam here) it'd be appreciated.

_Originally posted by @Kixunil in https://github.com/rust-bitcoin/rust-bitcoin/issues/810#issuecomment-1023030028_

To be clear: **we are not going to support BIP 39 in this library**. But I realize that there isn't anywhere on Github that we've listed reasons. (In a quick search was able to find "see IRC discussion".)

Off the top of my head, reasons to avoid BIP39 are:

* The use of multiple languages, with the *words themselves* fed into a hash function to map from mnemonic to BIP32 seed, meaning that different languages are not interconvertible
* No in-band way to indicate choice of language, number of words used, etc
* No versioning
* A "checksum" with zero error detection guarantees, and with very high probability (1/256) of not even detecting random errors.
* A "checksum" which is less than a word long, making it impossible to separate from the actual data
* Mapping to BIP32 seed is irreversible
* Mapping to BIP32 uses SHA512, which provides zero benefit over SHA256, but makes it impractical to migrate away from BIP39 by simply converting your seed words to a seed
* Poor choice of word list; a "guaranteed unique 4-character prefix" but not all words are 4 characters long; many words are similar e.g. "rock" and "racket"
* Impossible to compute by hand due to pointless (ab)use of SHA256

**Comment by dpc** [comment]
@Kixunil @apoelstra Would you consider enabling "Discussion" functionality for this github repo? Seems like this would fall right into this category.


My one question is - what's the recommended alternative to BIP39?

**Comment by apoelstra** [comment]
Right now probably SLIP39. I am working on an alternative standard with @roconnor-blockstream but it's not ready yet.

In any case the problem with BIP39 is that, because it uses sha-512 to produce a seed, it's impossible to move off of it without sweeping your coins :(.

**Comment by apoelstra** [comment]
Oh, neat. I enabled "Discussions" (and turned off the Wiki, which I don't think any of us were using)

**Comment by dpc** [comment]
Note: you can convert issues into discussions. Which comes handy because people start issues, which turn into non-actionable discussions all the time.

**Comment by apoelstra** [comment]
Oh, neat, there is a "Convert to Discussion" button right there on the sidebar. TIL.
