### ISSUE TITLE
Audit the crate adheres to Rust API guidelines

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#821]
The Rust API guidelines contain various recommendations to improve the quality of the crate. As far as I can tell they are very reasonable. Adhering to them not only improves the code but it makes it easier for rust-bitcoin newbies to use (and contribute to) the crate because of familiarity. It is also a green flag when deciding whether to use a crate.

https://rust-lang.github.io/api-guidelines/about.html

**Comment by apoelstra** [comment]
concept ACK

**Comment by tcharding** [comment]
Superseded by #1649
