### ISSUE TITLE
Should we have `CompressedPublicKey` type?

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#826]
`PublicKey` tracks whether it's compressed dynamically which leads to error checking when creating `wpubkey_hash`.
Having a separate type for it would push the responsibility to the caller which might be able to statically guarantee compressed key.
However it's quite a bit of added API surface just to remove a few error paths. Is it worth it?

**Comment by Kixunil** [comment]
Note that we could easily support both in relevant functions:

```rust
#[non_exhaustive]
struct UncompressedPublicKey;

impl TryFrom<PublicKey> for CompressedPublicKey { 
    type error = UncompressedPublicKey;
    ...
}

pub fn p2wpkh<Pk: TryInto<CompressedPublicKey>>(pk: Pk, network: Network) -> Result<Address, Pk::Error> {
...
}
```

**Comment by apoelstra** [comment]
It would remove more than a few error paths in rust-miniscript.

I'm in favor of this in principle. I think we've tried it in the past and it was hard to make workable. Maybe with 1.41.0 and TryFrom/TryInto it'll be more ergonomic.

**Comment by Kixunil** [comment]
@dr-orlovsky thanks for references! After reading them I think people are worried about type blow up. I think a good compromise would be having `CompressedPublicKey` and `PublicKey`, no `UncompressedPublicKey`. AFAIK uncomressed keys are only used in contexts where both are usable but there are places where only compressed is accepted.

**Comment by tcharding** [comment]
What is the intended meaning of the 'help wanted' label @Kixunil?

**Comment by Kixunil** [comment]
AFAIK it's asking for outside help (in this case feedback on API).

However maybe we should have a special label for requesting API feedback. Maybe even some event source for API consumers to subscribe to.

**Comment by dr-orlovsky** [comment]
@tcharding can't this be done with GitHub discussions? Just worried about multiplying communication channels

**Comment by tcharding** [comment]
AFAICT GitHub discussions is per repository, I think a communication channel that is for all Bitcoin projects that are written in Rust (specifically all the ones that depend on crates in this organisation) would be useful. I'm pushing for a `rust-bitcoin-dev` mailing list.

**Comment by Kixunil** [comment]
I don't see a big problem with (ab)using the `bitcoin` crate for all of them.

**Comment by tcharding** [comment]
Fair point, and I suppose I can get notifications from github discussions via email.

**Comment by dr-orlovsky** [comment]
BTW it seems I have seen discussions at the org level

**Comment by tcharding** [comment]
I don't see it, I looked at an organisation of which I'm the 'owner' (or creator or whatever) and I couldn't see it either? Are you sure of this?

**Comment by dr-orlovsky** [comment]
<img width="1308" alt="Screen Shot 2022-03-18 at 12 12 06" src="https://user-images.githubusercontent.com/372034/158993139-cfe9ada3-1dee-4a49-8d69-d108c5af4ad5.png">

**Comment by tcharding** [comment]
Yeah I saw teams but thought that wasn't suitable to us because its by definition exclusive, we want to include random contributors. Feels like teams is aimed at private, corporate, dev teams.

**Comment by dr-orlovsky** [comment]
@tcharding actually discussions on the org level are already in beta: https://github.com/github/feedback/discussions/13192

This is not the same as a team discussions. I think it could be a nice replacement for a mail list.

**Comment by tcharding** [comment]
Done in #2277
