### ISSUE TITLE
Doc typos tracking

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#828]
Doc typos aren't urgent to fix and it's more efficient to batch the fixes.
We track the fixes here and when there's enough we can fix them in a single PR.
Just mention this issue number in other issue to add typo or add a comment with exact file & line.

**Comment by Shatnerz** [comment]
https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/taproot.rs#L62
```
/// Internal macro to speficy the different taproot tagged hashes.
```

**Comment by tcharding** [comment]
4 instances of missing `n` in `consensus/encode.rs`

https://github.com/rust-bitcoin/rust-bitcoin/pull/1357#pullrequestreview-1206507745

**Comment by apoelstra** [comment]
Some formatting issues https://github.com/rust-bitcoin/rust-bitcoin/pull/1467 cc @danielabrozzoni

**Comment by apoelstra** [comment]
Closing this since #1486. Futher doc typos should be added to https://github.com/rust-bitcoin/rust-bitcoin/issues/1490.
