### ISSUE TITLE
"bitcoin_hashes" feature in rust-secp seems to break CI

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bitcoin#830]
See e.g. https://github.com/rust-bitcoin/rust-bitcoin/pull/819#issuecomment-1034273915

Not sure yet if the bug is in bitcoin_hashes, rust-secp or this library.

**Comment by tcharding** [comment]
Its the `no-std` build that fails. I cannot re-produce the build failure locally which is disconcerting but I've got a gut feeling that its something to do with the fact that we enable `bitcoin_hashes` in secp with default features enabled (implies `std`). However if we do not do this then users of secp have no way to enable std/alloc feature when enabling `bitcoin_hashes`?

**Comment by Kixunil** [comment]
@tcharding oh, yes, that looks like it!

>  then users of secp have no way to enable std/alloc feature when enabling `bitcoin_hashes`?

They do, just depend on `bitcoin_hashes` explicitly with the feature enabled. The real question is whether it causes problems mentioned in #840 If it does then we need `bitcoin_hashes_std` feature in `secp256k1`. Ugly but not entirely terrible I think.

**Comment by bruteforcecat** [comment]
> @tcharding oh, yes, that looks like it!
> 
> > then users of secp have no way to enable std/alloc feature when enabling `bitcoin_hashes`?
> 
> They do, just depend on `bitcoin_hashes` explicitly with the feature enabled. The real question is whether it causes problems mentioned in #840 If it does then we need `bitcoin_hashes_std` feature in `secp256k1`. Ugly but not entirely terrible I think.
> 
> Side note: using `default-features = false` will be a breaking change.

I verified that CI is fixed after setting `default-features = false` for bitcoin_hashes in secp deps. related issue https://github.com/rust-bitcoin/rust-bitcoin/pull/851#issuecomment-1054263393

**Comment by tcharding** [comment]
This issue is resolved, secp256k1 v0.24.0 does not enable default features (includes "std") for `bitcoin_hashes`.
