### ISSUE TITLE
Errors should return source instead of displaying it

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#831]
Not displaying the source and returning it from the `source` method is better for consumers as they may want to display error sources differently (line-by-line is a popular example, even Cargo does it). We're currently displaying sources together with messages. We should change it to use source.

There's one issue though: `no_std` would lose sources which may be annoying. I was previously ignoring this issue in my projects but I came up with a hopefully reasonable solution: continue displaying the source in `no_std` builds. This looks a bit backwards ("cargo features are supposed to be additive") but shouldn't break things unless people are foolishly matching against strings.

Another issue is adding cfgs could be annoying but I believe it can be easily solved with a macro. Something like this:

```rust
match error {
    Error::Foo(source) => write_err!(f, source, "some message"),
    Error::Bar(details, source) => write_err!(f, source, "the thing {} went wrong", details),
}
```

Perhaps it'd be even easier with something like `amplify` that could generate it together with std `Error` impl. Cc @dr-orlovsky

**Comment by Kixunil** [comment]
<details>
<summary>Off-topic GH-related thing I noticed</summary>

GitHub now shows "Tracked in" at the top, interesting! My guess is that closing this will mark it as done - something I asked at GH feedback not too long ago. Cool if they listened! Can't wait until it's closed :D

</details>

**Comment by apoelstra** [comment]
concept ACK

**Comment by Kixunil** [comment]
[Example implementation of `write_err!`](https://github.com/LNP-BP/ln-types/pull/7/files#diff-981f2c145a0f66eab4a69e665a06725b35903b9231bb63a93b2545966342e96e). Looks usable to me.

**Comment by dr-orlovsky** [comment]
concept ACK, I like it. So what will be the best path forward with that?

**Comment by Kixunil** [comment]
We need to copy the macro and rewrite error handling one-by-one. I don't see a better way.

**Comment by tcharding** [comment]
This issue is resolved by the following three PRs
- https://github.com/rust-bitcoin/rust-bitcoin/pull/987
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1003
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1049

**Comment by tcharding** [comment]
All done.
