### ISSUE TITLE
Improve Prevouts structure in taproot sighash computation 

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#834]
Recall that BIP341 requires hashing all previous UTXOs into the sighash algorithm. For doing this, we introduced a Prevouts structure, 
```rust
pub enum Prevouts<'u> {
    /// `One` variant allows to provide the single Prevout needed. It's useful for example
    /// when modifier `ANYONECANPAY` is provided, only prevout of the current input is needed.
    /// The first `usize` argument is the input index this [`TxOut`] is referring to.
    One(usize, &'u TxOut),
    /// When `ANYONECANPAY` is not provided, or the caller is handy giving all prevouts so the same
    /// variable can be used for multiple inputs.
    All(&'u [TxOut]),
}
```

I think we want the Prevouts::All variant to be `All(&'u [&'u TxOut])`. When using `taproot_signature_hash` in psbt workflow, this requires allocating a vector to create utxos from witness utxos/transaction outputs and later pass it as a slice while constructing `Prevout`.  

Does this make the API too awkward to use? At least in the psbt workflow, I find this to be a better design. If there are no objections to this, I will make this a good first issue in a couple of days.

**Comment by sanket1729** [comment]
Ideally, I would want this to be in 0.28.0. Adding the 0.28 label to get more attention. The PR should be super simple if there are no objections.

**Comment by sanket1729** [comment]
Raised #835 to address this

**Comment by tcharding** [comment]
Was this issue closed by https://github.com/rust-bitcoin/rust-bitcoin/pull/835? @sanket1729 I see you used `see #835` in the pr, did you intentionally mean to _not_ close this (i.e., use 'fixes', 'resolves', etc)?

**Comment by Kixunil** [comment]
Looks obviously forgotten to me, reopen if not.
