### ISSUE TITLE
Improve Psbt error handling

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#837]
The current psbt error handling is in a poor state. 

- The current psbt::serialize::Deserialize has an error type of consensus::encode::Error. I think we should cleanly separate consensus encoding errors from application-level encoding errors like psbt. 
- There is a recursive dependence between `encode::Error` and `psbt::Error` which would need to be cleanly dissected and separated so that there is no dependence or only one-way dependence. 
- There are a lot ParseError(String) messages that could use a better type to downflow the information. 

This might be a lot of work, but can be addressed in several PRs. Adding a good first issue label, please let us here know before you go ahead with attempting this.

**Comment by sanket1729** [comment]
> There are a lot ParseError(String) messages that could use a better type to downflow the information.

This can be addressed by Summer of bitcoin students as a new starter project.

**Comment by rish-singhal** [comment]
Hi @sanket1729, sure I would take this up.

**Comment by sanket1729** [comment]
@violet360. It looks like @rish-singhal is attempting this issue. 

Perhaps, we should wait a couple of days for them to respond before you pick this up. This is a large project and would definitely have enough work that contributors can work on separate things. 

1) The current psbt::serialize::Deserialize has an error type of consensus::encode::Error. I think we should cleanly separate consensus encoding errors from application-level encoding errors like psbt.

2) There are a lot ParseError(String) messages that could use a better type to downflow the information.

Maybe, one of you can pick either 1) or 2) to begin with. As we make progress with these, we will have a better idea how to cleanly separate things to avoid recusive error data types.

**Comment by violet360** [comment]
If @rish-singhal is working on it, then let us wait for him, although if he wants to distribute the task I will be more than happy to collaborate with him🙃

**Comment by sanket1729** [comment]
Hi @violet360, you can pick this up if you are interested. Feel free to start with anything, I suspect changing the `ParseError(String)` to actual error messages would be easier.

**Comment by DanGould** [comment]
How is this going @violet360 ? This is related to https://github.com/rust-bitcoin/rust-bitcoin/pull/988 which I'm working on

**Comment by violet360** [comment]
I haven't started on this yet, do you want to take up this task ?
@DanGould

**Comment by arturomf94** [comment]
Is this still up for grabs? I'd like to have a go...

**Comment by tcharding** [comment]
Hi @arturomf94, go for it man! Sing out if you would like any tips or suggestions. Note also there is an ongoing [error epic](https://github.com/rust-bitcoin/rust-bitcoin/issues/820) that may be related to this, depends how deep you want to go. I would definitely do this issue as multiple PRs if it was me, error handling done well can be very involved :). Thanks!

**Comment by arturomf94** [comment]
Hey! I'm so sorry. I thought I would have more time to try and tackle this one, but I don't think I will be able to, unfortunately.

**Comment by tcharding** [comment]
No worries mate, next time :) Good luck!

**Comment by arturomf94** [comment]
@tcharding - I will have some time for this and I'd love to go back to it. Could you please assign it to me? :) Apologies for the back-and-forth!

**Comment by tcharding** [comment]
You got it!

**Comment by Kixunil** [comment]
I just noticed [`NoMorePairs` variant](https://docs.rs/bitcoin/latest/bitcoin/util/psbt/enum.Error.html#variant.NoMorePairs) looks to be internal and maybe we should remove it.

**Comment by arturomf94** [comment]
Also, opened [1] to improve on at least **some** of the points mentioned in this issue. The recursive-dependency issue was omitted.

[1] - https://github.com/rust-bitcoin/rust-bitcoin/pull/1310.

**Comment by Kixunil** [comment]
Firstly, I don't particularly like `Encodable` and `Decodable` on PSBT types but maybe I could be convinced if a bunch of stuff changed names and documentation.

Secondly, I think most of the issues would go away if `Decodable` had an associated error type instead of a shared one. Interestingly, it'd also help with my first issue.

**Comment by apoelstra** [comment]
I could get behind `Decodable`/`Encodable` having associated error types. Of course, for all the Bitcoin primitives we'd want them to all use the same type, but that's fine.

It's a bit weird that PSBT has its own `Serialize`/`Deserialize` traits which are basically the same as `Encodable`/`Decodable` but with richer error handling....and then even weirder that PSBT then **also** tries to impl `Encodable`/`Decodable` directly.

If we gave `Encodable`/`Decodable` associated error types and then got rid of `Serialize`/`Deserialize` I think that'd be a lot cleaner.

**Comment by arturomf94** [comment]
Given the previous comments, I've decided to close #1310. I will work on a new PR to include the suggestions that have been mentioned, instead.

**Comment by arturomf94** [comment]
Hi - it's been a while since I last had a look at this, but I'd like to pick it up. I see there have already been some changes related to this issue. Would someone please help me understand where this is at and which bits are still relevant? I'd like to contribute again :)

**Comment by arturomf94** [comment]
@DanGould  - let me know if there's anything I could help with!

**Comment by DanGould** [comment]
@arturomf94 addressing the a few dangling nit suggestions, e.g. the one about `Cursor`, from comments in #988 may be an easy way to get started.

I'll tag you when I post the PR of the branch addressing this exact issue in a moment

**Comment by DanGould** [comment]
> If we gave `Encodable`/`Decodable` associated error types and then got rid of `Serialize`/`Deserialize` I think that'd be a lot cleaner. - @apoelstra 

We just did the opposite, and got rid of `Encodable`/`Decodable` only because they're supposed to be for consensus objects only according to #934. In doing so we sacrificed performance for a simpler interface with richer errors.

@Kixunil drafted an associate error, but I'm not sure how it fixes the problem since Psbt is no longer `Decodable`. Is the suggestion to make an associated error and depend on it in `deserialize()`?

> I believe that the best error untangling would be to make decodable error associated.

> I meant having associated `Error` type at `Decodable` trait. Encoding should only fail if the writer fails so we should have `io::Error` there (at least until we have something like `genio`).
> 
> > is a problem to instantiate consensus::encode::Error in this module for `io::Error`?
> 
> It certainly does look strange. Maybe we should have this shared type:
> 
> ```rust
> /// Error used when reading or decoding fails.
> pub enum ReadError<Io, Decode> {
>     /// Reading failed
>     Io(Io),
>     /// Decoding failed
>     Decode(Decode), // consensus and PSBT error here
> }
> ```
> 
> However this one will be annoying to use with `?` :( We could have `ResultExt` to provide `decode()` and `io()` methods to make it easier.
> 
> If that's not acceptable then I think deduplicated IO error is better.
