### ISSUE TITLE
Add a utility method to psbt to compute find sighash type of a given input

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#838]
For each psbt input, we have a field called sighash_ty.

https://github.com/rust-bitcoin/rust-bitcoin/blob/0c5b6951941bdfbbbb86f58f0549d8cca5a55538/src/util/psbt/map/input.rs#L95

We should add a two new APIs to input

- ecdsa_sighash_ty: Outputs Result<EcdsaSigHashType, Error>. If the sighash_ty field is none, output Ok(EcdsaSigHashType::All). Return err is the sighash type is non-standard.
- schnorr_sighash_ty: Same as above but for schnorr signatures.

**Comment by rish-singhal** [comment]
Hi @sanket1729, I am new to contributing to this repository and a participant in Summer of Bitcoin. I would like to solve this issue. Also, will the following work just wanted to confirm

```rust
impl Input {
    /// Returns the ['EcdsaSigHashType'] if the sighash_type is None else
    /// NonStandardSigHashType Error
    pub fn ecdsa_hash_ty(&self) -> Result<EcdsaSigHashType, Error> {
        if let Some(sighash_type_value) = self.sighash_type {
            Err(Error::NonStandardSigHashType(sighash_type_value.inner))
        } else {
            Ok(EcdsaSigHashType::All)
        }
    }

    /// Returns the ['SchnorrSigHashType'] if the sighash_type is None else
    /// NonStandardSigHashType Error
    pub fn schnorr_hash_ty(&self) -> Result<SchnorrSigHashType, Error> {
        if let Some(sighash_type_value) = self.sighash_type {
            Err(Error::NonStandardSigHashType(sighash_type_value.inner))
        } else {
            Ok(SchnorrSigHashType::All)
        }
    }
....
```

**Comment by Kixunil** [comment]
This doesn't look correct. I think it should be something like `Ok(self.sighash_type.map(|sighash_type| sighash_type.ecdsa_hash_ty()).transpose()?.unwrap_or(EcdsaSigHashType::All))`

**Comment by sanket1729** [comment]
Hi @rish-singhal , thanks for taking the time to look at this. The algorithm should be 
- If sighash_ty is `Some`, call .ecdsa_sighash_ty on the inner returning the result
- If it is `None`, return EcdsaSigHashtype::All.

SImilarly for Schnorr. Also, note that the `None` case of schnorr should be `SchnorrSignatureHashType::Default`. Feel to ask more questions here or you can approach me on the summer of bitcoin discord for more assistance on this.

**Comment by rish-singhal** [comment]
> Hi @rish-singhal , thanks for taking the time to look at this. The algorithm should be
> 
> * If sighash_ty is `Some`, call .ecdsa_sighash_ty on the inner returning the result
> * If it is `None`, return EcdsaSigHashtype::All.
> 
> SImilarly for Schnorr. Also, note that the `None` case of schnorr should be `SchnorrSignatureHashType::Default`. Feel to ask more questions here or you can approach me on the summer of bitcoin discord for more assistance on this.

Hi thanks for your reply, does the following work?
```rust

impl Input {
    /// Returns sighash_type.ecdsa_hash_ty() is sighash_type exists else 
    /// ['EcdsaSigHashType::All']
    pub fn ecdsa_hash_ty(&self) -> Result<EcdsaSigHashType, NonStandardSigHashType> {
        if let Some(sighash_type) = self.sighash_type {
            sighash_type.ecdsa_hash_ty()
        } else {
            Ok(EcdsaSigHashType::All)
        }
    }

    /// Returns sighash_type.schnorr_hash_ty() is sighash_type exists else 
    /// ['SchnorrSigHashType::Defaul']
    pub fn schnorr_hash_ty(&self) -> Result<SchnorrSigHashType, sighash::Error> {
        if let Some(sighash_type) = self.sighash_type {
            sighash_type.schnorr_hash_ty()
        } else {
            Ok(SchnorrSigHashType::Default)
        }
    }
...
```

**Comment by Kixunil** [comment]
That looks good. I like match a bit more when `None` is handled but not very important.

**Comment by rish-singhal** [comment]
> That looks good. I like match a bit more when `None` is handled but not very important.

sure would update the code with that, Thanks! Also, just a question is it ok to use closures and more of a functional programming style of code for the PRs, I am asking as I am new to contributing to this repository? I really liked your suggestion above.

**Comment by Kixunil** [comment]
I don't think there are hard rules. I personally prefer functional style but there are cases when match looks better. I suspect this is one of them. For iterators, functional has better performance.

Also my suggestion above is a bit complex, this is probably better: 

```rust
self.sighash_type
    .map(|sighash_type| sighash_type.ecdsa_hash_ty())
    .unwrap_or(Ok(EcdsaSigHashType::All))
```

**Comment by sanket1729** [comment]
@rish-singhal, I too prefer functional styles. Feel free to open a PR to start an implementation discussion there.
