### ISSUE TITLE
Check for incompatible feature combinations

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#840]
In https://github.com/rust-bitcoin/rust-secp256k1/pull/408#discussion_r811485136 I describe annoying issue with errors and features and I remember seeing features and conditional enum variants here, so we should check if they have the problem I describe there and fix it if we do.

**Comment by thomaseizinger** [comment]
Yes, conditional enum variants are a big no-no. I remember this being a known-issue but it just hasn't been addressed yet so thanks for tracking this here!

**Comment by Kixunil** [comment]
That's something else. Conditional enum variants will be solved with `#[non_exhaustive]` which is planned after MSRV bump.

**Comment by apoelstra** [comment]
Fixed by #1026

**Comment by Kixunil** [comment]
That PR does something completely different though.

**Comment by apoelstra** [comment]
Can you point to any features that, when enabled, break compilation? AFAIK since #1026 there are none.

**Comment by Kixunil** [comment]
This is an audit issue so someone has to go and check. AFAIK nobody did yet. :)

**Comment by apoelstra** [comment]
I checked before closing this.

**Comment by tcharding** [comment]
> I checked before closing this.
 
Issue is open still, should this be closed already?

**Comment by Kixunil** [comment]
@apoelstra since you referenced a PR that is unrelated to this I don't think you understood the issue. Probably because the comment I referenced describes two separate things and `#[non_exhaustive]` fixes only one of them. Sorry for confusion.

Hopefully more clearly: for every `enum SomeError` which references error types from optional external crates we need to conditionally compile `impl std::error::Error` such that the `source()` method returns `Some` IFF there is `external-crate-std` feature enabled. Where `external-crate-std` depends on `external-crate/std`.

For mandatory dependencies we only have to make sure `std` enables their `std` feature too.

**Comment by apoelstra** [comment]
You're right, I don't understand the issue. The issue that #1026 fixes is that adding features would literally break compilation by adding enum variants that people may have been matching on. By labelling these `#[non_exhaustive]` compilation no longer breaks. So to the extent that this is "incompatible feature combinations", the PR is very much related.

Separately, we shoud check that `source()` is implemented correctly regardless of feature combinations, yes -- but I'd consider that buggy code rather than "incompatible fetaure combinations" and it wasn't obvious to me that this issue had anything to do with that.

**Comment by Kixunil** [comment]
Yes it is a bug to have incompatible feature combinations because they can occur unexpectedly.

**Comment by apoelstra** [comment]
I still don't understand in what sense there are "incompatible feature combinations" :(

**Comment by Kixunil** [comment]
I *randomly* found one offender: `bitcoinconsensus::Error` - I did **not** audit everything.

**Comment by apoelstra** [comment]
I think this is actually the only error variant which is feature-gated at all.

**Comment by tcharding** [comment]
In my opinion, having been through all the error types a million times in the last six months this issue can be closed.

**Comment by Kixunil** [comment]
Yeah, I've seen a bunch of code a number of times and AFAICT all features are additive.
