### ISSUE TITLE
Broken CI

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin#846]
think I have seen the LLVM `sancov` error when the hongfuzz dependencies fail to install. Possibly because #833. Not experienced with actions to understand the stuff. 
 
 Logs: https://github.com/rust-bitcoin/rust-bitcoin/runs/5328234707?check_suite_focus=true

**Comment by TheBlueMatt** [comment]
We're seeing it on rust-lightning too, so it's upstream, probably the LLVM update rustc merged or the new release. I haven't dug enough to file an upstream bug yet on honggfuzz-rs, but it seems mostly unmaintained, sadly.

**Comment by sanket1729** [comment]
Yup, LLVM 13.0 renamed `sancov` to `sancov-module` and(I think) that breaks things in honggfuzz-rs. What do contributors feel about pinning the fuzz check to rust 1.58 while we investigate what's going on?

We should also explore other options for fuzzing.

**Comment by Kixunil** [comment]
Pinning sounds fine.

**Comment by apoelstra** [comment]
ack pinning

**Comment by tcharding** [comment]
Was this issue closed by: https://github.com/rust-bitcoin/rust-bitcoin/pull/848?

**Comment by Kixunil** [comment]
I think if we want to keep this around for later unpinning we should rename the issue.

**Comment by apoelstra** [comment]
Nah, I think we can close it. There's no particular reason (or rush) to unpin the CI, we can do it later whenever somebody thinks of it.
