### ISSUE TITLE
Local tests script for contribution not executing `cargo doc`

### ISSUE THREAD

**Issue by rish-singhal** [rust-bitcoin/rust-bitcoin#850]
The contribution guideline file [https://github.com/rust-bitcoin/rust-bitcoin/blob/master/CONTRIBUTING.md](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/CONTRIBUTING.md) suggests that there exist a script `ci.sh`

`BITCOIN_MSRV=1.29.0 ./contrib/ci.sh`

But I couldn't find this file in the repository, so I opened the contrib directory and found out `test.sh`. Recently, in my PR, I found out that docs tests were failing on github. But locally running `./contrib/test.sh` did not pointed out that.

I believe `cargo doc` is not being executed in `./contrib/test.sh` script for local testing. I am not sure if `./contrib/test.sh` was supposed to check documentation tests too.

**Comment by apoelstra** [comment]
Yes, both of these are bugs:

* contributing.md should have the correct filename, `test.sh`
* `test.sh` should be able to run the doc tests (should be gated by an environment var, similar to the existing fuzztests etc)
