### ISSUE TITLE
Test that we're not causing duplicate crates

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#857]
`bitcoin` 0.27.1 depends on `bitcoin_hashes` 0.10.0 and `secp256k1` 0.20.3 which depends on `bitcoin_hashes` 0.9.7 causing unavoidable duplication of `bitcoin_hashes` crate. Bumping `secp256k1`. This should get resolved in the upcoming release but we need to double-check it and we should test this in CI to avoid in the future.

Something like this should work:

```bash
if [ `cargo +stable tree --all-features -d | wc -l` -gt 0 ];
then
    echo "Error: duplicate dependencies present" >&2
    # Print the duplicates to help debugging quickly
    cargo +stable tree --all-features -d >&2
    exit 1
fi
```

**Comment by apoelstra** [comment]
I'm going to close this issue since it's an ongoing concern for every release cycle and there's no "permanent" solution. We could test this in CI but it'd always cause failures during update cycles.

**Comment by apoelstra** [comment]
Feel free to re-open if you think we can deal with this, or if you think we should at least try to use your snippit and see what happens.

**Comment by Kixunil** [comment]
Oh, so what you describe is:

* A depends on B without exposing it in the API (internal dependency)
* C depends on A and B
* We update A to use newer version of B which is semver-breaking
* We don't want to release C just yet, but do a couple more PRs

Then we get into this situation. I think this will be rare enough to just disable the check whenever it happens. I don't even remember any internal dependencies anywhere.

**Comment by apoelstra** [comment]
Ok, "I think it'll be rare enough" sounds like a good enough reason for us to try it.

On further reflection, I think that if we do this check for rust-bitcoin but not for anything else, that'll get us a lot of benefit without nearly as much pain as we'd have if we tried it on other crates (or all crates) in this ecosystem.

**Comment by Kixunil** [comment]
> if we do this check for rust-bitcoin but not for anything else, that'll get us a lot of benefit without nearly as much pain 

I briefly considered adding it in the reverse form into other crates but figured it can't work. However adding the normal check to others could save us from "oh we messed it up in `bitcoin_hashes`, now we have to update that and also `secp256k1`.

**Comment by tcharding** [comment]
We can close this one now since we check for duplicate dependencies in `bitcoin/contrib/test.sh`, right?
