### ISSUE TITLE
amount offer string serialization

### ISSUE THREAD

**Issue by JeremyRubin** [rust-bitcoin/rust-bitcoin#894]
In `amount`, we offer to serialize as u64 sats, or f64 BTC.

Serializing for JSON in BTC as a raw float is really not a good idea, because common software will mess this up potentially by switching to different notations. I *think* that all values of satoshis are supposed to be able to be rendered as a float precisely?

But it might be better, for applications where we do *want* to have a Bitcoin serialization, that we keep it in an exact string format.

```json
{
"something" : 0.00003
}
```
```json
{
"something": 3e-05
}
```

We could do this as a non-breaking change by adding a new serializing module, as_btc_str. As a breaking change we could just replace the existing as_btc with a string representation. As a final soft path to breaking change, we could make a new module for as_btc_str, deprecate as_btc, and then remove it in the future.

**Comment by apoelstra** [comment]
Yeah, we should affer to serialize as a string alongside u64 or f64. I believe Bitcoin Core has accepted stringly-formatted BTC amounts for a while.

**Comment by hashmap** [comment]
btw why `f64` is used and not decimal which is the standard for financial calculations?

**Comment by Kixunil** [comment]
I think the bigger problem is decimal not being in `serde` data model. (But yes, if `Decimal` was in `core` maybe it'd persuade `serde` to add it.)

**Comment by apoelstra** [comment]
FWIW `serde-json` specifically has some arbitrary-precision-number support, if you enable a cargo feature, but then you have to use their datatypes and it causes serde-json to pollute your actual codebase.

**Comment by JeremyRubin** [comment]
also it's not a standard json type compatible with e.g. JS JSON.parse

**Comment by tcharding** [comment]
Is this still an issue, adding the following code to the `serde_as_btc` test in `units` passes:

```rust
    // Ensure we don't get "amt": 3e-05
    let orig = T {
        amt: Amount::from_sat(3000),
        samt: SignedAmount::from_sat(-3000),
    };

    let got = serde_json::to_string(&orig).unwrap();
    let want = "{\"amt\":0.00003,\"samt\":-0.00003}";
    assert_eq!(got, want);
```

**Comment by apoelstra** [comment]
It seems like it -- you haven't serialized an amount as a string there, but as a float.

**Comment by tcharding** [comment]
Will look a bit harder, thanks.

**Comment by apoelstra** [comment]
If you just do `serde_json::to_string(&Amount::from_sat(3000))` I think this *will* get you a "string-serialized amount".

You can also do `Amount::from_sat(3000).display_with(denom)`.

So I think this issue may actually be resolved.
