### ISSUE TITLE
Taproot OP_RETURN commitments

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#895]
Taproot OP_RETURN script leaf, added at specific position to the script merkle tree, may act as an efficient way of committing to certain off-chain (client-side-validated) data. It does not require tweaking of public keys to spend the output (like in other P2C schemes), which simplifies wallet creation.

The use case for adding taproot OP_RETURN commitment is to insert an additional leaf to an already-defined Merkle tree taken from a certain wallet descriptor with all keys derived. This means adding additional branch to `TaprootSpendInfo` without using `TaprootBuilder` or miniscript. Currently, `TaprootSpendInfo` does not allow that: all fields are private and modification of the `ScriptMerkleProofMap` in it is not possible.

The use case I have with client-side-validation (RGB) requires the commitment to be present in a well-defined place, such that it can be proven that no alternative commitment may exist in the same output. The optimal is to put the commitment as the last leaf in the Mekrle tree. I propose to add a dedicated method `TaprootSpendInfo::push_script_leaf` that allows to do that modification. After discussion here I will work on the PR.

**Comment by sanket1729** [comment]
> requires the commitment to be present in a well-defined place,

Can you elaborate this well-defined place using an example? Do you mean in a specific leaf?

Adding another leaf to a well-constructed `TaprootSpendInfo` cannot be done directly. It would updates to the entire `ScriptMerkleProofMap` and the construction of the entire tree. 
Given this is the case, I think to get all the scripts from the tree and reconstruct the `TaprootSpendInfo` using either builder or Huffman API. You really need to know the structure of the tree to construct these. Because adding a leaf to a complete well-defined taproot tree is not a defined operation.

**Comment by dr-orlovsky** [comment]
> Can you elaborate this well-defined place using an example? Do you mean in a specific leaf?

I mean that it can be proven that the given tree contains one and only one commitment (and no alternative commitment is present). This means that we either add first leaf (shifting the rest of leaves) or the last leaf (updating all branch hashes, but not shifting leaf scripts).

>  It would updates to the entire ScriptMerkleProofMap and the construction of the entire tree.

Correct. But this is trivial if we add the last leaf: we just update branch hashes and output key

> I think to get all the scripts from the tree and reconstruct the TaprootSpendInfo using either builder or Huffman API. 

No, it will be non-trivial and non-deterministic/non-standardizable.

**Comment by dr-orlovsky** [comment]
> The first or last leaf is not an easy thing to define. I think you might have a fixed tree structure in mind. How do you add leaf script to a tree with 4 leaves (all of them are leaves at level 2)? What does shifting even mean here? I think the implementation is already non-trivial.

I will replace the 4th leave on level 2 with a node having two subleafs.

**Comment by sanket1729** [comment]
So, this is the last in the DFS order. You can do it if we expose an API to iterate all scripts in DFS order. Something that yeilds (depth, script) as we iterate in DFS order. This can belong in rust-bitcoin. See this https://github.com/rust-bitcoin/rust-bitcoin/blob/443a38567be8ea2b62e3cf99021ef6232b9e9347/src/util/psbt/serialize.rs#L320 for inspiration. 

Downstream, you can iterate all scripts in (depth, script). Than in `TaprootBuilder` API, you can add all scripts in the same order as you iterate. For adding at the last place, you add (depth + 1, last_script), (depth + 1, op_return). Does this sound like a reasonable separation? IMO, adding the last position script is too specific of a use-case that should be addressed in RBG.

**Comment by apoelstra** [comment]
concept ACK adding a way to do this.

I worry though that RGB might conflict with other protocols -- there is only a single "first" slot and a single "last" slot in DFS, and these would be the most popular choices. I wonder if there is some cryptographic way to avoid the "fixed position" necessity.

**Comment by dr-orlovsky** [comment]
@apoelstra RGB does not use that slot directly. Instead we have a concept of multi-protocol commitment in that place, where commitments under different protocols (RGB, other types of single-use-seals) are packed in a structure with multiple slots - please see https://github.com/LNP-BP/LNPBPs/blob/master/lnpbp-0004.md - and the final commitment that goes into bitcoin transaction may host multiple protocols in a non-conflicting way (these slots will be merklized into a single root with the new version of that proposal).

**Comment by tcharding** [comment]
Is this a bug fix? Does this one _really_ need to be in the 0.28 release @dr-orlovsky, we are up to RC releases so it should only be bug fixes now that we consider, we don't want to iterate for ever and not get the release out the door. I don't mean to be a jerk, I know its been my PRs holding up the release for ages :)

**Comment by sanket1729** [comment]
This is a non-breaking feature request. We can get a release out of the way, and then make a 0.28.1 with this and other non-breaking changes? If we want to do this, we should be really careful in merging this do not break things.

**Comment by tcharding** [comment]
> we should be really careful in merging this do not break things

Sounds like definitely not an RC-fix then. Removing the 0.28 milestone. Feel free to slap me if I'm out of line @dr-orlovsky.

**Comment by dr-orlovsky** [comment]
Sorry, with our even minor reeleases taking at least half of the year, I'd like to have this feature sooner, since I am really dependent on it downstream. Otherwise I will have not choice than to fork rust-bitcoin and maintain separate repo till the next release, which I am 100% sure will not happen soon (since right after taproot we will get into an endless rust 2018 and crate refactoring cycle)

**Comment by dr-orlovsky** [comment]
What can be an alternative of having it in `0.28.0.RC*` and still not postponing for many months until `0.29`? If we all agree to create b branch `0.28` right after `0.28.0` release and maintain it, such we have a place where we can backport bugfixes and implement minor API changes and have releasse cycles for `0.28.1` etc - independently from the work happening in `master`, where a big refactorings may take place. Otherwise we will end up with a situation as before: when somebody will propose to have a `0.28.1` we will discover that we already have some major API breaking PRs merged in `master` and this can't be done - and everybody needs to wait another half of the year even for bugfixing.

**Comment by dr-orlovsky** [comment]
Implemented TapTree script iterator in https://github.com/rust-bitcoin/rust-bitcoin/pull/901 after @sanket1729 suggestion. Explained there why I think that PR can be an RC fix.

**Comment by tcharding** [comment]
hmm tough problem you raise.

> with our even minor releases taking at least half of the year

I think this is the crux of the issue. Some thoughts:

- @sanket1729 has started a fixed-time release cycle [discussion](https://github.com/rust-bitcoin/rust-bitcoin/discussions/900) which might be the answer. 
- Your branch idea might work together with the fixed-time release cycle. 

I don't see an immediate solution to your problem with this PR other than trying to get it into the 0.28 release. What if we push ahead fast and instead of trying to make the 0.28.0 Taproot release perfect we put a MASSIVE note in all release docs that this release is a big change and we intend on iterating fast (i.e., 0.28.1 0.28.2) to make sure we got it right. Folks can then elect not to release production code yet until we get a few point releases out the door?

**Comment by dr-orlovsky** [comment]
>  What if we push ahead fast and instead of trying to make the 0.28.0 Taproot release perfect we put a MASSIVE note in all release docs that this release is a big change and we intend on iterating fast (i.e., 0.28.1 0.28.2) to make sure we got it right. Folks can then elect not to release production code yet until we get a few point releases out the door?

This is called RC, not minor releases. Why? First, because "Folks can then elect not to release production code" means that the "0.28.0 release" is not a production release, i.e. not a release but a candidate at best. Second, because we will end up needing to break API (I am quite sure a lot of stuff is still missed there required for real-world taproot applications), which can be done in `0.28.0-rc.N -> rc.N+1` updates, but not in `0.28.N -> 0.28.N+1` updates.

**Comment by tcharding** [comment]
Oooo, do you mean to say that we are going to be on `0.28.0-rc.N` for ages yet and that we are now trying to put together a `0.28.0-rc2` release? I thought we were pushing to get the `0.28.0` released, as in soon, like within a week or two. Am I mistaken? This whole time I thought the RC cycle was meant to be a couple of weeks at most.

**Comment by dr-orlovsky** [comment]
No, I am not saying what we are doing or should do, I am just explaining that if the folks can't/not recommended use the release in production and we will do a lot of changes to improve taproot to real-world tasks, which will probably mean some breaks in API, this will not be a minor cycle, but called "beta cycle" (or RC at best).

Also I think that we can't do `0.28.0` without `0.28.0-rc.2` at least, otherwise we will have issues like with some of previous `secp256k1` release. We already have too many changes since `0.28.0-rc.1` and need to test them with downstream crates before doing a full release.

**Comment by tcharding** [comment]
Cool, cheers.

**Comment by apoelstra** [comment]
I don't see why it would be such an unreasonable burden to maintain external code for creating special-purpose taptrees.

I don't mind having this in the library, it's fairly general and it's a cool/interesting use of Taproot, but let's not hold up releases because of it.

**Comment by dr-orlovsky** [comment]
@apoelstra I agree with the @sanket1729 and made #901 as the simplest minimal thing which allows taproot/return commitments. That PR pending the second ACK, so if you can do that we will have it in the RC fix. 

Once merged, I will work on a more advanced API for taproot/return commitments (for short, I call them "tapreturn" or "tapret" commitments). It can probably go into the next minor releases since it may take more time for review.

**Comment by sanket1729** [comment]
> I will work on a more advanced API for taproot/return commitments (for short, I call them "tapreturn" or "tapret" commitments).

To be clear, I don't think this belongs in rust-bitcoin. But we can debate that after release. 

@apoelstra #901 is not a special-purpose API. It offers a way to iterate over individual scripts from a tree. After #901, @dr-orlovsky should be able to do everything downstream using the `Builder` API.

**Comment by dr-orlovsky** [comment]
Closing: implemented using `TapTree` iterator added in the last RC
