### ISSUE TITLE
Non-uniform identifiers for 'sighash'

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#911]
Sometimes we use `SigHash` e.g., `EcdsaSigHashType`, `PsbtSigHashType` and sometimes we use `Sighash` e.g., `SighashComponents`, `TapSighash`.

We should be uniform in how we construct our identifiers.

This might be a RC-fix?

**Comment by apoelstra** [comment]
concept ACK making this a RC fix.

I have no preference here. Probably we should just copy Bitcoin Core?

**Comment by sanket1729** [comment]
Concept ACK. Don't know if has to be an RC-fix. We can break this in 0.29

**Comment by dr-orlovsky** [comment]
Concept ACK, also ACK for going after Bitcoin Core naming.

Rust naming guidelines suggests to start each word with a capital letter, but I am not sure whether `sighash` has not became a new word by itself (like "brexiting" :). At lease in the const names we use `SIGHASH`, not `SIG_HASH`.

**Comment by apoelstra** [comment]
That's a good observation. I do think of "sighash" as one word.

**Comment by dr-orlovsky** [comment]
So we need `Sighash`, `EcdsaSighashType`, `PsbtSighashType`, `SighashComponents`, `TapSighash`, `SIGHASH_*` etc

**Comment by tcharding** [comment]
lolz 'brexiting', I laughed out loud at that example, my mind jumped immediately to 'pubkey' :)

**Comment by tcharding** [comment]
> So we need `Sighash`, `EcdsaSighashType`, `PsbtSighashType`, `SighashComponents`, `TapSighash`, `SIGHASH_*`, `sighash` mod etc

I'll hack it up!
