### ISSUE TITLE
WASM build

### ISSUE THREAD

**Issue by antouhou** [rust-bitcoin/rust-bitcoin#930]
Hi! Thanks for the amazing work you're doing!

I've tried to integrate rust-bitcoin lib into some project that has WASM as a target and run into issues compiling it, at least on mac. The issues were mostly related to the libsecp256k1. I've checked the lib issues, and there was indeed some PR merged a couple of days ago that was fixing the WASM build. I've tried using it, but if I use rust-bitcoin as a dependency, the project won't compile anyway. I probably could tweak the build script and figure out how to make it work. I also was wondering if you are considering switching to pure rust libsecp265k1. There's a pure Rust implementation by Polkadot: https://github.com/paritytech/libsecp256k1. Is that something you're considering? If that is so, I probably could do the migration for you.

Thank you!

**Comment by apoelstra** [comment]
We are not switching off of rust-secp256k1. I am very disappointed to see that a pure Rust implementation of these crypto primitives is being marketed as production ready, given extremely sketchy sidechannel story for the Rust language.

The next version of rust-bitcoin, which will be released this weekend, will depend on the latest version of rust-secp, which should fix your compilation issue.

**Comment by antouhou** [comment]
Thank you for the answer, @apoelstra! What exact sidechannel story are you talking about? I would love to read about it to learn more. Thank you!

**Comment by Kixunil** [comment]
I believe the only "reliable" way to resolve sidechannel attacks is using assembly which should be supported in newer versions of Rust (but calling it "pure Rust" is kinda weird then). C itself can't guarantee constant time or other properties either. It literally uses the same optimizer underneath.

I put "reliable" in quotes because CPUs don't guarantee shit either. :man_shrugging: 

Another issue with pure Rust implementation is choosing exact same name as the C implementation that could confuse people.

**Comment by Kixunil** [comment]
Wow, kudos for such great work!

**Comment by antouhou** [comment]
@apoelstra That's is amazing work! And also thank you very much for the explanation,I appreciate it! Thank you!

**Comment by elichai** [comment]
I'd also like to note that parity's secp implementation at least originally (Idk what's the current status) was mainly just copying the C code from libsecp256k1 without fully grasping what's happening there, you can see this as an example: https://github.com/paritytech/libsecp256k1/commit/3126fd213c1c02d44c3c8779e3bed3f8763cc02d
(You can see the original code here: https://github.com/bitcoin-core/secp256k1/blob/8746600eec5e7fcd35dabd480839a3a4bdfee87b/src/scalar_4x64_impl.h#L158:L167, and that it uses a binary OR(`|`) and not a logical OR (`||`) like the parity's one used)

**Comment by elichai** [comment]
Users should be able to compile rust-bitcoin+rust-secp256k1 to WASM, and use LTO to remove unused parts (say if they don't use signing at all)

**Comment by Kixunil** [comment]
@dpc there was a discussion about making the C library optional, without which it wouldn't support cryptographic operations, just parsing with Rust-reimplemented check of the point being on curve etc.

**Comment by apoelstra** [comment]
@dpc agreed. It is tempting to allow swapping out to a pure-Rust implementation of the verification logic. My fear then changes from constant-timeness to consensus compatibility though. (I know there aren't a lot of wasm implementations that really care about consensus compatibility, but this is a subtle thing where mistakes are very hard to notice, so it's a road that I don't want to go down..)

@Kixunil we'd discussed making the C library optional and then implementing a few simple things (e.g. key/signature parsing/validation) in pure Rust. But implementing actual crypto, even crypto that doesn't touch secret keys, makes me nervous.

**Comment by Kixunil** [comment]
There are many applications that don't require crypto so having a bitcoin library without it should be already valuable.

**Comment by mcdallas** [comment]
This seems to be an issue still:
``` bash
> cargo init
> echo 'bitcoin = "*"' >> Cargo.toml
> cargo build --release --target wasm32-unknown-unknown                  
   Compiling bitcoin_hashes v0.11.0
   Compiling bech32 v0.9.1
   Compiling secp256k1-sys v0.6.0
The following warnings were emitted during compilation:

warning: error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-unknown"'
warning: 1 error generated.

error: failed to run custom build command for `secp256k1-sys v0.6.0`
```

I also tried adding `secp256k1 = {version = "0.24.0", features = ["global-context-less-secure"]}` suggested in another thread but it still fails

**Comment by antouhou** [comment]
@mcdallas If you're building on a mac, you need to install clang through the homebrew, as XCode's bundled clang doesn't provide the wasm target support. You can do it with homebrew: `brew install llvm`. For some reason, XCode highjacks the linker even if you export PATH and set all the env variables in the `.zshrc`, so to build something afterward you'll need to set those variables directly: `AR=/usr/local/opt/llvm/bin/llvm-ar CC=/usr/local/opt/llvm/bin/clang wasm-pack build`. I hope this helps!

**Comment by mcdallas** [comment]
Thanks I am indeed on MacOS, both targets work now after replacing the stock clang as @antouhou suggested

**Comment by antouhou** [comment]
Actually I has forgotten that I've opened this issue a while ago. Everything has been working for quite a while now, thank you!

**Comment by andrewrjohn** [comment]
> @mcdallas If you're building on a mac, you need to install clang through the homebrew, as XCode's bundled clang doesn't provide the wasm target support. You can do it with homebrew: `brew install llvm`. For some reason, XCode highjacks the linker even if you export PATH and set all the env variables in the `.zshrc`, so to build something afterward you'll need to set those variables directly: `AR=/usr/local/opt/llvm/bin/llvm-ar CC=/usr/local/opt/llvm/bin/clang wasm-pack build`. I hope this helps!

For anybody running into this issue in 2024, homebrew changed the path where it installs llvm, so set your variables to these instead in your `.zshrc`:
```bash
AR=/opt/homebrew/opt/llvm/bin/llvm-ar
CC=/opt/homebrew/opt/llvm/bin/clang
```

Then `wasm-pack build` will work as expected after sourcing your `.zshrc`!
