### ISSUE TITLE
PSBT lacking Eq implementation

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-bitcoin#931]
`PartiallySignedTransaction`, `psbt::Output` and `psbt::Input` all lacking `Eq` implementation (but have `PartialEq`). Was this intentional?

If not, I see two ways forward with the implementation: adding derive or manual implementation doing BIP-174 serialization to a vector and byte-comparing those vectors.

**Comment by sanket1729** [comment]
> If not, I see two ways forward with the implementation: adding derive or manual implementation doing BIP-174 serialization to a vector and byte-comparing those vectors.

Same Psbts can have different serializations because the order in which we serialize keys is not defined.  Even though the serialization in rust-bitcoin is deterministic, other implementations need not follow the same. I think we have to derive it on the `Psbt` data structure.

**Comment by dr-orlovsky** [comment]
@sanket1729 derived in #932

**Comment by apoelstra** [comment]
I'm not sure how to interpret Sanket's comment, but we *should* implemnet `Eq` everywhere here. This looks like an oversight.

**Comment by sanket1729** [comment]
@apoelstra, I think we are on the same page. There were two ways to derive `Eq`.

- `[#derive(Eq)]`
- Compare the consensus encoding.

I suggested using `[#derive(Eq)]` because the same Psbt structures need to necessarily have the same consensus encoding(key-value pairs can be serialized in any order).

**Comment by dr-orlovsky** [comment]
@sanket1729 I think @apoelstra meant that we need to introduce support for hidden branches into PSBT.
