### ISSUE TITLE
0.13.1 version breaks compatibility with the 0.13.0

### ISSUE THREAD

**Issue by alekseysidorov** [rust-bitcoin/rust-bitcoin#94]
Because the network enum adds a new `regtest` constant that affects the whole code that uses pattern matching with the `Network` constant.
For example
https://github.com/exonum/exonum-btc-anchoring/blob/ab3b22c6dbc117b0cc8115b978aa0973fc22703a/src/blockchain/consensus_storage.rs#L134

**Comment by popzxc** [comment]
Although that was my PR which leaded to those problems, I think that breaking changes must be included only in major releases.

**Comment by mvlabat** [comment]
Yeah, but we can still do breaking changes in minor releases (not patches) while we have no stable release (1.0.0)

**Comment by apoelstra** [comment]
@mvwlabat no we can't.

This was a mistake on our part, I guess we overlooked that adding enum variants was a breaking change. We'll have to revert and republish 0.13.2, and move this change to 0.14.
