### ISSUE TITLE
Optimize `Witness` serialization

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#942]
`self.to_vec()` allocates, it should be possible to avoid it - just feed the items into serializer.

**Comment by tcharding** [comment]
Warning re 'good first issue', might not be totally trivial to sort through the thread of discussion on https://github.com/rust-bitcoin/rust-bitcoin/pull/899 which is related to this.

**Comment by Kixunil** [comment]
I don't think it's too important, just looking at the code the optimization should be obvious.
