### ISSUE TITLE
Reconsider the internal representation of `Script`

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bitcoin#949]
`Script` currently contains a boxed slice.

Pros/cons vs `Vec<u8>`:

* Faster to move (but moves are fast anyway, so the difference is crazy small)
* Consumes less memory: 1 `usize` less for capacity and guaranteed no extra memory
* Construction may force costly reallocation even for ridiculous values (e.g. to save 1 byte of memory)
* Having a shitload of scripts outside `Transaction` is unusual, the speed of moving `Transaction` is already independent of `Script` size (type; not to be confused with length)

Are the benefits worth extra reallocation on construction? My guess is no, but we should probably benchmark it.

Possible approaches:

* It can be demonstrated that the current design is really the best and we just close this issue
* It can be demonstrated `Vec<u8>` is the best and we switch
* Depends on application we expose feature flag to globally switch the strategy - easier but less flexible
* We make it generic over storage with some reasonable default

**Comment by tcharding** [comment]
Possibly related issue: https://github.com/rust-bitcoin/rust-bitcoin/issues/522

**Comment by apoelstra** [comment]
I'm doubtful that `Box<iu8]>` is worth the hassle vs `Vec<u8>`. This was a premature optimization that I did when I discovered `Box<[u8]>` when the project was a toy and Script never changed, and I never benchmarked it.

**Comment by Kixunil** [comment]
FTR #1155 is surprisingly an improved version of the last option. The combination of relatively simple conversions between `ScriptBuf` and `Box<Script>`  and deref coercions make the implementation reasonably simple. Previously I expected this to be much more boilerplate-y with little value.
