### ISSUE TITLE
Txid byte order problem

### ISSUE THREAD

**Issue by lem-solutions** [rust-bitcoin/rust-bitcoin#958]
Apparently bitcoin reverses the byte order for txids in transaction inputs due to a mistake in the original bitcoin client software, which I wasn't aware of and this crate doesn't account for. We could just documented this quirk or even implement a ReverseTxid type to make it harder to use incorrectly.

**Comment by apoelstra** [comment]
What do you mean that this crate "doesn't account for" the reversed hashes? The `Txid` is a wrapper around the bitcoin_hashes `sha256d` type which [does indeed display hashes backward](https://github.com/rust-bitcoin/bitcoin_hashes/blob/master/src/sha256d.rs#L86).

**Comment by lem-solutions** [comment]
I mean the byte representation (the Deref<target=[u8]>)

**Comment by Kixunil** [comment]
FTR, `Deref` is often an anti-pattern and it looks like one in this case. Perhaps we should have methods `to_bytes_consensus(&self) -> [u8; 32]` and `to_bytes_native(&self) -> [u8; 32]` instead. (Feel free to suggest better names.)

**Comment by TheBlueMatt** [comment]
There shouldn't ever be a use of bytes with flipped byteorder. The byteorder flipping in "standard" (strange) bitcoin only happens when printing/creating hex. Given that I'm not sure why Deref is an anti-pattern or we need accessors - its always a 32 byte array with hash-output endianness.

**Comment by Kixunil** [comment]
https://github.com/rust-unofficial/patterns/blob/main/anti_patterns/deref.md

**Comment by TheBlueMatt** [comment]
I'd agree its an anti-pattern for "struct inheritance" as described there, but for newtypes, espectially byte-array-newtypes, I think I'd disagree. Not that its all that critical, the larger point is that the endianness here is "expected" for some definition of "what every bitcoin application does".

**Comment by apoelstra** [comment]
I also think this is a correct use of `Deref`.

**Comment by Kixunil** [comment]
I'm not really sure, this is supposed to be a newtype. `Deref` allows you to pass `&txid` to a method accepting `non_txid: &[u8]`.
Looks like a conflict of the objectives. Aside, as opposed to `&Vec<T>`, `&Txid` doesn't implement `IntoIterator`.

Anyway, if there's not use case for reversed bytes, this is probably just a doc issue.

**Comment by apoelstra** [comment]
I think it's fine to pass a txid to a function expecting a byte slice. We just don't want to be able to pass a txid to a function expecting a different specific type of hash.

**Comment by dpc** [comment]
`Txid` (and other hash types) automatically derefing to `&[u8]` seems harmless to me. They are all in fact just bunch of bytes from a hashing operation, and often will be treated as such. I can't come up with an example when things could go wrong because of this `Deref`, and that's the most important thing to me.

The more by-the-book approach would be something like `fn as_array(&self) -> &[u8; 32]` and `fn as_bytes(&self) -> &[u8]` or something like that. Not the end of the world to have to type it here and there, but doesn't seem worth it.
