### ISSUE TITLE
Remove deprecated rustc-serialize crate

### ISSUE THREAD

**Issue by BelfordZ** [rust-bitcoin/rust-bitcoin#96]
The use of the deprecated rustc-serialize crate is preventing users from using various compile targets, specifically `wasm32-unknown-unknown` which is crucial for users looking to compile for browsers / nodejs.

**Comment by apoelstra** [comment]
@BelfordZ does #107 fix your issue? `rustc-serialize` is still present as a dependency of `rust-crypto`. If that's still a problem perhaps we should prioritize moving away from rust-crypto.

**Comment by newpavlov** [comment]
You still depend on `rustc-serialize` via `rust-crypto`, so probably the best approach will be to follow #98.

**Comment by BelfordZ** [comment]
Defs getting there! there is the transitive dependency still, though since we are only using this crate for the bip39.

**Comment by apoelstra** [comment]
I think moving away from rust-crypto is going to slip for 0.14.0. I'd like to have a new release soon but fixing the crypto deps is pretty invasive -- there's a lot of inefficient stuff related to hashing (like the `Transaction` impl of `BitcoinHash` serializing the whole tx into a new `Vec` before hashing) that should be cleaned up at the same time.

I have code that does this locally, but it needs to be cleaned up and there's a bunch of supporting work to get in first.

**Comment by bodymindarts** [comment]
I'm also looking for support for wasm as a compile target. If I understand [this](https://github.com/rust-bitcoin/rust-bitcoin/issues/98) discussion correctly the decision has been made to solve this by moving to the [bitcoin_hashes](https://github.com/rust-bitcoin/bitcoin_hashes) library.

Is there a branch where I can follow the progress of this or make a contribution to speed this up? @apoelstra

**Comment by apoelstra** [comment]
The existing set of maintainers needs to finish the conference circuit that they are all on and approve the open PRs. There isn't anything that other contributors can do to speed it up, sorry.

**Comment by dongcarl** [comment]
Addressed by #215
